PROGRAM MAIN

USE TYPE_MODEL         , ONLY : MODEL
USE GEOMETRY_MOD       , ONLY : GEOMETRY
USE PARKIND1           , ONLY : JPIM, JPRB
USE YOMHOOK            , ONLY : LHOOK, DR_HOOK, JPHOOK
USE MPL_MPIF           , ONLY : MPI_COMM_WORLD, MPI_THREAD_MULTIPLE, MPI_THREAD_SINGLE, MPI_WTIME
USE MPL_MODULE         , ONLY : MPL_INIT, MPL_END

USE UTIL_MODEL_MOD
USE UTIL_GEOMETRY_MOD
USE UTIL_YOMMP0_MOD, ONLY : LOAD_YOMMP0

IMPLICIT NONE

TYPE(GEOMETRY)      :: YDGEOMETRY
TYPE(MODEL)         :: YDMODEL
REAL(KIND=JPRB), ALLOCATABLE :: PSPSP (:)
REAL(KIND=JPRB), ALLOCATABLE :: PSPVOR(:,:)
REAL(KIND=JPRB), ALLOCATABLE :: PSPDIV(:,:)
REAL(KIND=JPRB), ALLOCATABLE :: PSPT  (:,:)
REAL(KIND=JPRB), ALLOCATABLE :: PSPSPD(:,:)
REAL(KIND=JPRB), ALLOCATABLE :: PSPSVD(:,:)

INTEGER (KIND=JPIM) :: MYPROC
INTEGER (KIND=JPIM) :: NSMAX
INTEGER (KIND=JPIM) :: NDGLG
INTEGER (KIND=JPIM), ALLOCATABLE :: NLOENG (:)
INTEGER (KIND=JPIM) :: NRESOL
LOGICAL :: LSPLIT
LOGICAL :: LUSEFLT
LOGICAL :: LUSERPNM
LOGICAL :: LKEEPRPNM
LOGICAL :: LFFTW

INTEGER (KIND=JPIM) :: NPRGPNS
INTEGER (KIND=JPIM) :: NPRGPEW
INTEGER (KIND=JPIM) :: NPRTRW
LOGICAL :: LEQ_REGIONS
REAL (KIND=JPRB) :: RA

#include "spcm_simple.intfb.h"
#include "setup_trans0.h"
#include "setup_trans.h"
#include "abor1.intfb.h"


INTEGER :: ILUN, IERR
INTEGER :: IREQUIRED, IPROVIDED
CHARACTER (LEN=64) :: CLFILE, CLPROC

IREQUIRED = MPI_THREAD_MULTIPLE
IPROVIDED = MPI_THREAD_SINGLE
CALL MPI_INIT_THREAD (IREQUIRED, IPROVIDED, IERR)
IF (IERR /= 0) CALL ABOR1 ('MAIN: MPI_INIT_THREAD FAILED')

CALL MPI_COMM_RANK (MPI_COMM_WORLD, MYPROC, IERR)
MYPROC = MYPROC + 1

PRINT *, " MYPROC = ", MYPROC

ILUN = 77

CALL MPL_INIT ()

CLFILE = 'SETUP_TRANS.IN'

ILUN = 77

OPEN (ILUN, FILE="SETUP_TRANS0.IN", FORM='UNFORMATTED')
READ (ILUN) NPRGPNS
READ (ILUN) NPRGPEW
READ (ILUN) NPRTRW
READ (ILUN) LEQ_REGIONS
READ (ILUN) RA
CLOSE (ILUN)


CALL SETUP_TRANS0            &
  (KPRGPNS=NPRGPNS,          &
 & KPRGPEW=NPRGPEW,          &
 & KPRTRW=NPRTRW,            &
 & KPRINTLEV=2,              &
 & LDEQ_REGIONS=LEQ_REGIONS, &
 & PRAD=RA)


OPEN (ILUN, FILE=TRIM (CLFILE), FORM='UNFORMATTED')

READ (ILUN) NSMAX
READ (ILUN) NDGLG
ALLOCATE (NLOENG (NDGLG))
READ (ILUN) NLOENG
READ (ILUN) LSPLIT
READ (ILUN) NRESOL
READ (ILUN) LUSEFLT
READ (ILUN) LUSERPNM
READ (ILUN) LKEEPRPNM
WRITE (ILUN) LFFTW

CLOSE (ILUN)


WRITE (0, *) __FILE__, ':', __LINE__ 

CALL SETUP_TRANS(KSMAX=NSMAX,KDGL=NDGLG,KLOEN=NLOENG(1:NDGLG),&
 & LDSPLIT=LSPLIT,&
 & KRESOL=NRESOL,LDUSEFLT=LUSEFLT,LDUSERPNM=LUSERPNM,&
 & LDKEEPRPNM=LKEEPRPNM,LDUSEFFTW=LFFTW)

WRITE (0, *) __FILE__, ':', __LINE__ 

CLOSE (ILUN)

WRITE (CLPROC, '(I4.4)') MYPROC
CLFILE = 'SPCM_SIMPLE.IN.'//TRIM (CLPROC)

OPEN (ILUN, FILE=TRIM (CLFILE), FORM='UNFORMATTED')

CALL LOAD_YOMMP0 (ILUN)
CALL LOAD (ILUN, YDMODEL)
CALL LOAD (ILUN, YDGEOMETRY)

ALLOCATE (PSPSP (YDGEOMETRY%YRDIM%NSPEC2))
ALLOCATE (PSPVOR(YDGEOMETRY%YRDIMV%NFLEVL,YDGEOMETRY%YRDIM%NSPEC2))
ALLOCATE (PSPDIV(YDGEOMETRY%YRDIMV%NFLEVL,YDGEOMETRY%YRDIM%NSPEC2))
ALLOCATE (PSPT  (YDGEOMETRY%YRDIMV%NFLEVL,YDGEOMETRY%YRDIM%NSPEC2))
ALLOCATE (PSPSPD(YDGEOMETRY%YRDIMV%NFLEVL,YDGEOMETRY%YRDIM%NSPEC2))
ALLOCATE (PSPSVD(YDGEOMETRY%YRDIMV%NFLEVL,YDGEOMETRY%YRDIM%NSPEC2))

READ (ILUN) PSPSP 
READ (ILUN) PSPVOR
READ (ILUN) PSPDIV
READ (ILUN) PSPT  
READ (ILUN) PSPSPD
READ (ILUN) PSPSVD

CLOSE (ILUN)


CALL SPCM_SIMPLE (YDGEOMETRY,YDMODEL,PSPSP,PSPVOR,PSPDIV,PSPT,PSPSPD,PSPSVD)


PRINT *, " SPCM_SIMPLE DONE "

STOP

ILUN = 77

WRITE (CLPROC, '(I4.4)') MYPROC

CLFILE = 'SPCM_SIMPLE.OUT.'//TRIM (CLPROC)

OPEN (ILUN, FILE=TRIM (CLFILE), FORM='UNFORMATTED')

READ (ILUN) PSPSP 
READ (ILUN) PSPVOR
READ (ILUN) PSPDIV
READ (ILUN) PSPT  
READ (ILUN) PSPSPD
READ (ILUN) PSPSVD

CLOSE (ILUN)

999 CONTINUE

CALL MPL_END ()

END 

