
SRC=..

# PGI

FIAT=/home/gmap/mrpm/marguina/fiat/pginvtx+mplacc-build
ECTRANS=/home/gmap/mrpm/marguina/hub/install
ECCODES=/home/gmap/mrpm/marguina/install/PGI2211/eccodes-2.14.0

FFLAGS= -I$(SRC) -acc -mp -gpu=cc70,gvmode -fPIC -Minfo=accel -gopt -Mcuda -Mlarge_arrays -Mlist -traceback -Mnofma -Mbyteswapio -Mbackslash

FC=/home/gmap/mrpm/marguina/install/gmkpack_support/wrapper/PGI2211/mpif90 \
   -I$(FIAT)/include \
   -I$(FIAT)/module/parkind_dp \
   -I$(FIAT)/module/fiat \
   -I$(ECTRANS)/include/ectrans \
   -I$(ECTRANS)/module/trans_dp \
   -I$(ECCODES)/include \
   $(FFLAGS)

LIBS=-L$(FIAT)/lib -lparkind_dp -lfiat -Wl,-rpath,$(FIAT)/lib \
     -L$(ECTRANS)/lib64 -ltrans_dp -Wl,-rpath,$(ECTRANS)/lib64 \
     -L$(ECCODES)/lib -leccodes_f90 -leccodes -Wl,-rpath,$(ECCODES)/lib \
     -L/opt/softs/nvidia/hpc_sdk/Linux_x86_64/22.11/math_libs/11.8/targets/x86_64-linux/lib/stubs/ -lcublas \
     -L/opt/softs/nvidia/hpc_sdk/Linux_x86_64/22.11/compilers/lib -llapack_lp64 -lblas_lp64 \
     -Wl,-rpath,/opt/softs/nvidia/hpc_sdk/Linux_x86_64/22.11/compilers/lib \
     -Wl,-rpath,/opt/softs/nvidia/hpc_sdk/Linux_x86_64/22.11/cuda/11.8/lib64

