MODULE MODEL_DYNAMICS_MOD
  USE YOMDYNA     , ONLY : TDYNA
  USE YOMDYN      , ONLY : TDYN
  IMPLICIT NONE
    
  TYPE MODEL_DYNAMICS_TYPE
  ! general stuff
  TYPE(TDYNA)     :: YRDYNA
  TYPE(TDYN)      :: YRDYN
    
 END TYPE MODEL_DYNAMICS_TYPE

END MODULE MODEL_DYNAMICS_MOD

