INTERFACE
#if defined(_OPENACC)
SUBROUTINE MXPTMA(KLX,KVX,KVXS,PA,PBI,PCI,PBS,PCS,PX,PY)
#else
SUBROUTINE MXPTMA(KLX,KVX,KVXS,KIX,tnsmax,PA,PBI,PCI,PBS,PCS,PX,PY)
#endif
USE PARKIND1 ,ONLY : JPIM ,JPRB
INTEGER(KIND=JPIM),INTENT(IN) :: KLX
INTEGER(KIND=JPIM),INTENT(IN) :: KVXS
INTEGER(KIND=JPIM),INTENT(IN) :: KVX
#if defined(_OPENACC)

#else
INTEGER(KIND=JPIM),INTENT(IN) :: KIX
integer(kind=jpim),intent(in) :: tnsmax
#endif
REAL(KIND=JPRB) ,INTENT(IN) :: PA(KLX)
REAL(KIND=JPRB) ,INTENT(IN) :: PBI(KLX)
REAL(KIND=JPRB) ,INTENT(IN) :: PCI(KLX)
REAL(KIND=JPRB) ,INTENT(IN) :: PBS(KLX)
REAL(KIND=JPRB) ,INTENT(IN) :: PCS(KLX)
#if defined(_OPENACC)
REAL(KIND=JPRB) ,INTENT(IN) :: PX(2*KLX,kvxs)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PY(2*KLX,kvxs)
#else
REAL(KIND=JPRB) ,INTENT(IN) :: PX(tnsmax+1,KVXS,KIX)
REAL(KIND=JPRB) ,INTENT(OUT) :: PY(tnsmax+1,KVXS,KIX)
#endif
END SUBROUTINE MXPTMA
END INTERFACE
