INTERFACE
SUBROUTINE MXPTMA(KLX,KVX,KVXS,KIX,kixs,PA,PBI,PCI,PBS,PCS,PX,PY)
!$acc routine vector
USE PARKIND1 ,ONLY : JPIM ,JPRB
INTEGER(KIND=JPIM),INTENT(IN) :: KLX
INTEGER(KIND=JPIM),INTENT(IN) :: KVXS
INTEGER(KIND=JPIM),INTENT(IN) :: KIX
integer(kind=jpim),intent(in) :: kixs
INTEGER(KIND=JPIM),INTENT(IN) :: KVX
REAL(KIND=JPRB) ,INTENT(IN) :: PA(KLX)
REAL(KIND=JPRB) ,INTENT(IN) :: PBI(KLX)
REAL(KIND=JPRB) ,INTENT(IN) :: PCI(KLX)
REAL(KIND=JPRB) ,INTENT(IN) :: PBS(KLX)
REAL(KIND=JPRB) ,INTENT(IN) :: PCS(KLX)
#define inversee 0
#if defined(_OPENACC)
REAL(KIND=JPRB) ,INTENT(IN) :: PX(KVXS,KLX,KIX)
REAL(KIND=JPRB) ,INTENT(OUT) :: PY(KVXS,KLX,KIX)
#else
#if inversee
REAL(KIND=JPRB) ,INTENT(IN) :: PX(KLX,KIXs,kvxs)
REAL(KIND=JPRB) ,INTENT(OUT) :: PY(KLX,KIXs,kvxs)
#else
REAL(KIND=JPRB) ,INTENT(IN) :: PX(KVXS,KLX,KIXs)
REAL(KIND=JPRB) ,INTENT(OUT) :: PY(KVXS,KLX,KIXs)
#endif
#endif
END SUBROUTINE MXPTMA
END INTERFACE
