INTERFACE
#if defined(_OPENACC)
SUBROUTINE MXPTMA(KLX,KVX,KVXS,KIX,KTNSMAX,PA,PBI,PCI,PBS,PCS,PX,PY)
!$ACC ROUTINE VECTOR
#else
SUBROUTINE MXPTMA(KLX,KVX,KVXS,KIX,KTNSMAX,PA,PBI,PCI,PBS,PCS,PX,PY)
#endif
USE PARKIND1 ,ONLY : JPIM ,JPRB
#if defined(_OPENACC)
INTEGER(KIND=JPIM),INTENT(IN),VALUE    :: KLX 
INTEGER(KIND=JPIM),INTENT(IN),VALUE    :: KVXS 
INTEGER(KIND=JPIM),INTENT(IN),VALUE    :: KIX 
INTEGER(KIND=JPIM),INTENT(IN),VALUE    :: KVX
INTEGER(KIND=JPIM),INTENT(IN),VALUE    :: KTNSMAX
#else
INTEGER(KIND=JPIM),INTENT(IN)    :: KLX 
INTEGER(KIND=JPIM),INTENT(IN)    :: KVXS 
INTEGER(KIND=JPIM),INTENT(IN)    :: KIX 
INTEGER(KIND=JPIM),INTENT(IN)    :: KVX
INTEGER(KIND=JPIM),INTENT(IN)    :: KTNSMAX
#endif 
REAL(KIND=JPRB) ,INTENT(IN) :: PA(KLX)
REAL(KIND=JPRB) ,INTENT(IN) :: PBI(KLX)
REAL(KIND=JPRB) ,INTENT(IN) :: PCI(KLX)
REAL(KIND=JPRB) ,INTENT(IN) :: PBS(KLX)
REAL(KIND=JPRB) ,INTENT(IN) :: PCS(KLX)
#if defined(_OPENACC)
REAL(KIND=JPRB) ,INTENT(IN) :: PX(KTNSMAX+1,KVXS,KIX)
REAL(KIND=JPRB) ,INTENT(OUT) :: PY(KTNSMAX+1,KVXS,KIX)
#else
REAL(KIND=JPRB) ,INTENT(IN) :: PX(KTNSMAX+1,KVXS,KIX)
REAL(KIND=JPRB) ,INTENT(OUT) :: PY(KTNSMAX+1,KVXS,KIX)
#endif
END SUBROUTINE MXPTMA
END INTERFACE
