INTERFACE
#if defined(_OPENACC)
SUBROUTINE MXTURE(KLX,KT,LDMT,PA,PB,PC,PY,PX,pas,pbs,pcs,pys,pxs)
!$acc routine vector
USE PARKIND1 ,ONLY : JPIM ,JPRB
INTEGER(KIND=JPIM),INTENT(IN), value :: KLX
INTEGER(KIND=JPIM),INTENT(IN),value :: KT
LOGICAL ,INTENT(IN),value :: LDMT
REAL(KIND=JPRB) ,INTENT(IN) :: PA(klx)
REAL(KIND=JPRB) ,INTENT(IN) :: PB(klx)
REAL(KIND=JPRB) ,INTENT(IN) :: PC(klx)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PY(klx)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PX(klx)
REAL(KIND=JPRB) ,INTENT(INout) :: PAs(97)
REAL(KIND=JPRB) ,INTENT(INout) :: PBs(97)
REAL(KIND=JPRB) ,INTENT(INout) :: PCs(97)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PYs(97)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PXs(97)
#else
SUBROUTINE MXTURE(KLX,KVX,KVXS,KIX,tnsmax,KT,LDMT,PA,PB,PC,PY,PX)
USE PARKIND1 ,ONLY : JPIM ,JPRB
INTEGER(KIND=JPIM),INTENT(IN) :: KLX
INTEGER(KIND=JPIM),INTENT(IN) :: KVX
INTEGER(KIND=JPIM),INTENT(IN) :: KVXS
INTEGER(KIND=JPIM),INTENT(IN) :: KIX
integer(kind=jpim),intent(in) :: tnsmax
INTEGER(KIND=JPIM),INTENT(IN) :: KT
LOGICAL ,INTENT(IN) :: LDMT
REAL(KIND=JPRB) ,INTENT(IN) :: PA(KVX,KLX)
REAL(KIND=JPRB) ,INTENT(IN) :: PB(KVX,KLX)
REAL(KIND=JPRB) ,INTENT(IN) :: PC(KVX,KLX)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PY(KVXS,tnsmax+1,KIX)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PX(KVXS,tnsmax+1,KIX)
#endif
END SUBROUTINE MXTURE
END INTERFACE
