INTERFACE
#if defined(_OPENACC)
SUBROUTINE MXTURS(KLX,KVX,KVXS,KIX,tnsmax,PA,PB,PC,PY,PX)
!$acc routine vector
#else
SUBROUTINE MXTURS(KLX,KVX,KVXS,KIX,PA,PB,PC,PY,PX)
#endif
USE PARKIND1  ,ONLY : JPIM     ,JPRB
USE YOMHOOK   ,ONLY : LHOOK,   DR_HOOK, JPHOOK
IMPLICIT NONE
INTEGER(KIND=JPIM),INTENT(IN)    :: KLX
INTEGER(KIND=JPIM),INTENT(IN)    :: KVX
INTEGER(KIND=JPIM),INTENT(IN)    :: KVXS
INTEGER(KIND=JPIM),INTENT(IN)    :: KIX
#if defined(_OPENACC)
integer(kind=JPIM),intent(in)    :: tnsmax
#endif
REAL(KIND=JPRB)   ,INTENT(IN)    :: PA(KVX,KLX)
REAL(KIND=JPRB)   ,INTENT(IN)    :: PB(KVX,KLX)
REAL(KIND=JPRB)   ,INTENT(IN)    :: PC(KVX,KLX)
#if defined(_OPENACC)
REAL(KIND=JPRB)   ,INTENT(INOUT) :: PY(KVXS,tnsmax+1,KIX)
REAL(KIND=JPRB)   ,INTENT(INOUT) :: PX(KVXS,tnsmax+1,KIX)
#else
REAL(KIND=JPRB)   ,INTENT(INOUT) :: PY(KVXS,KLX,KIX)
REAL(KIND=JPRB)   ,INTENT(INOUT) :: PX(KVXS,KLX,KIX)
#endif
END SUBROUTINE MXTURS

END INTERFACE
