INTERFACE
#if defined(_OPENACC)
SUBROUTINE MXTURS(KLX,KVX,KVXS,KIX,KIXS,KTNSMAX,PA,PB,PC,PY,PX,KTBLOC,PAS,PBS,PCS,PYS,PXS)
!$ACC ROUTINE VECTOR
USE PARKIND1 ,ONLY : JPIM ,JPRB
INTEGER(KIND=JPIM),INTENT(IN),VALUE :: KLX
INTEGER(KIND=JPIM),INTENT(IN),VALUE :: KVX
INTEGER(KIND=JPIM),INTENT(IN),VALUE :: KVXS
INTEGER(KIND=JPIM),INTENT(IN),VALUE :: KIX
INTEGER(KIND=JPIM),INTENT(IN),VALUE :: KIXS
INTEGER(KIND=JPIM),INTENT(IN),VALUE :: KTNSMAX
REAL(KIND=JPRB) ,INTENT(IN) :: PA(KLX,KVX)
REAL(KIND=JPRB) ,INTENT(IN) :: PB(KLX,KVX)
REAL(KIND=JPRB) ,INTENT(IN) :: PC(KLX,KVX)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PY(KTNSMAX+1,KIXS,KVX)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PX(KTNSMAX+1,KIXS,KVX)
INTEGER(KIND=JPIM),INTENT(IN),VALUE :: KTBLOC
REAL(KIND=JPRB) ,INTENT(INout) :: PAS(KTBLOC+3,KVXS)
REAL(KIND=JPRB) ,INTENT(INout) :: PBS(KTBLOC+3,KVXS)
REAL(KIND=JPRB) ,INTENT(INout) :: PCS(KTBLOC+3,KVXS)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PYS(KTBLOC+3,KVXS,KIXS)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PXS(KTBLOC+3,KVXS,KIXS)
#else
SUBROUTINE MXTURS(KLX,KVX,KVXS,KIX,KTNSMAX,PA,PB,PC,PY,PX)
USE PARKIND1 ,ONLY : JPIM ,JPRB
INTEGER(KIND=JPIM),INTENT(IN) :: KLX
INTEGER(KIND=JPIM),INTENT(IN) :: KVX
INTEGER(KIND=JPIM),INTENT(IN) :: KVXS
INTEGER(KIND=JPIM),INTENT(IN) :: KIX
INTEGER(KIND=JPIM),INTENT(IN) :: KTNSMAX
REAL(KIND=JPRB) ,INTENT(IN) :: PA(KVX,KLX)
REAL(KIND=JPRB) ,INTENT(IN) :: PB(KVX,KLX)
REAL(KIND=JPRB) ,INTENT(IN) :: PC(KVX,KLX)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PY(KVXS,KTNSMAX+1,KIX)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PX(KVXS,KTNSMAX+1,KIX)
#endif
END SUBROUTINE MXTURS
END INTERFACE
