INTERFACE
#if defined(_OPENACC)
SUBROUTINE MXTURS(KLX,KVX,KVXS,KIX,KIXS,tnsmax,PA,PB,PC,PY,PX,tbloc,pas,pbs,pcs,pys,pxs)
!$acc routine vector
USE PARKIND1 ,ONLY : JPIM ,JPRB
INTEGER(KIND=JPIM),INTENT(IN),value :: KLX
INTEGER(KIND=JPIM),INTENT(IN),value :: KVX
INTEGER(KIND=JPIM),INTENT(IN),value :: KVXS
INTEGER(KIND=JPIM),INTENT(IN),value :: KIX
INTEGER(KIND=JPIM),INTENT(IN),value :: KIXS
INTEGER(KIND=JPIM),INTENT(IN),value :: tnsmax
REAL(KIND=JPRB) ,INTENT(IN) :: PA(klx,kvx)
REAL(KIND=JPRB) ,INTENT(IN) :: PB(klx,kvx)
REAL(KIND=JPRB) ,INTENT(IN) :: PC(klx,kvx)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PY(tnsmax+1,kixs,kvx)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PX(tnsmax+1,kixs,kvx)
integer(kind=jpim),intent(in),value :: tbloc
REAL(KIND=JPRB) ,INTENT(INout) :: PAs(tbloc+3,kvxs)
REAL(KIND=JPRB) ,INTENT(INout) :: PBs(tbloc+3,kvxs)
REAL(KIND=JPRB) ,INTENT(INout) :: PCs(tbloc+3,kvxs)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PYs(tbloc+3,kvxs,kixs)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PXs(tbloc+3,kvxs,kixs)
#else
SUBROUTINE MXTURS(KLX,KVX,KVXS,KIX,tnsmax,PA,PB,PC,PY,PX)
USE PARKIND1 ,ONLY : JPIM ,JPRB
INTEGER(KIND=JPIM),INTENT(IN) :: KLX
INTEGER(KIND=JPIM),INTENT(IN) :: KVX
INTEGER(KIND=JPIM),INTENT(IN) :: KVXS
INTEGER(KIND=JPIM),INTENT(IN) :: KIX
integer(kind=JPIM),intent(in) :: tnsmax
REAL(KIND=JPRB) ,INTENT(IN) :: PA(KVX,KLX)
REAL(KIND=JPRB) ,INTENT(IN) :: PB(KVX,KLX)
REAL(KIND=JPRB) ,INTENT(IN) :: PC(KVX,KLX)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PY(KVXS,tnsmax+1,KIX)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PX(KVXS,tnsmax+1,KIX)
#endif
END SUBROUTINE MXTURS
END INTERFACE
