INTERFACE
SUBROUTINE SET2PE(KPE,KPRGPNS,KPRGPEW,KPRTRW,KPRTRV)
USE PARKIND1 , ONLY : JPIM, JPRB
USE YOMHOOK  , ONLY : LHOOK, DR_HOOK, JPHOOK
USE YOMMP0   , ONLY : NPRGPNS, NPRGPEW, NPRTRW, NPRTRV, LMPOFF, LEQ_REGIONS, N_REGIONS_NS, N_REGIONS
USE YOMLUN   , ONLY : NULERR
USE MPL_MODULE
IMPLICIT NONE
INTEGER(KIND=JPIM),INTENT(OUT)   :: KPE
INTEGER(KIND=JPIM),INTENT(IN)    :: KPRGPNS
INTEGER(KIND=JPIM),INTENT(IN)    :: KPRGPEW
INTEGER(KIND=JPIM),INTENT(IN)    :: KPRTRW
INTEGER(KIND=JPIM),INTENT(IN)    :: KPRTRV
END SUBROUTINE SET2PE

END INTERFACE
