INTERFACE

#if defined(_OPENACC)
SUBROUTINE SITNU_SP_OPENMP (YDGEOMETRY, YDCST, YDDYN, KLEV, KSPEC, PD, PT, PSP,zsdiv,zout)
#else
SUBROUTINE SITNU_SP_OPENMP (YDGEOMETRY, YDCST, YDDYN, KLEV, KSPEC, PD, PT, PSP)
#endif
USE GEOMETRY_MOD , ONLY : GEOMETRY
USE PARKIND1     , ONLY : JPIM, JPRB
USE YOMHOOK      , ONLY : LHOOK, DR_HOOK, JPHOOK
USE YOMCST       , ONLY : TCST
USE YOMDYN       , ONLY : TDYN
IMPLICIT NONE
TYPE(GEOMETRY)    ,INTENT(IN)    :: YDGEOMETRY
TYPE(TCST)        ,INTENT(IN)    :: YDCST
TYPE(TDYN)        ,INTENT(IN)    :: YDDYN
INTEGER(KIND=JPIM),INTENT(IN)    :: KLEV
INTEGER(KIND=JPIM),INTENT(IN)    :: KSPEC

REAL(KIND=JPRB)   ,INTENT(IN)    :: PD(KSPEC,klev)
REAL(KIND=JPRB)   ,INTENT(OUT)   :: PT(KSPEC,klev)
REAL(KIND=JPRB)   ,INTENT(OUT)   :: PSP(KSPEC)
#if defined(_OPENACC)
REAL(KIND=JPRB), intent(inout)   :: ZSDIV(KSPEC,0:KLEV+1)
REAL(KIND=JPRB), intent(inout)   :: ZOUT(KSPEC,0:KLEV)
#endif
END SUBROUTINE SITNU_SP_OPENMP

END INTERFACE
