INTERFACE
SUBROUTINE SITNU_GP (YDGEOMETRY, YDCST, YDDYN, KLON, KLEV, PD, PT, PSP)
USE GEOMETRY_MOD , ONLY : GEOMETRY
USE PARKIND1     , ONLY : JPIM, JPRB
USE YOMHOOK      , ONLY : LHOOK, DR_HOOK, JPHOOK
USE YOMCST       , ONLY : TCST
USE YOMDYN       , ONLY : TDYN
TYPE(GEOMETRY)    ,INTENT(IN)    :: YDGEOMETRY
TYPE(TCST)        ,INTENT(IN)    :: YDCST
TYPE(TDYN)        ,INTENT(IN)    :: YDDYN
INTEGER(KIND=JPIM),INTENT(IN)    :: KLEV
INTEGER(KIND=JPIM),INTENT(IN)    :: KLON
REAL(KIND=JPRB)   ,INTENT(IN)    :: PD(KLON,KLEV)
REAL(KIND=JPRB)   ,INTENT(OUT)   :: PT(KLON,KLEV)
REAL(KIND=JPRB)   ,INTENT(OUT)   :: PSP(KLON)
END SUBROUTINE SITNU_GP

END INTERFACE
