INTERFACE
SUBROUTINE SPCIMPFPOST(YDCST,YDGEOMETRY,YDRIP,YDDYN,KM,KSTA,KEND,PSPDIV,PSPVOR)
USE GEOMETRY_MOD , ONLY : GEOMETRY
USE PARKIND1     , ONLY : JPIM, JPRB
USE YOMHOOK      , ONLY : LHOOK, DR_HOOK, JPHOOK
USE YOMCST       , ONLY : TCST
USE YOMDYN       , ONLY : TDYN
USE YOMRIP       , ONLY : TRIP
IMPLICIT NONE
TYPE(TCST)        ,INTENT(IN)    :: YDCST
TYPE(GEOMETRY)    ,INTENT(IN)    :: YDGEOMETRY
TYPE(TDYN)        ,INTENT(IN)    :: YDDYN
TYPE(TRIP)        ,INTENT(IN)    :: YDRIP
INTEGER(KIND=JPIM),INTENT(IN)    :: KM
INTEGER(KIND=JPIM),INTENT(IN)    :: KSTA
INTEGER(KIND=JPIM),INTENT(IN)    :: KEND
REAL(KIND=JPRB)   ,INTENT(IN)    :: PSPDIV(:,:)
REAL(KIND=JPRB)   ,INTENT(INOUT) :: PSPVOR(:,:)
END SUBROUTINE SPCIMPFPOST

END INTERFACE
