INTERFACE
SUBROUTINE SPCIMPFSOLVE(&
& YDGEOMETRY,YDCST,YDRIP,YDDYN,LDNHDYN,LDNHX,LDONEM,PSDIVP,&
& PSPDIVP)
USE GEOMETRY_MOD , ONLY : GEOMETRY
USE PARKIND1     , ONLY : JPIM, JPRB
USE YOMHOOK      , ONLY : LHOOK, DR_HOOK, JPHOOK
USE YOMDYN       , ONLY : TDYN
USE YOMRIP       , ONLY : TRIP
USE YOMCST       , ONLY : TCST
IMPLICIT NONE
TYPE(GEOMETRY)    ,INTENT(IN)    :: YDGEOMETRY
TYPE(TCST)        ,INTENT(IN)    :: YDCST
TYPE(TDYN)        ,INTENT(IN)    :: YDDYN
LOGICAL           ,INTENT(IN)    :: LDNHDYN
LOGICAL           ,INTENT(IN)    :: LDNHX
TYPE(TRIP)        ,INTENT(IN)    :: YDRIP
LOGICAL           ,INTENT(IN)    :: LDONEM
REAL(KIND=JPRB)   ,INTENT(IN)    :: PSDIVP (:,:)
REAL(KIND=JPRB)   ,INTENT(OUT)   :: PSPDIVP(:,:)
END SUBROUTINE SPCIMPFSOLVE

END INTERFACE
