#if defined(_OPENACC)
SUBROUTINE SPCM_SIMPLE (YDGEOMETRY,YDMODEL,PSPSP,PSPVOR,PSPDIV,PSPT,PSPSPD,PSPSVD,zbuf_m,zbuf_s)
#else
SUBROUTINE SPCM_SIMPLE (YDGEOMETRY,YDMODEL,PSPSP,PSPVOR,PSPDIV,PSPT,PSPSPD,PSPSVD)
#endif

USE TYPE_MODEL         , ONLY : MODEL
USE GEOMETRY_MOD       , ONLY : GEOMETRY
USE PARKIND1           , ONLY : JPIM, JPRB
USE YOMHOOK            , ONLY : LHOOK, DR_HOOK, JPHOOK

!     ------------------------------------------------------------------

IMPLICIT NONE

TYPE(GEOMETRY)      ,INTENT(IN)    :: YDGEOMETRY
TYPE(MODEL)         ,INTENT(INOUT) :: YDMODEL
REAL(KIND=JPRB)     ,INTENT(INOUT) :: PSPSP (YDGEOMETRY%YRDIM%NSPEC2)
REAL(KIND=JPRB)     ,INTENT(INOUT) :: PSPVOR(YDGEOMETRY%YRDIMV%NFLEVL,YDGEOMETRY%YRDIM%NSPEC2)
REAL(KIND=JPRB)     ,INTENT(INOUT) :: PSPDIV(YDGEOMETRY%YRDIMV%NFLEVL,YDGEOMETRY%YRDIM%NSPEC2)
REAL(KIND=JPRB)     ,INTENT(INOUT) :: PSPT  (YDGEOMETRY%YRDIMV%NFLEVL,YDGEOMETRY%YRDIM%NSPEC2)
REAL(KIND=JPRB)     ,INTENT(INOUT) :: PSPSPD(YDGEOMETRY%YRDIMV%NFLEVL,YDGEOMETRY%YRDIM%NSPEC2)
REAL(KIND=JPRB)     ,INTENT(INOUT) :: PSPSVD(YDGEOMETRY%YRDIMV%NFLEVL,YDGEOMETRY%YRDIM%NSPEC2)

#include "spcsi_cor.intfb.h"
#include "spcsi_str.intfb.h"
#include "trmtos.intfb.h"
#include "trstom.intfb.h"
#include "spcimpfinit.intfb.h"
#include "spcimpfpost.intfb.h"

#if defined(_OPENACC)
real(kind=jprb), intent(inout)  :: zbuf_m(:,:)
real(kind=jprb), intent(inout)  :: zbuf_s(:,:)
REAL(KIND=JPRB)  :: zsdiv(max(YDGEOMETRY%YRMP%NSPEC2V,YDGEOMETRY%YRMP%NSPEC2VF),YDGEOMETRY%YRDIMV%NFLEVG)
REAL(KIND=JPRB)  :: zhelp(max(YDGEOMETRY%YRMP%NSPEC2V,YDGEOMETRY%YRMP%NSPEC2VF),YDGEOMETRY%YRDIMV%NFLEVG)
REAL(KIND=JPRB)  :: zst(max(YDGEOMETRY%YRMP%NSPEC2V,YDGEOMETRY%YRMP%NSPEC2VF),YDGEOMETRY%YRDIMV%NFLEVG)
REAL(KIND=JPRB)  :: zsp(max(YDGEOMETRY%YRMP%NSPEC2V,YDGEOMETRY%YRMP%NSPEC2VF),YDGEOMETRY%YRDIMV%NFLEVG)
REAL(KIND=JPRB)  :: zsdivp(max(YDGEOMETRY%YRMP%NSPEC2V,YDGEOMETRY%YRMP%NSPEC2VF),YDGEOMETRY%YRDIMV%NFLEVG)
REAL(KIND=JPRB)  :: zspdivp(max(YDGEOMETRY%YRMP%NSPEC2V,YDGEOMETRY%YRMP%NSPEC2VF),YDGEOMETRY%YRDIMV%NFLEVG)
REAL(KIND=JPRB)  :: zsphi(max(YDGEOMETRY%YRMP%NSPEC2V,YDGEOMETRY%YRMP%NSPEC2VF),0:YDGEOMETRY%YRDIMV%NFLEVG+1)
REAL(KIND=JPRB)  :: zout(max(YDGEOMETRY%YRMP%NSPEC2V,YDGEOMETRY%YRMP%NSPEC2VF),0:YDGEOMETRY%YRDIMV%NFLEVG)
real(kind=JPRB)  :: zsdivpl(ydgeometry%yrdimv%nflevg,ydgeometry%yrdim%nsmax+1,2)
real(kind=JPRB)  :: zspdivpl(ydgeometry%yrdimv%nflevg,ydgeometry%yrdim%nsmax+1,2)
#endif

REAL(KIND=JPRB), ALLOCATABLE :: ZSPVORG2(:,:)
REAL(KIND=JPRB), ALLOCATABLE :: ZSPDIVG2(:,:)
REAL(KIND=JPRB), ALLOCATABLE :: ZSPTG2  (:,:)
REAL(KIND=JPRB), ALLOCATABLE :: ZSPSPDG2(:,:)
REAL(KIND=JPRB), ALLOCATABLE :: ZSPSVDG2(:,:)
REAL(KIND=JPRB), ALLOCATABLE :: ZSPSPG2 (:)
REAL(KIND=JPRB), ALLOCATABLE :: ZSPVORG(:,:)
REAL(KIND=JPRB), ALLOCATABLE :: ZSPDIVG(:,:)
REAL(KIND=JPRB), ALLOCATABLE :: ZSPTG  (:,:)
REAL(KIND=JPRB), ALLOCATABLE :: ZSPSPDG(:,:)
REAL(KIND=JPRB), ALLOCATABLE :: ZSPSVDG(:,:)
REAL(KIND=JPRB), ALLOCATABLE :: ZSPSPG (:)
REAL(KIND=JPRB), ALLOCATABLE :: ZSPTNDSI_VORG(:,:)
REAL(KIND=JPRB), ALLOCATABLE :: ZSPTNDSI_DIVG(:,:)
REAL(KIND=JPRB), ALLOCATABLE :: ZSPTNDSI_TG(:,:)
REAL(KIND=JPRB), ALLOCATABLE :: ZSPAUX (:,:)
REAL(KIND=JPRB), ALLOCATABLE :: ZSPAUXG(:,:)
REAL(KIND=JPRB), ALLOCATABLE :: PSPVOR2(:,:)
REAL(KIND=JPRB), ALLOCATABLE :: PSPDIV2(:,:)
REAL(KIND=JPRB), ALLOCATABLE :: PSPT2  (:,:)
REAL(KIND=JPRB), ALLOCATABLE :: PSPSPD2(:,:)
REAL(KIND=JPRB), ALLOCATABLE :: PSPSVD2(:,:)
REAL(KIND=JPRB), ALLOCATABLE :: PSPSP2 (:)

LOGICAL :: LLONEM

INTEGER(KIND=JPIM) :: IM, ISPEC2V
INTEGER (KIND=JPIM) :: JMLOC, ISTA, IEND

REAL(KIND=JPHOOK) ::  ZHOOK_HANDLE,zhook_handle2
integer(kind=jpim)::  compteur1,compteur2

IF (LHOOK) CALL DR_HOOK('SPCM_SIMPLE',0,ZHOOK_HANDLE)

ASSOCIATE(YDDIM=>YDGEOMETRY%YRDIM,YDDIMV=>YDGEOMETRY%YRDIMV,  YDMP=>YDGEOMETRY%YRMP, YDDYN=>YDMODEL%YRML_DYN%YRDYN,   &
&  YDDYNA=>YDMODEL%YRML_DYN%YRDYNA, YDLDDH=>YDMODEL%YRML_DIAG%YRLDDH, YDSPDDH=>YDMODEL%YRML_DIAG%YRSPDDH, &
&  YDLAP=>YDGEOMETRY%YRLAP)

ASSOCIATE(NFLEVG=>YDDIMV%NFLEVG, NSPEC2V=>YDMP%NSPEC2V, NSPEC2VF=>YDMP%NSPEC2VF, LIMPF=>YDDYN%LIMPF, &
& NFLSUR=>YDDIMV%NFLSUR, NSPEC2=>YDDIM%NSPEC2, NUMP=>YDDIM%NUMP, NSMAX=>YDDIM%NSMAX,nflevl=>yddimv%nflevl)

LLONEM = .NOT. LIMPF

IF (LLONEM) THEN
  ISPEC2V=NSPEC2VF
ELSE
  ISPEC2V=NSPEC2V
ENDIF

ALLOCATE(ZSPVORG2(NFLEVG,ISPEC2V))
ALLOCATE(ZSPDIVG2(NFLEVG,ISPEC2V))
ALLOCATE(ZSPTG2  (NFLEVG,ISPEC2V))
ALLOCATE(ZSPSPDG2(NFLEVG,ISPEC2V))
ALLOCATE(ZSPSVDG2(NFLEVG,ISPEC2V))
ALLOCATE(ZSPSPG2 (ISPEC2V))

ALLOCATE(PSPVOR2(nspec2,nflevl))
ALLOCATE(PSPDIV2(nspec2,nflevl))
ALLOCATE(PSPT2  (nspec2,nflevl))
ALLOCATE(PSPSPD2(nspec2,nflevl))
ALLOCATE(PSPSVD2(nspec2,nflevl))
ALLOCATE(PSPSP2 (nspec2))


#if defined(_OPENACC)
ALLOCATE(ZSPVORG(ISPEC2V,nflevg))
ALLOCATE(ZSPDIVG(ISPEC2V,nflevg))
ALLOCATE(ZSPTG  (ISPEC2V,nflevg))
ALLOCATE(ZSPSPDG(ISPEC2V,nflevg))
ALLOCATE(ZSPSVDG(ISPEC2V,nflevg))
ALLOCATE(ZSPSPG (ISPEC2V))
#else
ALLOCATE(ZSPVORG(NFLEVG,ISPEC2V))
ALLOCATE(ZSPDIVG(NFLEVG,ISPEC2V))
ALLOCATE(ZSPTG  (NFLEVG,ISPEC2V))
ALLOCATE(ZSPSPDG(NFLEVG,ISPEC2V))
ALLOCATE(ZSPSVDG(NFLEVG,ISPEC2V))
ALLOCATE(ZSPSPG (ISPEC2V))
#endif

ALLOCATE(ZSPTNDSI_VORG(1,1))
ALLOCATE(ZSPTNDSI_DIVG(1,1))
ALLOCATE(ZSPTNDSI_TG(1,1))

IF (LIMPF) THEN
  ALLOCATE(ZSPAUX(NFLSUR,NSPEC2))
  ALLOCATE(ZSPAUXG(NFLEVG,ISPEC2V))

!$OMP PARALLEL DO SCHEDULE(STATIC,1) PRIVATE(JMLOC,IM,ISTA,IEND)
  DO JMLOC=1,NUMP
    IM=YDLAP%MYMS(JMLOC)
    ISTA=YDLAP%NASM0(IM)
    IEND=ISTA+2*(NSMAX+1-IM)-1
    CALL SPCIMPFINIT(YDMODEL%YRCST,YDGEOMETRY,YDMODEL%YRML_GCONF%YRRIP,YDDYN,IM,ISTA,IEND,PSPVOR,ZSPAUX)
  ENDDO
!$OMP END PARALLEL DO

#if defined(_OPENACC)
  CALL TRMTOS(YDGEOMETRY,YDDYNA%LNHDYN,YDDYNA%LNHX,zbuf_m,zbuf_s,&
    & PSPVOR=PSPVOR,PSPDIV=PSPDIV,PSPT=PSPT,PSPSPD=PSPSPD,&
    & PSPSVD=PSPSVD,PSPSP=PSPSP,PSPAUX=ZSPAUX,& 
    & PSPVORG=ZSPVORG,PSPDIVG=ZSPDIVG,PSPTG=ZSPTG,PSPSPDG=ZSPSPDG,&
    & PSPSVDG=ZSPSVDG,PSPSPG=ZSPSPG,PSPAUXG=ZSPAUXG,&
    & LDFULLM=LLONEM)

  CALL SPCSI_COR(YDGEOMETRY, YDMODEL%YRCST, YDLDDH, YDMODEL%YRML_GCONF%YRRIP, YDDYN, ISPEC2V, &
  & LLONEM, ZSPVORG, ZSPDIVG, ZSPTG, ZSPSPG, ZSPTNDSI_VORG, ZSPTNDSI_DIVG, ZSPTNDSI_TG,       &
  & PSPAUXG=ZSPAUXG)

  CALL TRSTOM(&
    & YDGEOMETRY,YDDYNA%LNHDYN,YDDYNA%LNHX,zbuf_m,zbuf_s,&
    & PSPVORG=ZSPVORG,PSPDIVG=ZSPDIVG,PSPTG=ZSPTG,PSPSPDG=ZSPSPDG,&
    & PSPSVDG=ZSPSVDG,PSPSPG=ZSPSPG,&
    & PSPVOR=PSPVOR,PSPDIV=PSPDIV,PSPT=PSPT,PSPSPD=PSPSPD,&
    & PSPSVD=PSPSVD,PSPSP=PSPSP,&
    & LDFULLM=LLONEM,LDNEEDPS=.TRUE.)  
#else
  CALL TRMTOS(YDGEOMETRY,YDDYNA%LNHDYN,YDDYNA%LNHX,&
    & PSPVOR=PSPVOR,PSPDIV=PSPDIV,PSPT=PSPT,PSPSPD=PSPSPD,&
    & PSPSVD=PSPSVD,PSPSP=PSPSP,PSPAUX=ZSPAUX,& 
    & PSPVORG=ZSPVORG,PSPDIVG=ZSPDIVG,PSPTG=ZSPTG,PSPSPDG=ZSPSPDG,&
    & PSPSVDG=ZSPSVDG,PSPSPG=ZSPSPG,PSPAUXG=ZSPAUXG,&
    & LDFULLM=LLONEM)

  CALL SPCSI_COR(YDGEOMETRY, YDMODEL%YRCST, YDLDDH, YDMODEL%YRML_GCONF%YRRIP, YDDYN, ISPEC2V, &
  & LLONEM, ZSPVORG, ZSPDIVG, ZSPTG, ZSPSPG, ZSPTNDSI_VORG, ZSPTNDSI_DIVG, ZSPTNDSI_TG,       &
  & PSPAUXG=ZSPAUXG)

  CALL TRSTOM(&
    & YDGEOMETRY,YDDYNA%LNHDYN,YDDYNA%LNHX,&
    & PSPVORG=ZSPVORG,PSPDIVG=ZSPDIVG,PSPTG=ZSPTG,PSPSPDG=ZSPSPDG,&
    & PSPSVDG=ZSPSVDG,PSPSPG=ZSPSPG,&
    & PSPVOR=PSPVOR,PSPDIV=PSPDIV,PSPT=PSPT,PSPSPD=PSPSPD,&
    & PSPSVD=PSPSVD,PSPSP=PSPSP,&
    & LDFULLM=LLONEM,LDNEEDPS=.TRUE.)  

#endif

!$OMP PARALLEL DO SCHEDULE(STATIC,1) PRIVATE(JMLOC,IM,ISTA,IEND)
    DO JMLOC=1,NUMP
      IM=YDLAP%MYMS(JMLOC)
      ISTA=YDLAP%NASM0(IM)
      IEND=ISTA+2*(NSMAX+1-IM)-1
      CALL SPCIMPFPOST(YDMODEL%YRCST,YDGEOMETRY,YDMODEL%YRML_GCONF%YRRIP,YDDYN,IM,ISTA,IEND,PSPDIV,PSPVOR)
    ENDDO
!$OMP END PARALLEL DO

ELSE
#if defined(_OPENACC)
    pspsp2(:)=pspsp(:)
    do compteur1=1,nspec2
      do compteur2=1,nflevl
        pspvor2(compteur1,compteur2)=pspvor(compteur2,compteur1)
        pspdiv2(compteur1,compteur2)=pspdiv(compteur2,compteur1)
        pspt2(compteur1,compteur2)=pspt(compteur2,compteur1)
        pspspd2(compteur1,compteur2)=pspspd(compteur2,compteur1)
        pspsvd2(compteur1,compteur2)=pspsvd(compteur2,compteur1)
      enddo
    enddo

    if (lhook) call dr_hook('SPCM_SIMPLE_transferts1a',0,zhook_handle2)
    !$acc data copy(zspdivg,zsptg,zspspg) create(zsdivpl,zspdivpl)
    if (lhook) call dr_hook('SPCM_SIMPLE_transferts1a',1,zhook_handle2)
    if (lhook) call dr_hook('SPCM_SIMPLE_transferts1b',0,zhook_handle2)
    !$acc data create(zsdiv,zhelp,zsp,zst,zsphi,zout,zsdivp,zspdivp)
    if (lhook) call dr_hook('SPCM_SIMPLE_transferts1b',1,zhook_handle2)
    if (lhook) call dr_hook('SPCM_SIMPLE_transferts1c',0,zhook_handle2)
    !$acc data create(pspsp2,pspvor2,pspdiv2,pspt2,pspspd2,pspsvd2)
    if (lhook) call dr_hook('SPCM_SIMPLE_transferts1c',1,zhook_handle2)
 

  CALL TRMTOS(YDGEOMETRY,YDDYNA%LNHDYN,YDDYNA%LNHX,zbuf_m,zbuf_s,&
    & PSPVOR=PSPVOR2,PSPDIV=PSPDIV2,PSPT=PSPT2,PSPSPD=PSPSPD2,&
    & PSPSVD=PSPSVD2,PSPSP=PSPSP2,&
    & PSPVORG=ZSPVORG,PSPDIVG=ZSPDIVG,PSPTG=ZSPTG,PSPSPDG=ZSPSPDG,&
    & PSPSVDG=ZSPSVDG,PSPSPG=ZSPSPG,&
    & LDFULLM=LLONEM)

  CALL SPCSI_STR(YDGEOMETRY, YDMODEL%YRCST, YDLDDH, YDMODEL%YRML_GCONF%YRRIP, YDDYN, ISPEC2V, &
  & ZSPVORG, ZSPDIVG, ZSPTG, ZSPSPG, ZSPTNDSI_VORG, ZSPTNDSI_DIVG, ZSPTNDSI_TG,&
  & zsdiv,zhelp,zsp,zst,zsdivp,zspdivp,zsphi,zout,zsdivpl,zspdivpl)

  CALL TRSTOM(&
    & YDGEOMETRY,YDDYNA%LNHDYN,YDDYNA%LNHX,zbuf_m,zbuf_s,&
    & PSPVORG=ZSPVORG,PSPDIVG=ZSPDIVG,PSPTG=ZSPTG,PSPSPDG=ZSPSPDG,&
    & PSPSVDG=ZSPSVDG,PSPSPG=ZSPSPG,&
    & PSPVOR=PSPVOR2,PSPDIV=PSPDIV2,PSPT=PSPT2,PSPSPD=PSPSPD2,&
    & PSPSVD=PSPSVD2,PSPSP=PSPSP2,&
    & LDFULLM=LLONEM,LDNEEDPS=.TRUE.)  

    zspspg(:)=zspspg2(:)
    do compteur2=1,nspec2
      do compteur1=1,nflevl
        pspvor(compteur1,compteur2)=pspvor2(compteur2,compteur1)
        pspdiv(compteur1,compteur2)=pspdiv2(compteur2,compteur1)
        pspt(compteur1,compteur2)=pspt2(compteur2,compteur1)
        pspspd(compteur1,compteur2)=pspspd2(compteur2,compteur1)
        pspsvd(compteur1,compteur2)=pspsvd2(compteur2,compteur1)
      enddo
    enddo

    if (lhook) call dr_hook('SPCM_SIMPLE_transferts2c',0,zhook_handle2)
    !$acc end data
    if (lhook) call dr_hook('SPCM_SIMPLE_transferts2c',1,zhook_handle2)
    if (lhook) call dr_hook('SPCM_SIMPLE_transferts2b',0,zhook_handle2)
    !$acc end data
    if (lhook) call dr_hook('SPCM_SIMPLE_transferts2b',1,zhook_handle2)
    if (lhook) call dr_hook('SPCM_SIMPLE_transferts2a',0,zhook_handle2)
    !$acc end data
    if (lhook) call dr_hook('SPCM_SIMPLE_transferts2a',1,zhook_handle2)

#else

!!    if (lhook) call dr_hook('SPCM_SIMPLE_transpose1',0,zhook_handle2)
  CALL TRMTOS(YDGEOMETRY,YDDYNA%LNHDYN,YDDYNA%LNHX,&
    & PSPVOR=PSPVOR,PSPDIV=PSPDIV,PSPT=PSPT,PSPSPD=PSPSPD,&
    & PSPSVD=PSPSVD,PSPSP=PSPSP,&
    & PSPVORG=ZSPVORG,PSPDIVG=ZSPDIVG,PSPTG=ZSPTG,PSPSPDG=ZSPSPDG,&
    & PSPSVDG=ZSPSVDG,PSPSPG=ZSPSPG,&
    & LDFULLM=LLONEM)

  CALL SPCSI_STR(YDGEOMETRY, YDMODEL%YRCST, YDLDDH, YDMODEL%YRML_GCONF%YRRIP, YDDYN, ISPEC2V, &
  & ZSPVORG, ZSPDIVG, ZSPTG, ZSPSPG, ZSPTNDSI_VORG, ZSPTNDSI_DIVG, ZSPTNDSI_TG)

  CALL TRSTOM(&
    & YDGEOMETRY,YDDYNA%LNHDYN,YDDYNA%LNHX,&
    & PSPVORG=ZSPVORG,PSPDIVG=ZSPDIVG,PSPTG=ZSPTG,PSPSPDG=ZSPSPDG,&
    & PSPSVDG=ZSPSVDG,PSPSPG=ZSPSPG,&
    & PSPVOR=PSPVOR,PSPDIV=PSPDIV,PSPT=PSPT,PSPSPD=PSPSPD,&
    & PSPSVD=PSPSVD,PSPSP=PSPSP,&
    & LDFULLM=LLONEM,LDNEEDPS=.TRUE.)  

#endif

   !! if (lhook) call dr_hook('SPCM_SIMPLE_transpose2',1,zhook_handle2)




ENDIF

IF (ALLOCATED(ZSPVORG)) DEALLOCATE(ZSPVORG)
IF (ALLOCATED(ZSPDIVG)) DEALLOCATE(ZSPDIVG)
IF (ALLOCATED(ZSPTG))   DEALLOCATE(ZSPTG)
IF (ALLOCATED(ZSPSPDG)) DEALLOCATE(ZSPSPDG)
IF (ALLOCATED(ZSPSVDG)) DEALLOCATE(ZSPSVDG)
IF (ALLOCATED(ZSPSPG))  DEALLOCATE(ZSPSPG)

IF (ALLOCATED(ZSPVORG2)) DEALLOCATE(ZSPVORG2)
IF (ALLOCATED(ZSPDIVG2)) DEALLOCATE(ZSPDIVG2)
IF (ALLOCATED(ZSPTG2))   DEALLOCATE(ZSPTG2)
IF (ALLOCATED(ZSPSPDG2)) DEALLOCATE(ZSPSPDG2)
IF (ALLOCATED(ZSPSVDG2)) DEALLOCATE(ZSPSVDG2)
IF (ALLOCATED(ZSPSPG2))  DEALLOCATE(ZSPSPG2)

if (allocated(pspvor2)) DEALLOCATE(PSPVOR2)
if (allocated(pspdiv2)) DEALLOCATE(PSPDIV2)
if (allocated(pspt2)) DEALLOCATE(PSPT2)
if (allocated(pspspd2)) DEALLOCATE(PSPSPD2)
if (allocated(pspsvd2)) DEALLOCATE(PSPSVD2)
if (allocated(pspsp2)) DEALLOCATE(PSPSP2)

IF (ALLOCATED(ZSPTNDSI_VORG)) DEALLOCATE(ZSPTNDSI_VORG)
IF (ALLOCATED(ZSPTNDSI_DIVG)) DEALLOCATE(ZSPTNDSI_DIVG)
IF (ALLOCATED(ZSPTNDSI_TG))   DEALLOCATE(ZSPTNDSI_TG)

END ASSOCIATE
END ASSOCIATE

IF (LHOOK) CALL DR_HOOK('SPCM_SIMPLE',1,ZHOOK_HANDLE)

END SUBROUTINE SPCM_SIMPLE

