PROGRAM SPCM

USE XRD_GETOPTIONS
USE TYPE_MODEL         , ONLY : MODEL
USE GEOMETRY_MOD       , ONLY : GEOMETRY
USE PARKIND1           , ONLY : JPIM, JPRB
USE YOMHOOK            , ONLY : LHOOK, DR_HOOK, JPHOOK
USE MPL_MPIF           , ONLY : MPI_COMM_WORLD, MPI_THREAD_MULTIPLE, MPI_THREAD_SINGLE, MPI_WTIME
USE MPL_MODULE         , ONLY : MPL_INIT, MPL_END
USE MPL_BARRIER_MOD    , ONLY : MPL_BARRIER

USE UTIL_MODEL_MOD
USE UTIL_GEOMETRY_MOD
USE UTIL_YOMMP0_MOD, ONLY : LOAD_YOMMP0

IMPLICIT NONE

TYPE(GEOMETRY)      :: YDGEOMETRY
TYPE(MODEL)         :: YDMODEL

REAL(KIND=JPRB), ALLOCATABLE :: PSPSP (:)
REAL(KIND=JPRB), ALLOCATABLE :: PSPVOR(:,:)
REAL(KIND=JPRB), ALLOCATABLE :: PSPDIV(:,:)
REAL(KIND=JPRB), ALLOCATABLE :: PSPT  (:,:)
REAL(KIND=JPRB), ALLOCATABLE :: PSPSPD(:,:)
REAL(KIND=JPRB), ALLOCATABLE :: PSPSVD(:,:)

REAL(KIND=JPRB), ALLOCATABLE :: ZSPSP (:)
REAL(KIND=JPRB), ALLOCATABLE :: ZSPVOR(:,:)
REAL(KIND=JPRB), ALLOCATABLE :: ZSPDIV(:,:)
REAL(KIND=JPRB), ALLOCATABLE :: ZSPT  (:,:)
REAL(KIND=JPRB), ALLOCATABLE :: ZSPSPD(:,:)
REAL(KIND=JPRB), ALLOCATABLE :: ZSPSVD(:,:)

INTEGER (KIND=JPIM) :: MYPROC
INTEGER (KIND=JPIM) :: NSMAX
INTEGER (KIND=JPIM) :: NDGLG
INTEGER (KIND=JPIM), ALLOCATABLE :: NLOENG (:)
INTEGER (KIND=JPIM) :: NRESOL
LOGICAL :: LSPLIT
LOGICAL :: LUSEFLT
LOGICAL :: LUSERPNM
LOGICAL :: LKEEPRPNM
LOGICAL :: LFFTW

INTEGER (KIND=JPIM) :: NPRGPNS
INTEGER (KIND=JPIM) :: NPRGPEW
INTEGER (KIND=JPIM) :: NPRTRW
LOGICAL :: LEQ_REGIONS
REAL (KIND=JPRB) :: RA

#include "spcm_simple.intfb.h"
#include "setup_trans0.h"
#include "setup_trans.h"
#include "abor1.intfb.h"

INTEGER (KIND=JPIM) :: JSP, JLEV, JLON

INTEGER :: ILUN, IERR
INTEGER :: IREQUIRED, IPROVIDED
INTEGER :: IPRINTLEV
CHARACTER (LEN=64) :: CLFILE, CLPROC, CLCASE
LOGICAL :: LLVERBOSE, LLWRITE

CALL INITOPTIONS
CALL GETOPTION ("--verbose", LLVERBOSE)
CALL GETOPTION ("--write", LLWRITE)
CALL GETOPTION ("--case", CLCASE, MND=.TRUE.)
CALL CHECKOPTIONS

IPRINTLEV=0
IF (LLVERBOSE) IPRINTLEV=2

IREQUIRED = MPI_THREAD_MULTIPLE
IPROVIDED = MPI_THREAD_SINGLE
CALL MPI_INIT_THREAD (IREQUIRED, IPROVIDED, IERR)
IF (IERR /= 0) CALL ABOR1 ('MAIN: MPI_INIT_THREAD FAILED')

CALL MPI_COMM_RANK (MPI_COMM_WORLD, MYPROC, IERR)
MYPROC = MYPROC + 1

PRINT *, " MYPROC = ", MYPROC

ILUN = 77

CALL MPL_INIT ()

ILUN = 77

OPEN (ILUN, FILE=TRIM (CLCASE)//'/SETUP_TRANS0.IN', FORM='UNFORMATTED')
READ (ILUN) NPRGPNS
READ (ILUN) NPRGPEW
READ (ILUN) NPRTRW
READ (ILUN) LEQ_REGIONS
READ (ILUN) RA
CLOSE (ILUN)

CALL SETUP_TRANS0            &
  (KPRGPNS=NPRGPNS,          &
 & KPRGPEW=NPRGPEW,          &
 & KPRTRW=NPRTRW,            &
 & KPRINTLEV=IPRINTLEV,      &
 & LDEQ_REGIONS=LEQ_REGIONS, &
 & PRAD=RA)

OPEN (ILUN, FILE=TRIM (CLCASE)//'/SETUP_TRANS.IN', FORM='UNFORMATTED')

READ (ILUN) NSMAX
READ (ILUN) NDGLG
ALLOCATE (NLOENG (NDGLG))
READ (ILUN) NLOENG

WRITE (*, *) " NLOENG = ", NLOENG

READ (ILUN) LSPLIT
READ (ILUN) NRESOL
READ (ILUN) LUSEFLT
READ (ILUN) LUSERPNM
READ (ILUN) LKEEPRPNM
READ (ILUN) LFFTW
CLOSE (ILUN)


CALL SETUP_TRANS(KSMAX=NSMAX,KDGL=NDGLG,KLOEN=NLOENG(1:NDGLG),&
 & LDSPLIT=LSPLIT,KRESOL=NRESOL,LDUSEFLT=LUSEFLT,LDUSERPNM=LUSERPNM,&
 & LDKEEPRPNM=LKEEPRPNM,LDUSEFFTW=LFFTW)

CLOSE (ILUN)

WRITE (CLPROC, '(I4.4)') MYPROC
CLFILE = 'SPCM_SIMPLE.IN.'//TRIM (CLPROC)

OPEN (ILUN, FILE=TRIM (CLCASE)//'/'//TRIM (CLFILE), FORM='UNFORMATTED')

CALL LOAD_YOMMP0 (ILUN)
CALL LOAD (ILUN, YDMODEL)
CALL LOAD (ILUN, YDGEOMETRY)

ALLOCATE (PSPSP (YDGEOMETRY%YRDIM%NSPEC2))
ALLOCATE (PSPVOR(YDGEOMETRY%YRDIMV%NFLEVL,YDGEOMETRY%YRDIM%NSPEC2))
ALLOCATE (PSPDIV(YDGEOMETRY%YRDIMV%NFLEVL,YDGEOMETRY%YRDIM%NSPEC2))
ALLOCATE (PSPT  (YDGEOMETRY%YRDIMV%NFLEVL,YDGEOMETRY%YRDIM%NSPEC2))
ALLOCATE (PSPSPD(YDGEOMETRY%YRDIMV%NFLEVL,YDGEOMETRY%YRDIM%NSPEC2))
ALLOCATE (PSPSVD(YDGEOMETRY%YRDIMV%NFLEVL,YDGEOMETRY%YRDIM%NSPEC2))

READ (ILUN) PSPSP 
READ (ILUN) PSPVOR
READ (ILUN) PSPDIV
READ (ILUN) PSPT  
READ (ILUN) PSPSPD
READ (ILUN) PSPSVD

CLOSE (ILUN)


CALL SPCM_SIMPLE (YDGEOMETRY,YDMODEL,PSPSP,PSPVOR,PSPDIV,PSPT,PSPSPD,PSPSVD)

PRINT *, " SPCM_SIMPLE DONE "

ILUN = 77

WRITE (CLPROC, '(I4.4)') MYPROC

CLFILE = 'SPCM_SIMPLE.OUT.'//TRIM (CLPROC)

OPEN (ILUN, FILE=TRIM (CLCASE)//'/'//TRIM (CLFILE), FORM='UNFORMATTED')

ALLOCATE (ZSPSP (YDGEOMETRY%YRDIM%NSPEC2))
ALLOCATE (ZSPVOR(YDGEOMETRY%YRDIMV%NFLEVL,YDGEOMETRY%YRDIM%NSPEC2))
ALLOCATE (ZSPDIV(YDGEOMETRY%YRDIMV%NFLEVL,YDGEOMETRY%YRDIM%NSPEC2))
ALLOCATE (ZSPT  (YDGEOMETRY%YRDIMV%NFLEVL,YDGEOMETRY%YRDIM%NSPEC2))
ALLOCATE (ZSPSPD(YDGEOMETRY%YRDIMV%NFLEVL,YDGEOMETRY%YRDIM%NSPEC2))
ALLOCATE (ZSPSVD(YDGEOMETRY%YRDIMV%NFLEVL,YDGEOMETRY%YRDIM%NSPEC2))

READ (ILUN) ZSPSP 
READ (ILUN) ZSPVOR
READ (ILUN) ZSPDIV
READ (ILUN) ZSPT  
READ (ILUN) ZSPSPD
READ (ILUN) ZSPSVD

CLOSE (ILUN)


PRINT *, " SP "
DO JSP = 1, YDGEOMETRY%YRDIM%NSPEC2
  WRITE (*, '(3E30.20)') PSPSP (JSP), ZSPSP (JSP), PSPSP (JSP) - ZSPSP (JSP)
ENDDO

IF (.FALSE.) THEN

PRINT *, " T "
DO JLEV = 1, YDGEOMETRY%YRDIMV%NFLEVL
  PRINT *, " JLEV = ", JLEV
  DO JSP = 1, YDGEOMETRY%YRDIM%NSPEC2
    WRITE (*, '(3E30.20)') PSPT (JLEV,JSP), ZSPT (JLEV,JSP), PSPT (JLEV,JSP) - ZSPT (JLEV,JSP)
  ENDDO
ENDDO

ENDIF

IF (LLWRITE) THEN
  CALL WRSPEC (PSPT, 'PSPT')
ENDIF

999 CONTINUE

CALL FLUSH (0)
CALL FLUSH (6)
CALL MPL_BARRIER ()

CALL MPL_END ()

CONTAINS

SUBROUTINE SP2GP (PSPL, PGPL)

USE, INTRINSIC :: IEEE_ARITHMETIC, ONLY: IEEE_VALUE, IEEE_QUIET_NAN

REAL (KIND=JPRB), INTENT (IN)  :: PSPL (YDGEOMETRY%YRDIMV%NFLEVL,YDGEOMETRY%YRDIM%NSPEC2)
REAL (KIND=JPRB), INTENT (OUT) :: PGPL (YDGEOMETRY%YRGEM%NGPTOT,YDGEOMETRY%YRDIMV%NFLEVG,1)

#include "inv_trans.h"

REAL (KIND=JPRB) :: ZNAN
INTEGER (KIND=JPIM), ALLOCATABLE :: IVSET (:)

ZNAN = IEEE_VALUE (ZNAN, IEEE_QUIET_NAN)

PGPL = ZNAN

ALLOCATE (IVSET (YDGEOMETRY%YRDIMV%NFLEVG))

IVSET = YDGEOMETRY%YRMP%NBSETLEV

CALL INV_TRANS (PSPSCALAR=PSPL, KVSETSC=IVSET, KPROMA=YDGEOMETRY%YRGEM%NGPTOT, PGP=PGPL)

END SUBROUTINE

SUBROUTINE WRSPEC (PSPL, CDFILE)

USE ECCODES

REAL (KIND=JPRB),  INTENT (IN) :: PSPL (YDGEOMETRY%YRDIMV%NFLEVL,YDGEOMETRY%YRDIM%NSPEC2)
CHARACTER (LEN=*), INTENT (IN) :: CDFILE

#include "gath_grid.h"

REAL (KIND=JPRB) :: ZGPL (YDGEOMETRY%YRGEM%NGPTOT,YDGEOMETRY%YRDIMV%NFLEVG,1)
REAL (KIND=JPRB), ALLOCATABLE :: ZGPG (:,:)
INTEGER (KIND=JPIM) :: JLEV, JLON
INTEGER (KIND=JPIM), ALLOCATABLE :: ITO (:)
INTEGER :: IGRIB, IFILE

CALL SP2GP (PSPL, ZGPL)

DO JLEV = 1, YDGEOMETRY%YRDIMV%NFLEVG
  PRINT *, " JLEV = ", JLEV
  DO JLON = 1, YDGEOMETRY%YRGEM%NGPTOT
    WRITE (*, '(I6," ",F30.20)') JLON, ZGPL (JLON, JLEV, 1)
  ENDDO
ENDDO

ALLOCATE (ITO (YDGEOMETRY%YRDIMV%NFLEVG))
ITO = 1

IF (MYPROC == 1) THEN
  ALLOCATE (ZGPG (YDGEOMETRY%YRGEM%NGPTOTG, YDGEOMETRY%YRDIMV%NFLEVG))
  CALL GATH_GRID (KFGATHG=YDGEOMETRY%YRDIMV%NFLEVG, KTO=ITO, PGP=ZGPL, PGPG=ZGPG)
ELSE
  CALL GATH_GRID (KFGATHG=YDGEOMETRY%YRDIMV%NFLEVG, KTO=ITO, PGP=ZGPL)
ENDIF


IF (MYPROC == 1) THEN
  CALL GRIB_NEW_FROM_SAMPLES (IGRIB,  'reduced_gg_ml_grib2')
  CALL GRIB_SET (IGRIB, 'parameterNumber', 255)
  CALL GRIB_SET (IGRIB, 'interpretationOfNumberOfPoints', 1)
  CALL GRIB_SET (IGRIB, 'global', 1)
  CALL GRIB_SET (IGRIB, 'gridType', 'reduced_gg')
  CALL GRIB_SET (IGRIB, 'pl', NLOENG)
  CALL GRIB_SET (IGRIB, 'packingType', 'grid_simple')
  CALL GRIB_SET (IGRIB, 'values', ZGPG (:, 15))
  CALL GRIB_OPEN_FILE (IFILE, 'grib1.grb', 'w')
  CALL GRIB_WRITE (IGRIB, IFILE)
  CALL GRIB_CLOSE_FILE (IFILE)
  CALL GRIB_RELEASE (IGRIB)
ENDIF


END SUBROUTINE

END 

