SUBROUTINE SPCSIDG_PART0 (YDGEOMETRY, YDDYN, YDRIP, KSPEC2V, KMLOC, ZSDIV, PSPDIVG)

USE GEOMETRY_MOD , ONLY : GEOMETRY
USE PARKIND1     , ONLY : JPIM, JPRB
USE YOMHOOK      , ONLY : LHOOK, DR_HOOK, JPHOOK
USE YOMDYN       , ONLY : TDYN
USE YOMRIP       , ONLY : TRIP
USE YOMMP0       , ONLY : MYSETV

!     ------------------------------------------------------------------

IMPLICIT NONE

TYPE(GEOMETRY)    ,INTENT(IN)    :: YDGEOMETRY
TYPE(TDYN)        ,INTENT(IN)    :: YDDYN
TYPE(TRIP)        ,INTENT(IN)    :: YDRIP
INTEGER(KIND=JPIM),INTENT(IN)    :: KSPEC2V
INTEGER(KIND=JPIM),INTENT(IN)    :: KMLOC
REAL(KIND=JPRB),   INTENT(INOUT) :: ZSDIV (YDGEOMETRY%YRDIMV%NFLEVG,KSPEC2V)
REAL(KIND=JPRB),   INTENT(INOUT) :: PSPDIVG(YDGEOMETRY%YRDIMV%NFLEVG,KSPEC2V)

REAL(KIND=JPRB)  :: ZBDT
!     ------------------------------------------------------------------

INTEGER(KIND=JPIM):: IN,IM,ISTA,IEND,JSP,JLEV,IOFF

REAL(KIND=JPHOOK) :: ZHOOK_HANDLE

!     -----------------------

IF (LHOOK) CALL DR_HOOK('SPCSIDG_PART0',0,ZHOOK_HANDLE)

ASSOCIATE(YDDIM=>YDGEOMETRY%YRDIM,YDDIMV=>YDGEOMETRY%YRDIMV,YDLAP=>YDGEOMETRY%YRLAP,YDMP=>YDGEOMETRY%YRMP)
ASSOCIATE(NSMAX=>YDDIM%NSMAX,NFLEVG=>YDDIMV%NFLEVG,SIHEG=>YDDYN%SIHEG,SIHEG2=>YDDYN%SIHEG2,&
& NSPSTAF=>YDMP%NSPSTAF,TDT=>YDRIP%TDT,RBTS2=>YDDYN%RBTS2,NPTRSVF=>YDMP%NPTRSVF)

IM=YDLAP%MYMS(KMLOC)
ISTA=NSPSTAF(IM)
IEND=ISTA+2*(NSMAX+1-IM)-1

ZBDT=RBTS2*TDT
IOFF=NPTRSVF(MYSETV)-1

    IF (IM > 0) THEN
!$OMP PARALLEL DO PRIVATE(JSP,JLEV,IN)
      DO JSP=ISTA,IEND
        DO JLEV=1,NFLEVG
          IN=YDLAP%NVALUE(JSP+IOFF)
          ZSDIV(JLEV,JSP)=YDLAP%RLAPIN(IN)*PSPDIVG(JLEV,JSP)-ZBDT*ZSDIV(JLEV,JSP)      
        ENDDO
      ENDDO
!$OMP END PARALLEL DO
    ELSE
!$OMP PARALLEL DO PRIVATE(JSP,JLEV,IN)
      DO JSP=ISTA,IEND
        DO JLEV=1,NFLEVG
          IN=YDLAP%NVALUE(JSP+IOFF)
          ZSDIV(JLEV,JSP)=PSPDIVG(JLEV,JSP)-ZBDT*YDLAP%RLAPDI(IN)*ZSDIV(JLEV,JSP)  
        ENDDO
      ENDDO
!$OMP END PARALLEL DO
    ENDIF
 

END ASSOCIATE
END ASSOCIATE

IF (LHOOK) CALL DR_HOOK('SPCSIDG_PART0',1,ZHOOK_HANDLE)
END SUBROUTINE SPCSIDG_PART0

