INTERFACE
#if defined(_OPENACC)
SUBROUTINE SPCSIDG_PART1 (YDGEOMETRY, YDDYN, KSPEC2V, PSDIVP, PSPDIVP,&
  &zsdivpl,zspdivpl,param_mxture,KMLOCSTA,KMLOCEND)
#else
SUBROUTINE SPCSIDG_PART1 (YDGEOMETRY, YDDYN, KSPEC2V, PSDIVP, PSPDIVP,KMLOCSTA,KMLOCEND)
#endif
USE GEOMETRY_MOD , ONLY : GEOMETRY
USE PARKIND1     , ONLY : JPIM, JPRB
USE YOMHOOK      , ONLY : LHOOK, DR_HOOK, JPHOOK
USE YOMDYN       , ONLY : TDYN
IMPLICIT NONE
TYPE(GEOMETRY)    ,INTENT(IN)    :: YDGEOMETRY
TYPE(TDYN)        ,INTENT(IN)    :: YDDYN
INTEGER(KIND=JPIM),INTENT(IN)    :: KSPEC2V
INTEGER(KIND=JPIM),INTENT(IN)    :: KMLOCSTA
INTEGER(KIND=JPIM),INTENT(IN)    :: KMLOCEND

REAL(KIND=JPRB),   INTENT(IN)    :: PSDIVP (KSPEC2V,YDGEOMETRY%YRDIMV%NFLEVG)
REAL(KIND=JPRB),   INTENT(INOUT) :: PSPDIVP(KSPEC2V,YDGEOMETRY%YRDIMV%NFLEVG)
#if defined(_OPENACC)
REAL(KIND=JPRB),   INTENT(INOUT) :: ZSDIVPL (1:YDGEOMETRY%YRDIM%NSMAX+1,2,YDGEOMETRY%YRDIMV%NFLEVG,500)
REAL(KIND=JPRB),   INTENT(INOUT) :: ZSPDIVPL(1:YDGEOMETRY%YRDIM%NSMAX+1,2,YDGEOMETRY%YRDIMV%NFLEVG,500)
real(kind=jprb),   intent(in)    :: param_mxture(:,:,:)
#endif
END SUBROUTINE SPCSIDG_PART1

END INTERFACE
