INTERFACE
SUBROUTINE TRSTOM(YDGEOMETRY,LDNHDYN,LDNHX,LDTRANSPOSE,PSPVORG,PSPDIVG,PSPTG,PSPSPDG,PSPSVDG,PSPSNHXG, &
& PSPGFLG,PSPSPG,PSPAUXG,PSPSEL3DG,PSPSEL2DG,&
& PSPVOR,PSPDIV,PSPT,PSPSPD,PSPSVD,PSPSNHX,&
& PSPGFL,PSPSP,PSPAUX,PSPSEL3D,PSPSEL2D,&
& LDSELECT3D,LDSELECT2D,LDFULLM,LDNEEDPS)
USE GEOMETRY_MOD , ONLY : GEOMETRY
USE PARKIND1     , ONLY : JPIM, JPRB
USE YOMHOOK      , ONLY : LHOOK, DR_HOOK, JPHOOK
USE EXCHANGE_MS_MOD, ONLY: FIELDLIST, ADD3DF, ADD3DFL, ADD2DF, ADD2DFL, NEXCHANGE_STOM, EXCHANGE_MS
IMPLICIT NONE
TYPE(GEOMETRY)    ,          INTENT(IN)    :: YDGEOMETRY
LOGICAL           ,          INTENT(IN)    :: LDNHDYN
LOGICAL           ,          INTENT(IN)    :: LDNHX
LOGICAL           ,          INTENT(IN)    :: LDTRANSPOSE
REAL(KIND=JPRB)   ,OPTIONAL, INTENT(IN)    :: PSPVORG(:,:)
REAL(KIND=JPRB)   ,OPTIONAL, INTENT(IN)    :: PSPDIVG(:,:)
REAL(KIND=JPRB)   ,OPTIONAL, INTENT(IN)    :: PSPTG(:,:)
REAL(KIND=JPRB)   ,OPTIONAL, INTENT(IN)    :: PSPSPDG(:,:)
REAL(KIND=JPRB)   ,OPTIONAL, INTENT(IN)    :: PSPSVDG(:,:)
REAL(KIND=JPRB)   ,OPTIONAL, INTENT(IN)    :: PSPSNHXG(:,:)
REAL(KIND=JPRB)   ,OPTIONAL, INTENT(IN)    :: PSPGFLG(:,:,:)
REAL(KIND=JPRB)   ,OPTIONAL, INTENT(IN)    :: PSPSPG(:)
REAL(KIND=JPRB)   ,OPTIONAL, INTENT(IN)    :: PSPAUXG(:,:)
REAL(KIND=JPRB)   ,OPTIONAL, INTENT(IN)    :: PSPSEL3DG(:,:,:)
REAL(KIND=JPRB)   ,OPTIONAL, INTENT(IN)    :: PSPSEL2DG(:,:)
REAL(KIND=JPRB)   ,OPTIONAL, INTENT(OUT)   :: PSPVOR(:,:)
REAL(KIND=JPRB)   ,OPTIONAL, INTENT(OUT)   :: PSPDIV(:,:)
REAL(KIND=JPRB)   ,OPTIONAL, INTENT(OUT)   :: PSPT(:,:)
REAL(KIND=JPRB)   ,OPTIONAL, INTENT(OUT)   :: PSPSPD(:,:)
REAL(KIND=JPRB)   ,OPTIONAL, INTENT(OUT)   :: PSPSVD(:,:)
REAL(KIND=JPRB)   ,OPTIONAL, INTENT(OUT)   :: PSPSNHX(:,:)
REAL(KIND=JPRB)   ,OPTIONAL, INTENT(INOUT) :: PSPGFL(:,:,:)
REAL(KIND=JPRB)   ,OPTIONAL, INTENT(OUT)   :: PSPSP(:)
REAL(KIND=JPRB)   ,OPTIONAL, INTENT(OUT)   :: PSPAUX(:,:)
REAL(KIND=JPRB)   ,OPTIONAL, INTENT(INOUT) :: PSPSEL3D(:,:,:)
REAL(KIND=JPRB)   ,OPTIONAL, INTENT(INOUT) :: PSPSEL2D(:,:)
LOGICAL           ,OPTIONAL, INTENT(IN)    :: LDSELECT3D(:)
LOGICAL           ,OPTIONAL, INTENT(IN)    :: LDSELECT2D(:)
LOGICAL           ,OPTIONAL, INTENT(IN)    :: LDFULLM
LOGICAL           ,OPTIONAL, INTENT(IN)    :: LDNEEDPS
END SUBROUTINE TRSTOM

END INTERFACE
