MODULE UTIL_TGFLT_MOD

USE INTDYN_MOD, ONLY : TGFLT

INTERFACE SAVE
MODULE PROCEDURE SAVE_TGFLT
END INTERFACE

INTERFACE LOAD
MODULE PROCEDURE LOAD_TGFLT
END INTERFACE

INTERFACE COPY
MODULE PROCEDURE COPY_TGFLT
END INTERFACE

INTERFACE WIPE
MODULE PROCEDURE WIPE_TGFLT
END INTERFACE



CONTAINS

SUBROUTINE SAVE_TGFLT (KLUN, YD)

IMPLICIT NONE
INTEGER, INTENT (IN) :: KLUN
TYPE (TGFLT), INTENT (IN), TARGET :: YD

WRITE (KLUN) YD%M_Q
WRITE (KLUN) YD%M_L
WRITE (KLUN) YD%M_I
WRITE (KLUN) YD%NDIM
END SUBROUTINE

SUBROUTINE LOAD_TGFLT (KLUN, YD)

IMPLICIT NONE
INTEGER, INTENT (IN) :: KLUN
TYPE (TGFLT), INTENT (OUT), TARGET :: YD

READ (KLUN) YD%M_Q
READ (KLUN) YD%M_L
READ (KLUN) YD%M_I
READ (KLUN) YD%NDIM
END SUBROUTINE


SUBROUTINE COPY_TGFLT (YD, LDCREATED)

IMPLICIT NONE
TYPE (TGFLT), INTENT (IN), TARGET :: YD
LOGICAL, OPTIONAL, INTENT (IN) :: LDCREATED
LOGICAL :: LLCREATED

LLCREATED = .FALSE.
IF (PRESENT (LDCREATED)) THEN
  LLCREATED = LDCREATED
ENDIF
IF (.NOT. LLCREATED) THEN
  !$acc enter data create (YD)
  !$acc update device (YD)
ENDIF




END SUBROUTINE

SUBROUTINE WIPE_TGFLT (YD, LDDELETED)

IMPLICIT NONE
TYPE (TGFLT), INTENT (IN), TARGET :: YD
LOGICAL, OPTIONAL, INTENT (IN) :: LDDELETED
LOGICAL :: LLDELETED





LLDELETED = .FALSE.
IF (PRESENT (LDDELETED)) THEN
  LLDELETED = LDDELETED
ENDIF
IF (.NOT. LLDELETED) THEN
  !$acc exit data delete (YD)
ENDIF
END SUBROUTINE



END MODULE
