MODULE UTIL_GEOMETRY_MOD

USE TYPE_GEOMETRY, ONLY : GEOMETRY

INTERFACE SAVE
MODULE PROCEDURE SAVE_GEOMETRY
END INTERFACE

INTERFACE LOAD
MODULE PROCEDURE LOAD_GEOMETRY
END INTERFACE

INTERFACE COPY
MODULE PROCEDURE COPY_GEOMETRY
END INTERFACE

INTERFACE WIPE
MODULE PROCEDURE WIPE_GEOMETRY
END INTERFACE



CONTAINS

SUBROUTINE SAVE_GEOMETRY (KLUN, YD)
USE UTIL_TCSGEOM_BLOCKED_MOD
USE UTIL_TCSGEOM_MOD
USE UTIL_TCSGLEG_MOD
USE UTIL_TCVER_MOD
USE UTIL_TDIMV_MOD
USE UTIL_TDIM_MOD
USE UTIL_TEDIM_MOD
USE UTIL_TEGEO_MOD
USE UTIL_TEGSL_MOD
USE UTIL_TELBC_GEO_MOD
USE UTIL_TEMMP_MOD
USE UTIL_TGEM_MOD
USE UTIL_TGSGEOM_BLOCKED_MOD
USE UTIL_TGSGEOM_MOD
USE UTIL_TLAP_MOD
USE UTIL_TLEP_MOD
USE UTIL_TMP_MOD
USE UTIL_TOROG_BLOCKED_MOD
USE UTIL_TOROG_MOD
USE UTIL_TSPGEOM_MOD
USE UTIL_TSTA_MOD
USE UTIL_TVAB_MOD
USE UTIL_TVERTICAL_GEOM_MOD
USE UTIL_TVETA_MOD
USE UTIL_TVFE_MOD
IMPLICIT NONE
INTEGER, INTENT (IN) :: KLUN
TYPE (GEOMETRY), INTENT (IN), TARGET :: YD
INTEGER :: J1
LOGICAL :: LLNONHYD_GEOM, LYRCSGEOM, LYRCSGEOMAD, LYRCVER, LYRELBC_GEO, LYRGSGEOM, LYRGSGEOMAD, LYROROG, LYRVAB, LYRVETA
LOGICAL :: LYRVFE
LLNONHYD_GEOM = ASSOCIATED (YD%LNONHYD_GEOM)
WRITE (KLUN) LLNONHYD_GEOM
IF (LLNONHYD_GEOM) THEN
  WRITE (KLUN) YD%LNONHYD_GEOM
ENDIF
WRITE (KLUN) YD%LNHX_GEOM
CALL SAVE (KLUN, YD%YRVERT_GEOM)
LYRVAB = ASSOCIATED (YD%YRVAB)
WRITE (KLUN) LYRVAB
IF (LYRVAB) THEN
  CALL SAVE (KLUN, YD%YRVAB)
ENDIF
LYRVETA = ASSOCIATED (YD%YRVETA)
WRITE (KLUN) LYRVETA
IF (LYRVETA) THEN
  CALL SAVE (KLUN, YD%YRVETA)
ENDIF
LYRVFE = ASSOCIATED (YD%YRVFE)
WRITE (KLUN) LYRVFE
IF (LYRVFE) THEN
  CALL SAVE (KLUN, YD%YRVFE)
ENDIF
LYRCVER = ASSOCIATED (YD%YRCVER)
WRITE (KLUN) LYRCVER
IF (LYRCVER) THEN
  CALL SAVE (KLUN, YD%YRCVER)
ENDIF
CALL SAVE (KLUN, YD%YRSTA)
CALL SAVE (KLUN, YD%YRLAP)
CALL SAVE (KLUN, YD%YRCSGLEG)
CALL SAVE (KLUN, YD%YRDIM)
CALL SAVE (KLUN, YD%YRDIMV)
CALL SAVE (KLUN, YD%YRMP)
CALL SAVE (KLUN, YD%YRGEM)
LYRCSGEOM = ASSOCIATED (YD%YRCSGEOM)
WRITE (KLUN) LYRCSGEOM
IF (LYRCSGEOM) THEN
  WRITE (KLUN) LBOUND (YD%YRCSGEOM)
  WRITE (KLUN) UBOUND (YD%YRCSGEOM)
  DO J1 = LBOUND (YD%YRCSGEOM, 1), UBOUND (YD%YRCSGEOM, 1)
    CALL SAVE (KLUN, YD%YRCSGEOM (J1))
  ENDDO
ENDIF
CALL SAVE (KLUN, YD%YRCSGEOM_NB)
CALL SAVE (KLUN, YD%YRCSGEOM_B)
LYRGSGEOM = ASSOCIATED (YD%YRGSGEOM)
WRITE (KLUN) LYRGSGEOM
IF (LYRGSGEOM) THEN
  WRITE (KLUN) LBOUND (YD%YRGSGEOM)
  WRITE (KLUN) UBOUND (YD%YRGSGEOM)
  DO J1 = LBOUND (YD%YRGSGEOM, 1), UBOUND (YD%YRGSGEOM, 1)
    CALL SAVE (KLUN, YD%YRGSGEOM (J1))
  ENDDO
ENDIF
CALL SAVE (KLUN, YD%YRGSGEOM_NB)
CALL SAVE (KLUN, YD%YRGSGEOM_B)
WRITE (KLUN) YD%AD_GEOM
LYRCSGEOMAD = ASSOCIATED (YD%YRCSGEOMAD)
WRITE (KLUN) LYRCSGEOMAD
IF (LYRCSGEOMAD) THEN
  WRITE (KLUN) LBOUND (YD%YRCSGEOMAD)
  WRITE (KLUN) UBOUND (YD%YRCSGEOMAD)
  DO J1 = LBOUND (YD%YRCSGEOMAD, 1), UBOUND (YD%YRCSGEOMAD, 1)
    CALL SAVE (KLUN, YD%YRCSGEOMAD (J1))
  ENDDO
ENDIF
CALL SAVE (KLUN, YD%YRCSGEOMAD_NB)
LYRGSGEOMAD = ASSOCIATED (YD%YRGSGEOMAD)
WRITE (KLUN) LYRGSGEOMAD
IF (LYRGSGEOMAD) THEN
  WRITE (KLUN) LBOUND (YD%YRGSGEOMAD)
  WRITE (KLUN) UBOUND (YD%YRGSGEOMAD)
  DO J1 = LBOUND (YD%YRGSGEOMAD, 1), UBOUND (YD%YRGSGEOMAD, 1)
    CALL SAVE (KLUN, YD%YRGSGEOMAD (J1))
  ENDDO
ENDIF
CALL SAVE (KLUN, YD%YRGSGEOMAD_NB)
LYROROG = ALLOCATED (YD%YROROG)
WRITE (KLUN) LYROROG
IF (LYROROG) THEN
  WRITE (KLUN) LBOUND (YD%YROROG)
  WRITE (KLUN) UBOUND (YD%YROROG)
  DO J1 = LBOUND (YD%YROROG, 1), UBOUND (YD%YROROG, 1)
    CALL SAVE (KLUN, YD%YROROG (J1))
  ENDDO
ENDIF
CALL SAVE (KLUN, YD%YROROG_B)
CALL SAVE (KLUN, YD%YSPGEOM)
CALL SAVE (KLUN, YD%YVABIO)
CALL SAVE (KLUN, YD%YREDIM)
CALL SAVE (KLUN, YD%YREGEO)
CALL SAVE (KLUN, YD%YREMP)
CALL SAVE (KLUN, YD%YRELAP)
CALL SAVE (KLUN, YD%YREGSL)
LYRELBC_GEO = ASSOCIATED (YD%YRELBC_GEO)
WRITE (KLUN) LYRELBC_GEO
IF (LYRELBC_GEO) THEN
  CALL SAVE (KLUN, YD%YRELBC_GEO)
ENDIF
END SUBROUTINE

SUBROUTINE LOAD_GEOMETRY (KLUN, YD)
USE UTIL_TCSGEOM_BLOCKED_MOD
USE UTIL_TCSGEOM_MOD
USE UTIL_TCSGLEG_MOD
USE UTIL_TCVER_MOD
USE UTIL_TDIMV_MOD
USE UTIL_TDIM_MOD
USE UTIL_TEDIM_MOD
USE UTIL_TEGEO_MOD
USE UTIL_TEGSL_MOD
USE UTIL_TELBC_GEO_MOD
USE UTIL_TEMMP_MOD
USE UTIL_TGEM_MOD
USE UTIL_TGSGEOM_BLOCKED_MOD
USE UTIL_TGSGEOM_MOD
USE UTIL_TLAP_MOD
USE UTIL_TLEP_MOD
USE UTIL_TMP_MOD
USE UTIL_TOROG_BLOCKED_MOD
USE UTIL_TOROG_MOD
USE UTIL_TSPGEOM_MOD
USE UTIL_TSTA_MOD
USE UTIL_TVAB_MOD
USE UTIL_TVERTICAL_GEOM_MOD
USE UTIL_TVETA_MOD
USE UTIL_TVFE_MOD

IMPLICIT NONE
INTEGER, INTENT (IN) :: KLUN
TYPE (GEOMETRY), INTENT (OUT), TARGET :: YD
INTEGER :: J1
INTEGER :: IL1(1), IU1(1)
LOGICAL :: LLNONHYD_GEOM, LYRCSGEOM, LYRCSGEOMAD, LYRCVER, LYRELBC_GEO, LYRGSGEOM, LYRGSGEOMAD, LYROROG, LYRVAB, LYRVETA
LOGICAL :: LYRVFE
READ (KLUN) LLNONHYD_GEOM
IF (LLNONHYD_GEOM) THEN
  ALLOCATE (YD%LNONHYD_GEOM)
  READ (KLUN) YD%LNONHYD_GEOM
ELSE
  NULLIFY (YD%LNONHYD_GEOM)
ENDIF
READ (KLUN) YD%LNHX_GEOM
CALL LOAD (KLUN, YD%YRVERT_GEOM)
READ (KLUN) LYRVAB
IF (LYRVAB) THEN
  ALLOCATE (YD%YRVAB)
  CALL LOAD (KLUN, YD%YRVAB)
ELSE
  NULLIFY (YD%YRVAB)
ENDIF
READ (KLUN) LYRVETA
IF (LYRVETA) THEN
  ALLOCATE (YD%YRVETA)
  CALL LOAD (KLUN, YD%YRVETA)
ELSE
  NULLIFY (YD%YRVETA)
ENDIF
READ (KLUN) LYRVFE
IF (LYRVFE) THEN
  ALLOCATE (YD%YRVFE)
  CALL LOAD (KLUN, YD%YRVFE)
ELSE
  NULLIFY (YD%YRVFE)
ENDIF
READ (KLUN) LYRCVER
IF (LYRCVER) THEN
  ALLOCATE (YD%YRCVER)
  CALL LOAD (KLUN, YD%YRCVER)
ELSE
  NULLIFY (YD%YRCVER)
ENDIF
CALL LOAD (KLUN, YD%YRSTA)
CALL LOAD (KLUN, YD%YRLAP)
CALL LOAD (KLUN, YD%YRCSGLEG)
CALL LOAD (KLUN, YD%YRDIM)
CALL LOAD (KLUN, YD%YRDIMV)
CALL LOAD (KLUN, YD%YRMP)
CALL LOAD (KLUN, YD%YRGEM)
READ (KLUN) LYRCSGEOM
IF (LYRCSGEOM) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (YD%YRCSGEOM (IL1(1):IU1(1)))
  DO J1 = LBOUND (YD%YRCSGEOM, 1), UBOUND (YD%YRCSGEOM, 1)
    CALL LOAD (KLUN, YD%YRCSGEOM (J1))
  ENDDO
ELSE
  NULLIFY (YD%YRCSGEOM)
ENDIF
CALL LOAD (KLUN, YD%YRCSGEOM_NB)
CALL LOAD (KLUN, YD%YRCSGEOM_B)
READ (KLUN) LYRGSGEOM
IF (LYRGSGEOM) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (YD%YRGSGEOM (IL1(1):IU1(1)))
  DO J1 = LBOUND (YD%YRGSGEOM, 1), UBOUND (YD%YRGSGEOM, 1)
    CALL LOAD (KLUN, YD%YRGSGEOM (J1))
  ENDDO
ELSE
  NULLIFY (YD%YRGSGEOM)
ENDIF
CALL LOAD (KLUN, YD%YRGSGEOM_NB)
CALL LOAD (KLUN, YD%YRGSGEOM_B)
READ (KLUN) YD%AD_GEOM
READ (KLUN) LYRCSGEOMAD
IF (LYRCSGEOMAD) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (YD%YRCSGEOMAD (IL1(1):IU1(1)))
  DO J1 = LBOUND (YD%YRCSGEOMAD, 1), UBOUND (YD%YRCSGEOMAD, 1)
    CALL LOAD (KLUN, YD%YRCSGEOMAD (J1))
  ENDDO
ELSE
  NULLIFY (YD%YRCSGEOMAD)
ENDIF
CALL LOAD (KLUN, YD%YRCSGEOMAD_NB)
READ (KLUN) LYRGSGEOMAD
IF (LYRGSGEOMAD) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (YD%YRGSGEOMAD (IL1(1):IU1(1)))
  DO J1 = LBOUND (YD%YRGSGEOMAD, 1), UBOUND (YD%YRGSGEOMAD, 1)
    CALL LOAD (KLUN, YD%YRGSGEOMAD (J1))
  ENDDO
ELSE
  NULLIFY (YD%YRGSGEOMAD)
ENDIF
CALL LOAD (KLUN, YD%YRGSGEOMAD_NB)
READ (KLUN) LYROROG
IF (LYROROG) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (YD%YROROG (IL1(1):IU1(1)))
  DO J1 = LBOUND (YD%YROROG, 1), UBOUND (YD%YROROG, 1)
    CALL LOAD (KLUN, YD%YROROG (J1))
  ENDDO
ENDIF
CALL LOAD (KLUN, YD%YROROG_B)
CALL LOAD (KLUN, YD%YSPGEOM)
CALL LOAD (KLUN, YD%YVABIO)
CALL LOAD (KLUN, YD%YREDIM)
CALL LOAD (KLUN, YD%YREGEO)
CALL LOAD (KLUN, YD%YREMP)
CALL LOAD (KLUN, YD%YRELAP)
CALL LOAD (KLUN, YD%YREGSL)
READ (KLUN) LYRELBC_GEO
IF (LYRELBC_GEO) THEN
  ALLOCATE (YD%YRELBC_GEO)
  CALL LOAD (KLUN, YD%YRELBC_GEO)
ELSE
  NULLIFY (YD%YRELBC_GEO)
ENDIF
END SUBROUTINE


SUBROUTINE COPY_GEOMETRY (YD, LDCREATED)
USE UTIL_TCSGEOM_BLOCKED_MOD
USE UTIL_TCSGEOM_MOD
USE UTIL_TCSGLEG_MOD
USE UTIL_TCVER_MOD
USE UTIL_TDIMV_MOD
USE UTIL_TDIM_MOD
USE UTIL_TEDIM_MOD
USE UTIL_TEGEO_MOD
USE UTIL_TEGSL_MOD
USE UTIL_TELBC_GEO_MOD
USE UTIL_TEMMP_MOD
USE UTIL_TGEM_MOD
USE UTIL_TGSGEOM_BLOCKED_MOD
USE UTIL_TGSGEOM_MOD
USE UTIL_TLAP_MOD
USE UTIL_TLEP_MOD
USE UTIL_TMP_MOD
USE UTIL_TOROG_BLOCKED_MOD
USE UTIL_TOROG_MOD
USE UTIL_TSPGEOM_MOD
USE UTIL_TSTA_MOD
USE UTIL_TVAB_MOD
USE UTIL_TVERTICAL_GEOM_MOD
USE UTIL_TVETA_MOD
USE UTIL_TVFE_MOD
IMPLICIT NONE
TYPE (GEOMETRY), INTENT (IN), TARGET :: YD
LOGICAL, OPTIONAL, INTENT (IN) :: LDCREATED
LOGICAL :: LLCREATED
INTEGER :: J1
LOGICAL :: LLNONHYD_GEOM, LYRCSGEOM, LYRCSGEOMAD, LYRCVER, LYRELBC_GEO, LYRGSGEOM, LYRGSGEOMAD, LYROROG, LYRVAB, LYRVETA
LOGICAL :: LYRVFE

LLCREATED = .FALSE.
IF (PRESENT (LDCREATED)) THEN
  LLCREATED = LDCREATED
ENDIF
IF (.NOT. LLCREATED) THEN
  !$acc enter data create (YD)
  !$acc update device (YD)
ENDIF
LLNONHYD_GEOM = ASSOCIATED (YD%LNONHYD_GEOM)
IF (LLNONHYD_GEOM) THEN
  !$acc enter data create (YD%LNONHYD_GEOM)
  !$acc update device (YD%LNONHYD_GEOM)
  !$acc enter data attach (YD%LNONHYD_GEOM)
ENDIF


CALL COPY (YD%YRVERT_GEOM, LDCREATED=.TRUE.)

LYRVAB = ASSOCIATED (YD%YRVAB)
IF (LYRVAB) THEN
  !$acc enter data create (YD%YRVAB)
  !$acc update device (YD%YRVAB)
  CALL COPY (YD%YRVAB, LDCREATED=.TRUE.)
  !$acc enter data attach (YD%YRVAB)
ENDIF

LYRVETA = ASSOCIATED (YD%YRVETA)
IF (LYRVETA) THEN
  !$acc enter data create (YD%YRVETA)
  !$acc update device (YD%YRVETA)
  CALL COPY (YD%YRVETA, LDCREATED=.TRUE.)
  !$acc enter data attach (YD%YRVETA)
ENDIF

LYRVFE = ASSOCIATED (YD%YRVFE)
IF (LYRVFE) THEN
  !$acc enter data create (YD%YRVFE)
  !$acc update device (YD%YRVFE)
  CALL COPY (YD%YRVFE, LDCREATED=.TRUE.)
  !$acc enter data attach (YD%YRVFE)
ENDIF

LYRCVER = ASSOCIATED (YD%YRCVER)
IF (LYRCVER) THEN
  !$acc enter data create (YD%YRCVER)
  !$acc update device (YD%YRCVER)
  CALL COPY (YD%YRCVER, LDCREATED=.TRUE.)
  !$acc enter data attach (YD%YRCVER)
ENDIF

CALL COPY (YD%YRSTA, LDCREATED=.TRUE.)

CALL COPY (YD%YRLAP, LDCREATED=.TRUE.)

CALL COPY (YD%YRCSGLEG, LDCREATED=.TRUE.)

CALL COPY (YD%YRDIM, LDCREATED=.TRUE.)

CALL COPY (YD%YRDIMV, LDCREATED=.TRUE.)

CALL COPY (YD%YRMP, LDCREATED=.TRUE.)

CALL COPY (YD%YRGEM, LDCREATED=.TRUE.)

LYRCSGEOM = ASSOCIATED (YD%YRCSGEOM)
IF (LYRCSGEOM) THEN
  !$acc enter data create (YD%YRCSGEOM)
  !$acc update device (YD%YRCSGEOM)
  DO J1 = LBOUND (YD%YRCSGEOM, 1), UBOUND (YD%YRCSGEOM, 1)
    CALL COPY (YD%YRCSGEOM (J1), LDCREATED=.TRUE.)
  ENDDO
  !$acc enter data attach (YD%YRCSGEOM)
ENDIF

CALL COPY (YD%YRCSGEOM_NB, LDCREATED=.TRUE.)

CALL COPY (YD%YRCSGEOM_B, LDCREATED=.TRUE.)

LYRGSGEOM = ASSOCIATED (YD%YRGSGEOM)
IF (LYRGSGEOM) THEN
  !$acc enter data create (YD%YRGSGEOM)
  !$acc update device (YD%YRGSGEOM)
  DO J1 = LBOUND (YD%YRGSGEOM, 1), UBOUND (YD%YRGSGEOM, 1)
    CALL COPY (YD%YRGSGEOM (J1), LDCREATED=.TRUE.)
  ENDDO
  !$acc enter data attach (YD%YRGSGEOM)
ENDIF

CALL COPY (YD%YRGSGEOM_NB, LDCREATED=.TRUE.)

CALL COPY (YD%YRGSGEOM_B, LDCREATED=.TRUE.)


LYRCSGEOMAD = ASSOCIATED (YD%YRCSGEOMAD)
IF (LYRCSGEOMAD) THEN
  !$acc enter data create (YD%YRCSGEOMAD)
  !$acc update device (YD%YRCSGEOMAD)
  DO J1 = LBOUND (YD%YRCSGEOMAD, 1), UBOUND (YD%YRCSGEOMAD, 1)
    CALL COPY (YD%YRCSGEOMAD (J1), LDCREATED=.TRUE.)
  ENDDO
  !$acc enter data attach (YD%YRCSGEOMAD)
ENDIF

CALL COPY (YD%YRCSGEOMAD_NB, LDCREATED=.TRUE.)

LYRGSGEOMAD = ASSOCIATED (YD%YRGSGEOMAD)
IF (LYRGSGEOMAD) THEN
  !$acc enter data create (YD%YRGSGEOMAD)
  !$acc update device (YD%YRGSGEOMAD)
  DO J1 = LBOUND (YD%YRGSGEOMAD, 1), UBOUND (YD%YRGSGEOMAD, 1)
    CALL COPY (YD%YRGSGEOMAD (J1), LDCREATED=.TRUE.)
  ENDDO
  !$acc enter data attach (YD%YRGSGEOMAD)
ENDIF

CALL COPY (YD%YRGSGEOMAD_NB, LDCREATED=.TRUE.)

LYROROG = ALLOCATED (YD%YROROG)
IF (LYROROG) THEN
  !$acc enter data create (YD%YROROG)
  !$acc update device (YD%YROROG)
  DO J1 = LBOUND (YD%YROROG, 1), UBOUND (YD%YROROG, 1)
    CALL COPY (YD%YROROG (J1), LDCREATED=.TRUE.)
  ENDDO
  !$acc enter data attach (YD%YROROG)
ENDIF

CALL COPY (YD%YROROG_B, LDCREATED=.TRUE.)

CALL COPY (YD%YSPGEOM, LDCREATED=.TRUE.)

CALL COPY (YD%YVABIO, LDCREATED=.TRUE.)

CALL COPY (YD%YREDIM, LDCREATED=.TRUE.)

CALL COPY (YD%YREGEO, LDCREATED=.TRUE.)

CALL COPY (YD%YREMP, LDCREATED=.TRUE.)

CALL COPY (YD%YRELAP, LDCREATED=.TRUE.)

CALL COPY (YD%YREGSL, LDCREATED=.TRUE.)

LYRELBC_GEO = ASSOCIATED (YD%YRELBC_GEO)
IF (LYRELBC_GEO) THEN
  !$acc enter data create (YD%YRELBC_GEO)
  !$acc update device (YD%YRELBC_GEO)
  CALL COPY (YD%YRELBC_GEO, LDCREATED=.TRUE.)
  !$acc enter data attach (YD%YRELBC_GEO)
ENDIF

END SUBROUTINE

SUBROUTINE WIPE_GEOMETRY (YD, LDDELETED)
USE UTIL_TCSGEOM_BLOCKED_MOD
USE UTIL_TCSGEOM_MOD
USE UTIL_TCSGLEG_MOD
USE UTIL_TCVER_MOD
USE UTIL_TDIMV_MOD
USE UTIL_TDIM_MOD
USE UTIL_TEDIM_MOD
USE UTIL_TEGEO_MOD
USE UTIL_TEGSL_MOD
USE UTIL_TELBC_GEO_MOD
USE UTIL_TEMMP_MOD
USE UTIL_TGEM_MOD
USE UTIL_TGSGEOM_BLOCKED_MOD
USE UTIL_TGSGEOM_MOD
USE UTIL_TLAP_MOD
USE UTIL_TLEP_MOD
USE UTIL_TMP_MOD
USE UTIL_TOROG_BLOCKED_MOD
USE UTIL_TOROG_MOD
USE UTIL_TSPGEOM_MOD
USE UTIL_TSTA_MOD
USE UTIL_TVAB_MOD
USE UTIL_TVERTICAL_GEOM_MOD
USE UTIL_TVETA_MOD
USE UTIL_TVFE_MOD
IMPLICIT NONE
TYPE (GEOMETRY), INTENT (IN), TARGET :: YD
LOGICAL, OPTIONAL, INTENT (IN) :: LDDELETED
LOGICAL :: LLDELETED
INTEGER :: J1
LOGICAL :: LLNONHYD_GEOM, LYRCSGEOM, LYRCSGEOMAD, LYRCVER, LYRELBC_GEO, LYRGSGEOM, LYRGSGEOMAD, LYROROG, LYRVAB, LYRVETA
LOGICAL :: LYRVFE

LLNONHYD_GEOM = ASSOCIATED (YD%LNONHYD_GEOM)
IF (LLNONHYD_GEOM) THEN
  !$acc exit data detach (YD%LNONHYD_GEOM)
  !$acc exit data delete (YD%LNONHYD_GEOM)
ENDIF


CALL WIPE (YD%YRVERT_GEOM, LDDELETED=.TRUE.)

LYRVAB = ASSOCIATED (YD%YRVAB)
IF (LYRVAB) THEN
  !$acc exit data detach (YD%YRVAB)
  CALL WIPE (YD%YRVAB, LDDELETED=.TRUE.)
  !$acc exit data delete (YD%YRVAB)
ENDIF

LYRVETA = ASSOCIATED (YD%YRVETA)
IF (LYRVETA) THEN
  !$acc exit data detach (YD%YRVETA)
  CALL WIPE (YD%YRVETA, LDDELETED=.TRUE.)
  !$acc exit data delete (YD%YRVETA)
ENDIF

LYRVFE = ASSOCIATED (YD%YRVFE)
IF (LYRVFE) THEN
  !$acc exit data detach (YD%YRVFE)
  CALL WIPE (YD%YRVFE, LDDELETED=.TRUE.)
  !$acc exit data delete (YD%YRVFE)
ENDIF

LYRCVER = ASSOCIATED (YD%YRCVER)
IF (LYRCVER) THEN
  !$acc exit data detach (YD%YRCVER)
  CALL WIPE (YD%YRCVER, LDDELETED=.TRUE.)
  !$acc exit data delete (YD%YRCVER)
ENDIF

CALL WIPE (YD%YRSTA, LDDELETED=.TRUE.)

CALL WIPE (YD%YRLAP, LDDELETED=.TRUE.)

CALL WIPE (YD%YRCSGLEG, LDDELETED=.TRUE.)

CALL WIPE (YD%YRDIM, LDDELETED=.TRUE.)

CALL WIPE (YD%YRDIMV, LDDELETED=.TRUE.)

CALL WIPE (YD%YRMP, LDDELETED=.TRUE.)

CALL WIPE (YD%YRGEM, LDDELETED=.TRUE.)

LYRCSGEOM = ASSOCIATED (YD%YRCSGEOM)
IF (LYRCSGEOM) THEN
  !$acc exit data detach (YD%YRCSGEOM)
  DO J1 = LBOUND (YD%YRCSGEOM, 1), UBOUND (YD%YRCSGEOM, 1)
    CALL WIPE (YD%YRCSGEOM (J1), LDDELETED=.TRUE.)
  ENDDO
  !$acc exit data delete (YD%YRCSGEOM)
ENDIF

CALL WIPE (YD%YRCSGEOM_NB, LDDELETED=.TRUE.)

CALL WIPE (YD%YRCSGEOM_B, LDDELETED=.TRUE.)

LYRGSGEOM = ASSOCIATED (YD%YRGSGEOM)
IF (LYRGSGEOM) THEN
  !$acc exit data detach (YD%YRGSGEOM)
  DO J1 = LBOUND (YD%YRGSGEOM, 1), UBOUND (YD%YRGSGEOM, 1)
    CALL WIPE (YD%YRGSGEOM (J1), LDDELETED=.TRUE.)
  ENDDO
  !$acc exit data delete (YD%YRGSGEOM)
ENDIF

CALL WIPE (YD%YRGSGEOM_NB, LDDELETED=.TRUE.)

CALL WIPE (YD%YRGSGEOM_B, LDDELETED=.TRUE.)


LYRCSGEOMAD = ASSOCIATED (YD%YRCSGEOMAD)
IF (LYRCSGEOMAD) THEN
  !$acc exit data detach (YD%YRCSGEOMAD)
  DO J1 = LBOUND (YD%YRCSGEOMAD, 1), UBOUND (YD%YRCSGEOMAD, 1)
    CALL WIPE (YD%YRCSGEOMAD (J1), LDDELETED=.TRUE.)
  ENDDO
  !$acc exit data delete (YD%YRCSGEOMAD)
ENDIF

CALL WIPE (YD%YRCSGEOMAD_NB, LDDELETED=.TRUE.)

LYRGSGEOMAD = ASSOCIATED (YD%YRGSGEOMAD)
IF (LYRGSGEOMAD) THEN
  !$acc exit data detach (YD%YRGSGEOMAD)
  DO J1 = LBOUND (YD%YRGSGEOMAD, 1), UBOUND (YD%YRGSGEOMAD, 1)
    CALL WIPE (YD%YRGSGEOMAD (J1), LDDELETED=.TRUE.)
  ENDDO
  !$acc exit data delete (YD%YRGSGEOMAD)
ENDIF

CALL WIPE (YD%YRGSGEOMAD_NB, LDDELETED=.TRUE.)

LYROROG = ALLOCATED (YD%YROROG)
IF (LYROROG) THEN
  !$acc exit data detach (YD%YROROG)
  DO J1 = LBOUND (YD%YROROG, 1), UBOUND (YD%YROROG, 1)
    CALL WIPE (YD%YROROG (J1), LDDELETED=.TRUE.)
  ENDDO
  !$acc exit data delete (YD%YROROG)
ENDIF

CALL WIPE (YD%YROROG_B, LDDELETED=.TRUE.)

CALL WIPE (YD%YSPGEOM, LDDELETED=.TRUE.)

CALL WIPE (YD%YVABIO, LDDELETED=.TRUE.)

CALL WIPE (YD%YREDIM, LDDELETED=.TRUE.)

CALL WIPE (YD%YREGEO, LDDELETED=.TRUE.)

CALL WIPE (YD%YREMP, LDDELETED=.TRUE.)

CALL WIPE (YD%YRELAP, LDDELETED=.TRUE.)

CALL WIPE (YD%YREGSL, LDDELETED=.TRUE.)

LYRELBC_GEO = ASSOCIATED (YD%YRELBC_GEO)
IF (LYRELBC_GEO) THEN
  !$acc exit data detach (YD%YRELBC_GEO)
  CALL WIPE (YD%YRELBC_GEO, LDDELETED=.TRUE.)
  !$acc exit data delete (YD%YRELBC_GEO)
ENDIF

LLDELETED = .FALSE.
IF (PRESENT (LDDELETED)) THEN
  LLDELETED = LDDELETED
ENDIF
IF (.NOT. LLDELETED) THEN
  !$acc exit data delete (YD)
ENDIF
END SUBROUTINE



END MODULE
