MODULE UTIL_TEAERC_MACC_MOD

USE YOEAERC, ONLY : TEAERC_MACC

INTERFACE SAVE
MODULE PROCEDURE SAVE_TEAERC_MACC
END INTERFACE

INTERFACE LOAD
MODULE PROCEDURE LOAD_TEAERC_MACC
END INTERFACE

INTERFACE COPY
MODULE PROCEDURE COPY_TEAERC_MACC
END INTERFACE

INTERFACE WIPE
MODULE PROCEDURE WIPE_TEAERC_MACC
END INTERFACE



CONTAINS

SUBROUTINE SAVE_TEAERC_MACC (KLUN, YD)

IMPLICIT NONE
INTEGER, INTENT (IN) :: KLUN
TYPE (TEAERC_MACC), INTENT (IN), TARGET :: YD
LOGICAL :: LREF_AER_DPRS, LREF_AER_PRS, LREF_MON_AER_DPRS, LREF_MON_AER_PRS, LRMACBC, LRMACBC1, LRMACBC13D, LRMACBC2, LRMACBC23D, LRMACOR
LOGICAL :: LRMACOR1, LRMACOR13D, LRMACOR2, LRMACOR23D, LRMACSD, LRMACSD1, LRMACSD13D, LRMACSD2, LRMACSD23D, LRMACSD3
LOGICAL :: LRMACSD33D, LRMACSS, LRMACSS1, LRMACSS13D, LRMACSS2, LRMACSS23D, LRMACSS3, LRMACSS33D, LRMACSU, LRMACSU1
LOGICAL :: LRMACSU13D, LRMAEBC, LRMAEBC1, LRMAEBC13D, LRMAEBC2, LRMAEBC23D, LRMAEOR, LRMAEOR1, LRMAEOR13D, LRMAEOR2
LOGICAL :: LRMAEOR23D, LRMAESD, LRMAESD1, LRMAESD13D, LRMAESD2, LRMAESD23D, LRMAESD3, LRMAESD33D, LRMAESS, LRMAESS1
LOGICAL :: LRMAESS13D, LRMAESS2, LRMAESS23D, LRMAESS3, LRMAESS33D, LRMAESU, LRMAESU1, LRMAESU13D
LRMACBC = ALLOCATED (YD%RMACBC)
WRITE (KLUN) LRMACBC
IF (LRMACBC) THEN
  WRITE (KLUN) LBOUND (YD%RMACBC)
  WRITE (KLUN) UBOUND (YD%RMACBC)
  WRITE (KLUN) YD%RMACBC
ENDIF
LRMACOR = ALLOCATED (YD%RMACOR)
WRITE (KLUN) LRMACOR
IF (LRMACOR) THEN
  WRITE (KLUN) LBOUND (YD%RMACOR)
  WRITE (KLUN) UBOUND (YD%RMACOR)
  WRITE (KLUN) YD%RMACOR
ENDIF
LRMACSD = ALLOCATED (YD%RMACSD)
WRITE (KLUN) LRMACSD
IF (LRMACSD) THEN
  WRITE (KLUN) LBOUND (YD%RMACSD)
  WRITE (KLUN) UBOUND (YD%RMACSD)
  WRITE (KLUN) YD%RMACSD
ENDIF
LRMACSS = ALLOCATED (YD%RMACSS)
WRITE (KLUN) LRMACSS
IF (LRMACSS) THEN
  WRITE (KLUN) LBOUND (YD%RMACSS)
  WRITE (KLUN) UBOUND (YD%RMACSS)
  WRITE (KLUN) YD%RMACSS
ENDIF
LRMACSU = ALLOCATED (YD%RMACSU)
WRITE (KLUN) LRMACSU
IF (LRMACSU) THEN
  WRITE (KLUN) LBOUND (YD%RMACSU)
  WRITE (KLUN) UBOUND (YD%RMACSU)
  WRITE (KLUN) YD%RMACSU
ENDIF
LRMAEBC = ALLOCATED (YD%RMAEBC)
WRITE (KLUN) LRMAEBC
IF (LRMAEBC) THEN
  WRITE (KLUN) LBOUND (YD%RMAEBC)
  WRITE (KLUN) UBOUND (YD%RMAEBC)
  WRITE (KLUN) YD%RMAEBC
ENDIF
LRMAEOR = ALLOCATED (YD%RMAEOR)
WRITE (KLUN) LRMAEOR
IF (LRMAEOR) THEN
  WRITE (KLUN) LBOUND (YD%RMAEOR)
  WRITE (KLUN) UBOUND (YD%RMAEOR)
  WRITE (KLUN) YD%RMAEOR
ENDIF
LRMAESD = ALLOCATED (YD%RMAESD)
WRITE (KLUN) LRMAESD
IF (LRMAESD) THEN
  WRITE (KLUN) LBOUND (YD%RMAESD)
  WRITE (KLUN) UBOUND (YD%RMAESD)
  WRITE (KLUN) YD%RMAESD
ENDIF
LRMAESS = ALLOCATED (YD%RMAESS)
WRITE (KLUN) LRMAESS
IF (LRMAESS) THEN
  WRITE (KLUN) LBOUND (YD%RMAESS)
  WRITE (KLUN) UBOUND (YD%RMAESS)
  WRITE (KLUN) YD%RMAESS
ENDIF
LRMAESU = ALLOCATED (YD%RMAESU)
WRITE (KLUN) LRMAESU
IF (LRMAESU) THEN
  WRITE (KLUN) LBOUND (YD%RMAESU)
  WRITE (KLUN) UBOUND (YD%RMAESU)
  WRITE (KLUN) YD%RMAESU
ENDIF
LRMACBC1 = ALLOCATED (YD%RMACBC1)
WRITE (KLUN) LRMACBC1
IF (LRMACBC1) THEN
  WRITE (KLUN) LBOUND (YD%RMACBC1)
  WRITE (KLUN) UBOUND (YD%RMACBC1)
  WRITE (KLUN) YD%RMACBC1
ENDIF
LRMACBC2 = ALLOCATED (YD%RMACBC2)
WRITE (KLUN) LRMACBC2
IF (LRMACBC2) THEN
  WRITE (KLUN) LBOUND (YD%RMACBC2)
  WRITE (KLUN) UBOUND (YD%RMACBC2)
  WRITE (KLUN) YD%RMACBC2
ENDIF
LRMAEBC1 = ALLOCATED (YD%RMAEBC1)
WRITE (KLUN) LRMAEBC1
IF (LRMAEBC1) THEN
  WRITE (KLUN) LBOUND (YD%RMAEBC1)
  WRITE (KLUN) UBOUND (YD%RMAEBC1)
  WRITE (KLUN) YD%RMAEBC1
ENDIF
LRMAEBC2 = ALLOCATED (YD%RMAEBC2)
WRITE (KLUN) LRMAEBC2
IF (LRMAEBC2) THEN
  WRITE (KLUN) LBOUND (YD%RMAEBC2)
  WRITE (KLUN) UBOUND (YD%RMAEBC2)
  WRITE (KLUN) YD%RMAEBC2
ENDIF
LRMACOR1 = ALLOCATED (YD%RMACOR1)
WRITE (KLUN) LRMACOR1
IF (LRMACOR1) THEN
  WRITE (KLUN) LBOUND (YD%RMACOR1)
  WRITE (KLUN) UBOUND (YD%RMACOR1)
  WRITE (KLUN) YD%RMACOR1
ENDIF
LRMACOR2 = ALLOCATED (YD%RMACOR2)
WRITE (KLUN) LRMACOR2
IF (LRMACOR2) THEN
  WRITE (KLUN) LBOUND (YD%RMACOR2)
  WRITE (KLUN) UBOUND (YD%RMACOR2)
  WRITE (KLUN) YD%RMACOR2
ENDIF
LRMAEOR1 = ALLOCATED (YD%RMAEOR1)
WRITE (KLUN) LRMAEOR1
IF (LRMAEOR1) THEN
  WRITE (KLUN) LBOUND (YD%RMAEOR1)
  WRITE (KLUN) UBOUND (YD%RMAEOR1)
  WRITE (KLUN) YD%RMAEOR1
ENDIF
LRMAEOR2 = ALLOCATED (YD%RMAEOR2)
WRITE (KLUN) LRMAEOR2
IF (LRMAEOR2) THEN
  WRITE (KLUN) LBOUND (YD%RMAEOR2)
  WRITE (KLUN) UBOUND (YD%RMAEOR2)
  WRITE (KLUN) YD%RMAEOR2
ENDIF
LRMACSD1 = ALLOCATED (YD%RMACSD1)
WRITE (KLUN) LRMACSD1
IF (LRMACSD1) THEN
  WRITE (KLUN) LBOUND (YD%RMACSD1)
  WRITE (KLUN) UBOUND (YD%RMACSD1)
  WRITE (KLUN) YD%RMACSD1
ENDIF
LRMACSD2 = ALLOCATED (YD%RMACSD2)
WRITE (KLUN) LRMACSD2
IF (LRMACSD2) THEN
  WRITE (KLUN) LBOUND (YD%RMACSD2)
  WRITE (KLUN) UBOUND (YD%RMACSD2)
  WRITE (KLUN) YD%RMACSD2
ENDIF
LRMACSD3 = ALLOCATED (YD%RMACSD3)
WRITE (KLUN) LRMACSD3
IF (LRMACSD3) THEN
  WRITE (KLUN) LBOUND (YD%RMACSD3)
  WRITE (KLUN) UBOUND (YD%RMACSD3)
  WRITE (KLUN) YD%RMACSD3
ENDIF
LRMAESD1 = ALLOCATED (YD%RMAESD1)
WRITE (KLUN) LRMAESD1
IF (LRMAESD1) THEN
  WRITE (KLUN) LBOUND (YD%RMAESD1)
  WRITE (KLUN) UBOUND (YD%RMAESD1)
  WRITE (KLUN) YD%RMAESD1
ENDIF
LRMAESD2 = ALLOCATED (YD%RMAESD2)
WRITE (KLUN) LRMAESD2
IF (LRMAESD2) THEN
  WRITE (KLUN) LBOUND (YD%RMAESD2)
  WRITE (KLUN) UBOUND (YD%RMAESD2)
  WRITE (KLUN) YD%RMAESD2
ENDIF
LRMAESD3 = ALLOCATED (YD%RMAESD3)
WRITE (KLUN) LRMAESD3
IF (LRMAESD3) THEN
  WRITE (KLUN) LBOUND (YD%RMAESD3)
  WRITE (KLUN) UBOUND (YD%RMAESD3)
  WRITE (KLUN) YD%RMAESD3
ENDIF
LRMACSS1 = ALLOCATED (YD%RMACSS1)
WRITE (KLUN) LRMACSS1
IF (LRMACSS1) THEN
  WRITE (KLUN) LBOUND (YD%RMACSS1)
  WRITE (KLUN) UBOUND (YD%RMACSS1)
  WRITE (KLUN) YD%RMACSS1
ENDIF
LRMACSS2 = ALLOCATED (YD%RMACSS2)
WRITE (KLUN) LRMACSS2
IF (LRMACSS2) THEN
  WRITE (KLUN) LBOUND (YD%RMACSS2)
  WRITE (KLUN) UBOUND (YD%RMACSS2)
  WRITE (KLUN) YD%RMACSS2
ENDIF
LRMACSS3 = ALLOCATED (YD%RMACSS3)
WRITE (KLUN) LRMACSS3
IF (LRMACSS3) THEN
  WRITE (KLUN) LBOUND (YD%RMACSS3)
  WRITE (KLUN) UBOUND (YD%RMACSS3)
  WRITE (KLUN) YD%RMACSS3
ENDIF
LRMAESS1 = ALLOCATED (YD%RMAESS1)
WRITE (KLUN) LRMAESS1
IF (LRMAESS1) THEN
  WRITE (KLUN) LBOUND (YD%RMAESS1)
  WRITE (KLUN) UBOUND (YD%RMAESS1)
  WRITE (KLUN) YD%RMAESS1
ENDIF
LRMAESS2 = ALLOCATED (YD%RMAESS2)
WRITE (KLUN) LRMAESS2
IF (LRMAESS2) THEN
  WRITE (KLUN) LBOUND (YD%RMAESS2)
  WRITE (KLUN) UBOUND (YD%RMAESS2)
  WRITE (KLUN) YD%RMAESS2
ENDIF
LRMAESS3 = ALLOCATED (YD%RMAESS3)
WRITE (KLUN) LRMAESS3
IF (LRMAESS3) THEN
  WRITE (KLUN) LBOUND (YD%RMAESS3)
  WRITE (KLUN) UBOUND (YD%RMAESS3)
  WRITE (KLUN) YD%RMAESS3
ENDIF
LRMACSU1 = ALLOCATED (YD%RMACSU1)
WRITE (KLUN) LRMACSU1
IF (LRMACSU1) THEN
  WRITE (KLUN) LBOUND (YD%RMACSU1)
  WRITE (KLUN) UBOUND (YD%RMACSU1)
  WRITE (KLUN) YD%RMACSU1
ENDIF
LRMAESU1 = ALLOCATED (YD%RMAESU1)
WRITE (KLUN) LRMAESU1
IF (LRMAESU1) THEN
  WRITE (KLUN) LBOUND (YD%RMAESU1)
  WRITE (KLUN) UBOUND (YD%RMAESU1)
  WRITE (KLUN) YD%RMAESU1
ENDIF
LRMACBC13D = ASSOCIATED (YD%RMACBC13D)
WRITE (KLUN) LRMACBC13D
IF (LRMACBC13D) THEN
  WRITE (KLUN) LBOUND (YD%RMACBC13D)
  WRITE (KLUN) UBOUND (YD%RMACBC13D)
  WRITE (KLUN) YD%RMACBC13D
ENDIF
LRMACBC23D = ASSOCIATED (YD%RMACBC23D)
WRITE (KLUN) LRMACBC23D
IF (LRMACBC23D) THEN
  WRITE (KLUN) LBOUND (YD%RMACBC23D)
  WRITE (KLUN) UBOUND (YD%RMACBC23D)
  WRITE (KLUN) YD%RMACBC23D
ENDIF
LRMACOR13D = ASSOCIATED (YD%RMACOR13D)
WRITE (KLUN) LRMACOR13D
IF (LRMACOR13D) THEN
  WRITE (KLUN) LBOUND (YD%RMACOR13D)
  WRITE (KLUN) UBOUND (YD%RMACOR13D)
  WRITE (KLUN) YD%RMACOR13D
ENDIF
LRMACOR23D = ASSOCIATED (YD%RMACOR23D)
WRITE (KLUN) LRMACOR23D
IF (LRMACOR23D) THEN
  WRITE (KLUN) LBOUND (YD%RMACOR23D)
  WRITE (KLUN) UBOUND (YD%RMACOR23D)
  WRITE (KLUN) YD%RMACOR23D
ENDIF
LRMACSD13D = ASSOCIATED (YD%RMACSD13D)
WRITE (KLUN) LRMACSD13D
IF (LRMACSD13D) THEN
  WRITE (KLUN) LBOUND (YD%RMACSD13D)
  WRITE (KLUN) UBOUND (YD%RMACSD13D)
  WRITE (KLUN) YD%RMACSD13D
ENDIF
LRMACSD23D = ASSOCIATED (YD%RMACSD23D)
WRITE (KLUN) LRMACSD23D
IF (LRMACSD23D) THEN
  WRITE (KLUN) LBOUND (YD%RMACSD23D)
  WRITE (KLUN) UBOUND (YD%RMACSD23D)
  WRITE (KLUN) YD%RMACSD23D
ENDIF
LRMACSD33D = ASSOCIATED (YD%RMACSD33D)
WRITE (KLUN) LRMACSD33D
IF (LRMACSD33D) THEN
  WRITE (KLUN) LBOUND (YD%RMACSD33D)
  WRITE (KLUN) UBOUND (YD%RMACSD33D)
  WRITE (KLUN) YD%RMACSD33D
ENDIF
LRMACSS13D = ASSOCIATED (YD%RMACSS13D)
WRITE (KLUN) LRMACSS13D
IF (LRMACSS13D) THEN
  WRITE (KLUN) LBOUND (YD%RMACSS13D)
  WRITE (KLUN) UBOUND (YD%RMACSS13D)
  WRITE (KLUN) YD%RMACSS13D
ENDIF
LRMACSS23D = ASSOCIATED (YD%RMACSS23D)
WRITE (KLUN) LRMACSS23D
IF (LRMACSS23D) THEN
  WRITE (KLUN) LBOUND (YD%RMACSS23D)
  WRITE (KLUN) UBOUND (YD%RMACSS23D)
  WRITE (KLUN) YD%RMACSS23D
ENDIF
LRMACSS33D = ASSOCIATED (YD%RMACSS33D)
WRITE (KLUN) LRMACSS33D
IF (LRMACSS33D) THEN
  WRITE (KLUN) LBOUND (YD%RMACSS33D)
  WRITE (KLUN) UBOUND (YD%RMACSS33D)
  WRITE (KLUN) YD%RMACSS33D
ENDIF
LRMACSU13D = ASSOCIATED (YD%RMACSU13D)
WRITE (KLUN) LRMACSU13D
IF (LRMACSU13D) THEN
  WRITE (KLUN) LBOUND (YD%RMACSU13D)
  WRITE (KLUN) UBOUND (YD%RMACSU13D)
  WRITE (KLUN) YD%RMACSU13D
ENDIF
LREF_MON_AER_PRS = ASSOCIATED (YD%REF_MON_AER_PRS)
WRITE (KLUN) LREF_MON_AER_PRS
IF (LREF_MON_AER_PRS) THEN
  WRITE (KLUN) LBOUND (YD%REF_MON_AER_PRS)
  WRITE (KLUN) UBOUND (YD%REF_MON_AER_PRS)
  WRITE (KLUN) YD%REF_MON_AER_PRS
ENDIF
LREF_MON_AER_DPRS = ASSOCIATED (YD%REF_MON_AER_DPRS)
WRITE (KLUN) LREF_MON_AER_DPRS
IF (LREF_MON_AER_DPRS) THEN
  WRITE (KLUN) LBOUND (YD%REF_MON_AER_DPRS)
  WRITE (KLUN) UBOUND (YD%REF_MON_AER_DPRS)
  WRITE (KLUN) YD%REF_MON_AER_DPRS
ENDIF
LRMAEBC13D = ALLOCATED (YD%RMAEBC13D)
WRITE (KLUN) LRMAEBC13D
IF (LRMAEBC13D) THEN
  WRITE (KLUN) LBOUND (YD%RMAEBC13D)
  WRITE (KLUN) UBOUND (YD%RMAEBC13D)
  WRITE (KLUN) YD%RMAEBC13D
ENDIF
LRMAEBC23D = ALLOCATED (YD%RMAEBC23D)
WRITE (KLUN) LRMAEBC23D
IF (LRMAEBC23D) THEN
  WRITE (KLUN) LBOUND (YD%RMAEBC23D)
  WRITE (KLUN) UBOUND (YD%RMAEBC23D)
  WRITE (KLUN) YD%RMAEBC23D
ENDIF
LRMAEOR13D = ALLOCATED (YD%RMAEOR13D)
WRITE (KLUN) LRMAEOR13D
IF (LRMAEOR13D) THEN
  WRITE (KLUN) LBOUND (YD%RMAEOR13D)
  WRITE (KLUN) UBOUND (YD%RMAEOR13D)
  WRITE (KLUN) YD%RMAEOR13D
ENDIF
LRMAEOR23D = ALLOCATED (YD%RMAEOR23D)
WRITE (KLUN) LRMAEOR23D
IF (LRMAEOR23D) THEN
  WRITE (KLUN) LBOUND (YD%RMAEOR23D)
  WRITE (KLUN) UBOUND (YD%RMAEOR23D)
  WRITE (KLUN) YD%RMAEOR23D
ENDIF
LRMAESD13D = ALLOCATED (YD%RMAESD13D)
WRITE (KLUN) LRMAESD13D
IF (LRMAESD13D) THEN
  WRITE (KLUN) LBOUND (YD%RMAESD13D)
  WRITE (KLUN) UBOUND (YD%RMAESD13D)
  WRITE (KLUN) YD%RMAESD13D
ENDIF
LRMAESD23D = ALLOCATED (YD%RMAESD23D)
WRITE (KLUN) LRMAESD23D
IF (LRMAESD23D) THEN
  WRITE (KLUN) LBOUND (YD%RMAESD23D)
  WRITE (KLUN) UBOUND (YD%RMAESD23D)
  WRITE (KLUN) YD%RMAESD23D
ENDIF
LRMAESD33D = ALLOCATED (YD%RMAESD33D)
WRITE (KLUN) LRMAESD33D
IF (LRMAESD33D) THEN
  WRITE (KLUN) LBOUND (YD%RMAESD33D)
  WRITE (KLUN) UBOUND (YD%RMAESD33D)
  WRITE (KLUN) YD%RMAESD33D
ENDIF
LRMAESS13D = ALLOCATED (YD%RMAESS13D)
WRITE (KLUN) LRMAESS13D
IF (LRMAESS13D) THEN
  WRITE (KLUN) LBOUND (YD%RMAESS13D)
  WRITE (KLUN) UBOUND (YD%RMAESS13D)
  WRITE (KLUN) YD%RMAESS13D
ENDIF
LRMAESS23D = ALLOCATED (YD%RMAESS23D)
WRITE (KLUN) LRMAESS23D
IF (LRMAESS23D) THEN
  WRITE (KLUN) LBOUND (YD%RMAESS23D)
  WRITE (KLUN) UBOUND (YD%RMAESS23D)
  WRITE (KLUN) YD%RMAESS23D
ENDIF
LRMAESS33D = ALLOCATED (YD%RMAESS33D)
WRITE (KLUN) LRMAESS33D
IF (LRMAESS33D) THEN
  WRITE (KLUN) LBOUND (YD%RMAESS33D)
  WRITE (KLUN) UBOUND (YD%RMAESS33D)
  WRITE (KLUN) YD%RMAESS33D
ENDIF
LRMAESU13D = ALLOCATED (YD%RMAESU13D)
WRITE (KLUN) LRMAESU13D
IF (LRMAESU13D) THEN
  WRITE (KLUN) LBOUND (YD%RMAESU13D)
  WRITE (KLUN) UBOUND (YD%RMAESU13D)
  WRITE (KLUN) YD%RMAESU13D
ENDIF
LREF_AER_PRS = ALLOCATED (YD%REF_AER_PRS)
WRITE (KLUN) LREF_AER_PRS
IF (LREF_AER_PRS) THEN
  WRITE (KLUN) LBOUND (YD%REF_AER_PRS)
  WRITE (KLUN) UBOUND (YD%REF_AER_PRS)
  WRITE (KLUN) YD%REF_AER_PRS
ENDIF
LREF_AER_DPRS = ALLOCATED (YD%REF_AER_DPRS)
WRITE (KLUN) LREF_AER_DPRS
IF (LREF_AER_DPRS) THEN
  WRITE (KLUN) LBOUND (YD%REF_AER_DPRS)
  WRITE (KLUN) UBOUND (YD%REF_AER_DPRS)
  WRITE (KLUN) YD%REF_AER_DPRS
ENDIF
WRITE (KLUN) YD%IS_INITIALISED
END SUBROUTINE

SUBROUTINE LOAD_TEAERC_MACC (KLUN, YD)
USE PARKIND1, ONLY : JPRD

IMPLICIT NONE
INTEGER, INTENT (IN) :: KLUN
TYPE (TEAERC_MACC), INTENT (OUT), TARGET :: YD
INTEGER :: IL2(2), IU2(2), IL3(3), IU3(3), IL4(4), IU4(4)
LOGICAL :: LREF_AER_DPRS, LREF_AER_PRS, LREF_MON_AER_DPRS, LREF_MON_AER_PRS, LRMACBC, LRMACBC1, LRMACBC13D, LRMACBC2, LRMACBC23D, LRMACOR
LOGICAL :: LRMACOR1, LRMACOR13D, LRMACOR2, LRMACOR23D, LRMACSD, LRMACSD1, LRMACSD13D, LRMACSD2, LRMACSD23D, LRMACSD3
LOGICAL :: LRMACSD33D, LRMACSS, LRMACSS1, LRMACSS13D, LRMACSS2, LRMACSS23D, LRMACSS3, LRMACSS33D, LRMACSU, LRMACSU1
LOGICAL :: LRMACSU13D, LRMAEBC, LRMAEBC1, LRMAEBC13D, LRMAEBC2, LRMAEBC23D, LRMAEOR, LRMAEOR1, LRMAEOR13D, LRMAEOR2
LOGICAL :: LRMAEOR23D, LRMAESD, LRMAESD1, LRMAESD13D, LRMAESD2, LRMAESD23D, LRMAESD3, LRMAESD33D, LRMAESS, LRMAESS1
LOGICAL :: LRMAESS13D, LRMAESS2, LRMAESS23D, LRMAESS3, LRMAESS33D, LRMAESU, LRMAESU1, LRMAESU13D
REAL(KIND=JPRD), ALLOCATABLE :: ZTMP2 (:,:)
REAL(KIND=JPRD), ALLOCATABLE :: ZTMP3 (:,:,:)
REAL(KIND=JPRD), ALLOCATABLE :: ZTMP4 (:,:,:,:)
READ (KLUN) LRMACBC
IF (LRMACBC) THEN
  READ (KLUN) IL3
  READ (KLUN) IU3
  ALLOCATE (YD%RMACBC (IL3(1):IU3(1), IL3(2):IU3(2), IL3(3):IU3(3)))
  ALLOCATE (ZTMP3(LBOUND(YD%RMACBC,1):UBOUND(YD%RMACBC,1), LBOUND(YD%RMACBC,2):UBOUND(YD%RMACBC,2), LBOUND(YD%RMACBC,3):UBOUND(YD%RMACBC,3)))
  READ (KLUN) ZTMP3
  YD%RMACBC = ZTMP3
  DEALLOCATE (ZTMP3)
ENDIF
READ (KLUN) LRMACOR
IF (LRMACOR) THEN
  READ (KLUN) IL3
  READ (KLUN) IU3
  ALLOCATE (YD%RMACOR (IL3(1):IU3(1), IL3(2):IU3(2), IL3(3):IU3(3)))
  ALLOCATE (ZTMP3(LBOUND(YD%RMACOR,1):UBOUND(YD%RMACOR,1), LBOUND(YD%RMACOR,2):UBOUND(YD%RMACOR,2), LBOUND(YD%RMACOR,3):UBOUND(YD%RMACOR,3)))
  READ (KLUN) ZTMP3
  YD%RMACOR = ZTMP3
  DEALLOCATE (ZTMP3)
ENDIF
READ (KLUN) LRMACSD
IF (LRMACSD) THEN
  READ (KLUN) IL3
  READ (KLUN) IU3
  ALLOCATE (YD%RMACSD (IL3(1):IU3(1), IL3(2):IU3(2), IL3(3):IU3(3)))
  ALLOCATE (ZTMP3(LBOUND(YD%RMACSD,1):UBOUND(YD%RMACSD,1), LBOUND(YD%RMACSD,2):UBOUND(YD%RMACSD,2), LBOUND(YD%RMACSD,3):UBOUND(YD%RMACSD,3)))
  READ (KLUN) ZTMP3
  YD%RMACSD = ZTMP3
  DEALLOCATE (ZTMP3)
ENDIF
READ (KLUN) LRMACSS
IF (LRMACSS) THEN
  READ (KLUN) IL3
  READ (KLUN) IU3
  ALLOCATE (YD%RMACSS (IL3(1):IU3(1), IL3(2):IU3(2), IL3(3):IU3(3)))
  ALLOCATE (ZTMP3(LBOUND(YD%RMACSS,1):UBOUND(YD%RMACSS,1), LBOUND(YD%RMACSS,2):UBOUND(YD%RMACSS,2), LBOUND(YD%RMACSS,3):UBOUND(YD%RMACSS,3)))
  READ (KLUN) ZTMP3
  YD%RMACSS = ZTMP3
  DEALLOCATE (ZTMP3)
ENDIF
READ (KLUN) LRMACSU
IF (LRMACSU) THEN
  READ (KLUN) IL3
  READ (KLUN) IU3
  ALLOCATE (YD%RMACSU (IL3(1):IU3(1), IL3(2):IU3(2), IL3(3):IU3(3)))
  ALLOCATE (ZTMP3(LBOUND(YD%RMACSU,1):UBOUND(YD%RMACSU,1), LBOUND(YD%RMACSU,2):UBOUND(YD%RMACSU,2), LBOUND(YD%RMACSU,3):UBOUND(YD%RMACSU,3)))
  READ (KLUN) ZTMP3
  YD%RMACSU = ZTMP3
  DEALLOCATE (ZTMP3)
ENDIF
READ (KLUN) LRMAEBC
IF (LRMAEBC) THEN
  READ (KLUN) IL2
  READ (KLUN) IU2
  ALLOCATE (YD%RMAEBC (IL2(1):IU2(1), IL2(2):IU2(2)))
  ALLOCATE (ZTMP2(LBOUND(YD%RMAEBC,1):UBOUND(YD%RMAEBC,1), LBOUND(YD%RMAEBC,2):UBOUND(YD%RMAEBC,2)))
  READ (KLUN) ZTMP2
  YD%RMAEBC = ZTMP2
  DEALLOCATE (ZTMP2)
ENDIF
READ (KLUN) LRMAEOR
IF (LRMAEOR) THEN
  READ (KLUN) IL2
  READ (KLUN) IU2
  ALLOCATE (YD%RMAEOR (IL2(1):IU2(1), IL2(2):IU2(2)))
  ALLOCATE (ZTMP2(LBOUND(YD%RMAEOR,1):UBOUND(YD%RMAEOR,1), LBOUND(YD%RMAEOR,2):UBOUND(YD%RMAEOR,2)))
  READ (KLUN) ZTMP2
  YD%RMAEOR = ZTMP2
  DEALLOCATE (ZTMP2)
ENDIF
READ (KLUN) LRMAESD
IF (LRMAESD) THEN
  READ (KLUN) IL2
  READ (KLUN) IU2
  ALLOCATE (YD%RMAESD (IL2(1):IU2(1), IL2(2):IU2(2)))
  ALLOCATE (ZTMP2(LBOUND(YD%RMAESD,1):UBOUND(YD%RMAESD,1), LBOUND(YD%RMAESD,2):UBOUND(YD%RMAESD,2)))
  READ (KLUN) ZTMP2
  YD%RMAESD = ZTMP2
  DEALLOCATE (ZTMP2)
ENDIF
READ (KLUN) LRMAESS
IF (LRMAESS) THEN
  READ (KLUN) IL2
  READ (KLUN) IU2
  ALLOCATE (YD%RMAESS (IL2(1):IU2(1), IL2(2):IU2(2)))
  ALLOCATE (ZTMP2(LBOUND(YD%RMAESS,1):UBOUND(YD%RMAESS,1), LBOUND(YD%RMAESS,2):UBOUND(YD%RMAESS,2)))
  READ (KLUN) ZTMP2
  YD%RMAESS = ZTMP2
  DEALLOCATE (ZTMP2)
ENDIF
READ (KLUN) LRMAESU
IF (LRMAESU) THEN
  READ (KLUN) IL2
  READ (KLUN) IU2
  ALLOCATE (YD%RMAESU (IL2(1):IU2(1), IL2(2):IU2(2)))
  ALLOCATE (ZTMP2(LBOUND(YD%RMAESU,1):UBOUND(YD%RMAESU,1), LBOUND(YD%RMAESU,2):UBOUND(YD%RMAESU,2)))
  READ (KLUN) ZTMP2
  YD%RMAESU = ZTMP2
  DEALLOCATE (ZTMP2)
ENDIF
READ (KLUN) LRMACBC1
IF (LRMACBC1) THEN
  READ (KLUN) IL3
  READ (KLUN) IU3
  ALLOCATE (YD%RMACBC1 (IL3(1):IU3(1), IL3(2):IU3(2), IL3(3):IU3(3)))
  ALLOCATE (ZTMP3(LBOUND(YD%RMACBC1,1):UBOUND(YD%RMACBC1,1), LBOUND(YD%RMACBC1,2):UBOUND(YD%RMACBC1,2), LBOUND(YD%RMACBC1,3):UBOUND(YD%RMACBC1,3)))
  READ (KLUN) ZTMP3
  YD%RMACBC1 = ZTMP3
  DEALLOCATE (ZTMP3)
ENDIF
READ (KLUN) LRMACBC2
IF (LRMACBC2) THEN
  READ (KLUN) IL3
  READ (KLUN) IU3
  ALLOCATE (YD%RMACBC2 (IL3(1):IU3(1), IL3(2):IU3(2), IL3(3):IU3(3)))
  ALLOCATE (ZTMP3(LBOUND(YD%RMACBC2,1):UBOUND(YD%RMACBC2,1), LBOUND(YD%RMACBC2,2):UBOUND(YD%RMACBC2,2), LBOUND(YD%RMACBC2,3):UBOUND(YD%RMACBC2,3)))
  READ (KLUN) ZTMP3
  YD%RMACBC2 = ZTMP3
  DEALLOCATE (ZTMP3)
ENDIF
READ (KLUN) LRMAEBC1
IF (LRMAEBC1) THEN
  READ (KLUN) IL2
  READ (KLUN) IU2
  ALLOCATE (YD%RMAEBC1 (IL2(1):IU2(1), IL2(2):IU2(2)))
  ALLOCATE (ZTMP2(LBOUND(YD%RMAEBC1,1):UBOUND(YD%RMAEBC1,1), LBOUND(YD%RMAEBC1,2):UBOUND(YD%RMAEBC1,2)))
  READ (KLUN) ZTMP2
  YD%RMAEBC1 = ZTMP2
  DEALLOCATE (ZTMP2)
ENDIF
READ (KLUN) LRMAEBC2
IF (LRMAEBC2) THEN
  READ (KLUN) IL2
  READ (KLUN) IU2
  ALLOCATE (YD%RMAEBC2 (IL2(1):IU2(1), IL2(2):IU2(2)))
  ALLOCATE (ZTMP2(LBOUND(YD%RMAEBC2,1):UBOUND(YD%RMAEBC2,1), LBOUND(YD%RMAEBC2,2):UBOUND(YD%RMAEBC2,2)))
  READ (KLUN) ZTMP2
  YD%RMAEBC2 = ZTMP2
  DEALLOCATE (ZTMP2)
ENDIF
READ (KLUN) LRMACOR1
IF (LRMACOR1) THEN
  READ (KLUN) IL3
  READ (KLUN) IU3
  ALLOCATE (YD%RMACOR1 (IL3(1):IU3(1), IL3(2):IU3(2), IL3(3):IU3(3)))
  ALLOCATE (ZTMP3(LBOUND(YD%RMACOR1,1):UBOUND(YD%RMACOR1,1), LBOUND(YD%RMACOR1,2):UBOUND(YD%RMACOR1,2), LBOUND(YD%RMACOR1,3):UBOUND(YD%RMACOR1,3)))
  READ (KLUN) ZTMP3
  YD%RMACOR1 = ZTMP3
  DEALLOCATE (ZTMP3)
ENDIF
READ (KLUN) LRMACOR2
IF (LRMACOR2) THEN
  READ (KLUN) IL3
  READ (KLUN) IU3
  ALLOCATE (YD%RMACOR2 (IL3(1):IU3(1), IL3(2):IU3(2), IL3(3):IU3(3)))
  ALLOCATE (ZTMP3(LBOUND(YD%RMACOR2,1):UBOUND(YD%RMACOR2,1), LBOUND(YD%RMACOR2,2):UBOUND(YD%RMACOR2,2), LBOUND(YD%RMACOR2,3):UBOUND(YD%RMACOR2,3)))
  READ (KLUN) ZTMP3
  YD%RMACOR2 = ZTMP3
  DEALLOCATE (ZTMP3)
ENDIF
READ (KLUN) LRMAEOR1
IF (LRMAEOR1) THEN
  READ (KLUN) IL2
  READ (KLUN) IU2
  ALLOCATE (YD%RMAEOR1 (IL2(1):IU2(1), IL2(2):IU2(2)))
  ALLOCATE (ZTMP2(LBOUND(YD%RMAEOR1,1):UBOUND(YD%RMAEOR1,1), LBOUND(YD%RMAEOR1,2):UBOUND(YD%RMAEOR1,2)))
  READ (KLUN) ZTMP2
  YD%RMAEOR1 = ZTMP2
  DEALLOCATE (ZTMP2)
ENDIF
READ (KLUN) LRMAEOR2
IF (LRMAEOR2) THEN
  READ (KLUN) IL2
  READ (KLUN) IU2
  ALLOCATE (YD%RMAEOR2 (IL2(1):IU2(1), IL2(2):IU2(2)))
  ALLOCATE (ZTMP2(LBOUND(YD%RMAEOR2,1):UBOUND(YD%RMAEOR2,1), LBOUND(YD%RMAEOR2,2):UBOUND(YD%RMAEOR2,2)))
  READ (KLUN) ZTMP2
  YD%RMAEOR2 = ZTMP2
  DEALLOCATE (ZTMP2)
ENDIF
READ (KLUN) LRMACSD1
IF (LRMACSD1) THEN
  READ (KLUN) IL3
  READ (KLUN) IU3
  ALLOCATE (YD%RMACSD1 (IL3(1):IU3(1), IL3(2):IU3(2), IL3(3):IU3(3)))
  ALLOCATE (ZTMP3(LBOUND(YD%RMACSD1,1):UBOUND(YD%RMACSD1,1), LBOUND(YD%RMACSD1,2):UBOUND(YD%RMACSD1,2), LBOUND(YD%RMACSD1,3):UBOUND(YD%RMACSD1,3)))
  READ (KLUN) ZTMP3
  YD%RMACSD1 = ZTMP3
  DEALLOCATE (ZTMP3)
ENDIF
READ (KLUN) LRMACSD2
IF (LRMACSD2) THEN
  READ (KLUN) IL3
  READ (KLUN) IU3
  ALLOCATE (YD%RMACSD2 (IL3(1):IU3(1), IL3(2):IU3(2), IL3(3):IU3(3)))
  ALLOCATE (ZTMP3(LBOUND(YD%RMACSD2,1):UBOUND(YD%RMACSD2,1), LBOUND(YD%RMACSD2,2):UBOUND(YD%RMACSD2,2), LBOUND(YD%RMACSD2,3):UBOUND(YD%RMACSD2,3)))
  READ (KLUN) ZTMP3
  YD%RMACSD2 = ZTMP3
  DEALLOCATE (ZTMP3)
ENDIF
READ (KLUN) LRMACSD3
IF (LRMACSD3) THEN
  READ (KLUN) IL3
  READ (KLUN) IU3
  ALLOCATE (YD%RMACSD3 (IL3(1):IU3(1), IL3(2):IU3(2), IL3(3):IU3(3)))
  ALLOCATE (ZTMP3(LBOUND(YD%RMACSD3,1):UBOUND(YD%RMACSD3,1), LBOUND(YD%RMACSD3,2):UBOUND(YD%RMACSD3,2), LBOUND(YD%RMACSD3,3):UBOUND(YD%RMACSD3,3)))
  READ (KLUN) ZTMP3
  YD%RMACSD3 = ZTMP3
  DEALLOCATE (ZTMP3)
ENDIF
READ (KLUN) LRMAESD1
IF (LRMAESD1) THEN
  READ (KLUN) IL2
  READ (KLUN) IU2
  ALLOCATE (YD%RMAESD1 (IL2(1):IU2(1), IL2(2):IU2(2)))
  ALLOCATE (ZTMP2(LBOUND(YD%RMAESD1,1):UBOUND(YD%RMAESD1,1), LBOUND(YD%RMAESD1,2):UBOUND(YD%RMAESD1,2)))
  READ (KLUN) ZTMP2
  YD%RMAESD1 = ZTMP2
  DEALLOCATE (ZTMP2)
ENDIF
READ (KLUN) LRMAESD2
IF (LRMAESD2) THEN
  READ (KLUN) IL2
  READ (KLUN) IU2
  ALLOCATE (YD%RMAESD2 (IL2(1):IU2(1), IL2(2):IU2(2)))
  ALLOCATE (ZTMP2(LBOUND(YD%RMAESD2,1):UBOUND(YD%RMAESD2,1), LBOUND(YD%RMAESD2,2):UBOUND(YD%RMAESD2,2)))
  READ (KLUN) ZTMP2
  YD%RMAESD2 = ZTMP2
  DEALLOCATE (ZTMP2)
ENDIF
READ (KLUN) LRMAESD3
IF (LRMAESD3) THEN
  READ (KLUN) IL2
  READ (KLUN) IU2
  ALLOCATE (YD%RMAESD3 (IL2(1):IU2(1), IL2(2):IU2(2)))
  ALLOCATE (ZTMP2(LBOUND(YD%RMAESD3,1):UBOUND(YD%RMAESD3,1), LBOUND(YD%RMAESD3,2):UBOUND(YD%RMAESD3,2)))
  READ (KLUN) ZTMP2
  YD%RMAESD3 = ZTMP2
  DEALLOCATE (ZTMP2)
ENDIF
READ (KLUN) LRMACSS1
IF (LRMACSS1) THEN
  READ (KLUN) IL3
  READ (KLUN) IU3
  ALLOCATE (YD%RMACSS1 (IL3(1):IU3(1), IL3(2):IU3(2), IL3(3):IU3(3)))
  ALLOCATE (ZTMP3(LBOUND(YD%RMACSS1,1):UBOUND(YD%RMACSS1,1), LBOUND(YD%RMACSS1,2):UBOUND(YD%RMACSS1,2), LBOUND(YD%RMACSS1,3):UBOUND(YD%RMACSS1,3)))
  READ (KLUN) ZTMP3
  YD%RMACSS1 = ZTMP3
  DEALLOCATE (ZTMP3)
ENDIF
READ (KLUN) LRMACSS2
IF (LRMACSS2) THEN
  READ (KLUN) IL3
  READ (KLUN) IU3
  ALLOCATE (YD%RMACSS2 (IL3(1):IU3(1), IL3(2):IU3(2), IL3(3):IU3(3)))
  ALLOCATE (ZTMP3(LBOUND(YD%RMACSS2,1):UBOUND(YD%RMACSS2,1), LBOUND(YD%RMACSS2,2):UBOUND(YD%RMACSS2,2), LBOUND(YD%RMACSS2,3):UBOUND(YD%RMACSS2,3)))
  READ (KLUN) ZTMP3
  YD%RMACSS2 = ZTMP3
  DEALLOCATE (ZTMP3)
ENDIF
READ (KLUN) LRMACSS3
IF (LRMACSS3) THEN
  READ (KLUN) IL3
  READ (KLUN) IU3
  ALLOCATE (YD%RMACSS3 (IL3(1):IU3(1), IL3(2):IU3(2), IL3(3):IU3(3)))
  ALLOCATE (ZTMP3(LBOUND(YD%RMACSS3,1):UBOUND(YD%RMACSS3,1), LBOUND(YD%RMACSS3,2):UBOUND(YD%RMACSS3,2), LBOUND(YD%RMACSS3,3):UBOUND(YD%RMACSS3,3)))
  READ (KLUN) ZTMP3
  YD%RMACSS3 = ZTMP3
  DEALLOCATE (ZTMP3)
ENDIF
READ (KLUN) LRMAESS1
IF (LRMAESS1) THEN
  READ (KLUN) IL2
  READ (KLUN) IU2
  ALLOCATE (YD%RMAESS1 (IL2(1):IU2(1), IL2(2):IU2(2)))
  ALLOCATE (ZTMP2(LBOUND(YD%RMAESS1,1):UBOUND(YD%RMAESS1,1), LBOUND(YD%RMAESS1,2):UBOUND(YD%RMAESS1,2)))
  READ (KLUN) ZTMP2
  YD%RMAESS1 = ZTMP2
  DEALLOCATE (ZTMP2)
ENDIF
READ (KLUN) LRMAESS2
IF (LRMAESS2) THEN
  READ (KLUN) IL2
  READ (KLUN) IU2
  ALLOCATE (YD%RMAESS2 (IL2(1):IU2(1), IL2(2):IU2(2)))
  ALLOCATE (ZTMP2(LBOUND(YD%RMAESS2,1):UBOUND(YD%RMAESS2,1), LBOUND(YD%RMAESS2,2):UBOUND(YD%RMAESS2,2)))
  READ (KLUN) ZTMP2
  YD%RMAESS2 = ZTMP2
  DEALLOCATE (ZTMP2)
ENDIF
READ (KLUN) LRMAESS3
IF (LRMAESS3) THEN
  READ (KLUN) IL2
  READ (KLUN) IU2
  ALLOCATE (YD%RMAESS3 (IL2(1):IU2(1), IL2(2):IU2(2)))
  ALLOCATE (ZTMP2(LBOUND(YD%RMAESS3,1):UBOUND(YD%RMAESS3,1), LBOUND(YD%RMAESS3,2):UBOUND(YD%RMAESS3,2)))
  READ (KLUN) ZTMP2
  YD%RMAESS3 = ZTMP2
  DEALLOCATE (ZTMP2)
ENDIF
READ (KLUN) LRMACSU1
IF (LRMACSU1) THEN
  READ (KLUN) IL3
  READ (KLUN) IU3
  ALLOCATE (YD%RMACSU1 (IL3(1):IU3(1), IL3(2):IU3(2), IL3(3):IU3(3)))
  ALLOCATE (ZTMP3(LBOUND(YD%RMACSU1,1):UBOUND(YD%RMACSU1,1), LBOUND(YD%RMACSU1,2):UBOUND(YD%RMACSU1,2), LBOUND(YD%RMACSU1,3):UBOUND(YD%RMACSU1,3)))
  READ (KLUN) ZTMP3
  YD%RMACSU1 = ZTMP3
  DEALLOCATE (ZTMP3)
ENDIF
READ (KLUN) LRMAESU1
IF (LRMAESU1) THEN
  READ (KLUN) IL2
  READ (KLUN) IU2
  ALLOCATE (YD%RMAESU1 (IL2(1):IU2(1), IL2(2):IU2(2)))
  ALLOCATE (ZTMP2(LBOUND(YD%RMAESU1,1):UBOUND(YD%RMAESU1,1), LBOUND(YD%RMAESU1,2):UBOUND(YD%RMAESU1,2)))
  READ (KLUN) ZTMP2
  YD%RMAESU1 = ZTMP2
  DEALLOCATE (ZTMP2)
ENDIF
READ (KLUN) LRMACBC13D
IF (LRMACBC13D) THEN
  READ (KLUN) IL4
  READ (KLUN) IU4
  ALLOCATE (YD%RMACBC13D (IL4(1):IU4(1), IL4(2):IU4(2), IL4(3):IU4(3), IL4(4):IU4(4)))
  ALLOCATE (ZTMP4(LBOUND(YD%RMACBC13D,1):UBOUND(YD%RMACBC13D,1), LBOUND(YD%RMACBC13D,2):UBOUND(YD%RMACBC13D,2), LBOUND(YD%RMACBC13D,3):UBOUND(YD%RMACBC13D,3), LBOUND(YD%RMACBC13D,4):UBOUND(YD%RMACBC13D,4)))
  READ (KLUN) ZTMP4
  YD%RMACBC13D = ZTMP4
  DEALLOCATE (ZTMP4)
ELSE
  NULLIFY (YD%RMACBC13D)
ENDIF
READ (KLUN) LRMACBC23D
IF (LRMACBC23D) THEN
  READ (KLUN) IL4
  READ (KLUN) IU4
  ALLOCATE (YD%RMACBC23D (IL4(1):IU4(1), IL4(2):IU4(2), IL4(3):IU4(3), IL4(4):IU4(4)))
  ALLOCATE (ZTMP4(LBOUND(YD%RMACBC23D,1):UBOUND(YD%RMACBC23D,1), LBOUND(YD%RMACBC23D,2):UBOUND(YD%RMACBC23D,2), LBOUND(YD%RMACBC23D,3):UBOUND(YD%RMACBC23D,3), LBOUND(YD%RMACBC23D,4):UBOUND(YD%RMACBC23D,4)))
  READ (KLUN) ZTMP4
  YD%RMACBC23D = ZTMP4
  DEALLOCATE (ZTMP4)
ELSE
  NULLIFY (YD%RMACBC23D)
ENDIF
READ (KLUN) LRMACOR13D
IF (LRMACOR13D) THEN
  READ (KLUN) IL4
  READ (KLUN) IU4
  ALLOCATE (YD%RMACOR13D (IL4(1):IU4(1), IL4(2):IU4(2), IL4(3):IU4(3), IL4(4):IU4(4)))
  ALLOCATE (ZTMP4(LBOUND(YD%RMACOR13D,1):UBOUND(YD%RMACOR13D,1), LBOUND(YD%RMACOR13D,2):UBOUND(YD%RMACOR13D,2), LBOUND(YD%RMACOR13D,3):UBOUND(YD%RMACOR13D,3), LBOUND(YD%RMACOR13D,4):UBOUND(YD%RMACOR13D,4)))
  READ (KLUN) ZTMP4
  YD%RMACOR13D = ZTMP4
  DEALLOCATE (ZTMP4)
ELSE
  NULLIFY (YD%RMACOR13D)
ENDIF
READ (KLUN) LRMACOR23D
IF (LRMACOR23D) THEN
  READ (KLUN) IL4
  READ (KLUN) IU4
  ALLOCATE (YD%RMACOR23D (IL4(1):IU4(1), IL4(2):IU4(2), IL4(3):IU4(3), IL4(4):IU4(4)))
  ALLOCATE (ZTMP4(LBOUND(YD%RMACOR23D,1):UBOUND(YD%RMACOR23D,1), LBOUND(YD%RMACOR23D,2):UBOUND(YD%RMACOR23D,2), LBOUND(YD%RMACOR23D,3):UBOUND(YD%RMACOR23D,3), LBOUND(YD%RMACOR23D,4):UBOUND(YD%RMACOR23D,4)))
  READ (KLUN) ZTMP4
  YD%RMACOR23D = ZTMP4
  DEALLOCATE (ZTMP4)
ELSE
  NULLIFY (YD%RMACOR23D)
ENDIF
READ (KLUN) LRMACSD13D
IF (LRMACSD13D) THEN
  READ (KLUN) IL4
  READ (KLUN) IU4
  ALLOCATE (YD%RMACSD13D (IL4(1):IU4(1), IL4(2):IU4(2), IL4(3):IU4(3), IL4(4):IU4(4)))
  ALLOCATE (ZTMP4(LBOUND(YD%RMACSD13D,1):UBOUND(YD%RMACSD13D,1), LBOUND(YD%RMACSD13D,2):UBOUND(YD%RMACSD13D,2), LBOUND(YD%RMACSD13D,3):UBOUND(YD%RMACSD13D,3), LBOUND(YD%RMACSD13D,4):UBOUND(YD%RMACSD13D,4)))
  READ (KLUN) ZTMP4
  YD%RMACSD13D = ZTMP4
  DEALLOCATE (ZTMP4)
ELSE
  NULLIFY (YD%RMACSD13D)
ENDIF
READ (KLUN) LRMACSD23D
IF (LRMACSD23D) THEN
  READ (KLUN) IL4
  READ (KLUN) IU4
  ALLOCATE (YD%RMACSD23D (IL4(1):IU4(1), IL4(2):IU4(2), IL4(3):IU4(3), IL4(4):IU4(4)))
  ALLOCATE (ZTMP4(LBOUND(YD%RMACSD23D,1):UBOUND(YD%RMACSD23D,1), LBOUND(YD%RMACSD23D,2):UBOUND(YD%RMACSD23D,2), LBOUND(YD%RMACSD23D,3):UBOUND(YD%RMACSD23D,3), LBOUND(YD%RMACSD23D,4):UBOUND(YD%RMACSD23D,4)))
  READ (KLUN) ZTMP4
  YD%RMACSD23D = ZTMP4
  DEALLOCATE (ZTMP4)
ELSE
  NULLIFY (YD%RMACSD23D)
ENDIF
READ (KLUN) LRMACSD33D
IF (LRMACSD33D) THEN
  READ (KLUN) IL4
  READ (KLUN) IU4
  ALLOCATE (YD%RMACSD33D (IL4(1):IU4(1), IL4(2):IU4(2), IL4(3):IU4(3), IL4(4):IU4(4)))
  ALLOCATE (ZTMP4(LBOUND(YD%RMACSD33D,1):UBOUND(YD%RMACSD33D,1), LBOUND(YD%RMACSD33D,2):UBOUND(YD%RMACSD33D,2), LBOUND(YD%RMACSD33D,3):UBOUND(YD%RMACSD33D,3), LBOUND(YD%RMACSD33D,4):UBOUND(YD%RMACSD33D,4)))
  READ (KLUN) ZTMP4
  YD%RMACSD33D = ZTMP4
  DEALLOCATE (ZTMP4)
ELSE
  NULLIFY (YD%RMACSD33D)
ENDIF
READ (KLUN) LRMACSS13D
IF (LRMACSS13D) THEN
  READ (KLUN) IL4
  READ (KLUN) IU4
  ALLOCATE (YD%RMACSS13D (IL4(1):IU4(1), IL4(2):IU4(2), IL4(3):IU4(3), IL4(4):IU4(4)))
  ALLOCATE (ZTMP4(LBOUND(YD%RMACSS13D,1):UBOUND(YD%RMACSS13D,1), LBOUND(YD%RMACSS13D,2):UBOUND(YD%RMACSS13D,2), LBOUND(YD%RMACSS13D,3):UBOUND(YD%RMACSS13D,3), LBOUND(YD%RMACSS13D,4):UBOUND(YD%RMACSS13D,4)))
  READ (KLUN) ZTMP4
  YD%RMACSS13D = ZTMP4
  DEALLOCATE (ZTMP4)
ELSE
  NULLIFY (YD%RMACSS13D)
ENDIF
READ (KLUN) LRMACSS23D
IF (LRMACSS23D) THEN
  READ (KLUN) IL4
  READ (KLUN) IU4
  ALLOCATE (YD%RMACSS23D (IL4(1):IU4(1), IL4(2):IU4(2), IL4(3):IU4(3), IL4(4):IU4(4)))
  ALLOCATE (ZTMP4(LBOUND(YD%RMACSS23D,1):UBOUND(YD%RMACSS23D,1), LBOUND(YD%RMACSS23D,2):UBOUND(YD%RMACSS23D,2), LBOUND(YD%RMACSS23D,3):UBOUND(YD%RMACSS23D,3), LBOUND(YD%RMACSS23D,4):UBOUND(YD%RMACSS23D,4)))
  READ (KLUN) ZTMP4
  YD%RMACSS23D = ZTMP4
  DEALLOCATE (ZTMP4)
ELSE
  NULLIFY (YD%RMACSS23D)
ENDIF
READ (KLUN) LRMACSS33D
IF (LRMACSS33D) THEN
  READ (KLUN) IL4
  READ (KLUN) IU4
  ALLOCATE (YD%RMACSS33D (IL4(1):IU4(1), IL4(2):IU4(2), IL4(3):IU4(3), IL4(4):IU4(4)))
  ALLOCATE (ZTMP4(LBOUND(YD%RMACSS33D,1):UBOUND(YD%RMACSS33D,1), LBOUND(YD%RMACSS33D,2):UBOUND(YD%RMACSS33D,2), LBOUND(YD%RMACSS33D,3):UBOUND(YD%RMACSS33D,3), LBOUND(YD%RMACSS33D,4):UBOUND(YD%RMACSS33D,4)))
  READ (KLUN) ZTMP4
  YD%RMACSS33D = ZTMP4
  DEALLOCATE (ZTMP4)
ELSE
  NULLIFY (YD%RMACSS33D)
ENDIF
READ (KLUN) LRMACSU13D
IF (LRMACSU13D) THEN
  READ (KLUN) IL4
  READ (KLUN) IU4
  ALLOCATE (YD%RMACSU13D (IL4(1):IU4(1), IL4(2):IU4(2), IL4(3):IU4(3), IL4(4):IU4(4)))
  ALLOCATE (ZTMP4(LBOUND(YD%RMACSU13D,1):UBOUND(YD%RMACSU13D,1), LBOUND(YD%RMACSU13D,2):UBOUND(YD%RMACSU13D,2), LBOUND(YD%RMACSU13D,3):UBOUND(YD%RMACSU13D,3), LBOUND(YD%RMACSU13D,4):UBOUND(YD%RMACSU13D,4)))
  READ (KLUN) ZTMP4
  YD%RMACSU13D = ZTMP4
  DEALLOCATE (ZTMP4)
ELSE
  NULLIFY (YD%RMACSU13D)
ENDIF
READ (KLUN) LREF_MON_AER_PRS
IF (LREF_MON_AER_PRS) THEN
  READ (KLUN) IL4
  READ (KLUN) IU4
  ALLOCATE (YD%REF_MON_AER_PRS (IL4(1):IU4(1), IL4(2):IU4(2), IL4(3):IU4(3), IL4(4):IU4(4)))
  ALLOCATE (ZTMP4(LBOUND(YD%REF_MON_AER_PRS,1):UBOUND(YD%REF_MON_AER_PRS,1), LBOUND(YD%REF_MON_AER_PRS,2):UBOUND(YD%REF_MON_AER_PRS,2), LBOUND(YD%REF_MON_AER_PRS,3):UBOUND(YD%REF_MON_AER_PRS,3), LBOUND(YD%REF_MON_AER_PRS,4):UBOUND(YD%REF_MON_AER_PRS,4)))
  READ (KLUN) ZTMP4
  YD%REF_MON_AER_PRS = ZTMP4
  DEALLOCATE (ZTMP4)
ELSE
  NULLIFY (YD%REF_MON_AER_PRS)
ENDIF
READ (KLUN) LREF_MON_AER_DPRS
IF (LREF_MON_AER_DPRS) THEN
  READ (KLUN) IL4
  READ (KLUN) IU4
  ALLOCATE (YD%REF_MON_AER_DPRS (IL4(1):IU4(1), IL4(2):IU4(2), IL4(3):IU4(3), IL4(4):IU4(4)))
  ALLOCATE (ZTMP4(LBOUND(YD%REF_MON_AER_DPRS,1):UBOUND(YD%REF_MON_AER_DPRS,1), LBOUND(YD%REF_MON_AER_DPRS,2):UBOUND(YD%REF_MON_AER_DPRS,2), LBOUND(YD%REF_MON_AER_DPRS,3):UBOUND(YD%REF_MON_AER_DPRS,3), LBOUND(YD%REF_MON_AER_DPRS,4):UBOUND(YD%REF_MON_AER_DPRS,4)))
  READ (KLUN) ZTMP4
  YD%REF_MON_AER_DPRS = ZTMP4
  DEALLOCATE (ZTMP4)
ELSE
  NULLIFY (YD%REF_MON_AER_DPRS)
ENDIF
READ (KLUN) LRMAEBC13D
IF (LRMAEBC13D) THEN
  READ (KLUN) IL3
  READ (KLUN) IU3
  ALLOCATE (YD%RMAEBC13D (IL3(1):IU3(1), IL3(2):IU3(2), IL3(3):IU3(3)))
  ALLOCATE (ZTMP3(LBOUND(YD%RMAEBC13D,1):UBOUND(YD%RMAEBC13D,1), LBOUND(YD%RMAEBC13D,2):UBOUND(YD%RMAEBC13D,2), LBOUND(YD%RMAEBC13D,3):UBOUND(YD%RMAEBC13D,3)))
  READ (KLUN) ZTMP3
  YD%RMAEBC13D = ZTMP3
  DEALLOCATE (ZTMP3)
ENDIF
READ (KLUN) LRMAEBC23D
IF (LRMAEBC23D) THEN
  READ (KLUN) IL3
  READ (KLUN) IU3
  ALLOCATE (YD%RMAEBC23D (IL3(1):IU3(1), IL3(2):IU3(2), IL3(3):IU3(3)))
  ALLOCATE (ZTMP3(LBOUND(YD%RMAEBC23D,1):UBOUND(YD%RMAEBC23D,1), LBOUND(YD%RMAEBC23D,2):UBOUND(YD%RMAEBC23D,2), LBOUND(YD%RMAEBC23D,3):UBOUND(YD%RMAEBC23D,3)))
  READ (KLUN) ZTMP3
  YD%RMAEBC23D = ZTMP3
  DEALLOCATE (ZTMP3)
ENDIF
READ (KLUN) LRMAEOR13D
IF (LRMAEOR13D) THEN
  READ (KLUN) IL3
  READ (KLUN) IU3
  ALLOCATE (YD%RMAEOR13D (IL3(1):IU3(1), IL3(2):IU3(2), IL3(3):IU3(3)))
  ALLOCATE (ZTMP3(LBOUND(YD%RMAEOR13D,1):UBOUND(YD%RMAEOR13D,1), LBOUND(YD%RMAEOR13D,2):UBOUND(YD%RMAEOR13D,2), LBOUND(YD%RMAEOR13D,3):UBOUND(YD%RMAEOR13D,3)))
  READ (KLUN) ZTMP3
  YD%RMAEOR13D = ZTMP3
  DEALLOCATE (ZTMP3)
ENDIF
READ (KLUN) LRMAEOR23D
IF (LRMAEOR23D) THEN
  READ (KLUN) IL3
  READ (KLUN) IU3
  ALLOCATE (YD%RMAEOR23D (IL3(1):IU3(1), IL3(2):IU3(2), IL3(3):IU3(3)))
  ALLOCATE (ZTMP3(LBOUND(YD%RMAEOR23D,1):UBOUND(YD%RMAEOR23D,1), LBOUND(YD%RMAEOR23D,2):UBOUND(YD%RMAEOR23D,2), LBOUND(YD%RMAEOR23D,3):UBOUND(YD%RMAEOR23D,3)))
  READ (KLUN) ZTMP3
  YD%RMAEOR23D = ZTMP3
  DEALLOCATE (ZTMP3)
ENDIF
READ (KLUN) LRMAESD13D
IF (LRMAESD13D) THEN
  READ (KLUN) IL3
  READ (KLUN) IU3
  ALLOCATE (YD%RMAESD13D (IL3(1):IU3(1), IL3(2):IU3(2), IL3(3):IU3(3)))
  ALLOCATE (ZTMP3(LBOUND(YD%RMAESD13D,1):UBOUND(YD%RMAESD13D,1), LBOUND(YD%RMAESD13D,2):UBOUND(YD%RMAESD13D,2), LBOUND(YD%RMAESD13D,3):UBOUND(YD%RMAESD13D,3)))
  READ (KLUN) ZTMP3
  YD%RMAESD13D = ZTMP3
  DEALLOCATE (ZTMP3)
ENDIF
READ (KLUN) LRMAESD23D
IF (LRMAESD23D) THEN
  READ (KLUN) IL3
  READ (KLUN) IU3
  ALLOCATE (YD%RMAESD23D (IL3(1):IU3(1), IL3(2):IU3(2), IL3(3):IU3(3)))
  ALLOCATE (ZTMP3(LBOUND(YD%RMAESD23D,1):UBOUND(YD%RMAESD23D,1), LBOUND(YD%RMAESD23D,2):UBOUND(YD%RMAESD23D,2), LBOUND(YD%RMAESD23D,3):UBOUND(YD%RMAESD23D,3)))
  READ (KLUN) ZTMP3
  YD%RMAESD23D = ZTMP3
  DEALLOCATE (ZTMP3)
ENDIF
READ (KLUN) LRMAESD33D
IF (LRMAESD33D) THEN
  READ (KLUN) IL3
  READ (KLUN) IU3
  ALLOCATE (YD%RMAESD33D (IL3(1):IU3(1), IL3(2):IU3(2), IL3(3):IU3(3)))
  ALLOCATE (ZTMP3(LBOUND(YD%RMAESD33D,1):UBOUND(YD%RMAESD33D,1), LBOUND(YD%RMAESD33D,2):UBOUND(YD%RMAESD33D,2), LBOUND(YD%RMAESD33D,3):UBOUND(YD%RMAESD33D,3)))
  READ (KLUN) ZTMP3
  YD%RMAESD33D = ZTMP3
  DEALLOCATE (ZTMP3)
ENDIF
READ (KLUN) LRMAESS13D
IF (LRMAESS13D) THEN
  READ (KLUN) IL3
  READ (KLUN) IU3
  ALLOCATE (YD%RMAESS13D (IL3(1):IU3(1), IL3(2):IU3(2), IL3(3):IU3(3)))
  ALLOCATE (ZTMP3(LBOUND(YD%RMAESS13D,1):UBOUND(YD%RMAESS13D,1), LBOUND(YD%RMAESS13D,2):UBOUND(YD%RMAESS13D,2), LBOUND(YD%RMAESS13D,3):UBOUND(YD%RMAESS13D,3)))
  READ (KLUN) ZTMP3
  YD%RMAESS13D = ZTMP3
  DEALLOCATE (ZTMP3)
ENDIF
READ (KLUN) LRMAESS23D
IF (LRMAESS23D) THEN
  READ (KLUN) IL3
  READ (KLUN) IU3
  ALLOCATE (YD%RMAESS23D (IL3(1):IU3(1), IL3(2):IU3(2), IL3(3):IU3(3)))
  ALLOCATE (ZTMP3(LBOUND(YD%RMAESS23D,1):UBOUND(YD%RMAESS23D,1), LBOUND(YD%RMAESS23D,2):UBOUND(YD%RMAESS23D,2), LBOUND(YD%RMAESS23D,3):UBOUND(YD%RMAESS23D,3)))
  READ (KLUN) ZTMP3
  YD%RMAESS23D = ZTMP3
  DEALLOCATE (ZTMP3)
ENDIF
READ (KLUN) LRMAESS33D
IF (LRMAESS33D) THEN
  READ (KLUN) IL3
  READ (KLUN) IU3
  ALLOCATE (YD%RMAESS33D (IL3(1):IU3(1), IL3(2):IU3(2), IL3(3):IU3(3)))
  ALLOCATE (ZTMP3(LBOUND(YD%RMAESS33D,1):UBOUND(YD%RMAESS33D,1), LBOUND(YD%RMAESS33D,2):UBOUND(YD%RMAESS33D,2), LBOUND(YD%RMAESS33D,3):UBOUND(YD%RMAESS33D,3)))
  READ (KLUN) ZTMP3
  YD%RMAESS33D = ZTMP3
  DEALLOCATE (ZTMP3)
ENDIF
READ (KLUN) LRMAESU13D
IF (LRMAESU13D) THEN
  READ (KLUN) IL3
  READ (KLUN) IU3
  ALLOCATE (YD%RMAESU13D (IL3(1):IU3(1), IL3(2):IU3(2), IL3(3):IU3(3)))
  ALLOCATE (ZTMP3(LBOUND(YD%RMAESU13D,1):UBOUND(YD%RMAESU13D,1), LBOUND(YD%RMAESU13D,2):UBOUND(YD%RMAESU13D,2), LBOUND(YD%RMAESU13D,3):UBOUND(YD%RMAESU13D,3)))
  READ (KLUN) ZTMP3
  YD%RMAESU13D = ZTMP3
  DEALLOCATE (ZTMP3)
ENDIF
READ (KLUN) LREF_AER_PRS
IF (LREF_AER_PRS) THEN
  READ (KLUN) IL3
  READ (KLUN) IU3
  ALLOCATE (YD%REF_AER_PRS (IL3(1):IU3(1), IL3(2):IU3(2), IL3(3):IU3(3)))
  ALLOCATE (ZTMP3(LBOUND(YD%REF_AER_PRS,1):UBOUND(YD%REF_AER_PRS,1), LBOUND(YD%REF_AER_PRS,2):UBOUND(YD%REF_AER_PRS,2), LBOUND(YD%REF_AER_PRS,3):UBOUND(YD%REF_AER_PRS,3)))
  READ (KLUN) ZTMP3
  YD%REF_AER_PRS = ZTMP3
  DEALLOCATE (ZTMP3)
ENDIF
READ (KLUN) LREF_AER_DPRS
IF (LREF_AER_DPRS) THEN
  READ (KLUN) IL3
  READ (KLUN) IU3
  ALLOCATE (YD%REF_AER_DPRS (IL3(1):IU3(1), IL3(2):IU3(2), IL3(3):IU3(3)))
  ALLOCATE (ZTMP3(LBOUND(YD%REF_AER_DPRS,1):UBOUND(YD%REF_AER_DPRS,1), LBOUND(YD%REF_AER_DPRS,2):UBOUND(YD%REF_AER_DPRS,2), LBOUND(YD%REF_AER_DPRS,3):UBOUND(YD%REF_AER_DPRS,3)))
  READ (KLUN) ZTMP3
  YD%REF_AER_DPRS = ZTMP3
  DEALLOCATE (ZTMP3)
ENDIF
READ (KLUN) YD%IS_INITIALISED
END SUBROUTINE


SUBROUTINE COPY_TEAERC_MACC (YD, LDCREATED)

IMPLICIT NONE
TYPE (TEAERC_MACC), INTENT (IN), TARGET :: YD
LOGICAL, OPTIONAL, INTENT (IN) :: LDCREATED
LOGICAL :: LLCREATED
LOGICAL :: LREF_AER_DPRS, LREF_AER_PRS, LREF_MON_AER_DPRS, LREF_MON_AER_PRS, LRMACBC, LRMACBC1, LRMACBC13D, LRMACBC2, LRMACBC23D, LRMACOR
LOGICAL :: LRMACOR1, LRMACOR13D, LRMACOR2, LRMACOR23D, LRMACSD, LRMACSD1, LRMACSD13D, LRMACSD2, LRMACSD23D, LRMACSD3
LOGICAL :: LRMACSD33D, LRMACSS, LRMACSS1, LRMACSS13D, LRMACSS2, LRMACSS23D, LRMACSS3, LRMACSS33D, LRMACSU, LRMACSU1
LOGICAL :: LRMACSU13D, LRMAEBC, LRMAEBC1, LRMAEBC13D, LRMAEBC2, LRMAEBC23D, LRMAEOR, LRMAEOR1, LRMAEOR13D, LRMAEOR2
LOGICAL :: LRMAEOR23D, LRMAESD, LRMAESD1, LRMAESD13D, LRMAESD2, LRMAESD23D, LRMAESD3, LRMAESD33D, LRMAESS, LRMAESS1
LOGICAL :: LRMAESS13D, LRMAESS2, LRMAESS23D, LRMAESS3, LRMAESS33D, LRMAESU, LRMAESU1, LRMAESU13D

LLCREATED = .FALSE.
IF (PRESENT (LDCREATED)) THEN
  LLCREATED = LDCREATED
ENDIF
IF (.NOT. LLCREATED) THEN
  !$acc enter data create (YD)
  !$acc update device (YD)
ENDIF
LRMACBC = ALLOCATED (YD%RMACBC)
IF (LRMACBC) THEN
  !$acc enter data create (YD%RMACBC)
  !$acc update device (YD%RMACBC)
  !$acc enter data attach (YD%RMACBC)
ENDIF

LRMACOR = ALLOCATED (YD%RMACOR)
IF (LRMACOR) THEN
  !$acc enter data create (YD%RMACOR)
  !$acc update device (YD%RMACOR)
  !$acc enter data attach (YD%RMACOR)
ENDIF

LRMACSD = ALLOCATED (YD%RMACSD)
IF (LRMACSD) THEN
  !$acc enter data create (YD%RMACSD)
  !$acc update device (YD%RMACSD)
  !$acc enter data attach (YD%RMACSD)
ENDIF

LRMACSS = ALLOCATED (YD%RMACSS)
IF (LRMACSS) THEN
  !$acc enter data create (YD%RMACSS)
  !$acc update device (YD%RMACSS)
  !$acc enter data attach (YD%RMACSS)
ENDIF

LRMACSU = ALLOCATED (YD%RMACSU)
IF (LRMACSU) THEN
  !$acc enter data create (YD%RMACSU)
  !$acc update device (YD%RMACSU)
  !$acc enter data attach (YD%RMACSU)
ENDIF

LRMAEBC = ALLOCATED (YD%RMAEBC)
IF (LRMAEBC) THEN
  !$acc enter data create (YD%RMAEBC)
  !$acc update device (YD%RMAEBC)
  !$acc enter data attach (YD%RMAEBC)
ENDIF

LRMAEOR = ALLOCATED (YD%RMAEOR)
IF (LRMAEOR) THEN
  !$acc enter data create (YD%RMAEOR)
  !$acc update device (YD%RMAEOR)
  !$acc enter data attach (YD%RMAEOR)
ENDIF

LRMAESD = ALLOCATED (YD%RMAESD)
IF (LRMAESD) THEN
  !$acc enter data create (YD%RMAESD)
  !$acc update device (YD%RMAESD)
  !$acc enter data attach (YD%RMAESD)
ENDIF

LRMAESS = ALLOCATED (YD%RMAESS)
IF (LRMAESS) THEN
  !$acc enter data create (YD%RMAESS)
  !$acc update device (YD%RMAESS)
  !$acc enter data attach (YD%RMAESS)
ENDIF

LRMAESU = ALLOCATED (YD%RMAESU)
IF (LRMAESU) THEN
  !$acc enter data create (YD%RMAESU)
  !$acc update device (YD%RMAESU)
  !$acc enter data attach (YD%RMAESU)
ENDIF

LRMACBC1 = ALLOCATED (YD%RMACBC1)
IF (LRMACBC1) THEN
  !$acc enter data create (YD%RMACBC1)
  !$acc update device (YD%RMACBC1)
  !$acc enter data attach (YD%RMACBC1)
ENDIF

LRMACBC2 = ALLOCATED (YD%RMACBC2)
IF (LRMACBC2) THEN
  !$acc enter data create (YD%RMACBC2)
  !$acc update device (YD%RMACBC2)
  !$acc enter data attach (YD%RMACBC2)
ENDIF

LRMAEBC1 = ALLOCATED (YD%RMAEBC1)
IF (LRMAEBC1) THEN
  !$acc enter data create (YD%RMAEBC1)
  !$acc update device (YD%RMAEBC1)
  !$acc enter data attach (YD%RMAEBC1)
ENDIF

LRMAEBC2 = ALLOCATED (YD%RMAEBC2)
IF (LRMAEBC2) THEN
  !$acc enter data create (YD%RMAEBC2)
  !$acc update device (YD%RMAEBC2)
  !$acc enter data attach (YD%RMAEBC2)
ENDIF

LRMACOR1 = ALLOCATED (YD%RMACOR1)
IF (LRMACOR1) THEN
  !$acc enter data create (YD%RMACOR1)
  !$acc update device (YD%RMACOR1)
  !$acc enter data attach (YD%RMACOR1)
ENDIF

LRMACOR2 = ALLOCATED (YD%RMACOR2)
IF (LRMACOR2) THEN
  !$acc enter data create (YD%RMACOR2)
  !$acc update device (YD%RMACOR2)
  !$acc enter data attach (YD%RMACOR2)
ENDIF

LRMAEOR1 = ALLOCATED (YD%RMAEOR1)
IF (LRMAEOR1) THEN
  !$acc enter data create (YD%RMAEOR1)
  !$acc update device (YD%RMAEOR1)
  !$acc enter data attach (YD%RMAEOR1)
ENDIF

LRMAEOR2 = ALLOCATED (YD%RMAEOR2)
IF (LRMAEOR2) THEN
  !$acc enter data create (YD%RMAEOR2)
  !$acc update device (YD%RMAEOR2)
  !$acc enter data attach (YD%RMAEOR2)
ENDIF

LRMACSD1 = ALLOCATED (YD%RMACSD1)
IF (LRMACSD1) THEN
  !$acc enter data create (YD%RMACSD1)
  !$acc update device (YD%RMACSD1)
  !$acc enter data attach (YD%RMACSD1)
ENDIF

LRMACSD2 = ALLOCATED (YD%RMACSD2)
IF (LRMACSD2) THEN
  !$acc enter data create (YD%RMACSD2)
  !$acc update device (YD%RMACSD2)
  !$acc enter data attach (YD%RMACSD2)
ENDIF

LRMACSD3 = ALLOCATED (YD%RMACSD3)
IF (LRMACSD3) THEN
  !$acc enter data create (YD%RMACSD3)
  !$acc update device (YD%RMACSD3)
  !$acc enter data attach (YD%RMACSD3)
ENDIF

LRMAESD1 = ALLOCATED (YD%RMAESD1)
IF (LRMAESD1) THEN
  !$acc enter data create (YD%RMAESD1)
  !$acc update device (YD%RMAESD1)
  !$acc enter data attach (YD%RMAESD1)
ENDIF

LRMAESD2 = ALLOCATED (YD%RMAESD2)
IF (LRMAESD2) THEN
  !$acc enter data create (YD%RMAESD2)
  !$acc update device (YD%RMAESD2)
  !$acc enter data attach (YD%RMAESD2)
ENDIF

LRMAESD3 = ALLOCATED (YD%RMAESD3)
IF (LRMAESD3) THEN
  !$acc enter data create (YD%RMAESD3)
  !$acc update device (YD%RMAESD3)
  !$acc enter data attach (YD%RMAESD3)
ENDIF

LRMACSS1 = ALLOCATED (YD%RMACSS1)
IF (LRMACSS1) THEN
  !$acc enter data create (YD%RMACSS1)
  !$acc update device (YD%RMACSS1)
  !$acc enter data attach (YD%RMACSS1)
ENDIF

LRMACSS2 = ALLOCATED (YD%RMACSS2)
IF (LRMACSS2) THEN
  !$acc enter data create (YD%RMACSS2)
  !$acc update device (YD%RMACSS2)
  !$acc enter data attach (YD%RMACSS2)
ENDIF

LRMACSS3 = ALLOCATED (YD%RMACSS3)
IF (LRMACSS3) THEN
  !$acc enter data create (YD%RMACSS3)
  !$acc update device (YD%RMACSS3)
  !$acc enter data attach (YD%RMACSS3)
ENDIF

LRMAESS1 = ALLOCATED (YD%RMAESS1)
IF (LRMAESS1) THEN
  !$acc enter data create (YD%RMAESS1)
  !$acc update device (YD%RMAESS1)
  !$acc enter data attach (YD%RMAESS1)
ENDIF

LRMAESS2 = ALLOCATED (YD%RMAESS2)
IF (LRMAESS2) THEN
  !$acc enter data create (YD%RMAESS2)
  !$acc update device (YD%RMAESS2)
  !$acc enter data attach (YD%RMAESS2)
ENDIF

LRMAESS3 = ALLOCATED (YD%RMAESS3)
IF (LRMAESS3) THEN
  !$acc enter data create (YD%RMAESS3)
  !$acc update device (YD%RMAESS3)
  !$acc enter data attach (YD%RMAESS3)
ENDIF

LRMACSU1 = ALLOCATED (YD%RMACSU1)
IF (LRMACSU1) THEN
  !$acc enter data create (YD%RMACSU1)
  !$acc update device (YD%RMACSU1)
  !$acc enter data attach (YD%RMACSU1)
ENDIF

LRMAESU1 = ALLOCATED (YD%RMAESU1)
IF (LRMAESU1) THEN
  !$acc enter data create (YD%RMAESU1)
  !$acc update device (YD%RMAESU1)
  !$acc enter data attach (YD%RMAESU1)
ENDIF

LRMACBC13D = ASSOCIATED (YD%RMACBC13D)
IF (LRMACBC13D) THEN
  !$acc enter data create (YD%RMACBC13D)
  !$acc update device (YD%RMACBC13D)
  !$acc enter data attach (YD%RMACBC13D)
ENDIF

LRMACBC23D = ASSOCIATED (YD%RMACBC23D)
IF (LRMACBC23D) THEN
  !$acc enter data create (YD%RMACBC23D)
  !$acc update device (YD%RMACBC23D)
  !$acc enter data attach (YD%RMACBC23D)
ENDIF

LRMACOR13D = ASSOCIATED (YD%RMACOR13D)
IF (LRMACOR13D) THEN
  !$acc enter data create (YD%RMACOR13D)
  !$acc update device (YD%RMACOR13D)
  !$acc enter data attach (YD%RMACOR13D)
ENDIF

LRMACOR23D = ASSOCIATED (YD%RMACOR23D)
IF (LRMACOR23D) THEN
  !$acc enter data create (YD%RMACOR23D)
  !$acc update device (YD%RMACOR23D)
  !$acc enter data attach (YD%RMACOR23D)
ENDIF

LRMACSD13D = ASSOCIATED (YD%RMACSD13D)
IF (LRMACSD13D) THEN
  !$acc enter data create (YD%RMACSD13D)
  !$acc update device (YD%RMACSD13D)
  !$acc enter data attach (YD%RMACSD13D)
ENDIF

LRMACSD23D = ASSOCIATED (YD%RMACSD23D)
IF (LRMACSD23D) THEN
  !$acc enter data create (YD%RMACSD23D)
  !$acc update device (YD%RMACSD23D)
  !$acc enter data attach (YD%RMACSD23D)
ENDIF

LRMACSD33D = ASSOCIATED (YD%RMACSD33D)
IF (LRMACSD33D) THEN
  !$acc enter data create (YD%RMACSD33D)
  !$acc update device (YD%RMACSD33D)
  !$acc enter data attach (YD%RMACSD33D)
ENDIF

LRMACSS13D = ASSOCIATED (YD%RMACSS13D)
IF (LRMACSS13D) THEN
  !$acc enter data create (YD%RMACSS13D)
  !$acc update device (YD%RMACSS13D)
  !$acc enter data attach (YD%RMACSS13D)
ENDIF

LRMACSS23D = ASSOCIATED (YD%RMACSS23D)
IF (LRMACSS23D) THEN
  !$acc enter data create (YD%RMACSS23D)
  !$acc update device (YD%RMACSS23D)
  !$acc enter data attach (YD%RMACSS23D)
ENDIF

LRMACSS33D = ASSOCIATED (YD%RMACSS33D)
IF (LRMACSS33D) THEN
  !$acc enter data create (YD%RMACSS33D)
  !$acc update device (YD%RMACSS33D)
  !$acc enter data attach (YD%RMACSS33D)
ENDIF

LRMACSU13D = ASSOCIATED (YD%RMACSU13D)
IF (LRMACSU13D) THEN
  !$acc enter data create (YD%RMACSU13D)
  !$acc update device (YD%RMACSU13D)
  !$acc enter data attach (YD%RMACSU13D)
ENDIF

LREF_MON_AER_PRS = ASSOCIATED (YD%REF_MON_AER_PRS)
IF (LREF_MON_AER_PRS) THEN
  !$acc enter data create (YD%REF_MON_AER_PRS)
  !$acc update device (YD%REF_MON_AER_PRS)
  !$acc enter data attach (YD%REF_MON_AER_PRS)
ENDIF

LREF_MON_AER_DPRS = ASSOCIATED (YD%REF_MON_AER_DPRS)
IF (LREF_MON_AER_DPRS) THEN
  !$acc enter data create (YD%REF_MON_AER_DPRS)
  !$acc update device (YD%REF_MON_AER_DPRS)
  !$acc enter data attach (YD%REF_MON_AER_DPRS)
ENDIF

LRMAEBC13D = ALLOCATED (YD%RMAEBC13D)
IF (LRMAEBC13D) THEN
  !$acc enter data create (YD%RMAEBC13D)
  !$acc update device (YD%RMAEBC13D)
  !$acc enter data attach (YD%RMAEBC13D)
ENDIF

LRMAEBC23D = ALLOCATED (YD%RMAEBC23D)
IF (LRMAEBC23D) THEN
  !$acc enter data create (YD%RMAEBC23D)
  !$acc update device (YD%RMAEBC23D)
  !$acc enter data attach (YD%RMAEBC23D)
ENDIF

LRMAEOR13D = ALLOCATED (YD%RMAEOR13D)
IF (LRMAEOR13D) THEN
  !$acc enter data create (YD%RMAEOR13D)
  !$acc update device (YD%RMAEOR13D)
  !$acc enter data attach (YD%RMAEOR13D)
ENDIF

LRMAEOR23D = ALLOCATED (YD%RMAEOR23D)
IF (LRMAEOR23D) THEN
  !$acc enter data create (YD%RMAEOR23D)
  !$acc update device (YD%RMAEOR23D)
  !$acc enter data attach (YD%RMAEOR23D)
ENDIF

LRMAESD13D = ALLOCATED (YD%RMAESD13D)
IF (LRMAESD13D) THEN
  !$acc enter data create (YD%RMAESD13D)
  !$acc update device (YD%RMAESD13D)
  !$acc enter data attach (YD%RMAESD13D)
ENDIF

LRMAESD23D = ALLOCATED (YD%RMAESD23D)
IF (LRMAESD23D) THEN
  !$acc enter data create (YD%RMAESD23D)
  !$acc update device (YD%RMAESD23D)
  !$acc enter data attach (YD%RMAESD23D)
ENDIF

LRMAESD33D = ALLOCATED (YD%RMAESD33D)
IF (LRMAESD33D) THEN
  !$acc enter data create (YD%RMAESD33D)
  !$acc update device (YD%RMAESD33D)
  !$acc enter data attach (YD%RMAESD33D)
ENDIF

LRMAESS13D = ALLOCATED (YD%RMAESS13D)
IF (LRMAESS13D) THEN
  !$acc enter data create (YD%RMAESS13D)
  !$acc update device (YD%RMAESS13D)
  !$acc enter data attach (YD%RMAESS13D)
ENDIF

LRMAESS23D = ALLOCATED (YD%RMAESS23D)
IF (LRMAESS23D) THEN
  !$acc enter data create (YD%RMAESS23D)
  !$acc update device (YD%RMAESS23D)
  !$acc enter data attach (YD%RMAESS23D)
ENDIF

LRMAESS33D = ALLOCATED (YD%RMAESS33D)
IF (LRMAESS33D) THEN
  !$acc enter data create (YD%RMAESS33D)
  !$acc update device (YD%RMAESS33D)
  !$acc enter data attach (YD%RMAESS33D)
ENDIF

LRMAESU13D = ALLOCATED (YD%RMAESU13D)
IF (LRMAESU13D) THEN
  !$acc enter data create (YD%RMAESU13D)
  !$acc update device (YD%RMAESU13D)
  !$acc enter data attach (YD%RMAESU13D)
ENDIF

LREF_AER_PRS = ALLOCATED (YD%REF_AER_PRS)
IF (LREF_AER_PRS) THEN
  !$acc enter data create (YD%REF_AER_PRS)
  !$acc update device (YD%REF_AER_PRS)
  !$acc enter data attach (YD%REF_AER_PRS)
ENDIF

LREF_AER_DPRS = ALLOCATED (YD%REF_AER_DPRS)
IF (LREF_AER_DPRS) THEN
  !$acc enter data create (YD%REF_AER_DPRS)
  !$acc update device (YD%REF_AER_DPRS)
  !$acc enter data attach (YD%REF_AER_DPRS)
ENDIF


END SUBROUTINE

SUBROUTINE WIPE_TEAERC_MACC (YD, LDDELETED)

IMPLICIT NONE
TYPE (TEAERC_MACC), INTENT (IN), TARGET :: YD
LOGICAL, OPTIONAL, INTENT (IN) :: LDDELETED
LOGICAL :: LLDELETED
LOGICAL :: LREF_AER_DPRS, LREF_AER_PRS, LREF_MON_AER_DPRS, LREF_MON_AER_PRS, LRMACBC, LRMACBC1, LRMACBC13D, LRMACBC2, LRMACBC23D, LRMACOR
LOGICAL :: LRMACOR1, LRMACOR13D, LRMACOR2, LRMACOR23D, LRMACSD, LRMACSD1, LRMACSD13D, LRMACSD2, LRMACSD23D, LRMACSD3
LOGICAL :: LRMACSD33D, LRMACSS, LRMACSS1, LRMACSS13D, LRMACSS2, LRMACSS23D, LRMACSS3, LRMACSS33D, LRMACSU, LRMACSU1
LOGICAL :: LRMACSU13D, LRMAEBC, LRMAEBC1, LRMAEBC13D, LRMAEBC2, LRMAEBC23D, LRMAEOR, LRMAEOR1, LRMAEOR13D, LRMAEOR2
LOGICAL :: LRMAEOR23D, LRMAESD, LRMAESD1, LRMAESD13D, LRMAESD2, LRMAESD23D, LRMAESD3, LRMAESD33D, LRMAESS, LRMAESS1
LOGICAL :: LRMAESS13D, LRMAESS2, LRMAESS23D, LRMAESS3, LRMAESS33D, LRMAESU, LRMAESU1, LRMAESU13D

LRMACBC = ALLOCATED (YD%RMACBC)
IF (LRMACBC) THEN
  !$acc exit data detach (YD%RMACBC)
  !$acc exit data delete (YD%RMACBC)
ENDIF

LRMACOR = ALLOCATED (YD%RMACOR)
IF (LRMACOR) THEN
  !$acc exit data detach (YD%RMACOR)
  !$acc exit data delete (YD%RMACOR)
ENDIF

LRMACSD = ALLOCATED (YD%RMACSD)
IF (LRMACSD) THEN
  !$acc exit data detach (YD%RMACSD)
  !$acc exit data delete (YD%RMACSD)
ENDIF

LRMACSS = ALLOCATED (YD%RMACSS)
IF (LRMACSS) THEN
  !$acc exit data detach (YD%RMACSS)
  !$acc exit data delete (YD%RMACSS)
ENDIF

LRMACSU = ALLOCATED (YD%RMACSU)
IF (LRMACSU) THEN
  !$acc exit data detach (YD%RMACSU)
  !$acc exit data delete (YD%RMACSU)
ENDIF

LRMAEBC = ALLOCATED (YD%RMAEBC)
IF (LRMAEBC) THEN
  !$acc exit data detach (YD%RMAEBC)
  !$acc exit data delete (YD%RMAEBC)
ENDIF

LRMAEOR = ALLOCATED (YD%RMAEOR)
IF (LRMAEOR) THEN
  !$acc exit data detach (YD%RMAEOR)
  !$acc exit data delete (YD%RMAEOR)
ENDIF

LRMAESD = ALLOCATED (YD%RMAESD)
IF (LRMAESD) THEN
  !$acc exit data detach (YD%RMAESD)
  !$acc exit data delete (YD%RMAESD)
ENDIF

LRMAESS = ALLOCATED (YD%RMAESS)
IF (LRMAESS) THEN
  !$acc exit data detach (YD%RMAESS)
  !$acc exit data delete (YD%RMAESS)
ENDIF

LRMAESU = ALLOCATED (YD%RMAESU)
IF (LRMAESU) THEN
  !$acc exit data detach (YD%RMAESU)
  !$acc exit data delete (YD%RMAESU)
ENDIF

LRMACBC1 = ALLOCATED (YD%RMACBC1)
IF (LRMACBC1) THEN
  !$acc exit data detach (YD%RMACBC1)
  !$acc exit data delete (YD%RMACBC1)
ENDIF

LRMACBC2 = ALLOCATED (YD%RMACBC2)
IF (LRMACBC2) THEN
  !$acc exit data detach (YD%RMACBC2)
  !$acc exit data delete (YD%RMACBC2)
ENDIF

LRMAEBC1 = ALLOCATED (YD%RMAEBC1)
IF (LRMAEBC1) THEN
  !$acc exit data detach (YD%RMAEBC1)
  !$acc exit data delete (YD%RMAEBC1)
ENDIF

LRMAEBC2 = ALLOCATED (YD%RMAEBC2)
IF (LRMAEBC2) THEN
  !$acc exit data detach (YD%RMAEBC2)
  !$acc exit data delete (YD%RMAEBC2)
ENDIF

LRMACOR1 = ALLOCATED (YD%RMACOR1)
IF (LRMACOR1) THEN
  !$acc exit data detach (YD%RMACOR1)
  !$acc exit data delete (YD%RMACOR1)
ENDIF

LRMACOR2 = ALLOCATED (YD%RMACOR2)
IF (LRMACOR2) THEN
  !$acc exit data detach (YD%RMACOR2)
  !$acc exit data delete (YD%RMACOR2)
ENDIF

LRMAEOR1 = ALLOCATED (YD%RMAEOR1)
IF (LRMAEOR1) THEN
  !$acc exit data detach (YD%RMAEOR1)
  !$acc exit data delete (YD%RMAEOR1)
ENDIF

LRMAEOR2 = ALLOCATED (YD%RMAEOR2)
IF (LRMAEOR2) THEN
  !$acc exit data detach (YD%RMAEOR2)
  !$acc exit data delete (YD%RMAEOR2)
ENDIF

LRMACSD1 = ALLOCATED (YD%RMACSD1)
IF (LRMACSD1) THEN
  !$acc exit data detach (YD%RMACSD1)
  !$acc exit data delete (YD%RMACSD1)
ENDIF

LRMACSD2 = ALLOCATED (YD%RMACSD2)
IF (LRMACSD2) THEN
  !$acc exit data detach (YD%RMACSD2)
  !$acc exit data delete (YD%RMACSD2)
ENDIF

LRMACSD3 = ALLOCATED (YD%RMACSD3)
IF (LRMACSD3) THEN
  !$acc exit data detach (YD%RMACSD3)
  !$acc exit data delete (YD%RMACSD3)
ENDIF

LRMAESD1 = ALLOCATED (YD%RMAESD1)
IF (LRMAESD1) THEN
  !$acc exit data detach (YD%RMAESD1)
  !$acc exit data delete (YD%RMAESD1)
ENDIF

LRMAESD2 = ALLOCATED (YD%RMAESD2)
IF (LRMAESD2) THEN
  !$acc exit data detach (YD%RMAESD2)
  !$acc exit data delete (YD%RMAESD2)
ENDIF

LRMAESD3 = ALLOCATED (YD%RMAESD3)
IF (LRMAESD3) THEN
  !$acc exit data detach (YD%RMAESD3)
  !$acc exit data delete (YD%RMAESD3)
ENDIF

LRMACSS1 = ALLOCATED (YD%RMACSS1)
IF (LRMACSS1) THEN
  !$acc exit data detach (YD%RMACSS1)
  !$acc exit data delete (YD%RMACSS1)
ENDIF

LRMACSS2 = ALLOCATED (YD%RMACSS2)
IF (LRMACSS2) THEN
  !$acc exit data detach (YD%RMACSS2)
  !$acc exit data delete (YD%RMACSS2)
ENDIF

LRMACSS3 = ALLOCATED (YD%RMACSS3)
IF (LRMACSS3) THEN
  !$acc exit data detach (YD%RMACSS3)
  !$acc exit data delete (YD%RMACSS3)
ENDIF

LRMAESS1 = ALLOCATED (YD%RMAESS1)
IF (LRMAESS1) THEN
  !$acc exit data detach (YD%RMAESS1)
  !$acc exit data delete (YD%RMAESS1)
ENDIF

LRMAESS2 = ALLOCATED (YD%RMAESS2)
IF (LRMAESS2) THEN
  !$acc exit data detach (YD%RMAESS2)
  !$acc exit data delete (YD%RMAESS2)
ENDIF

LRMAESS3 = ALLOCATED (YD%RMAESS3)
IF (LRMAESS3) THEN
  !$acc exit data detach (YD%RMAESS3)
  !$acc exit data delete (YD%RMAESS3)
ENDIF

LRMACSU1 = ALLOCATED (YD%RMACSU1)
IF (LRMACSU1) THEN
  !$acc exit data detach (YD%RMACSU1)
  !$acc exit data delete (YD%RMACSU1)
ENDIF

LRMAESU1 = ALLOCATED (YD%RMAESU1)
IF (LRMAESU1) THEN
  !$acc exit data detach (YD%RMAESU1)
  !$acc exit data delete (YD%RMAESU1)
ENDIF

LRMACBC13D = ASSOCIATED (YD%RMACBC13D)
IF (LRMACBC13D) THEN
  !$acc exit data detach (YD%RMACBC13D)
  !$acc exit data delete (YD%RMACBC13D)
ENDIF

LRMACBC23D = ASSOCIATED (YD%RMACBC23D)
IF (LRMACBC23D) THEN
  !$acc exit data detach (YD%RMACBC23D)
  !$acc exit data delete (YD%RMACBC23D)
ENDIF

LRMACOR13D = ASSOCIATED (YD%RMACOR13D)
IF (LRMACOR13D) THEN
  !$acc exit data detach (YD%RMACOR13D)
  !$acc exit data delete (YD%RMACOR13D)
ENDIF

LRMACOR23D = ASSOCIATED (YD%RMACOR23D)
IF (LRMACOR23D) THEN
  !$acc exit data detach (YD%RMACOR23D)
  !$acc exit data delete (YD%RMACOR23D)
ENDIF

LRMACSD13D = ASSOCIATED (YD%RMACSD13D)
IF (LRMACSD13D) THEN
  !$acc exit data detach (YD%RMACSD13D)
  !$acc exit data delete (YD%RMACSD13D)
ENDIF

LRMACSD23D = ASSOCIATED (YD%RMACSD23D)
IF (LRMACSD23D) THEN
  !$acc exit data detach (YD%RMACSD23D)
  !$acc exit data delete (YD%RMACSD23D)
ENDIF

LRMACSD33D = ASSOCIATED (YD%RMACSD33D)
IF (LRMACSD33D) THEN
  !$acc exit data detach (YD%RMACSD33D)
  !$acc exit data delete (YD%RMACSD33D)
ENDIF

LRMACSS13D = ASSOCIATED (YD%RMACSS13D)
IF (LRMACSS13D) THEN
  !$acc exit data detach (YD%RMACSS13D)
  !$acc exit data delete (YD%RMACSS13D)
ENDIF

LRMACSS23D = ASSOCIATED (YD%RMACSS23D)
IF (LRMACSS23D) THEN
  !$acc exit data detach (YD%RMACSS23D)
  !$acc exit data delete (YD%RMACSS23D)
ENDIF

LRMACSS33D = ASSOCIATED (YD%RMACSS33D)
IF (LRMACSS33D) THEN
  !$acc exit data detach (YD%RMACSS33D)
  !$acc exit data delete (YD%RMACSS33D)
ENDIF

LRMACSU13D = ASSOCIATED (YD%RMACSU13D)
IF (LRMACSU13D) THEN
  !$acc exit data detach (YD%RMACSU13D)
  !$acc exit data delete (YD%RMACSU13D)
ENDIF

LREF_MON_AER_PRS = ASSOCIATED (YD%REF_MON_AER_PRS)
IF (LREF_MON_AER_PRS) THEN
  !$acc exit data detach (YD%REF_MON_AER_PRS)
  !$acc exit data delete (YD%REF_MON_AER_PRS)
ENDIF

LREF_MON_AER_DPRS = ASSOCIATED (YD%REF_MON_AER_DPRS)
IF (LREF_MON_AER_DPRS) THEN
  !$acc exit data detach (YD%REF_MON_AER_DPRS)
  !$acc exit data delete (YD%REF_MON_AER_DPRS)
ENDIF

LRMAEBC13D = ALLOCATED (YD%RMAEBC13D)
IF (LRMAEBC13D) THEN
  !$acc exit data detach (YD%RMAEBC13D)
  !$acc exit data delete (YD%RMAEBC13D)
ENDIF

LRMAEBC23D = ALLOCATED (YD%RMAEBC23D)
IF (LRMAEBC23D) THEN
  !$acc exit data detach (YD%RMAEBC23D)
  !$acc exit data delete (YD%RMAEBC23D)
ENDIF

LRMAEOR13D = ALLOCATED (YD%RMAEOR13D)
IF (LRMAEOR13D) THEN
  !$acc exit data detach (YD%RMAEOR13D)
  !$acc exit data delete (YD%RMAEOR13D)
ENDIF

LRMAEOR23D = ALLOCATED (YD%RMAEOR23D)
IF (LRMAEOR23D) THEN
  !$acc exit data detach (YD%RMAEOR23D)
  !$acc exit data delete (YD%RMAEOR23D)
ENDIF

LRMAESD13D = ALLOCATED (YD%RMAESD13D)
IF (LRMAESD13D) THEN
  !$acc exit data detach (YD%RMAESD13D)
  !$acc exit data delete (YD%RMAESD13D)
ENDIF

LRMAESD23D = ALLOCATED (YD%RMAESD23D)
IF (LRMAESD23D) THEN
  !$acc exit data detach (YD%RMAESD23D)
  !$acc exit data delete (YD%RMAESD23D)
ENDIF

LRMAESD33D = ALLOCATED (YD%RMAESD33D)
IF (LRMAESD33D) THEN
  !$acc exit data detach (YD%RMAESD33D)
  !$acc exit data delete (YD%RMAESD33D)
ENDIF

LRMAESS13D = ALLOCATED (YD%RMAESS13D)
IF (LRMAESS13D) THEN
  !$acc exit data detach (YD%RMAESS13D)
  !$acc exit data delete (YD%RMAESS13D)
ENDIF

LRMAESS23D = ALLOCATED (YD%RMAESS23D)
IF (LRMAESS23D) THEN
  !$acc exit data detach (YD%RMAESS23D)
  !$acc exit data delete (YD%RMAESS23D)
ENDIF

LRMAESS33D = ALLOCATED (YD%RMAESS33D)
IF (LRMAESS33D) THEN
  !$acc exit data detach (YD%RMAESS33D)
  !$acc exit data delete (YD%RMAESS33D)
ENDIF

LRMAESU13D = ALLOCATED (YD%RMAESU13D)
IF (LRMAESU13D) THEN
  !$acc exit data detach (YD%RMAESU13D)
  !$acc exit data delete (YD%RMAESU13D)
ENDIF

LREF_AER_PRS = ALLOCATED (YD%REF_AER_PRS)
IF (LREF_AER_PRS) THEN
  !$acc exit data detach (YD%REF_AER_PRS)
  !$acc exit data delete (YD%REF_AER_PRS)
ENDIF

LREF_AER_DPRS = ALLOCATED (YD%REF_AER_DPRS)
IF (LREF_AER_DPRS) THEN
  !$acc exit data detach (YD%REF_AER_DPRS)
  !$acc exit data delete (YD%REF_AER_DPRS)
ENDIF


LLDELETED = .FALSE.
IF (PRESENT (LDDELETED)) THEN
  LLDELETED = LDDELETED
ENDIF
IF (.NOT. LLDELETED) THEN
  !$acc exit data delete (YD)
ENDIF
END SUBROUTINE



END MODULE
