MODULE UTIL_TXYBDER_MOD

USE INTDYN_MOD, ONLY : TXYBDER

INTERFACE SAVE
MODULE PROCEDURE SAVE_TXYBDER
END INTERFACE

INTERFACE LOAD
MODULE PROCEDURE LOAD_TXYBDER
END INTERFACE

INTERFACE COPY
MODULE PROCEDURE COPY_TXYBDER
END INTERFACE

INTERFACE WIPE
MODULE PROCEDURE WIPE_TXYBDER
END INTERFACE



CONTAINS

SUBROUTINE SAVE_TXYBDER (KLUN, YD)

IMPLICIT NONE
INTEGER, INTENT (IN) :: KLUN
TYPE (TXYBDER), INTENT (IN), TARGET :: YD

WRITE (KLUN) YD%M_LNPRL
WRITE (KLUN) YD%M_LNPRM
WRITE (KLUN) YD%M_ALPHL
WRITE (KLUN) YD%M_ALPHM
WRITE (KLUN) YD%M_ALPHPLL
WRITE (KLUN) YD%M_ALPHPLM
WRITE (KLUN) YD%M_COEFD
WRITE (KLUN) YD%M_COEFA
WRITE (KLUN) YD%M_COEFAPL
WRITE (KLUN) YD%NDIM
END SUBROUTINE

SUBROUTINE LOAD_TXYBDER (KLUN, YD)

IMPLICIT NONE
INTEGER, INTENT (IN) :: KLUN
TYPE (TXYBDER), INTENT (OUT), TARGET :: YD

READ (KLUN) YD%M_LNPRL
READ (KLUN) YD%M_LNPRM
READ (KLUN) YD%M_ALPHL
READ (KLUN) YD%M_ALPHM
READ (KLUN) YD%M_ALPHPLL
READ (KLUN) YD%M_ALPHPLM
READ (KLUN) YD%M_COEFD
READ (KLUN) YD%M_COEFA
READ (KLUN) YD%M_COEFAPL
READ (KLUN) YD%NDIM
END SUBROUTINE


SUBROUTINE COPY_TXYBDER (YD, LDCREATED)

IMPLICIT NONE
TYPE (TXYBDER), INTENT (IN), TARGET :: YD
LOGICAL, OPTIONAL, INTENT (IN) :: LDCREATED
LOGICAL :: LLCREATED

LLCREATED = .FALSE.
IF (PRESENT (LDCREATED)) THEN
  LLCREATED = LDCREATED
ENDIF
IF (.NOT. LLCREATED) THEN
  !$acc enter data create (YD)
  !$acc update device (YD)
ENDIF










END SUBROUTINE

SUBROUTINE WIPE_TXYBDER (YD, LDDELETED)

IMPLICIT NONE
TYPE (TXYBDER), INTENT (IN), TARGET :: YD
LOGICAL, OPTIONAL, INTENT (IN) :: LDDELETED
LOGICAL :: LLDELETED











LLDELETED = .FALSE.
IF (PRESENT (LDDELETED)) THEN
  LLDELETED = LDDELETED
ENDIF
IF (.NOT. LLDELETED) THEN
  !$acc exit data delete (YD)
ENDIF
END SUBROUTINE



END MODULE
