MODULE UTIL_TRIP_MOD

USE YOMRIP, ONLY : TRIP

INTERFACE SAVE
MODULE PROCEDURE SAVE_TRIP
END INTERFACE

INTERFACE LOAD
MODULE PROCEDURE LOAD_TRIP
END INTERFACE

INTERFACE COPY
MODULE PROCEDURE COPY_TRIP
END INTERFACE

INTERFACE WIPE
MODULE PROCEDURE WIPE_TRIP
END INTERFACE



CONTAINS

SUBROUTINE SAVE_TRIP (KLUN, YD)
USE UTIL_REGLATLON_FIELD_MOD
USE UTIL_TEAERC_MACC_MOD
USE UTIL_TEAERC_TEGEN_MOD
USE UTIL_TECMIP_MOD
USE UTIL_TEOZOC_MOD
USE UTIL_TRADGHG_MOD
IMPLICIT NONE
INTEGER, INTENT (IN) :: KLUN
TYPE (TRIP), INTENT (IN), TARGET :: YD

WRITE (KLUN) YD%NSTART
WRITE (KLUN) YD%NSTOP
WRITE (KLUN) YD%CSTOP
WRITE (KLUN) YD%NSTADD
WRITE (KLUN) YD%NSTASS
WRITE (KLUN) YD%NFOST
WRITE (KLUN) YD%RSTATI
WRITE (KLUN) YD%RTIMTR
WRITE (KLUN) YD%RHGMT
WRITE (KLUN) YD%REQTIM
WRITE (KLUN) YD%RSOVR
WRITE (KLUN) YD%RDEASO
WRITE (KLUN) YD%RDECLI
WRITE (KLUN) YD%RWSOVR
WRITE (KLUN) YD%RIP0
WRITE (KLUN) YD%RCODEC
WRITE (KLUN) YD%RSIDEC
WRITE (KLUN) YD%RCOVSR
WRITE (KLUN) YD%RSIVSR
WRITE (KLUN) YD%RCODECN
WRITE (KLUN) YD%RSIDECN
WRITE (KLUN) YD%RCOVSRN
WRITE (KLUN) YD%RSIVSRN
WRITE (KLUN) YD%RCODECF
WRITE (KLUN) YD%RSIDECF
WRITE (KLUN) YD%RCOVSRF
WRITE (KLUN) YD%RSIVSRF
WRITE (KLUN) YD%TSTEP
WRITE (KLUN) YD%TDT
WRITE (KLUN) YD%RDTSA
WRITE (KLUN) YD%RDTSA2
WRITE (KLUN) YD%RDTS62
WRITE (KLUN) YD%RDTS22
WRITE (KLUN) YD%RTDT
WRITE (KLUN) YD%RDECLU
WRITE (KLUN) YD%RTMOLT
WRITE (KLUN) YD%RIP0LU
WRITE (KLUN) YD%RCODECLU
WRITE (KLUN) YD%RSIDECLU
WRITE (KLUN) YD%RCOVSRLU
WRITE (KLUN) YD%RSIVSRLU
CALL SAVE (KLUN, YD%YREOZOC)
CALL SAVE (KLUN, YD%YRECMIP)
CALL SAVE (KLUN, YD%YRERADGHG)
CALL SAVE (KLUN, YD%YREAERC_TEGEN)
CALL SAVE (KLUN, YD%YREAERC_MACC)
CALL SAVE (KLUN, YD%RAERSO4)
END SUBROUTINE

SUBROUTINE LOAD_TRIP (KLUN, YD)
USE UTIL_REGLATLON_FIELD_MOD
USE UTIL_TEAERC_MACC_MOD
USE UTIL_TEAERC_TEGEN_MOD
USE UTIL_TECMIP_MOD
USE UTIL_TEOZOC_MOD
USE UTIL_TRADGHG_MOD
USE PARKIND1, ONLY : JPRD

IMPLICIT NONE
INTEGER, INTENT (IN) :: KLUN
TYPE (TRIP), INTENT (OUT), TARGET :: YD
REAL(KIND=JPRD) :: ZTMP0
READ (KLUN) YD%NSTART
READ (KLUN) YD%NSTOP
READ (KLUN) YD%CSTOP
READ (KLUN) YD%NSTADD
READ (KLUN) YD%NSTASS
READ (KLUN) YD%NFOST
READ (KLUN) ZTMP0
YD%RSTATI = ZTMP0
READ (KLUN) ZTMP0
YD%RTIMTR = ZTMP0
READ (KLUN) ZTMP0
YD%RHGMT = ZTMP0
READ (KLUN) ZTMP0
YD%REQTIM = ZTMP0
READ (KLUN) ZTMP0
YD%RSOVR = ZTMP0
READ (KLUN) ZTMP0
YD%RDEASO = ZTMP0
READ (KLUN) ZTMP0
YD%RDECLI = ZTMP0
READ (KLUN) ZTMP0
YD%RWSOVR = ZTMP0
READ (KLUN) ZTMP0
YD%RIP0 = ZTMP0
READ (KLUN) ZTMP0
YD%RCODEC = ZTMP0
READ (KLUN) ZTMP0
YD%RSIDEC = ZTMP0
READ (KLUN) ZTMP0
YD%RCOVSR = ZTMP0
READ (KLUN) ZTMP0
YD%RSIVSR = ZTMP0
READ (KLUN) ZTMP0
YD%RCODECN = ZTMP0
READ (KLUN) ZTMP0
YD%RSIDECN = ZTMP0
READ (KLUN) ZTMP0
YD%RCOVSRN = ZTMP0
READ (KLUN) ZTMP0
YD%RSIVSRN = ZTMP0
READ (KLUN) ZTMP0
YD%RCODECF = ZTMP0
READ (KLUN) ZTMP0
YD%RSIDECF = ZTMP0
READ (KLUN) ZTMP0
YD%RCOVSRF = ZTMP0
READ (KLUN) ZTMP0
YD%RSIVSRF = ZTMP0
READ (KLUN) ZTMP0
YD%TSTEP = ZTMP0
READ (KLUN) ZTMP0
YD%TDT = ZTMP0
READ (KLUN) ZTMP0
YD%RDTSA = ZTMP0
READ (KLUN) ZTMP0
YD%RDTSA2 = ZTMP0
READ (KLUN) ZTMP0
YD%RDTS62 = ZTMP0
READ (KLUN) ZTMP0
YD%RDTS22 = ZTMP0
READ (KLUN) ZTMP0
YD%RTDT = ZTMP0
READ (KLUN) ZTMP0
YD%RDECLU = ZTMP0
READ (KLUN) ZTMP0
YD%RTMOLT = ZTMP0
READ (KLUN) ZTMP0
YD%RIP0LU = ZTMP0
READ (KLUN) ZTMP0
YD%RCODECLU = ZTMP0
READ (KLUN) ZTMP0
YD%RSIDECLU = ZTMP0
READ (KLUN) ZTMP0
YD%RCOVSRLU = ZTMP0
READ (KLUN) ZTMP0
YD%RSIVSRLU = ZTMP0
CALL LOAD (KLUN, YD%YREOZOC)
CALL LOAD (KLUN, YD%YRECMIP)
CALL LOAD (KLUN, YD%YRERADGHG)
CALL LOAD (KLUN, YD%YREAERC_TEGEN)
CALL LOAD (KLUN, YD%YREAERC_MACC)
CALL LOAD (KLUN, YD%RAERSO4)
END SUBROUTINE


SUBROUTINE COPY_TRIP (YD, LDCREATED)
USE UTIL_REGLATLON_FIELD_MOD
USE UTIL_TEAERC_MACC_MOD
USE UTIL_TEAERC_TEGEN_MOD
USE UTIL_TECMIP_MOD
USE UTIL_TEOZOC_MOD
USE UTIL_TRADGHG_MOD
IMPLICIT NONE
TYPE (TRIP), INTENT (IN), TARGET :: YD
LOGICAL, OPTIONAL, INTENT (IN) :: LDCREATED
LOGICAL :: LLCREATED

LLCREATED = .FALSE.
IF (PRESENT (LDCREATED)) THEN
  LLCREATED = LDCREATED
ENDIF
IF (.NOT. LLCREATED) THEN
  !$acc enter data create (YD)
  !$acc update device (YD)
ENDIF









































CALL COPY (YD%YREOZOC, LDCREATED=.TRUE.)

CALL COPY (YD%YRECMIP, LDCREATED=.TRUE.)

CALL COPY (YD%YRERADGHG, LDCREATED=.TRUE.)

CALL COPY (YD%YREAERC_TEGEN, LDCREATED=.TRUE.)

CALL COPY (YD%YREAERC_MACC, LDCREATED=.TRUE.)

CALL COPY (YD%RAERSO4, LDCREATED=.TRUE.)

END SUBROUTINE

SUBROUTINE WIPE_TRIP (YD, LDDELETED)
USE UTIL_REGLATLON_FIELD_MOD
USE UTIL_TEAERC_MACC_MOD
USE UTIL_TEAERC_TEGEN_MOD
USE UTIL_TECMIP_MOD
USE UTIL_TEOZOC_MOD
USE UTIL_TRADGHG_MOD
IMPLICIT NONE
TYPE (TRIP), INTENT (IN), TARGET :: YD
LOGICAL, OPTIONAL, INTENT (IN) :: LDDELETED
LOGICAL :: LLDELETED










































CALL WIPE (YD%YREOZOC, LDDELETED=.TRUE.)

CALL WIPE (YD%YRECMIP, LDDELETED=.TRUE.)

CALL WIPE (YD%YRERADGHG, LDDELETED=.TRUE.)

CALL WIPE (YD%YREAERC_TEGEN, LDDELETED=.TRUE.)

CALL WIPE (YD%YREAERC_MACC, LDDELETED=.TRUE.)

CALL WIPE (YD%RAERSO4, LDDELETED=.TRUE.)

LLDELETED = .FALSE.
IF (PRESENT (LDDELETED)) THEN
  LLDELETED = LDDELETED
ENDIF
IF (.NOT. LLDELETED) THEN
  !$acc exit data delete (YD)
ENDIF
END SUBROUTINE



END MODULE
