MODULE UTIL_TEAERC_TEGEN_MOD

USE YOEAERC, ONLY : TEAERC_TEGEN

INTERFACE SAVE
MODULE PROCEDURE SAVE_TEAERC_TEGEN
END INTERFACE

INTERFACE LOAD
MODULE PROCEDURE LOAD_TEAERC_TEGEN
END INTERFACE

INTERFACE COPY
MODULE PROCEDURE COPY_TEAERC_TEGEN
END INTERFACE

INTERFACE WIPE
MODULE PROCEDURE WIPE_TEAERC_TEGEN
END INTERFACE



CONTAINS

SUBROUTINE SAVE_TEAERC_TEGEN (KLUN, YD)

IMPLICIT NONE
INTEGER, INTENT (IN) :: KLUN
TYPE (TEAERC_TEGEN), INTENT (IN), TARGET :: YD
LOGICAL :: LRAERBC, LRAEROR, LRAERSD, LRAERSS, LRAERSU, LRAERV, LRLATV
WRITE (KLUN) YD%REPAER
LRAERBC = ASSOCIATED (YD%RAERBC)
WRITE (KLUN) LRAERBC
IF (LRAERBC) THEN
  WRITE (KLUN) LBOUND (YD%RAERBC)
  WRITE (KLUN) UBOUND (YD%RAERBC)
  WRITE (KLUN) YD%RAERBC
ENDIF
LRAEROR = ASSOCIATED (YD%RAEROR)
WRITE (KLUN) LRAEROR
IF (LRAEROR) THEN
  WRITE (KLUN) LBOUND (YD%RAEROR)
  WRITE (KLUN) UBOUND (YD%RAEROR)
  WRITE (KLUN) YD%RAEROR
ENDIF
LRAERSD = ASSOCIATED (YD%RAERSD)
WRITE (KLUN) LRAERSD
IF (LRAERSD) THEN
  WRITE (KLUN) LBOUND (YD%RAERSD)
  WRITE (KLUN) UBOUND (YD%RAERSD)
  WRITE (KLUN) YD%RAERSD
ENDIF
LRAERSS = ASSOCIATED (YD%RAERSS)
WRITE (KLUN) LRAERSS
IF (LRAERSS) THEN
  WRITE (KLUN) LBOUND (YD%RAERSS)
  WRITE (KLUN) UBOUND (YD%RAERSS)
  WRITE (KLUN) YD%RAERSS
ENDIF
LRAERSU = ASSOCIATED (YD%RAERSU)
WRITE (KLUN) LRAERSU
IF (LRAERSU) THEN
  WRITE (KLUN) LBOUND (YD%RAERSU)
  WRITE (KLUN) UBOUND (YD%RAERSU)
  WRITE (KLUN) YD%RAERSU
ENDIF
LRAERV = ASSOCIATED (YD%RAERV)
WRITE (KLUN) LRAERV
IF (LRAERV) THEN
  WRITE (KLUN) LBOUND (YD%RAERV)
  WRITE (KLUN) UBOUND (YD%RAERV)
  WRITE (KLUN) YD%RAERV
ENDIF
LRLATV = ASSOCIATED (YD%RLATV)
WRITE (KLUN) LRLATV
IF (LRLATV) THEN
  WRITE (KLUN) LBOUND (YD%RLATV)
  WRITE (KLUN) UBOUND (YD%RLATV)
  WRITE (KLUN) YD%RLATV
ENDIF
WRITE (KLUN) YD%RTAEBC
WRITE (KLUN) YD%RTAEOR
WRITE (KLUN) YD%RTAESD
WRITE (KLUN) YD%RTAESS
WRITE (KLUN) YD%RTAESU
WRITE (KLUN) YD%RTAEVO
WRITE (KLUN) YD%ISYEAR
WRITE (KLUN) YD%IEYEAR
WRITE (KLUN) YD%IS_INITIALISED
END SUBROUTINE

SUBROUTINE LOAD_TEAERC_TEGEN (KLUN, YD)
USE PARKIND1, ONLY : JPRD

IMPLICIT NONE
INTEGER, INTENT (IN) :: KLUN
TYPE (TEAERC_TEGEN), INTENT (OUT), TARGET :: YD
INTEGER :: IL1(1), IU1(1), IL3(3), IU3(3)
LOGICAL :: LRAERBC, LRAEROR, LRAERSD, LRAERSS, LRAERSU, LRAERV, LRLATV
REAL(KIND=JPRD) :: ZTMP0
REAL(KIND=JPRD), ALLOCATABLE :: ZTMP1 (:)
REAL(KIND=JPRD), ALLOCATABLE :: ZTMP2 (:,:)
REAL(KIND=JPRD), ALLOCATABLE :: ZTMP3 (:,:,:)
READ (KLUN) ZTMP0
YD%REPAER = ZTMP0
READ (KLUN) LRAERBC
IF (LRAERBC) THEN
  READ (KLUN) IL3
  READ (KLUN) IU3
  ALLOCATE (YD%RAERBC (IL3(1):IU3(1), IL3(2):IU3(2), IL3(3):IU3(3)))
  ALLOCATE (ZTMP3(LBOUND(YD%RAERBC,1):UBOUND(YD%RAERBC,1), LBOUND(YD%RAERBC,2):UBOUND(YD%RAERBC,2), LBOUND(YD%RAERBC,3):UBOUND(YD%RAERBC,3)))
  READ (KLUN) ZTMP3
  YD%RAERBC = ZTMP3
  DEALLOCATE (ZTMP3)
ELSE
  NULLIFY (YD%RAERBC)
ENDIF
READ (KLUN) LRAEROR
IF (LRAEROR) THEN
  READ (KLUN) IL3
  READ (KLUN) IU3
  ALLOCATE (YD%RAEROR (IL3(1):IU3(1), IL3(2):IU3(2), IL3(3):IU3(3)))
  ALLOCATE (ZTMP3(LBOUND(YD%RAEROR,1):UBOUND(YD%RAEROR,1), LBOUND(YD%RAEROR,2):UBOUND(YD%RAEROR,2), LBOUND(YD%RAEROR,3):UBOUND(YD%RAEROR,3)))
  READ (KLUN) ZTMP3
  YD%RAEROR = ZTMP3
  DEALLOCATE (ZTMP3)
ELSE
  NULLIFY (YD%RAEROR)
ENDIF
READ (KLUN) LRAERSD
IF (LRAERSD) THEN
  READ (KLUN) IL3
  READ (KLUN) IU3
  ALLOCATE (YD%RAERSD (IL3(1):IU3(1), IL3(2):IU3(2), IL3(3):IU3(3)))
  ALLOCATE (ZTMP3(LBOUND(YD%RAERSD,1):UBOUND(YD%RAERSD,1), LBOUND(YD%RAERSD,2):UBOUND(YD%RAERSD,2), LBOUND(YD%RAERSD,3):UBOUND(YD%RAERSD,3)))
  READ (KLUN) ZTMP3
  YD%RAERSD = ZTMP3
  DEALLOCATE (ZTMP3)
ELSE
  NULLIFY (YD%RAERSD)
ENDIF
READ (KLUN) LRAERSS
IF (LRAERSS) THEN
  READ (KLUN) IL3
  READ (KLUN) IU3
  ALLOCATE (YD%RAERSS (IL3(1):IU3(1), IL3(2):IU3(2), IL3(3):IU3(3)))
  ALLOCATE (ZTMP3(LBOUND(YD%RAERSS,1):UBOUND(YD%RAERSS,1), LBOUND(YD%RAERSS,2):UBOUND(YD%RAERSS,2), LBOUND(YD%RAERSS,3):UBOUND(YD%RAERSS,3)))
  READ (KLUN) ZTMP3
  YD%RAERSS = ZTMP3
  DEALLOCATE (ZTMP3)
ELSE
  NULLIFY (YD%RAERSS)
ENDIF
READ (KLUN) LRAERSU
IF (LRAERSU) THEN
  READ (KLUN) IL3
  READ (KLUN) IU3
  ALLOCATE (YD%RAERSU (IL3(1):IU3(1), IL3(2):IU3(2), IL3(3):IU3(3)))
  ALLOCATE (ZTMP3(LBOUND(YD%RAERSU,1):UBOUND(YD%RAERSU,1), LBOUND(YD%RAERSU,2):UBOUND(YD%RAERSU,2), LBOUND(YD%RAERSU,3):UBOUND(YD%RAERSU,3)))
  READ (KLUN) ZTMP3
  YD%RAERSU = ZTMP3
  DEALLOCATE (ZTMP3)
ELSE
  NULLIFY (YD%RAERSU)
ENDIF
READ (KLUN) LRAERV
IF (LRAERV) THEN
  READ (KLUN) IL3
  READ (KLUN) IU3
  ALLOCATE (YD%RAERV (IL3(1):IU3(1), IL3(2):IU3(2), IL3(3):IU3(3)))
  ALLOCATE (ZTMP3(LBOUND(YD%RAERV,1):UBOUND(YD%RAERV,1), LBOUND(YD%RAERV,2):UBOUND(YD%RAERV,2), LBOUND(YD%RAERV,3):UBOUND(YD%RAERV,3)))
  READ (KLUN) ZTMP3
  YD%RAERV = ZTMP3
  DEALLOCATE (ZTMP3)
ELSE
  NULLIFY (YD%RAERV)
ENDIF
READ (KLUN) LRLATV
IF (LRLATV) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (YD%RLATV (IL1(1):IU1(1)))
  ALLOCATE (ZTMP1(LBOUND(YD%RLATV,1):UBOUND(YD%RLATV,1)))
  READ (KLUN) ZTMP1
  YD%RLATV = ZTMP1
  DEALLOCATE (ZTMP1)
ELSE
  NULLIFY (YD%RLATV)
ENDIF
ALLOCATE (ZTMP2(LBOUND(YD%RTAEBC,1):UBOUND(YD%RTAEBC,1), LBOUND(YD%RTAEBC,2):UBOUND(YD%RTAEBC,2)))
READ (KLUN) ZTMP2
YD%RTAEBC = ZTMP2
DEALLOCATE (ZTMP2)
ALLOCATE (ZTMP2(LBOUND(YD%RTAEOR,1):UBOUND(YD%RTAEOR,1), LBOUND(YD%RTAEOR,2):UBOUND(YD%RTAEOR,2)))
READ (KLUN) ZTMP2
YD%RTAEOR = ZTMP2
DEALLOCATE (ZTMP2)
ALLOCATE (ZTMP2(LBOUND(YD%RTAESD,1):UBOUND(YD%RTAESD,1), LBOUND(YD%RTAESD,2):UBOUND(YD%RTAESD,2)))
READ (KLUN) ZTMP2
YD%RTAESD = ZTMP2
DEALLOCATE (ZTMP2)
ALLOCATE (ZTMP2(LBOUND(YD%RTAESS,1):UBOUND(YD%RTAESS,1), LBOUND(YD%RTAESS,2):UBOUND(YD%RTAESS,2)))
READ (KLUN) ZTMP2
YD%RTAESS = ZTMP2
DEALLOCATE (ZTMP2)
ALLOCATE (ZTMP2(LBOUND(YD%RTAESU,1):UBOUND(YD%RTAESU,1), LBOUND(YD%RTAESU,2):UBOUND(YD%RTAESU,2)))
READ (KLUN) ZTMP2
YD%RTAESU = ZTMP2
DEALLOCATE (ZTMP2)
ALLOCATE (ZTMP1(LBOUND(YD%RTAEVO,1):UBOUND(YD%RTAEVO,1)))
READ (KLUN) ZTMP1
YD%RTAEVO = ZTMP1
DEALLOCATE (ZTMP1)
READ (KLUN) YD%ISYEAR
READ (KLUN) YD%IEYEAR
READ (KLUN) YD%IS_INITIALISED
END SUBROUTINE


SUBROUTINE COPY_TEAERC_TEGEN (YD, LDCREATED)

IMPLICIT NONE
TYPE (TEAERC_TEGEN), INTENT (IN), TARGET :: YD
LOGICAL, OPTIONAL, INTENT (IN) :: LDCREATED
LOGICAL :: LLCREATED
LOGICAL :: LRAERBC, LRAEROR, LRAERSD, LRAERSS, LRAERSU, LRAERV, LRLATV

LLCREATED = .FALSE.
IF (PRESENT (LDCREATED)) THEN
  LLCREATED = LDCREATED
ENDIF
IF (.NOT. LLCREATED) THEN
  !$acc enter data create (YD)
  !$acc update device (YD)
ENDIF

LRAERBC = ASSOCIATED (YD%RAERBC)
IF (LRAERBC) THEN
  !$acc enter data create (YD%RAERBC)
  !$acc update device (YD%RAERBC)
  !$acc enter data attach (YD%RAERBC)
ENDIF

LRAEROR = ASSOCIATED (YD%RAEROR)
IF (LRAEROR) THEN
  !$acc enter data create (YD%RAEROR)
  !$acc update device (YD%RAEROR)
  !$acc enter data attach (YD%RAEROR)
ENDIF

LRAERSD = ASSOCIATED (YD%RAERSD)
IF (LRAERSD) THEN
  !$acc enter data create (YD%RAERSD)
  !$acc update device (YD%RAERSD)
  !$acc enter data attach (YD%RAERSD)
ENDIF

LRAERSS = ASSOCIATED (YD%RAERSS)
IF (LRAERSS) THEN
  !$acc enter data create (YD%RAERSS)
  !$acc update device (YD%RAERSS)
  !$acc enter data attach (YD%RAERSS)
ENDIF

LRAERSU = ASSOCIATED (YD%RAERSU)
IF (LRAERSU) THEN
  !$acc enter data create (YD%RAERSU)
  !$acc update device (YD%RAERSU)
  !$acc enter data attach (YD%RAERSU)
ENDIF

LRAERV = ASSOCIATED (YD%RAERV)
IF (LRAERV) THEN
  !$acc enter data create (YD%RAERV)
  !$acc update device (YD%RAERV)
  !$acc enter data attach (YD%RAERV)
ENDIF

LRLATV = ASSOCIATED (YD%RLATV)
IF (LRLATV) THEN
  !$acc enter data create (YD%RLATV)
  !$acc update device (YD%RLATV)
  !$acc enter data attach (YD%RLATV)
ENDIF










END SUBROUTINE

SUBROUTINE WIPE_TEAERC_TEGEN (YD, LDDELETED)

IMPLICIT NONE
TYPE (TEAERC_TEGEN), INTENT (IN), TARGET :: YD
LOGICAL, OPTIONAL, INTENT (IN) :: LDDELETED
LOGICAL :: LLDELETED
LOGICAL :: LRAERBC, LRAEROR, LRAERSD, LRAERSS, LRAERSU, LRAERV, LRLATV


LRAERBC = ASSOCIATED (YD%RAERBC)
IF (LRAERBC) THEN
  !$acc exit data detach (YD%RAERBC)
  !$acc exit data delete (YD%RAERBC)
ENDIF

LRAEROR = ASSOCIATED (YD%RAEROR)
IF (LRAEROR) THEN
  !$acc exit data detach (YD%RAEROR)
  !$acc exit data delete (YD%RAEROR)
ENDIF

LRAERSD = ASSOCIATED (YD%RAERSD)
IF (LRAERSD) THEN
  !$acc exit data detach (YD%RAERSD)
  !$acc exit data delete (YD%RAERSD)
ENDIF

LRAERSS = ASSOCIATED (YD%RAERSS)
IF (LRAERSS) THEN
  !$acc exit data detach (YD%RAERSS)
  !$acc exit data delete (YD%RAERSS)
ENDIF

LRAERSU = ASSOCIATED (YD%RAERSU)
IF (LRAERSU) THEN
  !$acc exit data detach (YD%RAERSU)
  !$acc exit data delete (YD%RAERSU)
ENDIF

LRAERV = ASSOCIATED (YD%RAERV)
IF (LRAERV) THEN
  !$acc exit data detach (YD%RAERV)
  !$acc exit data delete (YD%RAERV)
ENDIF

LRLATV = ASSOCIATED (YD%RLATV)
IF (LRLATV) THEN
  !$acc exit data detach (YD%RLATV)
  !$acc exit data delete (YD%RLATV)
ENDIF










LLDELETED = .FALSE.
IF (PRESENT (LDDELETED)) THEN
  LLDELETED = LDDELETED
ENDIF
IF (.NOT. LLDELETED) THEN
  !$acc exit data delete (YD)
ENDIF
END SUBROUTINE



END MODULE
