MODULE UTIL_MODEL_GENERAL_CONF_TYPE_MOD

USE MODEL_GENERAL_CONF_MOD, ONLY : MODEL_GENERAL_CONF_TYPE

INTERFACE SAVE
MODULE PROCEDURE SAVE_MODEL_GENERAL_CONF_TYPE
END INTERFACE

INTERFACE LOAD
MODULE PROCEDURE LOAD_MODEL_GENERAL_CONF_TYPE
END INTERFACE

INTERFACE COPY
MODULE PROCEDURE COPY_MODEL_GENERAL_CONF_TYPE
END INTERFACE

INTERFACE WIPE
MODULE PROCEDURE WIPE_MODEL_GENERAL_CONF_TYPE
END INTERFACE



CONTAINS

SUBROUTINE SAVE_MODEL_GENERAL_CONF_TYPE (KLUN, YD)
USE UTIL_TRIP_MOD
IMPLICIT NONE
INTEGER, INTENT (IN) :: KLUN
TYPE (MODEL_GENERAL_CONF_TYPE), INTENT (IN), TARGET :: YD

CALL SAVE (KLUN, YD%YRRIP)
END SUBROUTINE

SUBROUTINE LOAD_MODEL_GENERAL_CONF_TYPE (KLUN, YD)
USE UTIL_TRIP_MOD

IMPLICIT NONE
INTEGER, INTENT (IN) :: KLUN
TYPE (MODEL_GENERAL_CONF_TYPE), INTENT (OUT), TARGET :: YD

CALL LOAD (KLUN, YD%YRRIP)
END SUBROUTINE


SUBROUTINE COPY_MODEL_GENERAL_CONF_TYPE (YD, LDCREATED)
USE UTIL_TRIP_MOD
IMPLICIT NONE
TYPE (MODEL_GENERAL_CONF_TYPE), INTENT (IN), TARGET :: YD
LOGICAL, OPTIONAL, INTENT (IN) :: LDCREATED
LOGICAL :: LLCREATED

LLCREATED = .FALSE.
IF (PRESENT (LDCREATED)) THEN
  LLCREATED = LDCREATED
ENDIF
IF (.NOT. LLCREATED) THEN
  !$acc enter data create (YD)
  !$acc update device (YD)
ENDIF
CALL COPY (YD%YRRIP, LDCREATED=.TRUE.)

END SUBROUTINE

SUBROUTINE WIPE_MODEL_GENERAL_CONF_TYPE (YD, LDDELETED)
USE UTIL_TRIP_MOD
IMPLICIT NONE
TYPE (MODEL_GENERAL_CONF_TYPE), INTENT (IN), TARGET :: YD
LOGICAL, OPTIONAL, INTENT (IN) :: LDDELETED
LOGICAL :: LLDELETED

CALL WIPE (YD%YRRIP, LDDELETED=.TRUE.)

LLDELETED = .FALSE.
IF (PRESENT (LDDELETED)) THEN
  LLDELETED = LDDELETED
ENDIF
IF (.NOT. LLDELETED) THEN
  !$acc exit data delete (YD)
ENDIF
END SUBROUTINE



END MODULE
