MODULE UTIL_TXYB_MOD

USE INTDYN_MOD, ONLY : TXYB

INTERFACE SAVE
MODULE PROCEDURE SAVE_TXYB
END INTERFACE

INTERFACE LOAD
MODULE PROCEDURE LOAD_TXYB
END INTERFACE

INTERFACE COPY
MODULE PROCEDURE COPY_TXYB
END INTERFACE

INTERFACE WIPE
MODULE PROCEDURE WIPE_TXYB
END INTERFACE



CONTAINS

SUBROUTINE SAVE_TXYB (KLUN, YD)

IMPLICIT NONE
INTEGER, INTENT (IN) :: KLUN
TYPE (TXYB), INTENT (IN), TARGET :: YD

WRITE (KLUN) YD%M_DELP
WRITE (KLUN) YD%M_RDELP
WRITE (KLUN) YD%M_LNPR
WRITE (KLUN) YD%M_ALPH
WRITE (KLUN) YD%M_RTGR
WRITE (KLUN) YD%M_RPRE
WRITE (KLUN) YD%M_RPP
WRITE (KLUN) YD%NDIM
END SUBROUTINE

SUBROUTINE LOAD_TXYB (KLUN, YD)

IMPLICIT NONE
INTEGER, INTENT (IN) :: KLUN
TYPE (TXYB), INTENT (OUT), TARGET :: YD

READ (KLUN) YD%M_DELP
READ (KLUN) YD%M_RDELP
READ (KLUN) YD%M_LNPR
READ (KLUN) YD%M_ALPH
READ (KLUN) YD%M_RTGR
READ (KLUN) YD%M_RPRE
READ (KLUN) YD%M_RPP
READ (KLUN) YD%NDIM
END SUBROUTINE


SUBROUTINE COPY_TXYB (YD, LDCREATED)

IMPLICIT NONE
TYPE (TXYB), INTENT (IN), TARGET :: YD
LOGICAL, OPTIONAL, INTENT (IN) :: LDCREATED
LOGICAL :: LLCREATED

LLCREATED = .FALSE.
IF (PRESENT (LDCREATED)) THEN
  LLCREATED = LDCREATED
ENDIF
IF (.NOT. LLCREATED) THEN
  !$acc enter data create (YD)
  !$acc update device (YD)
ENDIF








END SUBROUTINE

SUBROUTINE WIPE_TXYB (YD, LDDELETED)

IMPLICIT NONE
TYPE (TXYB), INTENT (IN), TARGET :: YD
LOGICAL, OPTIONAL, INTENT (IN) :: LDDELETED
LOGICAL :: LLDELETED









LLDELETED = .FALSE.
IF (PRESENT (LDDELETED)) THEN
  LLDELETED = LDDELETED
ENDIF
IF (.NOT. LLDELETED) THEN
  !$acc exit data delete (YD)
ENDIF
END SUBROUTINE



END MODULE
