MODULE UTIL_REGLATLON_FIELD_MOD

USE REGLATLON_FIELD_MIX, ONLY : REGLATLON_FIELD

INTERFACE SAVE
MODULE PROCEDURE SAVE_REGLATLON_FIELD
END INTERFACE

INTERFACE LOAD
MODULE PROCEDURE LOAD_REGLATLON_FIELD
END INTERFACE

INTERFACE COPY
MODULE PROCEDURE COPY_REGLATLON_FIELD
END INTERFACE

INTERFACE WIPE
MODULE PROCEDURE WIPE_REGLATLON_FIELD
END INTERFACE



CONTAINS

SUBROUTINE SAVE_REGLATLON_FIELD (KLUN, YD)

IMPLICIT NONE
INTEGER, INTENT (IN) :: KLUN
TYPE (REGLATLON_FIELD), INTENT (IN), TARGET :: YD
LOGICAL :: LPFLD, LPLAT, LPLON, LPSIN
WRITE (KLUN) YD%NLAT
WRITE (KLUN) YD%NLON
WRITE (KLUN) YD%DLAT
WRITE (KLUN) YD%DLON
LPFLD = ASSOCIATED (YD%PFLD)
WRITE (KLUN) LPFLD
IF (LPFLD) THEN
  WRITE (KLUN) LBOUND (YD%PFLD)
  WRITE (KLUN) UBOUND (YD%PFLD)
  WRITE (KLUN) YD%PFLD
ENDIF
LPLAT = ASSOCIATED (YD%PLAT)
WRITE (KLUN) LPLAT
IF (LPLAT) THEN
  WRITE (KLUN) LBOUND (YD%PLAT)
  WRITE (KLUN) UBOUND (YD%PLAT)
  WRITE (KLUN) YD%PLAT
ENDIF
LPSIN = ASSOCIATED (YD%PSIN)
WRITE (KLUN) LPSIN
IF (LPSIN) THEN
  WRITE (KLUN) LBOUND (YD%PSIN)
  WRITE (KLUN) UBOUND (YD%PSIN)
  WRITE (KLUN) YD%PSIN
ENDIF
LPLON = ASSOCIATED (YD%PLON)
WRITE (KLUN) LPLON
IF (LPLON) THEN
  WRITE (KLUN) LBOUND (YD%PLON)
  WRITE (KLUN) UBOUND (YD%PLON)
  WRITE (KLUN) YD%PLON
ENDIF
END SUBROUTINE

SUBROUTINE LOAD_REGLATLON_FIELD (KLUN, YD)
USE PARKIND1, ONLY : JPRD

IMPLICIT NONE
INTEGER, INTENT (IN) :: KLUN
TYPE (REGLATLON_FIELD), INTENT (OUT), TARGET :: YD
INTEGER :: IL1(1), IU1(1), IL2(2), IU2(2)
LOGICAL :: LPFLD, LPLAT, LPLON, LPSIN
REAL(KIND=JPRD) :: ZTMP0
REAL(KIND=JPRD), ALLOCATABLE :: ZTMP1 (:)
REAL(KIND=JPRD), ALLOCATABLE :: ZTMP2 (:,:)
READ (KLUN) YD%NLAT
READ (KLUN) YD%NLON
READ (KLUN) ZTMP0
YD%DLAT = ZTMP0
READ (KLUN) ZTMP0
YD%DLON = ZTMP0
READ (KLUN) LPFLD
IF (LPFLD) THEN
  READ (KLUN) IL2
  READ (KLUN) IU2
  ALLOCATE (YD%PFLD (IL2(1):IU2(1), IL2(2):IU2(2)))
  ALLOCATE (ZTMP2(LBOUND(YD%PFLD,1):UBOUND(YD%PFLD,1), LBOUND(YD%PFLD,2):UBOUND(YD%PFLD,2)))
  READ (KLUN) ZTMP2
  YD%PFLD = ZTMP2
  DEALLOCATE (ZTMP2)
ELSE
  NULLIFY (YD%PFLD)
ENDIF
READ (KLUN) LPLAT
IF (LPLAT) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (YD%PLAT (IL1(1):IU1(1)))
  ALLOCATE (ZTMP1(LBOUND(YD%PLAT,1):UBOUND(YD%PLAT,1)))
  READ (KLUN) ZTMP1
  YD%PLAT = ZTMP1
  DEALLOCATE (ZTMP1)
ELSE
  NULLIFY (YD%PLAT)
ENDIF
READ (KLUN) LPSIN
IF (LPSIN) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (YD%PSIN (IL1(1):IU1(1)))
  ALLOCATE (ZTMP1(LBOUND(YD%PSIN,1):UBOUND(YD%PSIN,1)))
  READ (KLUN) ZTMP1
  YD%PSIN = ZTMP1
  DEALLOCATE (ZTMP1)
ELSE
  NULLIFY (YD%PSIN)
ENDIF
READ (KLUN) LPLON
IF (LPLON) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (YD%PLON (IL1(1):IU1(1)))
  ALLOCATE (ZTMP1(LBOUND(YD%PLON,1):UBOUND(YD%PLON,1)))
  READ (KLUN) ZTMP1
  YD%PLON = ZTMP1
  DEALLOCATE (ZTMP1)
ELSE
  NULLIFY (YD%PLON)
ENDIF
END SUBROUTINE


SUBROUTINE COPY_REGLATLON_FIELD (YD, LDCREATED)

IMPLICIT NONE
TYPE (REGLATLON_FIELD), INTENT (IN), TARGET :: YD
LOGICAL, OPTIONAL, INTENT (IN) :: LDCREATED
LOGICAL :: LLCREATED
LOGICAL :: LPFLD, LPLAT, LPLON, LPSIN

LLCREATED = .FALSE.
IF (PRESENT (LDCREATED)) THEN
  LLCREATED = LDCREATED
ENDIF
IF (.NOT. LLCREATED) THEN
  !$acc enter data create (YD)
  !$acc update device (YD)
ENDIF




LPFLD = ASSOCIATED (YD%PFLD)
IF (LPFLD) THEN
  !$acc enter data create (YD%PFLD)
  !$acc update device (YD%PFLD)
  !$acc enter data attach (YD%PFLD)
ENDIF

LPLAT = ASSOCIATED (YD%PLAT)
IF (LPLAT) THEN
  !$acc enter data create (YD%PLAT)
  !$acc update device (YD%PLAT)
  !$acc enter data attach (YD%PLAT)
ENDIF

LPSIN = ASSOCIATED (YD%PSIN)
IF (LPSIN) THEN
  !$acc enter data create (YD%PSIN)
  !$acc update device (YD%PSIN)
  !$acc enter data attach (YD%PSIN)
ENDIF

LPLON = ASSOCIATED (YD%PLON)
IF (LPLON) THEN
  !$acc enter data create (YD%PLON)
  !$acc update device (YD%PLON)
  !$acc enter data attach (YD%PLON)
ENDIF

END SUBROUTINE

SUBROUTINE WIPE_REGLATLON_FIELD (YD, LDDELETED)

IMPLICIT NONE
TYPE (REGLATLON_FIELD), INTENT (IN), TARGET :: YD
LOGICAL, OPTIONAL, INTENT (IN) :: LDDELETED
LOGICAL :: LLDELETED
LOGICAL :: LPFLD, LPLAT, LPLON, LPSIN





LPFLD = ASSOCIATED (YD%PFLD)
IF (LPFLD) THEN
  !$acc exit data detach (YD%PFLD)
  !$acc exit data delete (YD%PFLD)
ENDIF

LPLAT = ASSOCIATED (YD%PLAT)
IF (LPLAT) THEN
  !$acc exit data detach (YD%PLAT)
  !$acc exit data delete (YD%PLAT)
ENDIF

LPSIN = ASSOCIATED (YD%PSIN)
IF (LPSIN) THEN
  !$acc exit data detach (YD%PSIN)
  !$acc exit data delete (YD%PSIN)
ENDIF

LPLON = ASSOCIATED (YD%PLON)
IF (LPLON) THEN
  !$acc exit data detach (YD%PLON)
  !$acc exit data delete (YD%PLON)
ENDIF

LLDELETED = .FALSE.
IF (PRESENT (LDDELETED)) THEN
  LLDELETED = LDDELETED
ENDIF
IF (.NOT. LLDELETED) THEN
  !$acc exit data delete (YD)
ENDIF
END SUBROUTINE



END MODULE
