MODULE UTIL_TDYNA_MOD

USE YOMDYNA, ONLY : TDYNA

INTERFACE SAVE
MODULE PROCEDURE SAVE_TDYNA
END INTERFACE

INTERFACE LOAD
MODULE PROCEDURE LOAD_TDYNA
END INTERFACE

INTERFACE COPY
MODULE PROCEDURE COPY_TDYNA
END INTERFACE

INTERFACE WIPE
MODULE PROCEDURE WIPE_TDYNA
END INTERFACE



CONTAINS

SUBROUTINE SAVE_TDYNA (KLUN, YD)
USE UTIL_TGFLT_MOD
USE UTIL_TGMVT_MOD
USE UTIL_TTND_MOD
IMPLICIT NONE
INTEGER, INTENT (IN) :: KLUN
TYPE (TDYNA), INTENT (IN), TARGET :: YD

WRITE (KLUN) YD%LNHEE
WRITE (KLUN) YD%LNHQE
WRITE (KLUN) YD%LNHDYN
WRITE (KLUN) YD%LSACC
WRITE (KLUN) YD%LSPRT
WRITE (KLUN) YD%LTWOTL
WRITE (KLUN) YD%LSLAG
WRITE (KLUN) YD%NPDVAR
WRITE (KLUN) YD%NVDVAR
WRITE (KLUN) YD%ND4SYS
WRITE (KLUN) YD%LNHX
WRITE (KLUN) YD%LNHXDER
WRITE (KLUN) YD%LGWADV
WRITE (KLUN) YD%NGWADVSI
WRITE (KLUN) YD%LRDBBC
WRITE (KLUN) YD%LSI_NHEE
WRITE (KLUN) YD%LSLHD
WRITE (KLUN) YD%LSLHD_W
WRITE (KLUN) YD%LSLHD_T
WRITE (KLUN) YD%LSLHD_SPD
WRITE (KLUN) YD%LSLHD_SVD
WRITE (KLUN) YD%LSLHD_GFL
WRITE (KLUN) YD%LSLHD_OLD
WRITE (KLUN) YD%LSLHD_STATIC
WRITE (KLUN) YD%LSLHDQUAD
WRITE (KLUN) YD%SLHDKMIN
WRITE (KLUN) YD%SLHDKMAX
WRITE (KLUN) YD%SLHDKREF
WRITE (KLUN) YD%SLHDEPSH
WRITE (KLUN) YD%SLHDEPSV
WRITE (KLUN) YD%LSLVF
WRITE (KLUN) YD%SLVFEPS
WRITE (KLUN) YD%P_SLVF_BOT
WRITE (KLUN) YD%SLVFMIN
WRITE (KLUN) YD%SLVFTR
WRITE (KLUN) YD%P_SLVF_TR
WRITE (KLUN) YD%LGRADSP
WRITE (KLUN) YD%LPGFSF
WRITE (KLUN) YD%LPGREUSE
WRITE (KLUN) YD%L3DTURB
WRITE (KLUN) YD%LSLDIA
WRITE (KLUN) YD%LRPRSLTRJ
WRITE (KLUN) YD%LRALTVDISP
WRITE (KLUN) YD%LVSPLIP
WRITE (KLUN) YD%LRHSVWENO
WRITE (KLUN) YD%LCOMAD
WRITE (KLUN) YD%LCOMADH
WRITE (KLUN) YD%LCOMADV
WRITE (KLUN) YD%LCOMAD_W
WRITE (KLUN) YD%LCOMAD_T
WRITE (KLUN) YD%LCOMAD_SPD
WRITE (KLUN) YD%LCOMAD_SVD
WRITE (KLUN) YD%LCOMAD_SP
WRITE (KLUN) YD%LCOMAD_GFL
WRITE (KLUN) YD%LNESCT
WRITE (KLUN) YD%LNESCV
WRITE (KLUN) YD%LNESC
WRITE (KLUN) YD%LSETTLST
WRITE (KLUN) YD%LSETTLSV
WRITE (KLUN) YD%LSETTLS
WRITE (KLUN) YD%LELTRA
WRITE (KLUN) YD%LSLINLC2
WRITE (KLUN) YD%LSLINL
WRITE (KLUN) YD%LHOISLT
WRITE (KLUN) YD%HOISLTV
WRITE (KLUN) YD%HOISLTH
WRITE (KLUN) YD%LSLTVWENO
WRITE (KLUN) YD%LRUBC
WRITE (KLUN) YD%LREFINE_NHPRE_SURF
WRITE (KLUN) YD%LPC_FULL
WRITE (KLUN) YD%LPC_CHEAP
WRITE (KLUN) YD%LPC_CHEAP2
WRITE (KLUN) YD%LMIXETTLS
WRITE (KLUN) YD%LMIXETTLS_PRINT
WRITE (KLUN) YD%RMIXNL_TRH
WRITE (KLUN) YD%L_RDRY_VD
WRITE (KLUN) YD%L_RDRY_NHX
WRITE (KLUN) YD%L_DRY_KAP
CALL SAVE (KLUN, YD%YYTTND)
CALL SAVE (KLUN, YD%YYTGMVT95)
CALL SAVE (KLUN, YD%YYTGFLT95)
END SUBROUTINE

SUBROUTINE LOAD_TDYNA (KLUN, YD)
USE UTIL_TGFLT_MOD
USE UTIL_TGMVT_MOD
USE UTIL_TTND_MOD
USE PARKIND1, ONLY : JPRD

IMPLICIT NONE
INTEGER, INTENT (IN) :: KLUN
TYPE (TDYNA), INTENT (OUT), TARGET :: YD
REAL(KIND=JPRD) :: ZTMP0
READ (KLUN) YD%LNHEE
READ (KLUN) YD%LNHQE
READ (KLUN) YD%LNHDYN
READ (KLUN) YD%LSACC
READ (KLUN) YD%LSPRT
READ (KLUN) YD%LTWOTL
READ (KLUN) YD%LSLAG
READ (KLUN) YD%NPDVAR
READ (KLUN) YD%NVDVAR
READ (KLUN) YD%ND4SYS
READ (KLUN) YD%LNHX
READ (KLUN) YD%LNHXDER
READ (KLUN) YD%LGWADV
READ (KLUN) YD%NGWADVSI
READ (KLUN) YD%LRDBBC
READ (KLUN) YD%LSI_NHEE
READ (KLUN) YD%LSLHD
READ (KLUN) YD%LSLHD_W
READ (KLUN) YD%LSLHD_T
READ (KLUN) YD%LSLHD_SPD
READ (KLUN) YD%LSLHD_SVD
READ (KLUN) YD%LSLHD_GFL
READ (KLUN) YD%LSLHD_OLD
READ (KLUN) YD%LSLHD_STATIC
READ (KLUN) YD%LSLHDQUAD
READ (KLUN) ZTMP0
YD%SLHDKMIN = ZTMP0
READ (KLUN) ZTMP0
YD%SLHDKMAX = ZTMP0
READ (KLUN) ZTMP0
YD%SLHDKREF = ZTMP0
READ (KLUN) ZTMP0
YD%SLHDEPSH = ZTMP0
READ (KLUN) ZTMP0
YD%SLHDEPSV = ZTMP0
READ (KLUN) YD%LSLVF
READ (KLUN) ZTMP0
YD%SLVFEPS = ZTMP0
READ (KLUN) ZTMP0
YD%P_SLVF_BOT = ZTMP0
READ (KLUN) ZTMP0
YD%SLVFMIN = ZTMP0
READ (KLUN) ZTMP0
YD%SLVFTR = ZTMP0
READ (KLUN) ZTMP0
YD%P_SLVF_TR = ZTMP0
READ (KLUN) YD%LGRADSP
READ (KLUN) YD%LPGFSF
READ (KLUN) YD%LPGREUSE
READ (KLUN) YD%L3DTURB
READ (KLUN) YD%LSLDIA
READ (KLUN) YD%LRPRSLTRJ
READ (KLUN) YD%LRALTVDISP
READ (KLUN) YD%LVSPLIP
READ (KLUN) YD%LRHSVWENO
READ (KLUN) YD%LCOMAD
READ (KLUN) YD%LCOMADH
READ (KLUN) YD%LCOMADV
READ (KLUN) YD%LCOMAD_W
READ (KLUN) YD%LCOMAD_T
READ (KLUN) YD%LCOMAD_SPD
READ (KLUN) YD%LCOMAD_SVD
READ (KLUN) YD%LCOMAD_SP
READ (KLUN) YD%LCOMAD_GFL
READ (KLUN) YD%LNESCT
READ (KLUN) YD%LNESCV
READ (KLUN) YD%LNESC
READ (KLUN) YD%LSETTLST
READ (KLUN) YD%LSETTLSV
READ (KLUN) YD%LSETTLS
READ (KLUN) YD%LELTRA
READ (KLUN) YD%LSLINLC2
READ (KLUN) YD%LSLINL
READ (KLUN) YD%LHOISLT
READ (KLUN) ZTMP0
YD%HOISLTV = ZTMP0
READ (KLUN) ZTMP0
YD%HOISLTH = ZTMP0
READ (KLUN) YD%LSLTVWENO
READ (KLUN) YD%LRUBC
READ (KLUN) YD%LREFINE_NHPRE_SURF
READ (KLUN) YD%LPC_FULL
READ (KLUN) YD%LPC_CHEAP
READ (KLUN) YD%LPC_CHEAP2
READ (KLUN) YD%LMIXETTLS
READ (KLUN) YD%LMIXETTLS_PRINT
READ (KLUN) ZTMP0
YD%RMIXNL_TRH = ZTMP0
READ (KLUN) YD%L_RDRY_VD
READ (KLUN) YD%L_RDRY_NHX
READ (KLUN) YD%L_DRY_KAP
CALL LOAD (KLUN, YD%YYTTND)
CALL LOAD (KLUN, YD%YYTGMVT95)
CALL LOAD (KLUN, YD%YYTGFLT95)
END SUBROUTINE


SUBROUTINE COPY_TDYNA (YD, LDCREATED)
USE UTIL_TGFLT_MOD
USE UTIL_TGMVT_MOD
USE UTIL_TTND_MOD
IMPLICIT NONE
TYPE (TDYNA), INTENT (IN), TARGET :: YD
LOGICAL, OPTIONAL, INTENT (IN) :: LDCREATED
LOGICAL :: LLCREATED

LLCREATED = .FALSE.
IF (PRESENT (LDCREATED)) THEN
  LLCREATED = LDCREATED
ENDIF
IF (.NOT. LLCREATED) THEN
  !$acc enter data create (YD)
  !$acc update device (YD)
ENDIF














































































CALL COPY (YD%YYTTND, LDCREATED=.TRUE.)

CALL COPY (YD%YYTGMVT95, LDCREATED=.TRUE.)

CALL COPY (YD%YYTGFLT95, LDCREATED=.TRUE.)

END SUBROUTINE

SUBROUTINE WIPE_TDYNA (YD, LDDELETED)
USE UTIL_TGFLT_MOD
USE UTIL_TGMVT_MOD
USE UTIL_TTND_MOD
IMPLICIT NONE
TYPE (TDYNA), INTENT (IN), TARGET :: YD
LOGICAL, OPTIONAL, INTENT (IN) :: LDDELETED
LOGICAL :: LLDELETED















































































CALL WIPE (YD%YYTTND, LDDELETED=.TRUE.)

CALL WIPE (YD%YYTGMVT95, LDDELETED=.TRUE.)

CALL WIPE (YD%YYTGFLT95, LDDELETED=.TRUE.)

LLDELETED = .FALSE.
IF (PRESENT (LDDELETED)) THEN
  LLDELETED = LDDELETED
ENDIF
IF (.NOT. LLDELETED) THEN
  !$acc exit data delete (YD)
ENDIF
END SUBROUTINE



END MODULE
