MODULE UTIL_TECMIP_MOD

USE YOECMIP, ONLY : TECMIP

INTERFACE SAVE
MODULE PROCEDURE SAVE_TECMIP
END INTERFACE

INTERFACE LOAD
MODULE PROCEDURE LOAD_TECMIP
END INTERFACE

INTERFACE COPY
MODULE PROCEDURE COPY_TECMIP
END INTERFACE

INTERFACE WIPE
MODULE PROCEDURE WIPE_TECMIP
END INTERFACE



CONTAINS

SUBROUTINE SAVE_TECMIP (KLUN, YD)

IMPLICIT NONE
INTEGER, INTENT (IN) :: KLUN
TYPE (TECMIP), INTENT (IN), TARGET :: YD
LOGICAL :: LRLATCLI, LRLONCLI, LROZT1, LRPROC1, LRSINC1, LZOZCL
WRITE (KLUN) YD%NRCP
WRITE (KLUN) YD%NO3CMIP
WRITE (KLUN) YD%NGHGCMIP
WRITE (KLUN) YD%NCMIPFIXYR
WRITE (KLUN) YD%NCURRYR
WRITE (KLUN) YD%GHGDATADIR
WRITE (KLUN) YD%CSOLARDATA
WRITE (KLUN) YD%CO3DATADIR
WRITE (KLUN) YD%CO3DATAFIL
LZOZCL = ALLOCATED (YD%ZOZCL)
WRITE (KLUN) LZOZCL
IF (LZOZCL) THEN
  WRITE (KLUN) LBOUND (YD%ZOZCL)
  WRITE (KLUN) UBOUND (YD%ZOZCL)
  WRITE (KLUN) YD%ZOZCL
ENDIF
LRSINC1 = ALLOCATED (YD%RSINC1)
WRITE (KLUN) LRSINC1
IF (LRSINC1) THEN
  WRITE (KLUN) LBOUND (YD%RSINC1)
  WRITE (KLUN) UBOUND (YD%RSINC1)
  WRITE (KLUN) YD%RSINC1
ENDIF
LRPROC1 = ALLOCATED (YD%RPROC1)
WRITE (KLUN) LRPROC1
IF (LRPROC1) THEN
  WRITE (KLUN) LBOUND (YD%RPROC1)
  WRITE (KLUN) UBOUND (YD%RPROC1)
  WRITE (KLUN) YD%RPROC1
ENDIF
LRLATCLI = ALLOCATED (YD%RLATCLI)
WRITE (KLUN) LRLATCLI
IF (LRLATCLI) THEN
  WRITE (KLUN) LBOUND (YD%RLATCLI)
  WRITE (KLUN) UBOUND (YD%RLATCLI)
  WRITE (KLUN) YD%RLATCLI
ENDIF
LRLONCLI = ALLOCATED (YD%RLONCLI)
WRITE (KLUN) LRLONCLI
IF (LRLONCLI) THEN
  WRITE (KLUN) LBOUND (YD%RLONCLI)
  WRITE (KLUN) UBOUND (YD%RLONCLI)
  WRITE (KLUN) YD%RLONCLI
ENDIF
LROZT1 = ALLOCATED (YD%ROZT1)
WRITE (KLUN) LROZT1
IF (LROZT1) THEN
  WRITE (KLUN) LBOUND (YD%ROZT1)
  WRITE (KLUN) UBOUND (YD%ROZT1)
  WRITE (KLUN) YD%ROZT1
ENDIF
END SUBROUTINE

SUBROUTINE LOAD_TECMIP (KLUN, YD)
USE PARKIND1, ONLY : JPRD

IMPLICIT NONE
INTEGER, INTENT (IN) :: KLUN
TYPE (TECMIP), INTENT (OUT), TARGET :: YD
INTEGER :: IL1(1), IU1(1), IL3(3), IU3(3), IL4(4), IU4(4)
LOGICAL :: LRLATCLI, LRLONCLI, LROZT1, LRPROC1, LRSINC1, LZOZCL
REAL(KIND=JPRD), ALLOCATABLE :: ZTMP1 (:)
REAL(KIND=JPRD), ALLOCATABLE :: ZTMP3 (:,:,:)
REAL(KIND=JPRD), ALLOCATABLE :: ZTMP4 (:,:,:,:)
READ (KLUN) YD%NRCP
READ (KLUN) YD%NO3CMIP
READ (KLUN) YD%NGHGCMIP
READ (KLUN) YD%NCMIPFIXYR
READ (KLUN) YD%NCURRYR
READ (KLUN) YD%GHGDATADIR
READ (KLUN) YD%CSOLARDATA
READ (KLUN) YD%CO3DATADIR
READ (KLUN) YD%CO3DATAFIL
READ (KLUN) LZOZCL
IF (LZOZCL) THEN
  READ (KLUN) IL4
  READ (KLUN) IU4
  ALLOCATE (YD%ZOZCL (IL4(1):IU4(1), IL4(2):IU4(2), IL4(3):IU4(3), IL4(4):IU4(4)))
  ALLOCATE (ZTMP4(LBOUND(YD%ZOZCL,1):UBOUND(YD%ZOZCL,1), LBOUND(YD%ZOZCL,2):UBOUND(YD%ZOZCL,2), LBOUND(YD%ZOZCL,3):UBOUND(YD%ZOZCL,3), LBOUND(YD%ZOZCL,4):UBOUND(YD%ZOZCL,4)))
  READ (KLUN) ZTMP4
  YD%ZOZCL = ZTMP4
  DEALLOCATE (ZTMP4)
ENDIF
READ (KLUN) LRSINC1
IF (LRSINC1) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (YD%RSINC1 (IL1(1):IU1(1)))
  ALLOCATE (ZTMP1(LBOUND(YD%RSINC1,1):UBOUND(YD%RSINC1,1)))
  READ (KLUN) ZTMP1
  YD%RSINC1 = ZTMP1
  DEALLOCATE (ZTMP1)
ENDIF
READ (KLUN) LRPROC1
IF (LRPROC1) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (YD%RPROC1 (IL1(1):IU1(1)))
  ALLOCATE (ZTMP1(LBOUND(YD%RPROC1,1):UBOUND(YD%RPROC1,1)))
  READ (KLUN) ZTMP1
  YD%RPROC1 = ZTMP1
  DEALLOCATE (ZTMP1)
ENDIF
READ (KLUN) LRLATCLI
IF (LRLATCLI) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (YD%RLATCLI (IL1(1):IU1(1)))
  ALLOCATE (ZTMP1(LBOUND(YD%RLATCLI,1):UBOUND(YD%RLATCLI,1)))
  READ (KLUN) ZTMP1
  YD%RLATCLI = ZTMP1
  DEALLOCATE (ZTMP1)
ENDIF
READ (KLUN) LRLONCLI
IF (LRLONCLI) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (YD%RLONCLI (IL1(1):IU1(1)))
  ALLOCATE (ZTMP1(LBOUND(YD%RLONCLI,1):UBOUND(YD%RLONCLI,1)))
  READ (KLUN) ZTMP1
  YD%RLONCLI = ZTMP1
  DEALLOCATE (ZTMP1)
ENDIF
READ (KLUN) LROZT1
IF (LROZT1) THEN
  READ (KLUN) IL3
  READ (KLUN) IU3
  ALLOCATE (YD%ROZT1 (IL3(1):IU3(1), IL3(2):IU3(2), IL3(3):IU3(3)))
  ALLOCATE (ZTMP3(LBOUND(YD%ROZT1,1):UBOUND(YD%ROZT1,1), LBOUND(YD%ROZT1,2):UBOUND(YD%ROZT1,2), LBOUND(YD%ROZT1,3):UBOUND(YD%ROZT1,3)))
  READ (KLUN) ZTMP3
  YD%ROZT1 = ZTMP3
  DEALLOCATE (ZTMP3)
ENDIF
END SUBROUTINE


SUBROUTINE COPY_TECMIP (YD, LDCREATED)

IMPLICIT NONE
TYPE (TECMIP), INTENT (IN), TARGET :: YD
LOGICAL, OPTIONAL, INTENT (IN) :: LDCREATED
LOGICAL :: LLCREATED
LOGICAL :: LRLATCLI, LRLONCLI, LROZT1, LRPROC1, LRSINC1, LZOZCL

LLCREATED = .FALSE.
IF (PRESENT (LDCREATED)) THEN
  LLCREATED = LDCREATED
ENDIF
IF (.NOT. LLCREATED) THEN
  !$acc enter data create (YD)
  !$acc update device (YD)
ENDIF









LZOZCL = ALLOCATED (YD%ZOZCL)
IF (LZOZCL) THEN
  !$acc enter data create (YD%ZOZCL)
  !$acc update device (YD%ZOZCL)
  !$acc enter data attach (YD%ZOZCL)
ENDIF

LRSINC1 = ALLOCATED (YD%RSINC1)
IF (LRSINC1) THEN
  !$acc enter data create (YD%RSINC1)
  !$acc update device (YD%RSINC1)
  !$acc enter data attach (YD%RSINC1)
ENDIF

LRPROC1 = ALLOCATED (YD%RPROC1)
IF (LRPROC1) THEN
  !$acc enter data create (YD%RPROC1)
  !$acc update device (YD%RPROC1)
  !$acc enter data attach (YD%RPROC1)
ENDIF

LRLATCLI = ALLOCATED (YD%RLATCLI)
IF (LRLATCLI) THEN
  !$acc enter data create (YD%RLATCLI)
  !$acc update device (YD%RLATCLI)
  !$acc enter data attach (YD%RLATCLI)
ENDIF

LRLONCLI = ALLOCATED (YD%RLONCLI)
IF (LRLONCLI) THEN
  !$acc enter data create (YD%RLONCLI)
  !$acc update device (YD%RLONCLI)
  !$acc enter data attach (YD%RLONCLI)
ENDIF

LROZT1 = ALLOCATED (YD%ROZT1)
IF (LROZT1) THEN
  !$acc enter data create (YD%ROZT1)
  !$acc update device (YD%ROZT1)
  !$acc enter data attach (YD%ROZT1)
ENDIF

END SUBROUTINE

SUBROUTINE WIPE_TECMIP (YD, LDDELETED)

IMPLICIT NONE
TYPE (TECMIP), INTENT (IN), TARGET :: YD
LOGICAL, OPTIONAL, INTENT (IN) :: LDDELETED
LOGICAL :: LLDELETED
LOGICAL :: LRLATCLI, LRLONCLI, LROZT1, LRPROC1, LRSINC1, LZOZCL










LZOZCL = ALLOCATED (YD%ZOZCL)
IF (LZOZCL) THEN
  !$acc exit data detach (YD%ZOZCL)
  !$acc exit data delete (YD%ZOZCL)
ENDIF

LRSINC1 = ALLOCATED (YD%RSINC1)
IF (LRSINC1) THEN
  !$acc exit data detach (YD%RSINC1)
  !$acc exit data delete (YD%RSINC1)
ENDIF

LRPROC1 = ALLOCATED (YD%RPROC1)
IF (LRPROC1) THEN
  !$acc exit data detach (YD%RPROC1)
  !$acc exit data delete (YD%RPROC1)
ENDIF

LRLATCLI = ALLOCATED (YD%RLATCLI)
IF (LRLATCLI) THEN
  !$acc exit data detach (YD%RLATCLI)
  !$acc exit data delete (YD%RLATCLI)
ENDIF

LRLONCLI = ALLOCATED (YD%RLONCLI)
IF (LRLONCLI) THEN
  !$acc exit data detach (YD%RLONCLI)
  !$acc exit data delete (YD%RLONCLI)
ENDIF

LROZT1 = ALLOCATED (YD%ROZT1)
IF (LROZT1) THEN
  !$acc exit data detach (YD%ROZT1)
  !$acc exit data delete (YD%ROZT1)
ENDIF

LLDELETED = .FALSE.
IF (PRESENT (LDDELETED)) THEN
  LLDELETED = LDDELETED
ENDIF
IF (.NOT. LLDELETED) THEN
  !$acc exit data delete (YD)
ENDIF
END SUBROUTINE



END MODULE
