MODULE UTIL_TRCP_MOD

USE INTDYN_MOD, ONLY : TRCP

INTERFACE SAVE
MODULE PROCEDURE SAVE_TRCP
END INTERFACE

INTERFACE LOAD
MODULE PROCEDURE LOAD_TRCP
END INTERFACE

INTERFACE COPY
MODULE PROCEDURE COPY_TRCP
END INTERFACE

INTERFACE WIPE
MODULE PROCEDURE WIPE_TRCP
END INTERFACE



CONTAINS

SUBROUTINE SAVE_TRCP (KLUN, YD)

IMPLICIT NONE
INTEGER, INTENT (IN) :: KLUN
TYPE (TRCP), INTENT (IN), TARGET :: YD

WRITE (KLUN) YD%M_CP
WRITE (KLUN) YD%M_R
WRITE (KLUN) YD%M_KAP
WRITE (KLUN) YD%NDIM
END SUBROUTINE

SUBROUTINE LOAD_TRCP (KLUN, YD)

IMPLICIT NONE
INTEGER, INTENT (IN) :: KLUN
TYPE (TRCP), INTENT (OUT), TARGET :: YD

READ (KLUN) YD%M_CP
READ (KLUN) YD%M_R
READ (KLUN) YD%M_KAP
READ (KLUN) YD%NDIM
END SUBROUTINE


SUBROUTINE COPY_TRCP (YD, LDCREATED)

IMPLICIT NONE
TYPE (TRCP), INTENT (IN), TARGET :: YD
LOGICAL, OPTIONAL, INTENT (IN) :: LDCREATED
LOGICAL :: LLCREATED

LLCREATED = .FALSE.
IF (PRESENT (LDCREATED)) THEN
  LLCREATED = LDCREATED
ENDIF
IF (.NOT. LLCREATED) THEN
  !$acc enter data create (YD)
  !$acc update device (YD)
ENDIF




END SUBROUTINE

SUBROUTINE WIPE_TRCP (YD, LDDELETED)

IMPLICIT NONE
TYPE (TRCP), INTENT (IN), TARGET :: YD
LOGICAL, OPTIONAL, INTENT (IN) :: LDDELETED
LOGICAL :: LLDELETED





LLDELETED = .FALSE.
IF (PRESENT (LDDELETED)) THEN
  LLDELETED = LDDELETED
ENDIF
IF (.NOT. LLDELETED) THEN
  !$acc exit data delete (YD)
ENDIF
END SUBROUTINE



END MODULE
