MODULE UTIL_TGMVT_MOD

USE INTDYN_MOD, ONLY : TGMVT

INTERFACE SAVE
MODULE PROCEDURE SAVE_TGMVT
END INTERFACE

INTERFACE LOAD
MODULE PROCEDURE LOAD_TGMVT
END INTERFACE

INTERFACE COPY
MODULE PROCEDURE COPY_TGMVT
END INTERFACE

INTERFACE WIPE
MODULE PROCEDURE WIPE_TGMVT
END INTERFACE



CONTAINS

SUBROUTINE SAVE_TGMVT (KLUN, YD)

IMPLICIT NONE
INTEGER, INTENT (IN) :: KLUN
TYPE (TGMVT), INTENT (IN), TARGET :: YD

WRITE (KLUN) YD%M_U
WRITE (KLUN) YD%M_V
WRITE (KLUN) YD%M_T
WRITE (KLUN) YD%M_DIV
WRITE (KLUN) YD%M_SPD
WRITE (KLUN) YD%M_SVD
WRITE (KLUN) YD%NDIM
END SUBROUTINE

SUBROUTINE LOAD_TGMVT (KLUN, YD)

IMPLICIT NONE
INTEGER, INTENT (IN) :: KLUN
TYPE (TGMVT), INTENT (OUT), TARGET :: YD

READ (KLUN) YD%M_U
READ (KLUN) YD%M_V
READ (KLUN) YD%M_T
READ (KLUN) YD%M_DIV
READ (KLUN) YD%M_SPD
READ (KLUN) YD%M_SVD
READ (KLUN) YD%NDIM
END SUBROUTINE


SUBROUTINE COPY_TGMVT (YD, LDCREATED)

IMPLICIT NONE
TYPE (TGMVT), INTENT (IN), TARGET :: YD
LOGICAL, OPTIONAL, INTENT (IN) :: LDCREATED
LOGICAL :: LLCREATED

LLCREATED = .FALSE.
IF (PRESENT (LDCREATED)) THEN
  LLCREATED = LDCREATED
ENDIF
IF (.NOT. LLCREATED) THEN
  !$acc enter data create (YD)
  !$acc update device (YD)
ENDIF







END SUBROUTINE

SUBROUTINE WIPE_TGMVT (YD, LDDELETED)

IMPLICIT NONE
TYPE (TGMVT), INTENT (IN), TARGET :: YD
LOGICAL, OPTIONAL, INTENT (IN) :: LDDELETED
LOGICAL :: LLDELETED








LLDELETED = .FALSE.
IF (PRESENT (LDDELETED)) THEN
  LLDELETED = LDDELETED
ENDIF
IF (.NOT. LLDELETED) THEN
  !$acc exit data delete (YD)
ENDIF
END SUBROUTINE



END MODULE
