MODULE UTIL_TDYN_MOD

USE YOMDYN, ONLY : TDYN

INTERFACE SAVE
MODULE PROCEDURE SAVE_TDYN
END INTERFACE

INTERFACE LOAD
MODULE PROCEDURE LOAD_TDYN
END INTERFACE

INTERFACE COPY
MODULE PROCEDURE COPY_TDYN
END INTERFACE

INTERFACE WIPE
MODULE PROCEDURE WIPE_TDYN
END INTERFACE



CONTAINS

SUBROUTINE SAVE_TDYN (KLUN, YD)

IMPLICIT NONE
INTEGER, INTENT (IN) :: KLUN
TYPE (TDYN), INTENT (IN), TARGET :: YD
LOGICAL :: LRCORDIF, LRCORDIH, LRCORDIT, LRDHI, LRDHS, LRDIDIV, LRDIGFL, LRDIPD, LRDISP, LRDITG
LOGICAL :: LRDIVD, LRDIVOR, LRDSDIV, LRDSVD, LRDSVOR, LRGWFRIC, LRKRF, LRSAVEDP, LSIALPH, LSIALPH_NH
LOGICAL :: LSIB, LSIBI, LSIDELP, LSIDELP_NH, LSIDPHI, LSIDPHI_NH, LSIFAC, LSIFACI, LSIGFL, LSIGFM
LOGICAL :: LSIHEG, LSIHEG2, LSIHEGB, LSIHEGB2, LSILNPR, LSILNPR_NH, LSIMI, LSIMO, LSIRDEL, LSIRDEL_NH
LOGICAL :: LSISKAPI, LSITFL, LSITFM, LSITLAF, LSITLAF_NH, LSITLAH, LSITLAH_NH, LSITRAM, LSIVP, LSIWF2H
LOGICAL :: LSIWH2F, LSLHDA, LSLHDD0, LSLHD_MASK_T, LSLHD_MASK_U
WRITE (KLUN) YD%REPS1
WRITE (KLUN) YD%REPS2
WRITE (KLUN) YD%REPSM1
WRITE (KLUN) YD%REPSM2
WRITE (KLUN) YD%REPSP1
WRITE (KLUN) YD%HDIRVOR
WRITE (KLUN) YD%HDIRDIV
WRITE (KLUN) YD%HDIRT
WRITE (KLUN) YD%HDIRQ
WRITE (KLUN) YD%HDIRO3
WRITE (KLUN) YD%HDIRPD
WRITE (KLUN) YD%HDIRVD
WRITE (KLUN) YD%HDIRSP
WRITE (KLUN) YD%HRDIRVOR
WRITE (KLUN) YD%HRDIRDIV
WRITE (KLUN) YD%HRDIRT
WRITE (KLUN) YD%HRDIRQ
WRITE (KLUN) YD%HRDIRO3
WRITE (KLUN) YD%HRDIRPD
WRITE (KLUN) YD%HRDIRVD
WRITE (KLUN) YD%HRDIRSP
WRITE (KLUN) YD%RRDXTAU
WRITE (KLUN) YD%RDAMPVOR
WRITE (KLUN) YD%RDAMPDIV
WRITE (KLUN) YD%RDAMPT
WRITE (KLUN) YD%RDAMPQ
WRITE (KLUN) YD%RDAMPO3
WRITE (KLUN) YD%RDAMPPD
WRITE (KLUN) YD%RDAMPVD
WRITE (KLUN) YD%RDAMPSP
WRITE (KLUN) YD%LNEWHD
WRITE (KLUN) YD%REXPDH
WRITE (KLUN) YD%FRANDH
WRITE (KLUN) YD%SLEVDH
WRITE (KLUN) YD%SLEVDH1
WRITE (KLUN) YD%SLEVDH2
WRITE (KLUN) YD%SLEVDH3
WRITE (KLUN) YD%NSREFDH
WRITE (KLUN) YD%RATIO_HDI_TOP
WRITE (KLUN) YD%NPROFILEHD
WRITE (KLUN) YD%RPROFHDBT
WRITE (KLUN) YD%RPROFHDTP
WRITE (KLUN) YD%RPROFHDMX
WRITE (KLUN) YD%RPROFHDEX
WRITE (KLUN) YD%LRDISPE_EC
LRDIVOR = ALLOCATED (YD%RDIVOR)
WRITE (KLUN) LRDIVOR
IF (LRDIVOR) THEN
  WRITE (KLUN) LBOUND (YD%RDIVOR)
  WRITE (KLUN) UBOUND (YD%RDIVOR)
  WRITE (KLUN) YD%RDIVOR
ENDIF
LRDIDIV = ALLOCATED (YD%RDIDIV)
WRITE (KLUN) LRDIDIV
IF (LRDIDIV) THEN
  WRITE (KLUN) LBOUND (YD%RDIDIV)
  WRITE (KLUN) UBOUND (YD%RDIDIV)
  WRITE (KLUN) YD%RDIDIV
ENDIF
LRDITG = ALLOCATED (YD%RDITG)
WRITE (KLUN) LRDITG
IF (LRDITG) THEN
  WRITE (KLUN) LBOUND (YD%RDITG)
  WRITE (KLUN) UBOUND (YD%RDITG)
  WRITE (KLUN) YD%RDITG
ENDIF
LRDIGFL = ALLOCATED (YD%RDIGFL)
WRITE (KLUN) LRDIGFL
IF (LRDIGFL) THEN
  WRITE (KLUN) LBOUND (YD%RDIGFL)
  WRITE (KLUN) UBOUND (YD%RDIGFL)
  WRITE (KLUN) YD%RDIGFL
ENDIF
LRDIPD = ALLOCATED (YD%RDIPD)
WRITE (KLUN) LRDIPD
IF (LRDIPD) THEN
  WRITE (KLUN) LBOUND (YD%RDIPD)
  WRITE (KLUN) UBOUND (YD%RDIPD)
  WRITE (KLUN) YD%RDIPD
ENDIF
LRDIVD = ALLOCATED (YD%RDIVD)
WRITE (KLUN) LRDIVD
IF (LRDIVD) THEN
  WRITE (KLUN) LBOUND (YD%RDIVD)
  WRITE (KLUN) UBOUND (YD%RDIVD)
  WRITE (KLUN) YD%RDIVD
ENDIF
LRDISP = ALLOCATED (YD%RDISP)
WRITE (KLUN) LRDISP
IF (LRDISP) THEN
  WRITE (KLUN) LBOUND (YD%RDISP)
  WRITE (KLUN) UBOUND (YD%RDISP)
  WRITE (KLUN) YD%RDISP
ENDIF
LRDHI = ALLOCATED (YD%RDHI)
WRITE (KLUN) LRDHI
IF (LRDHI) THEN
  WRITE (KLUN) LBOUND (YD%RDHI)
  WRITE (KLUN) UBOUND (YD%RDHI)
  WRITE (KLUN) YD%RDHI
ENDIF
WRITE (KLUN) YD%LSTRHD
WRITE (KLUN) YD%HDTIME_STRHD
WRITE (KLUN) YD%KLSPONGE
WRITE (KLUN) YD%LM0DAMP
WRITE (KLUN) YD%RBEGSPONGE
WRITE (KLUN) YD%LTOP_VOR
WRITE (KLUN) YD%NTOP_VOR_TRUNC
WRITE (KLUN) YD%NTOP_VOR_BOT
LRSAVEDP = ALLOCATED (YD%RSAVEDP)
WRITE (KLUN) LRSAVEDP
IF (LRSAVEDP) THEN
  WRITE (KLUN) LBOUND (YD%RSAVEDP)
  WRITE (KLUN) UBOUND (YD%RSAVEDP)
  WRITE (KLUN) YD%RSAVEDP
ENDIF
LSLHDA = ALLOCATED (YD%SLHDA)
WRITE (KLUN) LSLHDA
IF (LSLHDA) THEN
  WRITE (KLUN) LBOUND (YD%SLHDA)
  WRITE (KLUN) UBOUND (YD%SLHDA)
  WRITE (KLUN) YD%SLHDA
ENDIF
WRITE (KLUN) YD%SLHDA0
WRITE (KLUN) YD%SLHDA0T
WRITE (KLUN) YD%SLHDB
WRITE (KLUN) YD%SLHDBT
LSLHDD0 = ALLOCATED (YD%SLHDD0)
WRITE (KLUN) LSLHDD0
IF (LSLHDD0) THEN
  WRITE (KLUN) LBOUND (YD%SLHDD0)
  WRITE (KLUN) UBOUND (YD%SLHDD0)
  WRITE (KLUN) YD%SLHDD0
ENDIF
WRITE (KLUN) YD%SLHDD00
WRITE (KLUN) YD%SLHDD00T
WRITE (KLUN) YD%SLHDDIV
WRITE (KLUN) YD%SLHDRATDDIV
WRITE (KLUN) YD%SLHDHOR
WRITE (KLUN) YD%SLHD_P_LOW
WRITE (KLUN) YD%SLHD_P_HIGH
WRITE (KLUN) YD%LSLHDHEAT
WRITE (KLUN) YD%LSLHDSPONGE
WRITE (KLUN) YD%HDSRVOR
WRITE (KLUN) YD%HDSRDIV
WRITE (KLUN) YD%HDSRVD
WRITE (KLUN) YD%HRDSRVOR
WRITE (KLUN) YD%HRDSRDIV
WRITE (KLUN) YD%HRDSRVD
WRITE (KLUN) YD%RDAMPVORS
WRITE (KLUN) YD%RDAMPDIVS
WRITE (KLUN) YD%RDAMPVDS
WRITE (KLUN) YD%RDAMPHDS
WRITE (KLUN) YD%REXPDHS
WRITE (KLUN) YD%SLEVDHS
WRITE (KLUN) YD%SLEVDHS1
WRITE (KLUN) YD%SLEVDHS2
WRITE (KLUN) YD%SDRED
LRDSVOR = ALLOCATED (YD%RDSVOR)
WRITE (KLUN) LRDSVOR
IF (LRDSVOR) THEN
  WRITE (KLUN) LBOUND (YD%RDSVOR)
  WRITE (KLUN) UBOUND (YD%RDSVOR)
  WRITE (KLUN) YD%RDSVOR
ENDIF
LRDSDIV = ALLOCATED (YD%RDSDIV)
WRITE (KLUN) LRDSDIV
IF (LRDSDIV) THEN
  WRITE (KLUN) LBOUND (YD%RDSDIV)
  WRITE (KLUN) UBOUND (YD%RDSDIV)
  WRITE (KLUN) YD%RDSDIV
ENDIF
LRDSVD = ALLOCATED (YD%RDSVD)
WRITE (KLUN) LRDSVD
IF (LRDSVD) THEN
  WRITE (KLUN) LBOUND (YD%RDSVD)
  WRITE (KLUN) UBOUND (YD%RDSVD)
  WRITE (KLUN) YD%RDSVD
ENDIF
LRDHS = ALLOCATED (YD%RDHS)
WRITE (KLUN) LRDHS
IF (LRDHS) THEN
  WRITE (KLUN) LBOUND (YD%RDHS)
  WRITE (KLUN) UBOUND (YD%RDHS)
  WRITE (KLUN) YD%RDHS
ENDIF
LSLHD_MASK_U = ALLOCATED (YD%SLHD_MASK_U)
WRITE (KLUN) LSLHD_MASK_U
IF (LSLHD_MASK_U) THEN
  WRITE (KLUN) LBOUND (YD%SLHD_MASK_U)
  WRITE (KLUN) UBOUND (YD%SLHD_MASK_U)
  WRITE (KLUN) YD%SLHD_MASK_U
ENDIF
LSLHD_MASK_T = ALLOCATED (YD%SLHD_MASK_T)
WRITE (KLUN) LSLHD_MASK_T
IF (LSLHD_MASK_T) THEN
  WRITE (KLUN) LBOUND (YD%SLHD_MASK_T)
  WRITE (KLUN) UBOUND (YD%SLHD_MASK_T)
  WRITE (KLUN) YD%SLHD_MASK_T
ENDIF
WRITE (KLUN) YD%NLEV_SPONGE
WRITE (KLUN) YD%LRFRIC
WRITE (KLUN) YD%LRFRICISOTR
LRCORDIT = ALLOCATED (YD%RCORDIT)
WRITE (KLUN) LRCORDIT
IF (LRCORDIT) THEN
  WRITE (KLUN) LBOUND (YD%RCORDIT)
  WRITE (KLUN) UBOUND (YD%RCORDIT)
  WRITE (KLUN) YD%RCORDIT
ENDIF
LRCORDIH = ALLOCATED (YD%RCORDIH)
WRITE (KLUN) LRCORDIH
IF (LRCORDIH) THEN
  WRITE (KLUN) LBOUND (YD%RCORDIH)
  WRITE (KLUN) UBOUND (YD%RCORDIH)
  WRITE (KLUN) YD%RCORDIH
ENDIF
LRCORDIF = ALLOCATED (YD%RCORDIF)
WRITE (KLUN) LRCORDIF
IF (LRCORDIF) THEN
  WRITE (KLUN) LBOUND (YD%RCORDIF)
  WRITE (KLUN) UBOUND (YD%RCORDIF)
  WRITE (KLUN) YD%RCORDIF
ENDIF
WRITE (KLUN) YD%VMAX1
WRITE (KLUN) YD%VMAX2
WRITE (KLUN) YD%RMAX_D3
WRITE (KLUN) YD%LBOUND_D3
LRKRF = ALLOCATED (YD%RKRF)
WRITE (KLUN) LRKRF
IF (LRKRF) THEN
  WRITE (KLUN) LBOUND (YD%RKRF)
  WRITE (KLUN) UBOUND (YD%RKRF)
  WRITE (KLUN) YD%RKRF
ENDIF
WRITE (KLUN) YD%NMAXLEVRF
WRITE (KLUN) YD%RRFZ1
WRITE (KLUN) YD%RRFPLM
WRITE (KLUN) YD%RRFTAU
WRITE (KLUN) YD%RTEMRB
WRITE (KLUN) YD%NRUBC
WRITE (KLUN) YD%LGWFRIC
WRITE (KLUN) YD%NLEV_GWFRIC
WRITE (KLUN) YD%RGWFRIC_MAX
WRITE (KLUN) YD%RGWFRIC_PLM
LRGWFRIC = ALLOCATED (YD%RGWFRIC)
WRITE (KLUN) LRGWFRIC
IF (LRGWFRIC) THEN
  WRITE (KLUN) LBOUND (YD%RGWFRIC)
  WRITE (KLUN) UBOUND (YD%RGWFRIC)
  WRITE (KLUN) YD%RGWFRIC
ENDIF
WRITE (KLUN) YD%LSIDG
WRITE (KLUN) YD%LDYN_STABAN
WRITE (KLUN) YD%LRHDI_LASTITERPC
WRITE (KLUN) YD%LREFINE_SILAPL
WRITE (KLUN) YD%BETADT
WRITE (KLUN) YD%RBT
WRITE (KLUN) YD%RBTS2
WRITE (KLUN) YD%REFGEO
WRITE (KLUN) YD%SIPR
WRITE (KLUN) YD%SIPRA
WRITE (KLUN) YD%SITR
WRITE (KLUN) YD%SITRA
WRITE (KLUN) YD%SISLP
WRITE (KLUN) YD%SITRUB
WRITE (KLUN) YD%SIPRUB
WRITE (KLUN) YD%SITIME
WRITE (KLUN) YD%SIRPRG
WRITE (KLUN) YD%SIRPRN
WRITE (KLUN) YD%NSITER
WRITE (KLUN) YD%NCURRENT_ITER
WRITE (KLUN) YD%NITERHELM
WRITE (KLUN) YD%NOPT_SITRA
WRITE (KLUN) YD%NOPT_SIPRA
WRITE (KLUN) YD%NOPT_SISLP
LSIALPH = ALLOCATED (YD%SIALPH)
WRITE (KLUN) LSIALPH
IF (LSIALPH) THEN
  WRITE (KLUN) LBOUND (YD%SIALPH)
  WRITE (KLUN) UBOUND (YD%SIALPH)
  WRITE (KLUN) YD%SIALPH
ENDIF
LSILNPR = ALLOCATED (YD%SILNPR)
WRITE (KLUN) LSILNPR
IF (LSILNPR) THEN
  WRITE (KLUN) LBOUND (YD%SILNPR)
  WRITE (KLUN) UBOUND (YD%SILNPR)
  WRITE (KLUN) YD%SILNPR
ENDIF
LSIDELP = ALLOCATED (YD%SIDELP)
WRITE (KLUN) LSIDELP
IF (LSIDELP) THEN
  WRITE (KLUN) LBOUND (YD%SIDELP)
  WRITE (KLUN) UBOUND (YD%SIDELP)
  WRITE (KLUN) YD%SIDELP
ENDIF
LSIRDEL = ALLOCATED (YD%SIRDEL)
WRITE (KLUN) LSIRDEL
IF (LSIRDEL) THEN
  WRITE (KLUN) LBOUND (YD%SIRDEL)
  WRITE (KLUN) UBOUND (YD%SIRDEL)
  WRITE (KLUN) YD%SIRDEL
ENDIF
LSITLAH = ALLOCATED (YD%SITLAH)
WRITE (KLUN) LSITLAH
IF (LSITLAH) THEN
  WRITE (KLUN) LBOUND (YD%SITLAH)
  WRITE (KLUN) UBOUND (YD%SITLAH)
  WRITE (KLUN) YD%SITLAH
ENDIF
LSITLAF = ALLOCATED (YD%SITLAF)
WRITE (KLUN) LSITLAF
IF (LSITLAF) THEN
  WRITE (KLUN) LBOUND (YD%SITLAF)
  WRITE (KLUN) UBOUND (YD%SITLAF)
  WRITE (KLUN) YD%SITLAF
ENDIF
LSIDPHI = ALLOCATED (YD%SIDPHI)
WRITE (KLUN) LSIDPHI
IF (LSIDPHI) THEN
  WRITE (KLUN) LBOUND (YD%SIDPHI)
  WRITE (KLUN) UBOUND (YD%SIDPHI)
  WRITE (KLUN) YD%SIDPHI
ENDIF
LSIALPH_NH = ALLOCATED (YD%SIALPH_NH)
WRITE (KLUN) LSIALPH_NH
IF (LSIALPH_NH) THEN
  WRITE (KLUN) LBOUND (YD%SIALPH_NH)
  WRITE (KLUN) UBOUND (YD%SIALPH_NH)
  WRITE (KLUN) YD%SIALPH_NH
ENDIF
LSILNPR_NH = ALLOCATED (YD%SILNPR_NH)
WRITE (KLUN) LSILNPR_NH
IF (LSILNPR_NH) THEN
  WRITE (KLUN) LBOUND (YD%SILNPR_NH)
  WRITE (KLUN) UBOUND (YD%SILNPR_NH)
  WRITE (KLUN) YD%SILNPR_NH
ENDIF
LSIDELP_NH = ALLOCATED (YD%SIDELP_NH)
WRITE (KLUN) LSIDELP_NH
IF (LSIDELP_NH) THEN
  WRITE (KLUN) LBOUND (YD%SIDELP_NH)
  WRITE (KLUN) UBOUND (YD%SIDELP_NH)
  WRITE (KLUN) YD%SIDELP_NH
ENDIF
LSIRDEL_NH = ALLOCATED (YD%SIRDEL_NH)
WRITE (KLUN) LSIRDEL_NH
IF (LSIRDEL_NH) THEN
  WRITE (KLUN) LBOUND (YD%SIRDEL_NH)
  WRITE (KLUN) UBOUND (YD%SIRDEL_NH)
  WRITE (KLUN) YD%SIRDEL_NH
ENDIF
LSITLAH_NH = ALLOCATED (YD%SITLAH_NH)
WRITE (KLUN) LSITLAH_NH
IF (LSITLAH_NH) THEN
  WRITE (KLUN) LBOUND (YD%SITLAH_NH)
  WRITE (KLUN) UBOUND (YD%SITLAH_NH)
  WRITE (KLUN) YD%SITLAH_NH
ENDIF
LSITLAF_NH = ALLOCATED (YD%SITLAF_NH)
WRITE (KLUN) LSITLAF_NH
IF (LSITLAF_NH) THEN
  WRITE (KLUN) LBOUND (YD%SITLAF_NH)
  WRITE (KLUN) UBOUND (YD%SITLAF_NH)
  WRITE (KLUN) YD%SITLAF_NH
ENDIF
LSIDPHI_NH = ALLOCATED (YD%SIDPHI_NH)
WRITE (KLUN) LSIDPHI_NH
IF (LSIDPHI_NH) THEN
  WRITE (KLUN) LBOUND (YD%SIDPHI_NH)
  WRITE (KLUN) UBOUND (YD%SIDPHI_NH)
  WRITE (KLUN) YD%SIDPHI_NH
ENDIF
LSIWF2H = ALLOCATED (YD%SIWF2H)
WRITE (KLUN) LSIWF2H
IF (LSIWF2H) THEN
  WRITE (KLUN) LBOUND (YD%SIWF2H)
  WRITE (KLUN) UBOUND (YD%SIWF2H)
  WRITE (KLUN) YD%SIWF2H
ENDIF
LSIWH2F = ALLOCATED (YD%SIWH2F)
WRITE (KLUN) LSIWH2F
IF (LSIWH2F) THEN
  WRITE (KLUN) LBOUND (YD%SIWH2F)
  WRITE (KLUN) UBOUND (YD%SIWH2F)
  WRITE (KLUN) YD%SIWH2F
ENDIF
LSIGFL = ALLOCATED (YD%SIGFL)
WRITE (KLUN) LSIGFL
IF (LSIGFL) THEN
  WRITE (KLUN) LBOUND (YD%SIGFL)
  WRITE (KLUN) UBOUND (YD%SIGFL)
  WRITE (KLUN) YD%SIGFL
ENDIF
LSIGFM = ALLOCATED (YD%SIGFM)
WRITE (KLUN) LSIGFM
IF (LSIGFM) THEN
  WRITE (KLUN) LBOUND (YD%SIGFM)
  WRITE (KLUN) UBOUND (YD%SIGFM)
  WRITE (KLUN) YD%SIGFM
ENDIF
LSITFL = ALLOCATED (YD%SITFL)
WRITE (KLUN) LSITFL
IF (LSITFL) THEN
  WRITE (KLUN) LBOUND (YD%SITFL)
  WRITE (KLUN) UBOUND (YD%SITFL)
  WRITE (KLUN) YD%SITFL
ENDIF
LSITFM = ALLOCATED (YD%SITFM)
WRITE (KLUN) LSITFM
IF (LSITFM) THEN
  WRITE (KLUN) LBOUND (YD%SITFM)
  WRITE (KLUN) UBOUND (YD%SITFM)
  WRITE (KLUN) YD%SITFM
ENDIF
LSIB = ALLOCATED (YD%SIB)
WRITE (KLUN) LSIB
IF (LSIB) THEN
  WRITE (KLUN) LBOUND (YD%SIB)
  WRITE (KLUN) UBOUND (YD%SIB)
  WRITE (KLUN) YD%SIB
ENDIF
LSIMO = ALLOCATED (YD%SIMO)
WRITE (KLUN) LSIMO
IF (LSIMO) THEN
  WRITE (KLUN) LBOUND (YD%SIMO)
  WRITE (KLUN) UBOUND (YD%SIMO)
  WRITE (KLUN) YD%SIMO
ENDIF
LSIMI = ALLOCATED (YD%SIMI)
WRITE (KLUN) LSIMI
IF (LSIMI) THEN
  WRITE (KLUN) LBOUND (YD%SIMI)
  WRITE (KLUN) UBOUND (YD%SIMI)
  WRITE (KLUN) YD%SIMI
ENDIF
LSIVP = ALLOCATED (YD%SIVP)
WRITE (KLUN) LSIVP
IF (LSIVP) THEN
  WRITE (KLUN) LBOUND (YD%SIVP)
  WRITE (KLUN) UBOUND (YD%SIVP)
  WRITE (KLUN) YD%SIVP
ENDIF
LSIHEG = ALLOCATED (YD%SIHEG)
WRITE (KLUN) LSIHEG
IF (LSIHEG) THEN
  WRITE (KLUN) LBOUND (YD%SIHEG)
  WRITE (KLUN) UBOUND (YD%SIHEG)
  WRITE (KLUN) YD%SIHEG
ENDIF
LSIHEG2 = ALLOCATED (YD%SIHEG2)
WRITE (KLUN) LSIHEG2
IF (LSIHEG2) THEN
  WRITE (KLUN) LBOUND (YD%SIHEG2)
  WRITE (KLUN) UBOUND (YD%SIHEG2)
  WRITE (KLUN) YD%SIHEG2
ENDIF
LSIHEGB = ALLOCATED (YD%SIHEGB)
WRITE (KLUN) LSIHEGB
IF (LSIHEGB) THEN
  WRITE (KLUN) LBOUND (YD%SIHEGB)
  WRITE (KLUN) UBOUND (YD%SIHEGB)
  WRITE (KLUN) YD%SIHEGB
ENDIF
LSIHEGB2 = ALLOCATED (YD%SIHEGB2)
WRITE (KLUN) LSIHEGB2
IF (LSIHEGB2) THEN
  WRITE (KLUN) LBOUND (YD%SIHEGB2)
  WRITE (KLUN) UBOUND (YD%SIHEGB2)
  WRITE (KLUN) YD%SIHEGB2
ENDIF
LSIFAC = ALLOCATED (YD%SIFAC)
WRITE (KLUN) LSIFAC
IF (LSIFAC) THEN
  WRITE (KLUN) LBOUND (YD%SIFAC)
  WRITE (KLUN) UBOUND (YD%SIFAC)
  WRITE (KLUN) YD%SIFAC
ENDIF
LSIFACI = ALLOCATED (YD%SIFACI)
WRITE (KLUN) LSIFACI
IF (LSIFACI) THEN
  WRITE (KLUN) LBOUND (YD%SIFACI)
  WRITE (KLUN) UBOUND (YD%SIFACI)
  WRITE (KLUN) YD%SIFACI
ENDIF
LSISKAPI = ALLOCATED (YD%SISKAPI)
WRITE (KLUN) LSISKAPI
IF (LSISKAPI) THEN
  WRITE (KLUN) LBOUND (YD%SISKAPI)
  WRITE (KLUN) UBOUND (YD%SISKAPI)
  WRITE (KLUN) YD%SISKAPI
ENDIF
LSITRAM = ALLOCATED (YD%SITRAM)
WRITE (KLUN) LSITRAM
IF (LSITRAM) THEN
  WRITE (KLUN) LBOUND (YD%SITRAM)
  WRITE (KLUN) UBOUND (YD%SITRAM)
  WRITE (KLUN) YD%SITRAM
ENDIF
WRITE (KLUN) YD%VNORM
WRITE (KLUN) YD%SLOPE_MAX
WRITE (KLUN) YD%PSURF_MIN
WRITE (KLUN) YD%NVLAG
WRITE (KLUN) YD%NWLAG
WRITE (KLUN) YD%NTLAG
WRITE (KLUN) YD%NSPDLAG
WRITE (KLUN) YD%NSVDLAG
WRITE (KLUN) YD%NSPLTHOI
WRITE (KLUN) YD%LSPLTHOIGFL
WRITE (KLUN) YD%NSLDIMK
WRITE (KLUN) YD%NITMP
WRITE (KLUN) YD%VETAON
WRITE (KLUN) YD%VETAOX
WRITE (KLUN) YD%LSETTLSVF
WRITE (KLUN) YD%LSETFSTAT
WRITE (KLUN) YD%LSETTLSVF_DIFF
WRITE (KLUN) YD%RW2TLFF
WRITE (KLUN) YD%RALPHA
WRITE (KLUN) YD%RALPHA_TOP
WRITE (KLUN) YD%NLEV_ZALPHA
WRITE (KLUN) YD%NEDER
WRITE (KLUN) YD%LWENOBC
WRITE (KLUN) YD%NQMHOISLT
WRITE (KLUN) YD%LSLDP_RK
WRITE (KLUN) YD%LSLDP_CURV
WRITE (KLUN) YD%LRHS_CURV
WRITE (KLUN) YD%LSLDP_XYZ
WRITE (KLUN) YD%LSLDP_SAVE
WRITE (KLUN) YD%VESL
WRITE (KLUN) YD%XIDT
WRITE (KLUN) YD%LQMW
WRITE (KLUN) YD%LQMHW
WRITE (KLUN) YD%LQMT
WRITE (KLUN) YD%LQMHT
WRITE (KLUN) YD%LQMP
WRITE (KLUN) YD%LQMHP
WRITE (KLUN) YD%LQMPD
WRITE (KLUN) YD%LQMHPD
WRITE (KLUN) YD%LQMVD
WRITE (KLUN) YD%LQMHVD
WRITE (KLUN) YD%LVWENO_W
WRITE (KLUN) YD%LVWENO_T
WRITE (KLUN) YD%LVWENO_SP
WRITE (KLUN) YD%LVWENO_SPD
WRITE (KLUN) YD%LVWENO_SVD
WRITE (KLUN) YD%WENO_ALPHA_W
WRITE (KLUN) YD%WENO_ALPHA_T
WRITE (KLUN) YD%WENO_ALPHA_SP
WRITE (KLUN) YD%WENO_ALPHA_SPD
WRITE (KLUN) YD%WENO_ALPHA_SVD
WRITE (KLUN) YD%LADVF
WRITE (KLUN) YD%LIMPF
WRITE (KLUN) YD%L2TLFF
WRITE (KLUN) YD%RCMSLP0
WRITE (KLUN) YD%NCOMP_CVGQ
WRITE (KLUN) YD%LSVTSM
WRITE (KLUN) YD%RPRES_SVTSM
WRITE (KLUN) YD%RPRES_SETTLSVF
WRITE (KLUN) YD%NFLEVSF
WRITE (KLUN) YD%RSCALE
WRITE (KLUN) YD%RSCALEOFF
WRITE (KLUN) YD%RINTOPT
WRITE (KLUN) YD%RRINTOPT
WRITE (KLUN) YD%LHDIFFM
WRITE (KLUN) YD%LSPECVIS
WRITE (KLUN) YD%NDIFFACT
WRITE (KLUN) YD%LGPSTRESS
WRITE (KLUN) YD%RCLSTRESS
WRITE (KLUN) YD%RCLPOLE
WRITE (KLUN) YD%NVSEPC
WRITE (KLUN) YD%NVSEPL
WRITE (KLUN) YD%LFINDVSEP
WRITE (KLUN) YD%LMASCOR
WRITE (KLUN) YD%LMASDRY
WRITE (KLUN) YD%LGPMASCOR
WRITE (KLUN) YD%NGPMASCOR
WRITE (KLUN) YD%GPMASSI
WRITE (KLUN) YD%GMASSI
WRITE (KLUN) YD%GMASS0
WRITE (KLUN) YD%GMASSINC
WRITE (KLUN) YD%LNODRYFLX
LSIBI = ALLOCATED (YD%SIBI)
WRITE (KLUN) LSIBI
IF (LSIBI) THEN
  WRITE (KLUN) LBOUND (YD%SIBI)
  WRITE (KLUN) UBOUND (YD%SIBI)
  WRITE (KLUN) YD%SIBI
ENDIF
END SUBROUTINE

SUBROUTINE LOAD_TDYN (KLUN, YD)
USE PARKIND1, ONLY : JPRD

IMPLICIT NONE
INTEGER, INTENT (IN) :: KLUN
TYPE (TDYN), INTENT (OUT), TARGET :: YD
INTEGER :: IL1(1), IU1(1), IL2(2), IU2(2), IL3(3), IU3(3), IL4(4), IU4(4)
LOGICAL :: LRCORDIF, LRCORDIH, LRCORDIT, LRDHI, LRDHS, LRDIDIV, LRDIGFL, LRDIPD, LRDISP, LRDITG
LOGICAL :: LRDIVD, LRDIVOR, LRDSDIV, LRDSVD, LRDSVOR, LRGWFRIC, LRKRF, LRSAVEDP, LSIALPH, LSIALPH_NH
LOGICAL :: LSIB, LSIBI, LSIDELP, LSIDELP_NH, LSIDPHI, LSIDPHI_NH, LSIFAC, LSIFACI, LSIGFL, LSIGFM
LOGICAL :: LSIHEG, LSIHEG2, LSIHEGB, LSIHEGB2, LSILNPR, LSILNPR_NH, LSIMI, LSIMO, LSIRDEL, LSIRDEL_NH
LOGICAL :: LSISKAPI, LSITFL, LSITFM, LSITLAF, LSITLAF_NH, LSITLAH, LSITLAH_NH, LSITRAM, LSIVP, LSIWF2H
LOGICAL :: LSIWH2F, LSLHDA, LSLHDD0, LSLHD_MASK_T, LSLHD_MASK_U
REAL(KIND=JPRD) :: ZTMP0
REAL(KIND=JPRD), ALLOCATABLE :: ZTMP1 (:)
REAL(KIND=JPRD), ALLOCATABLE :: ZTMP2 (:,:)
REAL(KIND=JPRD), ALLOCATABLE :: ZTMP3 (:,:,:)
REAL(KIND=JPRD), ALLOCATABLE :: ZTMP4 (:,:,:,:)
READ (KLUN) ZTMP0
YD%REPS1 = ZTMP0
READ (KLUN) ZTMP0
YD%REPS2 = ZTMP0
READ (KLUN) ZTMP0
YD%REPSM1 = ZTMP0
READ (KLUN) ZTMP0
YD%REPSM2 = ZTMP0
READ (KLUN) ZTMP0
YD%REPSP1 = ZTMP0
READ (KLUN) ZTMP0
YD%HDIRVOR = ZTMP0
READ (KLUN) ZTMP0
YD%HDIRDIV = ZTMP0
READ (KLUN) ZTMP0
YD%HDIRT = ZTMP0
READ (KLUN) ZTMP0
YD%HDIRQ = ZTMP0
READ (KLUN) ZTMP0
YD%HDIRO3 = ZTMP0
READ (KLUN) ZTMP0
YD%HDIRPD = ZTMP0
READ (KLUN) ZTMP0
YD%HDIRVD = ZTMP0
READ (KLUN) ZTMP0
YD%HDIRSP = ZTMP0
READ (KLUN) ZTMP0
YD%HRDIRVOR = ZTMP0
READ (KLUN) ZTMP0
YD%HRDIRDIV = ZTMP0
READ (KLUN) ZTMP0
YD%HRDIRT = ZTMP0
READ (KLUN) ZTMP0
YD%HRDIRQ = ZTMP0
READ (KLUN) ZTMP0
YD%HRDIRO3 = ZTMP0
READ (KLUN) ZTMP0
YD%HRDIRPD = ZTMP0
READ (KLUN) ZTMP0
YD%HRDIRVD = ZTMP0
READ (KLUN) ZTMP0
YD%HRDIRSP = ZTMP0
READ (KLUN) ZTMP0
YD%RRDXTAU = ZTMP0
READ (KLUN) ZTMP0
YD%RDAMPVOR = ZTMP0
READ (KLUN) ZTMP0
YD%RDAMPDIV = ZTMP0
READ (KLUN) ZTMP0
YD%RDAMPT = ZTMP0
READ (KLUN) ZTMP0
YD%RDAMPQ = ZTMP0
READ (KLUN) ZTMP0
YD%RDAMPO3 = ZTMP0
READ (KLUN) ZTMP0
YD%RDAMPPD = ZTMP0
READ (KLUN) ZTMP0
YD%RDAMPVD = ZTMP0
READ (KLUN) ZTMP0
YD%RDAMPSP = ZTMP0
READ (KLUN) YD%LNEWHD
READ (KLUN) ZTMP0
YD%REXPDH = ZTMP0
READ (KLUN) ZTMP0
YD%FRANDH = ZTMP0
READ (KLUN) ZTMP0
YD%SLEVDH = ZTMP0
READ (KLUN) ZTMP0
YD%SLEVDH1 = ZTMP0
READ (KLUN) ZTMP0
YD%SLEVDH2 = ZTMP0
READ (KLUN) ZTMP0
YD%SLEVDH3 = ZTMP0
READ (KLUN) YD%NSREFDH
READ (KLUN) ZTMP0
YD%RATIO_HDI_TOP = ZTMP0
READ (KLUN) YD%NPROFILEHD
READ (KLUN) ZTMP0
YD%RPROFHDBT = ZTMP0
READ (KLUN) ZTMP0
YD%RPROFHDTP = ZTMP0
READ (KLUN) ZTMP0
YD%RPROFHDMX = ZTMP0
READ (KLUN) ZTMP0
YD%RPROFHDEX = ZTMP0
READ (KLUN) YD%LRDISPE_EC
READ (KLUN) LRDIVOR
IF (LRDIVOR) THEN
  READ (KLUN) IL2
  READ (KLUN) IU2
  ALLOCATE (YD%RDIVOR (IL2(1):IU2(1), IL2(2):IU2(2)))
  ALLOCATE (ZTMP2(LBOUND(YD%RDIVOR,1):UBOUND(YD%RDIVOR,1), LBOUND(YD%RDIVOR,2):UBOUND(YD%RDIVOR,2)))
  READ (KLUN) ZTMP2
  YD%RDIVOR = ZTMP2
  DEALLOCATE (ZTMP2)
ENDIF
READ (KLUN) LRDIDIV
IF (LRDIDIV) THEN
  READ (KLUN) IL2
  READ (KLUN) IU2
  ALLOCATE (YD%RDIDIV (IL2(1):IU2(1), IL2(2):IU2(2)))
  ALLOCATE (ZTMP2(LBOUND(YD%RDIDIV,1):UBOUND(YD%RDIDIV,1), LBOUND(YD%RDIDIV,2):UBOUND(YD%RDIDIV,2)))
  READ (KLUN) ZTMP2
  YD%RDIDIV = ZTMP2
  DEALLOCATE (ZTMP2)
ENDIF
READ (KLUN) LRDITG
IF (LRDITG) THEN
  READ (KLUN) IL2
  READ (KLUN) IU2
  ALLOCATE (YD%RDITG (IL2(1):IU2(1), IL2(2):IU2(2)))
  ALLOCATE (ZTMP2(LBOUND(YD%RDITG,1):UBOUND(YD%RDITG,1), LBOUND(YD%RDITG,2):UBOUND(YD%RDITG,2)))
  READ (KLUN) ZTMP2
  YD%RDITG = ZTMP2
  DEALLOCATE (ZTMP2)
ENDIF
READ (KLUN) LRDIGFL
IF (LRDIGFL) THEN
  READ (KLUN) IL3
  READ (KLUN) IU3
  ALLOCATE (YD%RDIGFL (IL3(1):IU3(1), IL3(2):IU3(2), IL3(3):IU3(3)))
  ALLOCATE (ZTMP3(LBOUND(YD%RDIGFL,1):UBOUND(YD%RDIGFL,1), LBOUND(YD%RDIGFL,2):UBOUND(YD%RDIGFL,2), LBOUND(YD%RDIGFL,3):UBOUND(YD%RDIGFL,3)))
  READ (KLUN) ZTMP3
  YD%RDIGFL = ZTMP3
  DEALLOCATE (ZTMP3)
ENDIF
READ (KLUN) LRDIPD
IF (LRDIPD) THEN
  READ (KLUN) IL2
  READ (KLUN) IU2
  ALLOCATE (YD%RDIPD (IL2(1):IU2(1), IL2(2):IU2(2)))
  ALLOCATE (ZTMP2(LBOUND(YD%RDIPD,1):UBOUND(YD%RDIPD,1), LBOUND(YD%RDIPD,2):UBOUND(YD%RDIPD,2)))
  READ (KLUN) ZTMP2
  YD%RDIPD = ZTMP2
  DEALLOCATE (ZTMP2)
ENDIF
READ (KLUN) LRDIVD
IF (LRDIVD) THEN
  READ (KLUN) IL2
  READ (KLUN) IU2
  ALLOCATE (YD%RDIVD (IL2(1):IU2(1), IL2(2):IU2(2)))
  ALLOCATE (ZTMP2(LBOUND(YD%RDIVD,1):UBOUND(YD%RDIVD,1), LBOUND(YD%RDIVD,2):UBOUND(YD%RDIVD,2)))
  READ (KLUN) ZTMP2
  YD%RDIVD = ZTMP2
  DEALLOCATE (ZTMP2)
ENDIF
READ (KLUN) LRDISP
IF (LRDISP) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (YD%RDISP (IL1(1):IU1(1)))
  ALLOCATE (ZTMP1(LBOUND(YD%RDISP,1):UBOUND(YD%RDISP,1)))
  READ (KLUN) ZTMP1
  YD%RDISP = ZTMP1
  DEALLOCATE (ZTMP1)
ENDIF
READ (KLUN) LRDHI
IF (LRDHI) THEN
  READ (KLUN) IL3
  READ (KLUN) IU3
  ALLOCATE (YD%RDHI (IL3(1):IU3(1), IL3(2):IU3(2), IL3(3):IU3(3)))
  ALLOCATE (ZTMP3(LBOUND(YD%RDHI,1):UBOUND(YD%RDHI,1), LBOUND(YD%RDHI,2):UBOUND(YD%RDHI,2), LBOUND(YD%RDHI,3):UBOUND(YD%RDHI,3)))
  READ (KLUN) ZTMP3
  YD%RDHI = ZTMP3
  DEALLOCATE (ZTMP3)
ENDIF
READ (KLUN) YD%LSTRHD
READ (KLUN) ZTMP0
YD%HDTIME_STRHD = ZTMP0
READ (KLUN) ZTMP0
YD%KLSPONGE = ZTMP0
READ (KLUN) YD%LM0DAMP
READ (KLUN) ZTMP0
YD%RBEGSPONGE = ZTMP0
READ (KLUN) YD%LTOP_VOR
READ (KLUN) YD%NTOP_VOR_TRUNC
READ (KLUN) YD%NTOP_VOR_BOT
READ (KLUN) LRSAVEDP
IF (LRSAVEDP) THEN
  READ (KLUN) IL4
  READ (KLUN) IU4
  ALLOCATE (YD%RSAVEDP (IL4(1):IU4(1), IL4(2):IU4(2), IL4(3):IU4(3), IL4(4):IU4(4)))
  ALLOCATE (ZTMP4(LBOUND(YD%RSAVEDP,1):UBOUND(YD%RSAVEDP,1), LBOUND(YD%RSAVEDP,2):UBOUND(YD%RSAVEDP,2), LBOUND(YD%RSAVEDP,3):UBOUND(YD%RSAVEDP,3), LBOUND(YD%RSAVEDP,4):UBOUND(YD%RSAVEDP,4)))
  READ (KLUN) ZTMP4
  YD%RSAVEDP = ZTMP4
  DEALLOCATE (ZTMP4)
ENDIF
READ (KLUN) LSLHDA
IF (LSLHDA) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (YD%SLHDA (IL1(1):IU1(1)))
  ALLOCATE (ZTMP1(LBOUND(YD%SLHDA,1):UBOUND(YD%SLHDA,1)))
  READ (KLUN) ZTMP1
  YD%SLHDA = ZTMP1
  DEALLOCATE (ZTMP1)
ENDIF
READ (KLUN) ZTMP0
YD%SLHDA0 = ZTMP0
READ (KLUN) ZTMP0
YD%SLHDA0T = ZTMP0
READ (KLUN) ZTMP0
YD%SLHDB = ZTMP0
READ (KLUN) ZTMP0
YD%SLHDBT = ZTMP0
READ (KLUN) LSLHDD0
IF (LSLHDD0) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (YD%SLHDD0 (IL1(1):IU1(1)))
  ALLOCATE (ZTMP1(LBOUND(YD%SLHDD0,1):UBOUND(YD%SLHDD0,1)))
  READ (KLUN) ZTMP1
  YD%SLHDD0 = ZTMP1
  DEALLOCATE (ZTMP1)
ENDIF
READ (KLUN) ZTMP0
YD%SLHDD00 = ZTMP0
READ (KLUN) ZTMP0
YD%SLHDD00T = ZTMP0
READ (KLUN) ZTMP0
YD%SLHDDIV = ZTMP0
READ (KLUN) ZTMP0
YD%SLHDRATDDIV = ZTMP0
READ (KLUN) ZTMP0
YD%SLHDHOR = ZTMP0
READ (KLUN) ZTMP0
YD%SLHD_P_LOW = ZTMP0
READ (KLUN) ZTMP0
YD%SLHD_P_HIGH = ZTMP0
READ (KLUN) YD%LSLHDHEAT
READ (KLUN) YD%LSLHDSPONGE
READ (KLUN) ZTMP0
YD%HDSRVOR = ZTMP0
READ (KLUN) ZTMP0
YD%HDSRDIV = ZTMP0
READ (KLUN) ZTMP0
YD%HDSRVD = ZTMP0
READ (KLUN) ZTMP0
YD%HRDSRVOR = ZTMP0
READ (KLUN) ZTMP0
YD%HRDSRDIV = ZTMP0
READ (KLUN) ZTMP0
YD%HRDSRVD = ZTMP0
READ (KLUN) ZTMP0
YD%RDAMPVORS = ZTMP0
READ (KLUN) ZTMP0
YD%RDAMPDIVS = ZTMP0
READ (KLUN) ZTMP0
YD%RDAMPVDS = ZTMP0
READ (KLUN) ZTMP0
YD%RDAMPHDS = ZTMP0
READ (KLUN) ZTMP0
YD%REXPDHS = ZTMP0
READ (KLUN) ZTMP0
YD%SLEVDHS = ZTMP0
READ (KLUN) ZTMP0
YD%SLEVDHS1 = ZTMP0
READ (KLUN) ZTMP0
YD%SLEVDHS2 = ZTMP0
READ (KLUN) ZTMP0
YD%SDRED = ZTMP0
READ (KLUN) LRDSVOR
IF (LRDSVOR) THEN
  READ (KLUN) IL2
  READ (KLUN) IU2
  ALLOCATE (YD%RDSVOR (IL2(1):IU2(1), IL2(2):IU2(2)))
  ALLOCATE (ZTMP2(LBOUND(YD%RDSVOR,1):UBOUND(YD%RDSVOR,1), LBOUND(YD%RDSVOR,2):UBOUND(YD%RDSVOR,2)))
  READ (KLUN) ZTMP2
  YD%RDSVOR = ZTMP2
  DEALLOCATE (ZTMP2)
ENDIF
READ (KLUN) LRDSDIV
IF (LRDSDIV) THEN
  READ (KLUN) IL2
  READ (KLUN) IU2
  ALLOCATE (YD%RDSDIV (IL2(1):IU2(1), IL2(2):IU2(2)))
  ALLOCATE (ZTMP2(LBOUND(YD%RDSDIV,1):UBOUND(YD%RDSDIV,1), LBOUND(YD%RDSDIV,2):UBOUND(YD%RDSDIV,2)))
  READ (KLUN) ZTMP2
  YD%RDSDIV = ZTMP2
  DEALLOCATE (ZTMP2)
ENDIF
READ (KLUN) LRDSVD
IF (LRDSVD) THEN
  READ (KLUN) IL2
  READ (KLUN) IU2
  ALLOCATE (YD%RDSVD (IL2(1):IU2(1), IL2(2):IU2(2)))
  ALLOCATE (ZTMP2(LBOUND(YD%RDSVD,1):UBOUND(YD%RDSVD,1), LBOUND(YD%RDSVD,2):UBOUND(YD%RDSVD,2)))
  READ (KLUN) ZTMP2
  YD%RDSVD = ZTMP2
  DEALLOCATE (ZTMP2)
ENDIF
READ (KLUN) LRDHS
IF (LRDHS) THEN
  READ (KLUN) IL3
  READ (KLUN) IU3
  ALLOCATE (YD%RDHS (IL3(1):IU3(1), IL3(2):IU3(2), IL3(3):IU3(3)))
  ALLOCATE (ZTMP3(LBOUND(YD%RDHS,1):UBOUND(YD%RDHS,1), LBOUND(YD%RDHS,2):UBOUND(YD%RDHS,2), LBOUND(YD%RDHS,3):UBOUND(YD%RDHS,3)))
  READ (KLUN) ZTMP3
  YD%RDHS = ZTMP3
  DEALLOCATE (ZTMP3)
ENDIF
READ (KLUN) LSLHD_MASK_U
IF (LSLHD_MASK_U) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (YD%SLHD_MASK_U (IL1(1):IU1(1)))
  ALLOCATE (ZTMP1(LBOUND(YD%SLHD_MASK_U,1):UBOUND(YD%SLHD_MASK_U,1)))
  READ (KLUN) ZTMP1
  YD%SLHD_MASK_U = ZTMP1
  DEALLOCATE (ZTMP1)
ENDIF
READ (KLUN) LSLHD_MASK_T
IF (LSLHD_MASK_T) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (YD%SLHD_MASK_T (IL1(1):IU1(1)))
  ALLOCATE (ZTMP1(LBOUND(YD%SLHD_MASK_T,1):UBOUND(YD%SLHD_MASK_T,1)))
  READ (KLUN) ZTMP1
  YD%SLHD_MASK_T = ZTMP1
  DEALLOCATE (ZTMP1)
ENDIF
READ (KLUN) YD%NLEV_SPONGE
READ (KLUN) YD%LRFRIC
READ (KLUN) YD%LRFRICISOTR
READ (KLUN) LRCORDIT
IF (LRCORDIT) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (YD%RCORDIT (IL1(1):IU1(1)))
  ALLOCATE (ZTMP1(LBOUND(YD%RCORDIT,1):UBOUND(YD%RCORDIT,1)))
  READ (KLUN) ZTMP1
  YD%RCORDIT = ZTMP1
  DEALLOCATE (ZTMP1)
ENDIF
READ (KLUN) LRCORDIH
IF (LRCORDIH) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (YD%RCORDIH (IL1(1):IU1(1)))
  ALLOCATE (ZTMP1(LBOUND(YD%RCORDIH,1):UBOUND(YD%RCORDIH,1)))
  READ (KLUN) ZTMP1
  YD%RCORDIH = ZTMP1
  DEALLOCATE (ZTMP1)
ENDIF
READ (KLUN) LRCORDIF
IF (LRCORDIF) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (YD%RCORDIF (IL1(1):IU1(1)))
  ALLOCATE (ZTMP1(LBOUND(YD%RCORDIF,1):UBOUND(YD%RCORDIF,1)))
  READ (KLUN) ZTMP1
  YD%RCORDIF = ZTMP1
  DEALLOCATE (ZTMP1)
ENDIF
READ (KLUN) ZTMP0
YD%VMAX1 = ZTMP0
READ (KLUN) ZTMP0
YD%VMAX2 = ZTMP0
READ (KLUN) ZTMP0
YD%RMAX_D3 = ZTMP0
READ (KLUN) YD%LBOUND_D3
READ (KLUN) LRKRF
IF (LRKRF) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (YD%RKRF (IL1(1):IU1(1)))
  ALLOCATE (ZTMP1(LBOUND(YD%RKRF,1):UBOUND(YD%RKRF,1)))
  READ (KLUN) ZTMP1
  YD%RKRF = ZTMP1
  DEALLOCATE (ZTMP1)
ENDIF
READ (KLUN) YD%NMAXLEVRF
READ (KLUN) ZTMP0
YD%RRFZ1 = ZTMP0
READ (KLUN) ZTMP0
YD%RRFPLM = ZTMP0
READ (KLUN) ZTMP0
YD%RRFTAU = ZTMP0
READ (KLUN) ZTMP0
YD%RTEMRB = ZTMP0
READ (KLUN) YD%NRUBC
READ (KLUN) YD%LGWFRIC
READ (KLUN) YD%NLEV_GWFRIC
READ (KLUN) ZTMP0
YD%RGWFRIC_MAX = ZTMP0
READ (KLUN) ZTMP0
YD%RGWFRIC_PLM = ZTMP0
READ (KLUN) LRGWFRIC
IF (LRGWFRIC) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (YD%RGWFRIC (IL1(1):IU1(1)))
  ALLOCATE (ZTMP1(LBOUND(YD%RGWFRIC,1):UBOUND(YD%RGWFRIC,1)))
  READ (KLUN) ZTMP1
  YD%RGWFRIC = ZTMP1
  DEALLOCATE (ZTMP1)
ENDIF
READ (KLUN) YD%LSIDG
READ (KLUN) YD%LDYN_STABAN
READ (KLUN) YD%LRHDI_LASTITERPC
READ (KLUN) YD%LREFINE_SILAPL
READ (KLUN) ZTMP0
YD%BETADT = ZTMP0
READ (KLUN) ZTMP0
YD%RBT = ZTMP0
READ (KLUN) ZTMP0
YD%RBTS2 = ZTMP0
READ (KLUN) ZTMP0
YD%REFGEO = ZTMP0
READ (KLUN) ZTMP0
YD%SIPR = ZTMP0
READ (KLUN) ZTMP0
YD%SIPRA = ZTMP0
READ (KLUN) ZTMP0
YD%SITR = ZTMP0
READ (KLUN) ZTMP0
YD%SITRA = ZTMP0
READ (KLUN) ZTMP0
YD%SISLP = ZTMP0
READ (KLUN) ZTMP0
YD%SITRUB = ZTMP0
READ (KLUN) ZTMP0
YD%SIPRUB = ZTMP0
READ (KLUN) ZTMP0
YD%SITIME = ZTMP0
READ (KLUN) ZTMP0
YD%SIRPRG = ZTMP0
READ (KLUN) ZTMP0
YD%SIRPRN = ZTMP0
READ (KLUN) YD%NSITER
READ (KLUN) YD%NCURRENT_ITER
READ (KLUN) YD%NITERHELM
READ (KLUN) YD%NOPT_SITRA
READ (KLUN) YD%NOPT_SIPRA
READ (KLUN) YD%NOPT_SISLP
READ (KLUN) LSIALPH
IF (LSIALPH) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (YD%SIALPH (IL1(1):IU1(1)))
  ALLOCATE (ZTMP1(LBOUND(YD%SIALPH,1):UBOUND(YD%SIALPH,1)))
  READ (KLUN) ZTMP1
  YD%SIALPH = ZTMP1
  DEALLOCATE (ZTMP1)
ENDIF
READ (KLUN) LSILNPR
IF (LSILNPR) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (YD%SILNPR (IL1(1):IU1(1)))
  ALLOCATE (ZTMP1(LBOUND(YD%SILNPR,1):UBOUND(YD%SILNPR,1)))
  READ (KLUN) ZTMP1
  YD%SILNPR = ZTMP1
  DEALLOCATE (ZTMP1)
ENDIF
READ (KLUN) LSIDELP
IF (LSIDELP) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (YD%SIDELP (IL1(1):IU1(1)))
  ALLOCATE (ZTMP1(LBOUND(YD%SIDELP,1):UBOUND(YD%SIDELP,1)))
  READ (KLUN) ZTMP1
  YD%SIDELP = ZTMP1
  DEALLOCATE (ZTMP1)
ENDIF
READ (KLUN) LSIRDEL
IF (LSIRDEL) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (YD%SIRDEL (IL1(1):IU1(1)))
  ALLOCATE (ZTMP1(LBOUND(YD%SIRDEL,1):UBOUND(YD%SIRDEL,1)))
  READ (KLUN) ZTMP1
  YD%SIRDEL = ZTMP1
  DEALLOCATE (ZTMP1)
ENDIF
READ (KLUN) LSITLAH
IF (LSITLAH) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (YD%SITLAH (IL1(1):IU1(1)))
  ALLOCATE (ZTMP1(LBOUND(YD%SITLAH,1):UBOUND(YD%SITLAH,1)))
  READ (KLUN) ZTMP1
  YD%SITLAH = ZTMP1
  DEALLOCATE (ZTMP1)
ENDIF
READ (KLUN) LSITLAF
IF (LSITLAF) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (YD%SITLAF (IL1(1):IU1(1)))
  ALLOCATE (ZTMP1(LBOUND(YD%SITLAF,1):UBOUND(YD%SITLAF,1)))
  READ (KLUN) ZTMP1
  YD%SITLAF = ZTMP1
  DEALLOCATE (ZTMP1)
ENDIF
READ (KLUN) LSIDPHI
IF (LSIDPHI) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (YD%SIDPHI (IL1(1):IU1(1)))
  ALLOCATE (ZTMP1(LBOUND(YD%SIDPHI,1):UBOUND(YD%SIDPHI,1)))
  READ (KLUN) ZTMP1
  YD%SIDPHI = ZTMP1
  DEALLOCATE (ZTMP1)
ENDIF
READ (KLUN) LSIALPH_NH
IF (LSIALPH_NH) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (YD%SIALPH_NH (IL1(1):IU1(1)))
  ALLOCATE (ZTMP1(LBOUND(YD%SIALPH_NH,1):UBOUND(YD%SIALPH_NH,1)))
  READ (KLUN) ZTMP1
  YD%SIALPH_NH = ZTMP1
  DEALLOCATE (ZTMP1)
ENDIF
READ (KLUN) LSILNPR_NH
IF (LSILNPR_NH) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (YD%SILNPR_NH (IL1(1):IU1(1)))
  ALLOCATE (ZTMP1(LBOUND(YD%SILNPR_NH,1):UBOUND(YD%SILNPR_NH,1)))
  READ (KLUN) ZTMP1
  YD%SILNPR_NH = ZTMP1
  DEALLOCATE (ZTMP1)
ENDIF
READ (KLUN) LSIDELP_NH
IF (LSIDELP_NH) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (YD%SIDELP_NH (IL1(1):IU1(1)))
  ALLOCATE (ZTMP1(LBOUND(YD%SIDELP_NH,1):UBOUND(YD%SIDELP_NH,1)))
  READ (KLUN) ZTMP1
  YD%SIDELP_NH = ZTMP1
  DEALLOCATE (ZTMP1)
ENDIF
READ (KLUN) LSIRDEL_NH
IF (LSIRDEL_NH) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (YD%SIRDEL_NH (IL1(1):IU1(1)))
  ALLOCATE (ZTMP1(LBOUND(YD%SIRDEL_NH,1):UBOUND(YD%SIRDEL_NH,1)))
  READ (KLUN) ZTMP1
  YD%SIRDEL_NH = ZTMP1
  DEALLOCATE (ZTMP1)
ENDIF
READ (KLUN) LSITLAH_NH
IF (LSITLAH_NH) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (YD%SITLAH_NH (IL1(1):IU1(1)))
  ALLOCATE (ZTMP1(LBOUND(YD%SITLAH_NH,1):UBOUND(YD%SITLAH_NH,1)))
  READ (KLUN) ZTMP1
  YD%SITLAH_NH = ZTMP1
  DEALLOCATE (ZTMP1)
ENDIF
READ (KLUN) LSITLAF_NH
IF (LSITLAF_NH) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (YD%SITLAF_NH (IL1(1):IU1(1)))
  ALLOCATE (ZTMP1(LBOUND(YD%SITLAF_NH,1):UBOUND(YD%SITLAF_NH,1)))
  READ (KLUN) ZTMP1
  YD%SITLAF_NH = ZTMP1
  DEALLOCATE (ZTMP1)
ENDIF
READ (KLUN) LSIDPHI_NH
IF (LSIDPHI_NH) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (YD%SIDPHI_NH (IL1(1):IU1(1)))
  ALLOCATE (ZTMP1(LBOUND(YD%SIDPHI_NH,1):UBOUND(YD%SIDPHI_NH,1)))
  READ (KLUN) ZTMP1
  YD%SIDPHI_NH = ZTMP1
  DEALLOCATE (ZTMP1)
ENDIF
READ (KLUN) LSIWF2H
IF (LSIWF2H) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (YD%SIWF2H (IL1(1):IU1(1)))
  ALLOCATE (ZTMP1(LBOUND(YD%SIWF2H,1):UBOUND(YD%SIWF2H,1)))
  READ (KLUN) ZTMP1
  YD%SIWF2H = ZTMP1
  DEALLOCATE (ZTMP1)
ENDIF
READ (KLUN) LSIWH2F
IF (LSIWH2F) THEN
  READ (KLUN) IL2
  READ (KLUN) IU2
  ALLOCATE (YD%SIWH2F (IL2(1):IU2(1), IL2(2):IU2(2)))
  ALLOCATE (ZTMP2(LBOUND(YD%SIWH2F,1):UBOUND(YD%SIWH2F,1), LBOUND(YD%SIWH2F,2):UBOUND(YD%SIWH2F,2)))
  READ (KLUN) ZTMP2
  YD%SIWH2F = ZTMP2
  DEALLOCATE (ZTMP2)
ENDIF
READ (KLUN) LSIGFL
IF (LSIGFL) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (YD%SIGFL (IL1(1):IU1(1)))
  ALLOCATE (ZTMP1(LBOUND(YD%SIGFL,1):UBOUND(YD%SIGFL,1)))
  READ (KLUN) ZTMP1
  YD%SIGFL = ZTMP1
  DEALLOCATE (ZTMP1)
ENDIF
READ (KLUN) LSIGFM
IF (LSIGFM) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (YD%SIGFM (IL1(1):IU1(1)))
  ALLOCATE (ZTMP1(LBOUND(YD%SIGFM,1):UBOUND(YD%SIGFM,1)))
  READ (KLUN) ZTMP1
  YD%SIGFM = ZTMP1
  DEALLOCATE (ZTMP1)
ENDIF
READ (KLUN) LSITFL
IF (LSITFL) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (YD%SITFL (IL1(1):IU1(1)))
  ALLOCATE (ZTMP1(LBOUND(YD%SITFL,1):UBOUND(YD%SITFL,1)))
  READ (KLUN) ZTMP1
  YD%SITFL = ZTMP1
  DEALLOCATE (ZTMP1)
ENDIF
READ (KLUN) LSITFM
IF (LSITFM) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (YD%SITFM (IL1(1):IU1(1)))
  ALLOCATE (ZTMP1(LBOUND(YD%SITFM,1):UBOUND(YD%SITFM,1)))
  READ (KLUN) ZTMP1
  YD%SITFM = ZTMP1
  DEALLOCATE (ZTMP1)
ENDIF
READ (KLUN) LSIB
IF (LSIB) THEN
  READ (KLUN) IL2
  READ (KLUN) IU2
  ALLOCATE (YD%SIB (IL2(1):IU2(1), IL2(2):IU2(2)))
  ALLOCATE (ZTMP2(LBOUND(YD%SIB,1):UBOUND(YD%SIB,1), LBOUND(YD%SIB,2):UBOUND(YD%SIB,2)))
  READ (KLUN) ZTMP2
  YD%SIB = ZTMP2
  DEALLOCATE (ZTMP2)
ENDIF
READ (KLUN) LSIMO
IF (LSIMO) THEN
  READ (KLUN) IL2
  READ (KLUN) IU2
  ALLOCATE (YD%SIMO (IL2(1):IU2(1), IL2(2):IU2(2)))
  ALLOCATE (ZTMP2(LBOUND(YD%SIMO,1):UBOUND(YD%SIMO,1), LBOUND(YD%SIMO,2):UBOUND(YD%SIMO,2)))
  READ (KLUN) ZTMP2
  YD%SIMO = ZTMP2
  DEALLOCATE (ZTMP2)
ENDIF
READ (KLUN) LSIMI
IF (LSIMI) THEN
  READ (KLUN) IL2
  READ (KLUN) IU2
  ALLOCATE (YD%SIMI (IL2(1):IU2(1), IL2(2):IU2(2)))
  ALLOCATE (ZTMP2(LBOUND(YD%SIMI,1):UBOUND(YD%SIMI,1), LBOUND(YD%SIMI,2):UBOUND(YD%SIMI,2)))
  READ (KLUN) ZTMP2
  YD%SIMI = ZTMP2
  DEALLOCATE (ZTMP2)
ENDIF
READ (KLUN) LSIVP
IF (LSIVP) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (YD%SIVP (IL1(1):IU1(1)))
  ALLOCATE (ZTMP1(LBOUND(YD%SIVP,1):UBOUND(YD%SIVP,1)))
  READ (KLUN) ZTMP1
  YD%SIVP = ZTMP1
  DEALLOCATE (ZTMP1)
ENDIF
READ (KLUN) LSIHEG
IF (LSIHEG) THEN
  READ (KLUN) IL3
  READ (KLUN) IU3
  ALLOCATE (YD%SIHEG (IL3(1):IU3(1), IL3(2):IU3(2), IL3(3):IU3(3)))
  ALLOCATE (ZTMP3(LBOUND(YD%SIHEG,1):UBOUND(YD%SIHEG,1), LBOUND(YD%SIHEG,2):UBOUND(YD%SIHEG,2), LBOUND(YD%SIHEG,3):UBOUND(YD%SIHEG,3)))
  READ (KLUN) ZTMP3
  YD%SIHEG = ZTMP3
  DEALLOCATE (ZTMP3)
ENDIF
READ (KLUN) LSIHEG2
IF (LSIHEG2) THEN
  READ (KLUN) IL3
  READ (KLUN) IU3
  ALLOCATE (YD%SIHEG2 (IL3(1):IU3(1), IL3(2):IU3(2), IL3(3):IU3(3)))
  ALLOCATE (ZTMP3(LBOUND(YD%SIHEG2,1):UBOUND(YD%SIHEG2,1), LBOUND(YD%SIHEG2,2):UBOUND(YD%SIHEG2,2), LBOUND(YD%SIHEG2,3):UBOUND(YD%SIHEG2,3)))
  READ (KLUN) ZTMP3
  YD%SIHEG2 = ZTMP3
  DEALLOCATE (ZTMP3)
ENDIF
READ (KLUN) LSIHEGB
IF (LSIHEGB) THEN
  READ (KLUN) IL3
  READ (KLUN) IU3
  ALLOCATE (YD%SIHEGB (IL3(1):IU3(1), IL3(2):IU3(2), IL3(3):IU3(3)))
  ALLOCATE (ZTMP3(LBOUND(YD%SIHEGB,1):UBOUND(YD%SIHEGB,1), LBOUND(YD%SIHEGB,2):UBOUND(YD%SIHEGB,2), LBOUND(YD%SIHEGB,3):UBOUND(YD%SIHEGB,3)))
  READ (KLUN) ZTMP3
  YD%SIHEGB = ZTMP3
  DEALLOCATE (ZTMP3)
ENDIF
READ (KLUN) LSIHEGB2
IF (LSIHEGB2) THEN
  READ (KLUN) IL3
  READ (KLUN) IU3
  ALLOCATE (YD%SIHEGB2 (IL3(1):IU3(1), IL3(2):IU3(2), IL3(3):IU3(3)))
  ALLOCATE (ZTMP3(LBOUND(YD%SIHEGB2,1):UBOUND(YD%SIHEGB2,1), LBOUND(YD%SIHEGB2,2):UBOUND(YD%SIHEGB2,2), LBOUND(YD%SIHEGB2,3):UBOUND(YD%SIHEGB2,3)))
  READ (KLUN) ZTMP3
  YD%SIHEGB2 = ZTMP3
  DEALLOCATE (ZTMP3)
ENDIF
READ (KLUN) LSIFAC
IF (LSIFAC) THEN
  READ (KLUN) IL2
  READ (KLUN) IU2
  ALLOCATE (YD%SIFAC (IL2(1):IU2(1), IL2(2):IU2(2)))
  ALLOCATE (ZTMP2(LBOUND(YD%SIFAC,1):UBOUND(YD%SIFAC,1), LBOUND(YD%SIFAC,2):UBOUND(YD%SIFAC,2)))
  READ (KLUN) ZTMP2
  YD%SIFAC = ZTMP2
  DEALLOCATE (ZTMP2)
ENDIF
READ (KLUN) LSIFACI
IF (LSIFACI) THEN
  READ (KLUN) IL2
  READ (KLUN) IU2
  ALLOCATE (YD%SIFACI (IL2(1):IU2(1), IL2(2):IU2(2)))
  ALLOCATE (ZTMP2(LBOUND(YD%SIFACI,1):UBOUND(YD%SIFACI,1), LBOUND(YD%SIFACI,2):UBOUND(YD%SIFACI,2)))
  READ (KLUN) ZTMP2
  YD%SIFACI = ZTMP2
  DEALLOCATE (ZTMP2)
ENDIF
READ (KLUN) LSISKAPI
IF (LSISKAPI) THEN
  READ (KLUN) IL2
  READ (KLUN) IU2
  ALLOCATE (YD%SISKAPI (IL2(1):IU2(1), IL2(2):IU2(2)))
  ALLOCATE (ZTMP2(LBOUND(YD%SISKAPI,1):UBOUND(YD%SISKAPI,1), LBOUND(YD%SISKAPI,2):UBOUND(YD%SISKAPI,2)))
  READ (KLUN) ZTMP2
  YD%SISKAPI = ZTMP2
  DEALLOCATE (ZTMP2)
ENDIF
READ (KLUN) LSITRAM
IF (LSITRAM) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (YD%SITRAM (IL1(1):IU1(1)))
  ALLOCATE (ZTMP1(LBOUND(YD%SITRAM,1):UBOUND(YD%SITRAM,1)))
  READ (KLUN) ZTMP1
  YD%SITRAM = ZTMP1
  DEALLOCATE (ZTMP1)
ENDIF
READ (KLUN) ZTMP0
YD%VNORM = ZTMP0
READ (KLUN) ZTMP0
YD%SLOPE_MAX = ZTMP0
READ (KLUN) ZTMP0
YD%PSURF_MIN = ZTMP0
READ (KLUN) YD%NVLAG
READ (KLUN) YD%NWLAG
READ (KLUN) YD%NTLAG
READ (KLUN) YD%NSPDLAG
READ (KLUN) YD%NSVDLAG
READ (KLUN) YD%NSPLTHOI
READ (KLUN) YD%LSPLTHOIGFL
READ (KLUN) YD%NSLDIMK
READ (KLUN) YD%NITMP
READ (KLUN) ZTMP0
YD%VETAON = ZTMP0
READ (KLUN) ZTMP0
YD%VETAOX = ZTMP0
READ (KLUN) YD%LSETTLSVF
READ (KLUN) YD%LSETFSTAT
READ (KLUN) YD%LSETTLSVF_DIFF
READ (KLUN) ZTMP0
YD%RW2TLFF = ZTMP0
READ (KLUN) ZTMP0
YD%RALPHA = ZTMP0
READ (KLUN) ZTMP0
YD%RALPHA_TOP = ZTMP0
READ (KLUN) YD%NLEV_ZALPHA
READ (KLUN) YD%NEDER
READ (KLUN) YD%LWENOBC
READ (KLUN) YD%NQMHOISLT
READ (KLUN) YD%LSLDP_RK
READ (KLUN) YD%LSLDP_CURV
READ (KLUN) YD%LRHS_CURV
READ (KLUN) YD%LSLDP_XYZ
READ (KLUN) YD%LSLDP_SAVE
READ (KLUN) ZTMP0
YD%VESL = ZTMP0
READ (KLUN) ZTMP0
YD%XIDT = ZTMP0
READ (KLUN) YD%LQMW
READ (KLUN) YD%LQMHW
READ (KLUN) YD%LQMT
READ (KLUN) YD%LQMHT
READ (KLUN) YD%LQMP
READ (KLUN) YD%LQMHP
READ (KLUN) YD%LQMPD
READ (KLUN) YD%LQMHPD
READ (KLUN) YD%LQMVD
READ (KLUN) YD%LQMHVD
READ (KLUN) YD%LVWENO_W
READ (KLUN) YD%LVWENO_T
READ (KLUN) YD%LVWENO_SP
READ (KLUN) YD%LVWENO_SPD
READ (KLUN) YD%LVWENO_SVD
READ (KLUN) ZTMP0
YD%WENO_ALPHA_W = ZTMP0
READ (KLUN) ZTMP0
YD%WENO_ALPHA_T = ZTMP0
READ (KLUN) ZTMP0
YD%WENO_ALPHA_SP = ZTMP0
READ (KLUN) ZTMP0
YD%WENO_ALPHA_SPD = ZTMP0
READ (KLUN) ZTMP0
YD%WENO_ALPHA_SVD = ZTMP0
READ (KLUN) YD%LADVF
READ (KLUN) YD%LIMPF
READ (KLUN) YD%L2TLFF
READ (KLUN) ZTMP0
YD%RCMSLP0 = ZTMP0
READ (KLUN) YD%NCOMP_CVGQ
READ (KLUN) YD%LSVTSM
READ (KLUN) ZTMP0
YD%RPRES_SVTSM = ZTMP0
READ (KLUN) ZTMP0
YD%RPRES_SETTLSVF = ZTMP0
READ (KLUN) YD%NFLEVSF
READ (KLUN) ZTMP0
YD%RSCALE = ZTMP0
READ (KLUN) ZTMP0
YD%RSCALEOFF = ZTMP0
READ (KLUN) ZTMP0
YD%RINTOPT = ZTMP0
READ (KLUN) ZTMP0
YD%RRINTOPT = ZTMP0
READ (KLUN) YD%LHDIFFM
READ (KLUN) YD%LSPECVIS
READ (KLUN) YD%NDIFFACT
READ (KLUN) YD%LGPSTRESS
READ (KLUN) ZTMP0
YD%RCLSTRESS = ZTMP0
READ (KLUN) ZTMP0
YD%RCLPOLE = ZTMP0
READ (KLUN) YD%NVSEPC
READ (KLUN) YD%NVSEPL
READ (KLUN) YD%LFINDVSEP
READ (KLUN) YD%LMASCOR
READ (KLUN) YD%LMASDRY
READ (KLUN) YD%LGPMASCOR
READ (KLUN) YD%NGPMASCOR
READ (KLUN) ZTMP0
YD%GPMASSI = ZTMP0
READ (KLUN) ZTMP0
YD%GMASSI = ZTMP0
READ (KLUN) ZTMP0
YD%GMASS0 = ZTMP0
READ (KLUN) ZTMP0
YD%GMASSINC = ZTMP0
READ (KLUN) YD%LNODRYFLX
READ (KLUN) LSIBI
IF (LSIBI) THEN
  READ (KLUN) IL2
  READ (KLUN) IU2
  ALLOCATE (YD%SIBI (IL2(1):IU2(1), IL2(2):IU2(2)))
  ALLOCATE (ZTMP2(LBOUND(YD%SIBI,1):UBOUND(YD%SIBI,1), LBOUND(YD%SIBI,2):UBOUND(YD%SIBI,2)))
  READ (KLUN) ZTMP2
  YD%SIBI = ZTMP2
  DEALLOCATE (ZTMP2)
ENDIF
END SUBROUTINE


SUBROUTINE COPY_TDYN (YD, LDCREATED)

IMPLICIT NONE
TYPE (TDYN), INTENT (IN), TARGET :: YD
LOGICAL, OPTIONAL, INTENT (IN) :: LDCREATED
LOGICAL :: LLCREATED
LOGICAL :: LRCORDIF, LRCORDIH, LRCORDIT, LRDHI, LRDHS, LRDIDIV, LRDIGFL, LRDIPD, LRDISP, LRDITG
LOGICAL :: LRDIVD, LRDIVOR, LRDSDIV, LRDSVD, LRDSVOR, LRGWFRIC, LRKRF, LRSAVEDP, LSIALPH, LSIALPH_NH
LOGICAL :: LSIB, LSIBI, LSIDELP, LSIDELP_NH, LSIDPHI, LSIDPHI_NH, LSIFAC, LSIFACI, LSIGFL, LSIGFM
LOGICAL :: LSIHEG, LSIHEG2, LSIHEGB, LSIHEGB2, LSILNPR, LSILNPR_NH, LSIMI, LSIMO, LSIRDEL, LSIRDEL_NH
LOGICAL :: LSISKAPI, LSITFL, LSITFM, LSITLAF, LSITLAF_NH, LSITLAH, LSITLAH_NH, LSITRAM, LSIVP, LSIWF2H
LOGICAL :: LSIWH2F, LSLHDA, LSLHDD0, LSLHD_MASK_T, LSLHD_MASK_U

LLCREATED = .FALSE.
IF (PRESENT (LDCREATED)) THEN
  LLCREATED = LDCREATED
ENDIF
IF (.NOT. LLCREATED) THEN
  !$acc enter data create (YD)
  !$acc update device (YD)
ENDIF













































LRDIVOR = ALLOCATED (YD%RDIVOR)
IF (LRDIVOR) THEN
  !$acc enter data create (YD%RDIVOR)
  !$acc update device (YD%RDIVOR)
  !$acc enter data attach (YD%RDIVOR)
ENDIF

LRDIDIV = ALLOCATED (YD%RDIDIV)
IF (LRDIDIV) THEN
  !$acc enter data create (YD%RDIDIV)
  !$acc update device (YD%RDIDIV)
  !$acc enter data attach (YD%RDIDIV)
ENDIF

LRDITG = ALLOCATED (YD%RDITG)
IF (LRDITG) THEN
  !$acc enter data create (YD%RDITG)
  !$acc update device (YD%RDITG)
  !$acc enter data attach (YD%RDITG)
ENDIF

LRDIGFL = ALLOCATED (YD%RDIGFL)
IF (LRDIGFL) THEN
  !$acc enter data create (YD%RDIGFL)
  !$acc update device (YD%RDIGFL)
  !$acc enter data attach (YD%RDIGFL)
ENDIF

LRDIPD = ALLOCATED (YD%RDIPD)
IF (LRDIPD) THEN
  !$acc enter data create (YD%RDIPD)
  !$acc update device (YD%RDIPD)
  !$acc enter data attach (YD%RDIPD)
ENDIF

LRDIVD = ALLOCATED (YD%RDIVD)
IF (LRDIVD) THEN
  !$acc enter data create (YD%RDIVD)
  !$acc update device (YD%RDIVD)
  !$acc enter data attach (YD%RDIVD)
ENDIF

LRDISP = ALLOCATED (YD%RDISP)
IF (LRDISP) THEN
  !$acc enter data create (YD%RDISP)
  !$acc update device (YD%RDISP)
  !$acc enter data attach (YD%RDISP)
ENDIF

LRDHI = ALLOCATED (YD%RDHI)
IF (LRDHI) THEN
  !$acc enter data create (YD%RDHI)
  !$acc update device (YD%RDHI)
  !$acc enter data attach (YD%RDHI)
ENDIF









LRSAVEDP = ALLOCATED (YD%RSAVEDP)
IF (LRSAVEDP) THEN
  !$acc enter data create (YD%RSAVEDP)
  !$acc update device (YD%RSAVEDP)
  !$acc enter data attach (YD%RSAVEDP)
ENDIF

LSLHDA = ALLOCATED (YD%SLHDA)
IF (LSLHDA) THEN
  !$acc enter data create (YD%SLHDA)
  !$acc update device (YD%SLHDA)
  !$acc enter data attach (YD%SLHDA)
ENDIF





LSLHDD0 = ALLOCATED (YD%SLHDD0)
IF (LSLHDD0) THEN
  !$acc enter data create (YD%SLHDD0)
  !$acc update device (YD%SLHDD0)
  !$acc enter data attach (YD%SLHDD0)
ENDIF

























LRDSVOR = ALLOCATED (YD%RDSVOR)
IF (LRDSVOR) THEN
  !$acc enter data create (YD%RDSVOR)
  !$acc update device (YD%RDSVOR)
  !$acc enter data attach (YD%RDSVOR)
ENDIF

LRDSDIV = ALLOCATED (YD%RDSDIV)
IF (LRDSDIV) THEN
  !$acc enter data create (YD%RDSDIV)
  !$acc update device (YD%RDSDIV)
  !$acc enter data attach (YD%RDSDIV)
ENDIF

LRDSVD = ALLOCATED (YD%RDSVD)
IF (LRDSVD) THEN
  !$acc enter data create (YD%RDSVD)
  !$acc update device (YD%RDSVD)
  !$acc enter data attach (YD%RDSVD)
ENDIF

LRDHS = ALLOCATED (YD%RDHS)
IF (LRDHS) THEN
  !$acc enter data create (YD%RDHS)
  !$acc update device (YD%RDHS)
  !$acc enter data attach (YD%RDHS)
ENDIF

LSLHD_MASK_U = ALLOCATED (YD%SLHD_MASK_U)
IF (LSLHD_MASK_U) THEN
  !$acc enter data create (YD%SLHD_MASK_U)
  !$acc update device (YD%SLHD_MASK_U)
  !$acc enter data attach (YD%SLHD_MASK_U)
ENDIF

LSLHD_MASK_T = ALLOCATED (YD%SLHD_MASK_T)
IF (LSLHD_MASK_T) THEN
  !$acc enter data create (YD%SLHD_MASK_T)
  !$acc update device (YD%SLHD_MASK_T)
  !$acc enter data attach (YD%SLHD_MASK_T)
ENDIF




LRCORDIT = ALLOCATED (YD%RCORDIT)
IF (LRCORDIT) THEN
  !$acc enter data create (YD%RCORDIT)
  !$acc update device (YD%RCORDIT)
  !$acc enter data attach (YD%RCORDIT)
ENDIF

LRCORDIH = ALLOCATED (YD%RCORDIH)
IF (LRCORDIH) THEN
  !$acc enter data create (YD%RCORDIH)
  !$acc update device (YD%RCORDIH)
  !$acc enter data attach (YD%RCORDIH)
ENDIF

LRCORDIF = ALLOCATED (YD%RCORDIF)
IF (LRCORDIF) THEN
  !$acc enter data create (YD%RCORDIF)
  !$acc update device (YD%RCORDIF)
  !$acc enter data attach (YD%RCORDIF)
ENDIF





LRKRF = ALLOCATED (YD%RKRF)
IF (LRKRF) THEN
  !$acc enter data create (YD%RKRF)
  !$acc update device (YD%RKRF)
  !$acc enter data attach (YD%RKRF)
ENDIF











LRGWFRIC = ALLOCATED (YD%RGWFRIC)
IF (LRGWFRIC) THEN
  !$acc enter data create (YD%RGWFRIC)
  !$acc update device (YD%RGWFRIC)
  !$acc enter data attach (YD%RGWFRIC)
ENDIF

























LSIALPH = ALLOCATED (YD%SIALPH)
IF (LSIALPH) THEN
  !$acc enter data create (YD%SIALPH)
  !$acc update device (YD%SIALPH)
  !$acc enter data attach (YD%SIALPH)
ENDIF

LSILNPR = ALLOCATED (YD%SILNPR)
IF (LSILNPR) THEN
  !$acc enter data create (YD%SILNPR)
  !$acc update device (YD%SILNPR)
  !$acc enter data attach (YD%SILNPR)
ENDIF

LSIDELP = ALLOCATED (YD%SIDELP)
IF (LSIDELP) THEN
  !$acc enter data create (YD%SIDELP)
  !$acc update device (YD%SIDELP)
  !$acc enter data attach (YD%SIDELP)
ENDIF

LSIRDEL = ALLOCATED (YD%SIRDEL)
IF (LSIRDEL) THEN
  !$acc enter data create (YD%SIRDEL)
  !$acc update device (YD%SIRDEL)
  !$acc enter data attach (YD%SIRDEL)
ENDIF

LSITLAH = ALLOCATED (YD%SITLAH)
IF (LSITLAH) THEN
  !$acc enter data create (YD%SITLAH)
  !$acc update device (YD%SITLAH)
  !$acc enter data attach (YD%SITLAH)
ENDIF

LSITLAF = ALLOCATED (YD%SITLAF)
IF (LSITLAF) THEN
  !$acc enter data create (YD%SITLAF)
  !$acc update device (YD%SITLAF)
  !$acc enter data attach (YD%SITLAF)
ENDIF

LSIDPHI = ALLOCATED (YD%SIDPHI)
IF (LSIDPHI) THEN
  !$acc enter data create (YD%SIDPHI)
  !$acc update device (YD%SIDPHI)
  !$acc enter data attach (YD%SIDPHI)
ENDIF

LSIALPH_NH = ALLOCATED (YD%SIALPH_NH)
IF (LSIALPH_NH) THEN
  !$acc enter data create (YD%SIALPH_NH)
  !$acc update device (YD%SIALPH_NH)
  !$acc enter data attach (YD%SIALPH_NH)
ENDIF

LSILNPR_NH = ALLOCATED (YD%SILNPR_NH)
IF (LSILNPR_NH) THEN
  !$acc enter data create (YD%SILNPR_NH)
  !$acc update device (YD%SILNPR_NH)
  !$acc enter data attach (YD%SILNPR_NH)
ENDIF

LSIDELP_NH = ALLOCATED (YD%SIDELP_NH)
IF (LSIDELP_NH) THEN
  !$acc enter data create (YD%SIDELP_NH)
  !$acc update device (YD%SIDELP_NH)
  !$acc enter data attach (YD%SIDELP_NH)
ENDIF

LSIRDEL_NH = ALLOCATED (YD%SIRDEL_NH)
IF (LSIRDEL_NH) THEN
  !$acc enter data create (YD%SIRDEL_NH)
  !$acc update device (YD%SIRDEL_NH)
  !$acc enter data attach (YD%SIRDEL_NH)
ENDIF

LSITLAH_NH = ALLOCATED (YD%SITLAH_NH)
IF (LSITLAH_NH) THEN
  !$acc enter data create (YD%SITLAH_NH)
  !$acc update device (YD%SITLAH_NH)
  !$acc enter data attach (YD%SITLAH_NH)
ENDIF

LSITLAF_NH = ALLOCATED (YD%SITLAF_NH)
IF (LSITLAF_NH) THEN
  !$acc enter data create (YD%SITLAF_NH)
  !$acc update device (YD%SITLAF_NH)
  !$acc enter data attach (YD%SITLAF_NH)
ENDIF

LSIDPHI_NH = ALLOCATED (YD%SIDPHI_NH)
IF (LSIDPHI_NH) THEN
  !$acc enter data create (YD%SIDPHI_NH)
  !$acc update device (YD%SIDPHI_NH)
  !$acc enter data attach (YD%SIDPHI_NH)
ENDIF

LSIWF2H = ALLOCATED (YD%SIWF2H)
IF (LSIWF2H) THEN
  !$acc enter data create (YD%SIWF2H)
  !$acc update device (YD%SIWF2H)
  !$acc enter data attach (YD%SIWF2H)
ENDIF

LSIWH2F = ALLOCATED (YD%SIWH2F)
IF (LSIWH2F) THEN
  !$acc enter data create (YD%SIWH2F)
  !$acc update device (YD%SIWH2F)
  !$acc enter data attach (YD%SIWH2F)
ENDIF

LSIGFL = ALLOCATED (YD%SIGFL)
IF (LSIGFL) THEN
  !$acc enter data create (YD%SIGFL)
  !$acc update device (YD%SIGFL)
  !$acc enter data attach (YD%SIGFL)
ENDIF

LSIGFM = ALLOCATED (YD%SIGFM)
IF (LSIGFM) THEN
  !$acc enter data create (YD%SIGFM)
  !$acc update device (YD%SIGFM)
  !$acc enter data attach (YD%SIGFM)
ENDIF

LSITFL = ALLOCATED (YD%SITFL)
IF (LSITFL) THEN
  !$acc enter data create (YD%SITFL)
  !$acc update device (YD%SITFL)
  !$acc enter data attach (YD%SITFL)
ENDIF

LSITFM = ALLOCATED (YD%SITFM)
IF (LSITFM) THEN
  !$acc enter data create (YD%SITFM)
  !$acc update device (YD%SITFM)
  !$acc enter data attach (YD%SITFM)
ENDIF

LSIB = ALLOCATED (YD%SIB)
IF (LSIB) THEN
  !$acc enter data create (YD%SIB)
  !$acc update device (YD%SIB)
  !$acc enter data attach (YD%SIB)
ENDIF

LSIMO = ALLOCATED (YD%SIMO)
IF (LSIMO) THEN
  !$acc enter data create (YD%SIMO)
  !$acc update device (YD%SIMO)
  !$acc enter data attach (YD%SIMO)
ENDIF

LSIMI = ALLOCATED (YD%SIMI)
IF (LSIMI) THEN
  !$acc enter data create (YD%SIMI)
  !$acc update device (YD%SIMI)
  !$acc enter data attach (YD%SIMI)
ENDIF

LSIVP = ALLOCATED (YD%SIVP)
IF (LSIVP) THEN
  !$acc enter data create (YD%SIVP)
  !$acc update device (YD%SIVP)
  !$acc enter data attach (YD%SIVP)
ENDIF

LSIHEG = ALLOCATED (YD%SIHEG)
IF (LSIHEG) THEN
  !$acc enter data create (YD%SIHEG)
  !$acc update device (YD%SIHEG)
  !$acc enter data attach (YD%SIHEG)
ENDIF

LSIHEG2 = ALLOCATED (YD%SIHEG2)
IF (LSIHEG2) THEN
  !$acc enter data create (YD%SIHEG2)
  !$acc update device (YD%SIHEG2)
  !$acc enter data attach (YD%SIHEG2)
ENDIF

LSIHEGB = ALLOCATED (YD%SIHEGB)
IF (LSIHEGB) THEN
  !$acc enter data create (YD%SIHEGB)
  !$acc update device (YD%SIHEGB)
  !$acc enter data attach (YD%SIHEGB)
ENDIF

LSIHEGB2 = ALLOCATED (YD%SIHEGB2)
IF (LSIHEGB2) THEN
  !$acc enter data create (YD%SIHEGB2)
  !$acc update device (YD%SIHEGB2)
  !$acc enter data attach (YD%SIHEGB2)
ENDIF

LSIFAC = ALLOCATED (YD%SIFAC)
IF (LSIFAC) THEN
  !$acc enter data create (YD%SIFAC)
  !$acc update device (YD%SIFAC)
  !$acc enter data attach (YD%SIFAC)
ENDIF

LSIFACI = ALLOCATED (YD%SIFACI)
IF (LSIFACI) THEN
  !$acc enter data create (YD%SIFACI)
  !$acc update device (YD%SIFACI)
  !$acc enter data attach (YD%SIFACI)
ENDIF

LSISKAPI = ALLOCATED (YD%SISKAPI)
IF (LSISKAPI) THEN
  !$acc enter data create (YD%SISKAPI)
  !$acc update device (YD%SISKAPI)
  !$acc enter data attach (YD%SISKAPI)
ENDIF

LSITRAM = ALLOCATED (YD%SITRAM)
IF (LSITRAM) THEN
  !$acc enter data create (YD%SITRAM)
  !$acc update device (YD%SITRAM)
  !$acc enter data attach (YD%SITRAM)
ENDIF



















































































LSIBI = ALLOCATED (YD%SIBI)
IF (LSIBI) THEN
  !$acc enter data create (YD%SIBI)
  !$acc update device (YD%SIBI)
  !$acc enter data attach (YD%SIBI)
ENDIF

END SUBROUTINE

SUBROUTINE WIPE_TDYN (YD, LDDELETED)

IMPLICIT NONE
TYPE (TDYN), INTENT (IN), TARGET :: YD
LOGICAL, OPTIONAL, INTENT (IN) :: LDDELETED
LOGICAL :: LLDELETED
LOGICAL :: LRCORDIF, LRCORDIH, LRCORDIT, LRDHI, LRDHS, LRDIDIV, LRDIGFL, LRDIPD, LRDISP, LRDITG
LOGICAL :: LRDIVD, LRDIVOR, LRDSDIV, LRDSVD, LRDSVOR, LRGWFRIC, LRKRF, LRSAVEDP, LSIALPH, LSIALPH_NH
LOGICAL :: LSIB, LSIBI, LSIDELP, LSIDELP_NH, LSIDPHI, LSIDPHI_NH, LSIFAC, LSIFACI, LSIGFL, LSIGFM
LOGICAL :: LSIHEG, LSIHEG2, LSIHEGB, LSIHEGB2, LSILNPR, LSILNPR_NH, LSIMI, LSIMO, LSIRDEL, LSIRDEL_NH
LOGICAL :: LSISKAPI, LSITFL, LSITFM, LSITLAF, LSITLAF_NH, LSITLAH, LSITLAH_NH, LSITRAM, LSIVP, LSIWF2H
LOGICAL :: LSIWH2F, LSLHDA, LSLHDD0, LSLHD_MASK_T, LSLHD_MASK_U














































LRDIVOR = ALLOCATED (YD%RDIVOR)
IF (LRDIVOR) THEN
  !$acc exit data detach (YD%RDIVOR)
  !$acc exit data delete (YD%RDIVOR)
ENDIF

LRDIDIV = ALLOCATED (YD%RDIDIV)
IF (LRDIDIV) THEN
  !$acc exit data detach (YD%RDIDIV)
  !$acc exit data delete (YD%RDIDIV)
ENDIF

LRDITG = ALLOCATED (YD%RDITG)
IF (LRDITG) THEN
  !$acc exit data detach (YD%RDITG)
  !$acc exit data delete (YD%RDITG)
ENDIF

LRDIGFL = ALLOCATED (YD%RDIGFL)
IF (LRDIGFL) THEN
  !$acc exit data detach (YD%RDIGFL)
  !$acc exit data delete (YD%RDIGFL)
ENDIF

LRDIPD = ALLOCATED (YD%RDIPD)
IF (LRDIPD) THEN
  !$acc exit data detach (YD%RDIPD)
  !$acc exit data delete (YD%RDIPD)
ENDIF

LRDIVD = ALLOCATED (YD%RDIVD)
IF (LRDIVD) THEN
  !$acc exit data detach (YD%RDIVD)
  !$acc exit data delete (YD%RDIVD)
ENDIF

LRDISP = ALLOCATED (YD%RDISP)
IF (LRDISP) THEN
  !$acc exit data detach (YD%RDISP)
  !$acc exit data delete (YD%RDISP)
ENDIF

LRDHI = ALLOCATED (YD%RDHI)
IF (LRDHI) THEN
  !$acc exit data detach (YD%RDHI)
  !$acc exit data delete (YD%RDHI)
ENDIF









LRSAVEDP = ALLOCATED (YD%RSAVEDP)
IF (LRSAVEDP) THEN
  !$acc exit data detach (YD%RSAVEDP)
  !$acc exit data delete (YD%RSAVEDP)
ENDIF

LSLHDA = ALLOCATED (YD%SLHDA)
IF (LSLHDA) THEN
  !$acc exit data detach (YD%SLHDA)
  !$acc exit data delete (YD%SLHDA)
ENDIF





LSLHDD0 = ALLOCATED (YD%SLHDD0)
IF (LSLHDD0) THEN
  !$acc exit data detach (YD%SLHDD0)
  !$acc exit data delete (YD%SLHDD0)
ENDIF

























LRDSVOR = ALLOCATED (YD%RDSVOR)
IF (LRDSVOR) THEN
  !$acc exit data detach (YD%RDSVOR)
  !$acc exit data delete (YD%RDSVOR)
ENDIF

LRDSDIV = ALLOCATED (YD%RDSDIV)
IF (LRDSDIV) THEN
  !$acc exit data detach (YD%RDSDIV)
  !$acc exit data delete (YD%RDSDIV)
ENDIF

LRDSVD = ALLOCATED (YD%RDSVD)
IF (LRDSVD) THEN
  !$acc exit data detach (YD%RDSVD)
  !$acc exit data delete (YD%RDSVD)
ENDIF

LRDHS = ALLOCATED (YD%RDHS)
IF (LRDHS) THEN
  !$acc exit data detach (YD%RDHS)
  !$acc exit data delete (YD%RDHS)
ENDIF

LSLHD_MASK_U = ALLOCATED (YD%SLHD_MASK_U)
IF (LSLHD_MASK_U) THEN
  !$acc exit data detach (YD%SLHD_MASK_U)
  !$acc exit data delete (YD%SLHD_MASK_U)
ENDIF

LSLHD_MASK_T = ALLOCATED (YD%SLHD_MASK_T)
IF (LSLHD_MASK_T) THEN
  !$acc exit data detach (YD%SLHD_MASK_T)
  !$acc exit data delete (YD%SLHD_MASK_T)
ENDIF




LRCORDIT = ALLOCATED (YD%RCORDIT)
IF (LRCORDIT) THEN
  !$acc exit data detach (YD%RCORDIT)
  !$acc exit data delete (YD%RCORDIT)
ENDIF

LRCORDIH = ALLOCATED (YD%RCORDIH)
IF (LRCORDIH) THEN
  !$acc exit data detach (YD%RCORDIH)
  !$acc exit data delete (YD%RCORDIH)
ENDIF

LRCORDIF = ALLOCATED (YD%RCORDIF)
IF (LRCORDIF) THEN
  !$acc exit data detach (YD%RCORDIF)
  !$acc exit data delete (YD%RCORDIF)
ENDIF





LRKRF = ALLOCATED (YD%RKRF)
IF (LRKRF) THEN
  !$acc exit data detach (YD%RKRF)
  !$acc exit data delete (YD%RKRF)
ENDIF











LRGWFRIC = ALLOCATED (YD%RGWFRIC)
IF (LRGWFRIC) THEN
  !$acc exit data detach (YD%RGWFRIC)
  !$acc exit data delete (YD%RGWFRIC)
ENDIF

























LSIALPH = ALLOCATED (YD%SIALPH)
IF (LSIALPH) THEN
  !$acc exit data detach (YD%SIALPH)
  !$acc exit data delete (YD%SIALPH)
ENDIF

LSILNPR = ALLOCATED (YD%SILNPR)
IF (LSILNPR) THEN
  !$acc exit data detach (YD%SILNPR)
  !$acc exit data delete (YD%SILNPR)
ENDIF

LSIDELP = ALLOCATED (YD%SIDELP)
IF (LSIDELP) THEN
  !$acc exit data detach (YD%SIDELP)
  !$acc exit data delete (YD%SIDELP)
ENDIF

LSIRDEL = ALLOCATED (YD%SIRDEL)
IF (LSIRDEL) THEN
  !$acc exit data detach (YD%SIRDEL)
  !$acc exit data delete (YD%SIRDEL)
ENDIF

LSITLAH = ALLOCATED (YD%SITLAH)
IF (LSITLAH) THEN
  !$acc exit data detach (YD%SITLAH)
  !$acc exit data delete (YD%SITLAH)
ENDIF

LSITLAF = ALLOCATED (YD%SITLAF)
IF (LSITLAF) THEN
  !$acc exit data detach (YD%SITLAF)
  !$acc exit data delete (YD%SITLAF)
ENDIF

LSIDPHI = ALLOCATED (YD%SIDPHI)
IF (LSIDPHI) THEN
  !$acc exit data detach (YD%SIDPHI)
  !$acc exit data delete (YD%SIDPHI)
ENDIF

LSIALPH_NH = ALLOCATED (YD%SIALPH_NH)
IF (LSIALPH_NH) THEN
  !$acc exit data detach (YD%SIALPH_NH)
  !$acc exit data delete (YD%SIALPH_NH)
ENDIF

LSILNPR_NH = ALLOCATED (YD%SILNPR_NH)
IF (LSILNPR_NH) THEN
  !$acc exit data detach (YD%SILNPR_NH)
  !$acc exit data delete (YD%SILNPR_NH)
ENDIF

LSIDELP_NH = ALLOCATED (YD%SIDELP_NH)
IF (LSIDELP_NH) THEN
  !$acc exit data detach (YD%SIDELP_NH)
  !$acc exit data delete (YD%SIDELP_NH)
ENDIF

LSIRDEL_NH = ALLOCATED (YD%SIRDEL_NH)
IF (LSIRDEL_NH) THEN
  !$acc exit data detach (YD%SIRDEL_NH)
  !$acc exit data delete (YD%SIRDEL_NH)
ENDIF

LSITLAH_NH = ALLOCATED (YD%SITLAH_NH)
IF (LSITLAH_NH) THEN
  !$acc exit data detach (YD%SITLAH_NH)
  !$acc exit data delete (YD%SITLAH_NH)
ENDIF

LSITLAF_NH = ALLOCATED (YD%SITLAF_NH)
IF (LSITLAF_NH) THEN
  !$acc exit data detach (YD%SITLAF_NH)
  !$acc exit data delete (YD%SITLAF_NH)
ENDIF

LSIDPHI_NH = ALLOCATED (YD%SIDPHI_NH)
IF (LSIDPHI_NH) THEN
  !$acc exit data detach (YD%SIDPHI_NH)
  !$acc exit data delete (YD%SIDPHI_NH)
ENDIF

LSIWF2H = ALLOCATED (YD%SIWF2H)
IF (LSIWF2H) THEN
  !$acc exit data detach (YD%SIWF2H)
  !$acc exit data delete (YD%SIWF2H)
ENDIF

LSIWH2F = ALLOCATED (YD%SIWH2F)
IF (LSIWH2F) THEN
  !$acc exit data detach (YD%SIWH2F)
  !$acc exit data delete (YD%SIWH2F)
ENDIF

LSIGFL = ALLOCATED (YD%SIGFL)
IF (LSIGFL) THEN
  !$acc exit data detach (YD%SIGFL)
  !$acc exit data delete (YD%SIGFL)
ENDIF

LSIGFM = ALLOCATED (YD%SIGFM)
IF (LSIGFM) THEN
  !$acc exit data detach (YD%SIGFM)
  !$acc exit data delete (YD%SIGFM)
ENDIF

LSITFL = ALLOCATED (YD%SITFL)
IF (LSITFL) THEN
  !$acc exit data detach (YD%SITFL)
  !$acc exit data delete (YD%SITFL)
ENDIF

LSITFM = ALLOCATED (YD%SITFM)
IF (LSITFM) THEN
  !$acc exit data detach (YD%SITFM)
  !$acc exit data delete (YD%SITFM)
ENDIF

LSIB = ALLOCATED (YD%SIB)
IF (LSIB) THEN
  !$acc exit data detach (YD%SIB)
  !$acc exit data delete (YD%SIB)
ENDIF

LSIMO = ALLOCATED (YD%SIMO)
IF (LSIMO) THEN
  !$acc exit data detach (YD%SIMO)
  !$acc exit data delete (YD%SIMO)
ENDIF

LSIMI = ALLOCATED (YD%SIMI)
IF (LSIMI) THEN
  !$acc exit data detach (YD%SIMI)
  !$acc exit data delete (YD%SIMI)
ENDIF

LSIVP = ALLOCATED (YD%SIVP)
IF (LSIVP) THEN
  !$acc exit data detach (YD%SIVP)
  !$acc exit data delete (YD%SIVP)
ENDIF

LSIHEG = ALLOCATED (YD%SIHEG)
IF (LSIHEG) THEN
  !$acc exit data detach (YD%SIHEG)
  !$acc exit data delete (YD%SIHEG)
ENDIF

LSIHEG2 = ALLOCATED (YD%SIHEG2)
IF (LSIHEG2) THEN
  !$acc exit data detach (YD%SIHEG2)
  !$acc exit data delete (YD%SIHEG2)
ENDIF

LSIHEGB = ALLOCATED (YD%SIHEGB)
IF (LSIHEGB) THEN
  !$acc exit data detach (YD%SIHEGB)
  !$acc exit data delete (YD%SIHEGB)
ENDIF

LSIHEGB2 = ALLOCATED (YD%SIHEGB2)
IF (LSIHEGB2) THEN
  !$acc exit data detach (YD%SIHEGB2)
  !$acc exit data delete (YD%SIHEGB2)
ENDIF

LSIFAC = ALLOCATED (YD%SIFAC)
IF (LSIFAC) THEN
  !$acc exit data detach (YD%SIFAC)
  !$acc exit data delete (YD%SIFAC)
ENDIF

LSIFACI = ALLOCATED (YD%SIFACI)
IF (LSIFACI) THEN
  !$acc exit data detach (YD%SIFACI)
  !$acc exit data delete (YD%SIFACI)
ENDIF

LSISKAPI = ALLOCATED (YD%SISKAPI)
IF (LSISKAPI) THEN
  !$acc exit data detach (YD%SISKAPI)
  !$acc exit data delete (YD%SISKAPI)
ENDIF

LSITRAM = ALLOCATED (YD%SITRAM)
IF (LSITRAM) THEN
  !$acc exit data detach (YD%SITRAM)
  !$acc exit data delete (YD%SITRAM)
ENDIF



















































































LSIBI = ALLOCATED (YD%SIBI)
IF (LSIBI) THEN
  !$acc exit data detach (YD%SIBI)
  !$acc exit data delete (YD%SIBI)
ENDIF

LLDELETED = .FALSE.
IF (PRESENT (LDDELETED)) THEN
  LLDELETED = LDDELETED
ENDIF
IF (.NOT. LLDELETED) THEN
  !$acc exit data delete (YD)
ENDIF
END SUBROUTINE



END MODULE
