MODULE UTIL_TRADGHG_MOD

USE YOERADGHG, ONLY : TRADGHG

INTERFACE SAVE
MODULE PROCEDURE SAVE_TRADGHG
END INTERFACE

INTERFACE LOAD
MODULE PROCEDURE LOAD_TRADGHG
END INTERFACE

INTERFACE COPY
MODULE PROCEDURE COPY_TRADGHG
END INTERFACE

INTERFACE WIPE
MODULE PROCEDURE WIPE_TRADGHG
END INTERFACE



CONTAINS

SUBROUTINE SAVE_TRADGHG (KLUN, YD)

IMPLICIT NONE
INTEGER, INTENT (IN) :: KLUN
TYPE (TRADGHG), INTENT (IN), TARGET :: YD
LOGICAL :: LMASS_CCL4, LMASS_CFC11, LMASS_CFC12, LMASS_CH4, LMASS_CO2, LMASS_HCFC22, LMASS_N2O, LMASS_NO2, LMASS_O3, LPRESSURE_HL
LOGICAL :: LSINLAT
LSINLAT = ALLOCATED (YD%SINLAT)
WRITE (KLUN) LSINLAT
IF (LSINLAT) THEN
  WRITE (KLUN) LBOUND (YD%SINLAT)
  WRITE (KLUN) UBOUND (YD%SINLAT)
  WRITE (KLUN) YD%SINLAT
ENDIF
LPRESSURE_HL = ALLOCATED (YD%PRESSURE_HL)
WRITE (KLUN) LPRESSURE_HL
IF (LPRESSURE_HL) THEN
  WRITE (KLUN) LBOUND (YD%PRESSURE_HL)
  WRITE (KLUN) UBOUND (YD%PRESSURE_HL)
  WRITE (KLUN) YD%PRESSURE_HL
ENDIF
LMASS_CH4 = ALLOCATED (YD%MASS_CH4)
WRITE (KLUN) LMASS_CH4
IF (LMASS_CH4) THEN
  WRITE (KLUN) LBOUND (YD%MASS_CH4)
  WRITE (KLUN) UBOUND (YD%MASS_CH4)
  WRITE (KLUN) YD%MASS_CH4
ENDIF
LMASS_CO2 = ALLOCATED (YD%MASS_CO2)
WRITE (KLUN) LMASS_CO2
IF (LMASS_CO2) THEN
  WRITE (KLUN) LBOUND (YD%MASS_CO2)
  WRITE (KLUN) UBOUND (YD%MASS_CO2)
  WRITE (KLUN) YD%MASS_CO2
ENDIF
LMASS_N2O = ALLOCATED (YD%MASS_N2O)
WRITE (KLUN) LMASS_N2O
IF (LMASS_N2O) THEN
  WRITE (KLUN) LBOUND (YD%MASS_N2O)
  WRITE (KLUN) UBOUND (YD%MASS_N2O)
  WRITE (KLUN) YD%MASS_N2O
ENDIF
LMASS_NO2 = ALLOCATED (YD%MASS_NO2)
WRITE (KLUN) LMASS_NO2
IF (LMASS_NO2) THEN
  WRITE (KLUN) LBOUND (YD%MASS_NO2)
  WRITE (KLUN) UBOUND (YD%MASS_NO2)
  WRITE (KLUN) YD%MASS_NO2
ENDIF
LMASS_CFC11 = ALLOCATED (YD%MASS_CFC11)
WRITE (KLUN) LMASS_CFC11
IF (LMASS_CFC11) THEN
  WRITE (KLUN) LBOUND (YD%MASS_CFC11)
  WRITE (KLUN) UBOUND (YD%MASS_CFC11)
  WRITE (KLUN) YD%MASS_CFC11
ENDIF
LMASS_CFC12 = ALLOCATED (YD%MASS_CFC12)
WRITE (KLUN) LMASS_CFC12
IF (LMASS_CFC12) THEN
  WRITE (KLUN) LBOUND (YD%MASS_CFC12)
  WRITE (KLUN) UBOUND (YD%MASS_CFC12)
  WRITE (KLUN) YD%MASS_CFC12
ENDIF
LMASS_CCL4 = ALLOCATED (YD%MASS_CCL4)
WRITE (KLUN) LMASS_CCL4
IF (LMASS_CCL4) THEN
  WRITE (KLUN) LBOUND (YD%MASS_CCL4)
  WRITE (KLUN) UBOUND (YD%MASS_CCL4)
  WRITE (KLUN) YD%MASS_CCL4
ENDIF
LMASS_HCFC22 = ALLOCATED (YD%MASS_HCFC22)
WRITE (KLUN) LMASS_HCFC22
IF (LMASS_HCFC22) THEN
  WRITE (KLUN) LBOUND (YD%MASS_HCFC22)
  WRITE (KLUN) UBOUND (YD%MASS_HCFC22)
  WRITE (KLUN) YD%MASS_HCFC22
ENDIF
LMASS_O3 = ALLOCATED (YD%MASS_O3)
WRITE (KLUN) LMASS_O3
IF (LMASS_O3) THEN
  WRITE (KLUN) LBOUND (YD%MASS_O3)
  WRITE (KLUN) UBOUND (YD%MASS_O3)
  WRITE (KLUN) YD%MASS_O3
ENDIF
WRITE (KLUN) YD%NLATITUDE
WRITE (KLUN) YD%NPRESSURE
END SUBROUTINE

SUBROUTINE LOAD_TRADGHG (KLUN, YD)
USE PARKIND1, ONLY : JPRD

IMPLICIT NONE
INTEGER, INTENT (IN) :: KLUN
TYPE (TRADGHG), INTENT (OUT), TARGET :: YD
INTEGER :: IL1(1), IU1(1), IL2(2), IU2(2)
LOGICAL :: LMASS_CCL4, LMASS_CFC11, LMASS_CFC12, LMASS_CH4, LMASS_CO2, LMASS_HCFC22, LMASS_N2O, LMASS_NO2, LMASS_O3, LPRESSURE_HL
LOGICAL :: LSINLAT
REAL(KIND=JPRD), ALLOCATABLE :: ZTMP1 (:)
REAL(KIND=JPRD), ALLOCATABLE :: ZTMP2 (:,:)
READ (KLUN) LSINLAT
IF (LSINLAT) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (YD%SINLAT (IL1(1):IU1(1)))
  ALLOCATE (ZTMP1(LBOUND(YD%SINLAT,1):UBOUND(YD%SINLAT,1)))
  READ (KLUN) ZTMP1
  YD%SINLAT = ZTMP1
  DEALLOCATE (ZTMP1)
ENDIF
READ (KLUN) LPRESSURE_HL
IF (LPRESSURE_HL) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (YD%PRESSURE_HL (IL1(1):IU1(1)))
  ALLOCATE (ZTMP1(LBOUND(YD%PRESSURE_HL,1):UBOUND(YD%PRESSURE_HL,1)))
  READ (KLUN) ZTMP1
  YD%PRESSURE_HL = ZTMP1
  DEALLOCATE (ZTMP1)
ENDIF
READ (KLUN) LMASS_CH4
IF (LMASS_CH4) THEN
  READ (KLUN) IL2
  READ (KLUN) IU2
  ALLOCATE (YD%MASS_CH4 (IL2(1):IU2(1), IL2(2):IU2(2)))
  ALLOCATE (ZTMP2(LBOUND(YD%MASS_CH4,1):UBOUND(YD%MASS_CH4,1), LBOUND(YD%MASS_CH4,2):UBOUND(YD%MASS_CH4,2)))
  READ (KLUN) ZTMP2
  YD%MASS_CH4 = ZTMP2
  DEALLOCATE (ZTMP2)
ENDIF
READ (KLUN) LMASS_CO2
IF (LMASS_CO2) THEN
  READ (KLUN) IL2
  READ (KLUN) IU2
  ALLOCATE (YD%MASS_CO2 (IL2(1):IU2(1), IL2(2):IU2(2)))
  ALLOCATE (ZTMP2(LBOUND(YD%MASS_CO2,1):UBOUND(YD%MASS_CO2,1), LBOUND(YD%MASS_CO2,2):UBOUND(YD%MASS_CO2,2)))
  READ (KLUN) ZTMP2
  YD%MASS_CO2 = ZTMP2
  DEALLOCATE (ZTMP2)
ENDIF
READ (KLUN) LMASS_N2O
IF (LMASS_N2O) THEN
  READ (KLUN) IL2
  READ (KLUN) IU2
  ALLOCATE (YD%MASS_N2O (IL2(1):IU2(1), IL2(2):IU2(2)))
  ALLOCATE (ZTMP2(LBOUND(YD%MASS_N2O,1):UBOUND(YD%MASS_N2O,1), LBOUND(YD%MASS_N2O,2):UBOUND(YD%MASS_N2O,2)))
  READ (KLUN) ZTMP2
  YD%MASS_N2O = ZTMP2
  DEALLOCATE (ZTMP2)
ENDIF
READ (KLUN) LMASS_NO2
IF (LMASS_NO2) THEN
  READ (KLUN) IL2
  READ (KLUN) IU2
  ALLOCATE (YD%MASS_NO2 (IL2(1):IU2(1), IL2(2):IU2(2)))
  ALLOCATE (ZTMP2(LBOUND(YD%MASS_NO2,1):UBOUND(YD%MASS_NO2,1), LBOUND(YD%MASS_NO2,2):UBOUND(YD%MASS_NO2,2)))
  READ (KLUN) ZTMP2
  YD%MASS_NO2 = ZTMP2
  DEALLOCATE (ZTMP2)
ENDIF
READ (KLUN) LMASS_CFC11
IF (LMASS_CFC11) THEN
  READ (KLUN) IL2
  READ (KLUN) IU2
  ALLOCATE (YD%MASS_CFC11 (IL2(1):IU2(1), IL2(2):IU2(2)))
  ALLOCATE (ZTMP2(LBOUND(YD%MASS_CFC11,1):UBOUND(YD%MASS_CFC11,1), LBOUND(YD%MASS_CFC11,2):UBOUND(YD%MASS_CFC11,2)))
  READ (KLUN) ZTMP2
  YD%MASS_CFC11 = ZTMP2
  DEALLOCATE (ZTMP2)
ENDIF
READ (KLUN) LMASS_CFC12
IF (LMASS_CFC12) THEN
  READ (KLUN) IL2
  READ (KLUN) IU2
  ALLOCATE (YD%MASS_CFC12 (IL2(1):IU2(1), IL2(2):IU2(2)))
  ALLOCATE (ZTMP2(LBOUND(YD%MASS_CFC12,1):UBOUND(YD%MASS_CFC12,1), LBOUND(YD%MASS_CFC12,2):UBOUND(YD%MASS_CFC12,2)))
  READ (KLUN) ZTMP2
  YD%MASS_CFC12 = ZTMP2
  DEALLOCATE (ZTMP2)
ENDIF
READ (KLUN) LMASS_CCL4
IF (LMASS_CCL4) THEN
  READ (KLUN) IL2
  READ (KLUN) IU2
  ALLOCATE (YD%MASS_CCL4 (IL2(1):IU2(1), IL2(2):IU2(2)))
  ALLOCATE (ZTMP2(LBOUND(YD%MASS_CCL4,1):UBOUND(YD%MASS_CCL4,1), LBOUND(YD%MASS_CCL4,2):UBOUND(YD%MASS_CCL4,2)))
  READ (KLUN) ZTMP2
  YD%MASS_CCL4 = ZTMP2
  DEALLOCATE (ZTMP2)
ENDIF
READ (KLUN) LMASS_HCFC22
IF (LMASS_HCFC22) THEN
  READ (KLUN) IL2
  READ (KLUN) IU2
  ALLOCATE (YD%MASS_HCFC22 (IL2(1):IU2(1), IL2(2):IU2(2)))
  ALLOCATE (ZTMP2(LBOUND(YD%MASS_HCFC22,1):UBOUND(YD%MASS_HCFC22,1), LBOUND(YD%MASS_HCFC22,2):UBOUND(YD%MASS_HCFC22,2)))
  READ (KLUN) ZTMP2
  YD%MASS_HCFC22 = ZTMP2
  DEALLOCATE (ZTMP2)
ENDIF
READ (KLUN) LMASS_O3
IF (LMASS_O3) THEN
  READ (KLUN) IL2
  READ (KLUN) IU2
  ALLOCATE (YD%MASS_O3 (IL2(1):IU2(1), IL2(2):IU2(2)))
  ALLOCATE (ZTMP2(LBOUND(YD%MASS_O3,1):UBOUND(YD%MASS_O3,1), LBOUND(YD%MASS_O3,2):UBOUND(YD%MASS_O3,2)))
  READ (KLUN) ZTMP2
  YD%MASS_O3 = ZTMP2
  DEALLOCATE (ZTMP2)
ENDIF
READ (KLUN) YD%NLATITUDE
READ (KLUN) YD%NPRESSURE
END SUBROUTINE


SUBROUTINE COPY_TRADGHG (YD, LDCREATED)

IMPLICIT NONE
TYPE (TRADGHG), INTENT (IN), TARGET :: YD
LOGICAL, OPTIONAL, INTENT (IN) :: LDCREATED
LOGICAL :: LLCREATED
LOGICAL :: LMASS_CCL4, LMASS_CFC11, LMASS_CFC12, LMASS_CH4, LMASS_CO2, LMASS_HCFC22, LMASS_N2O, LMASS_NO2, LMASS_O3, LPRESSURE_HL
LOGICAL :: LSINLAT

LLCREATED = .FALSE.
IF (PRESENT (LDCREATED)) THEN
  LLCREATED = LDCREATED
ENDIF
IF (.NOT. LLCREATED) THEN
  !$acc enter data create (YD)
  !$acc update device (YD)
ENDIF
LSINLAT = ALLOCATED (YD%SINLAT)
IF (LSINLAT) THEN
  !$acc enter data create (YD%SINLAT)
  !$acc update device (YD%SINLAT)
  !$acc enter data attach (YD%SINLAT)
ENDIF

LPRESSURE_HL = ALLOCATED (YD%PRESSURE_HL)
IF (LPRESSURE_HL) THEN
  !$acc enter data create (YD%PRESSURE_HL)
  !$acc update device (YD%PRESSURE_HL)
  !$acc enter data attach (YD%PRESSURE_HL)
ENDIF

LMASS_CH4 = ALLOCATED (YD%MASS_CH4)
IF (LMASS_CH4) THEN
  !$acc enter data create (YD%MASS_CH4)
  !$acc update device (YD%MASS_CH4)
  !$acc enter data attach (YD%MASS_CH4)
ENDIF

LMASS_CO2 = ALLOCATED (YD%MASS_CO2)
IF (LMASS_CO2) THEN
  !$acc enter data create (YD%MASS_CO2)
  !$acc update device (YD%MASS_CO2)
  !$acc enter data attach (YD%MASS_CO2)
ENDIF

LMASS_N2O = ALLOCATED (YD%MASS_N2O)
IF (LMASS_N2O) THEN
  !$acc enter data create (YD%MASS_N2O)
  !$acc update device (YD%MASS_N2O)
  !$acc enter data attach (YD%MASS_N2O)
ENDIF

LMASS_NO2 = ALLOCATED (YD%MASS_NO2)
IF (LMASS_NO2) THEN
  !$acc enter data create (YD%MASS_NO2)
  !$acc update device (YD%MASS_NO2)
  !$acc enter data attach (YD%MASS_NO2)
ENDIF

LMASS_CFC11 = ALLOCATED (YD%MASS_CFC11)
IF (LMASS_CFC11) THEN
  !$acc enter data create (YD%MASS_CFC11)
  !$acc update device (YD%MASS_CFC11)
  !$acc enter data attach (YD%MASS_CFC11)
ENDIF

LMASS_CFC12 = ALLOCATED (YD%MASS_CFC12)
IF (LMASS_CFC12) THEN
  !$acc enter data create (YD%MASS_CFC12)
  !$acc update device (YD%MASS_CFC12)
  !$acc enter data attach (YD%MASS_CFC12)
ENDIF

LMASS_CCL4 = ALLOCATED (YD%MASS_CCL4)
IF (LMASS_CCL4) THEN
  !$acc enter data create (YD%MASS_CCL4)
  !$acc update device (YD%MASS_CCL4)
  !$acc enter data attach (YD%MASS_CCL4)
ENDIF

LMASS_HCFC22 = ALLOCATED (YD%MASS_HCFC22)
IF (LMASS_HCFC22) THEN
  !$acc enter data create (YD%MASS_HCFC22)
  !$acc update device (YD%MASS_HCFC22)
  !$acc enter data attach (YD%MASS_HCFC22)
ENDIF

LMASS_O3 = ALLOCATED (YD%MASS_O3)
IF (LMASS_O3) THEN
  !$acc enter data create (YD%MASS_O3)
  !$acc update device (YD%MASS_O3)
  !$acc enter data attach (YD%MASS_O3)
ENDIF



END SUBROUTINE

SUBROUTINE WIPE_TRADGHG (YD, LDDELETED)

IMPLICIT NONE
TYPE (TRADGHG), INTENT (IN), TARGET :: YD
LOGICAL, OPTIONAL, INTENT (IN) :: LDDELETED
LOGICAL :: LLDELETED
LOGICAL :: LMASS_CCL4, LMASS_CFC11, LMASS_CFC12, LMASS_CH4, LMASS_CO2, LMASS_HCFC22, LMASS_N2O, LMASS_NO2, LMASS_O3, LPRESSURE_HL
LOGICAL :: LSINLAT

LSINLAT = ALLOCATED (YD%SINLAT)
IF (LSINLAT) THEN
  !$acc exit data detach (YD%SINLAT)
  !$acc exit data delete (YD%SINLAT)
ENDIF

LPRESSURE_HL = ALLOCATED (YD%PRESSURE_HL)
IF (LPRESSURE_HL) THEN
  !$acc exit data detach (YD%PRESSURE_HL)
  !$acc exit data delete (YD%PRESSURE_HL)
ENDIF

LMASS_CH4 = ALLOCATED (YD%MASS_CH4)
IF (LMASS_CH4) THEN
  !$acc exit data detach (YD%MASS_CH4)
  !$acc exit data delete (YD%MASS_CH4)
ENDIF

LMASS_CO2 = ALLOCATED (YD%MASS_CO2)
IF (LMASS_CO2) THEN
  !$acc exit data detach (YD%MASS_CO2)
  !$acc exit data delete (YD%MASS_CO2)
ENDIF

LMASS_N2O = ALLOCATED (YD%MASS_N2O)
IF (LMASS_N2O) THEN
  !$acc exit data detach (YD%MASS_N2O)
  !$acc exit data delete (YD%MASS_N2O)
ENDIF

LMASS_NO2 = ALLOCATED (YD%MASS_NO2)
IF (LMASS_NO2) THEN
  !$acc exit data detach (YD%MASS_NO2)
  !$acc exit data delete (YD%MASS_NO2)
ENDIF

LMASS_CFC11 = ALLOCATED (YD%MASS_CFC11)
IF (LMASS_CFC11) THEN
  !$acc exit data detach (YD%MASS_CFC11)
  !$acc exit data delete (YD%MASS_CFC11)
ENDIF

LMASS_CFC12 = ALLOCATED (YD%MASS_CFC12)
IF (LMASS_CFC12) THEN
  !$acc exit data detach (YD%MASS_CFC12)
  !$acc exit data delete (YD%MASS_CFC12)
ENDIF

LMASS_CCL4 = ALLOCATED (YD%MASS_CCL4)
IF (LMASS_CCL4) THEN
  !$acc exit data detach (YD%MASS_CCL4)
  !$acc exit data delete (YD%MASS_CCL4)
ENDIF

LMASS_HCFC22 = ALLOCATED (YD%MASS_HCFC22)
IF (LMASS_HCFC22) THEN
  !$acc exit data detach (YD%MASS_HCFC22)
  !$acc exit data delete (YD%MASS_HCFC22)
ENDIF

LMASS_O3 = ALLOCATED (YD%MASS_O3)
IF (LMASS_O3) THEN
  !$acc exit data detach (YD%MASS_O3)
  !$acc exit data delete (YD%MASS_O3)
ENDIF



LLDELETED = .FALSE.
IF (PRESENT (LDDELETED)) THEN
  LLDELETED = LDDELETED
ENDIF
IF (.NOT. LLDELETED) THEN
  !$acc exit data delete (YD)
ENDIF
END SUBROUTINE



END MODULE
