MODULE UTIL_MODEL_DIAGNOSTICS_TYPE_MOD

USE MODEL_DIAGNOSTICS_MOD, ONLY : MODEL_DIAGNOSTICS_TYPE

INTERFACE SAVE
MODULE PROCEDURE SAVE_MODEL_DIAGNOSTICS_TYPE
END INTERFACE

INTERFACE LOAD
MODULE PROCEDURE LOAD_MODEL_DIAGNOSTICS_TYPE
END INTERFACE

INTERFACE COPY
MODULE PROCEDURE COPY_MODEL_DIAGNOSTICS_TYPE
END INTERFACE

INTERFACE WIPE
MODULE PROCEDURE WIPE_MODEL_DIAGNOSTICS_TYPE
END INTERFACE



CONTAINS

SUBROUTINE SAVE_MODEL_DIAGNOSTICS_TYPE (KLUN, YD)
USE UTIL_TLDDH_MOD
USE UTIL_TSPDDH_MOD
IMPLICIT NONE
INTEGER, INTENT (IN) :: KLUN
TYPE (MODEL_DIAGNOSTICS_TYPE), INTENT (IN), TARGET :: YD

CALL SAVE (KLUN, YD%YRLDDH)
CALL SAVE (KLUN, YD%YRSPDDH)
END SUBROUTINE

SUBROUTINE LOAD_MODEL_DIAGNOSTICS_TYPE (KLUN, YD)
USE UTIL_TLDDH_MOD
USE UTIL_TSPDDH_MOD

IMPLICIT NONE
INTEGER, INTENT (IN) :: KLUN
TYPE (MODEL_DIAGNOSTICS_TYPE), INTENT (OUT), TARGET :: YD

CALL LOAD (KLUN, YD%YRLDDH)
CALL LOAD (KLUN, YD%YRSPDDH)
END SUBROUTINE


SUBROUTINE COPY_MODEL_DIAGNOSTICS_TYPE (YD, LDCREATED)
USE UTIL_TLDDH_MOD
USE UTIL_TSPDDH_MOD
IMPLICIT NONE
TYPE (MODEL_DIAGNOSTICS_TYPE), INTENT (IN), TARGET :: YD
LOGICAL, OPTIONAL, INTENT (IN) :: LDCREATED
LOGICAL :: LLCREATED

LLCREATED = .FALSE.
IF (PRESENT (LDCREATED)) THEN
  LLCREATED = LDCREATED
ENDIF
IF (.NOT. LLCREATED) THEN
  !$acc enter data create (YD)
  !$acc update device (YD)
ENDIF
CALL COPY (YD%YRLDDH, LDCREATED=.TRUE.)

CALL COPY (YD%YRSPDDH, LDCREATED=.TRUE.)

END SUBROUTINE

SUBROUTINE WIPE_MODEL_DIAGNOSTICS_TYPE (YD, LDDELETED)
USE UTIL_TLDDH_MOD
USE UTIL_TSPDDH_MOD
IMPLICIT NONE
TYPE (MODEL_DIAGNOSTICS_TYPE), INTENT (IN), TARGET :: YD
LOGICAL, OPTIONAL, INTENT (IN) :: LDDELETED
LOGICAL :: LLDELETED

CALL WIPE (YD%YRLDDH, LDDELETED=.TRUE.)

CALL WIPE (YD%YRSPDDH, LDDELETED=.TRUE.)

LLDELETED = .FALSE.
IF (PRESENT (LDDELETED)) THEN
  LLDELETED = LDDELETED
ENDIF
IF (.NOT. LLDELETED) THEN
  !$acc exit data delete (YD)
ENDIF
END SUBROUTINE



END MODULE
