MODULE UTIL_TCVER_MOD

USE YOMCVER, ONLY : TCVER

INTERFACE SAVE
MODULE PROCEDURE SAVE_TCVER
END INTERFACE

INTERFACE LOAD
MODULE PROCEDURE LOAD_TCVER
END INTERFACE

INTERFACE COPY
MODULE PROCEDURE COPY_TCVER
END INTERFACE

INTERFACE WIPE
MODULE PROCEDURE WIPE_TCVER
END INTERFACE



CONTAINS

SUBROUTINE SAVE_TCVER (KLUN, YD)

IMPLICIT NONE
INTEGER, INTENT (IN) :: KLUN
TYPE (TCVER), INTENT (IN), TARGET :: YD

WRITE (KLUN) YD%LAPRXPK
WRITE (KLUN) YD%NDLNPR
WRITE (KLUN) YD%RHYDR0
WRITE (KLUN) YD%LREGETA
WRITE (KLUN) YD%LVFE_REGETA
WRITE (KLUN) YD%NVFE_TYPE
WRITE (KLUN) YD%NVFE_ORDER
WRITE (KLUN) YD%NVFE_INTERNALS
WRITE (KLUN) YD%LVERTFE
WRITE (KLUN) YD%LVFE_LAPL_BC
WRITE (KLUN) YD%LVFE_GW
WRITE (KLUN) YD%LVFE_GW_HALF
WRITE (KLUN) YD%LVFE_GWMPA
WRITE (KLUN) YD%LVFE_CHEB
WRITE (KLUN) YD%LVFE_ECMWF
WRITE (KLUN) YD%LVFE_NOBC
WRITE (KLUN) YD%LVFE_VERBOSE
WRITE (KLUN) YD%LVFE_NORMALIZE
WRITE (KLUN) YD%LDYN_ANALYSIS_STABILITY
WRITE (KLUN) YD%LPERCENTILS
WRITE (KLUN) YD%LVFE_COMPATIBLE
WRITE (KLUN) YD%LVFE_FD_MIX
WRITE (KLUN) YD%LVFD_COMPATIBLE
WRITE (KLUN) YD%RVFE_ALPHA
WRITE (KLUN) YD%RVFE_BETA
WRITE (KLUN) YD%RVFE_KNOT_STRETCH
WRITE (KLUN) YD%RFAC1
WRITE (KLUN) YD%RFAC2
WRITE (KLUN) YD%CVFE_ETAH
END SUBROUTINE

SUBROUTINE LOAD_TCVER (KLUN, YD)
USE PARKIND1, ONLY : JPRD

IMPLICIT NONE
INTEGER, INTENT (IN) :: KLUN
TYPE (TCVER), INTENT (OUT), TARGET :: YD
REAL(KIND=JPRD) :: ZTMP0
READ (KLUN) YD%LAPRXPK
READ (KLUN) YD%NDLNPR
READ (KLUN) ZTMP0
YD%RHYDR0 = ZTMP0
READ (KLUN) YD%LREGETA
READ (KLUN) YD%LVFE_REGETA
READ (KLUN) YD%NVFE_TYPE
READ (KLUN) YD%NVFE_ORDER
READ (KLUN) YD%NVFE_INTERNALS
READ (KLUN) YD%LVERTFE
READ (KLUN) YD%LVFE_LAPL_BC
READ (KLUN) YD%LVFE_GW
READ (KLUN) YD%LVFE_GW_HALF
READ (KLUN) YD%LVFE_GWMPA
READ (KLUN) YD%LVFE_CHEB
READ (KLUN) YD%LVFE_ECMWF
READ (KLUN) YD%LVFE_NOBC
READ (KLUN) YD%LVFE_VERBOSE
READ (KLUN) YD%LVFE_NORMALIZE
READ (KLUN) YD%LDYN_ANALYSIS_STABILITY
READ (KLUN) YD%LPERCENTILS
READ (KLUN) YD%LVFE_COMPATIBLE
READ (KLUN) YD%LVFE_FD_MIX
READ (KLUN) YD%LVFD_COMPATIBLE
READ (KLUN) ZTMP0
YD%RVFE_ALPHA = ZTMP0
READ (KLUN) ZTMP0
YD%RVFE_BETA = ZTMP0
READ (KLUN) ZTMP0
YD%RVFE_KNOT_STRETCH = ZTMP0
READ (KLUN) ZTMP0
YD%RFAC1 = ZTMP0
READ (KLUN) ZTMP0
YD%RFAC2 = ZTMP0
READ (KLUN) YD%CVFE_ETAH
END SUBROUTINE


SUBROUTINE COPY_TCVER (YD, LDCREATED)

IMPLICIT NONE
TYPE (TCVER), INTENT (IN), TARGET :: YD
LOGICAL, OPTIONAL, INTENT (IN) :: LDCREATED
LOGICAL :: LLCREATED

LLCREATED = .FALSE.
IF (PRESENT (LDCREATED)) THEN
  LLCREATED = LDCREATED
ENDIF
IF (.NOT. LLCREATED) THEN
  !$acc enter data create (YD)
  !$acc update device (YD)
ENDIF





























END SUBROUTINE

SUBROUTINE WIPE_TCVER (YD, LDDELETED)

IMPLICIT NONE
TYPE (TCVER), INTENT (IN), TARGET :: YD
LOGICAL, OPTIONAL, INTENT (IN) :: LDDELETED
LOGICAL :: LLDELETED






























LLDELETED = .FALSE.
IF (PRESENT (LDDELETED)) THEN
  LLDELETED = LDDELETED
ENDIF
IF (.NOT. LLDELETED) THEN
  !$acc exit data delete (YD)
ENDIF
END SUBROUTINE



END MODULE
