MODULE UTIL_YOMMP0_MOD

USE YOMMP0









CONTAINS

SUBROUTINE SAVE_YOMMP0 (KLUN)

IMPLICIT NONE
INTEGER, INTENT (IN) :: KLUN

LOGICAL :: LNGPSET2PE, LNPRCIDS, LN_REGIONS
LNPRCIDS = ALLOCATED (NPRCIDS)
WRITE (KLUN) LNPRCIDS
IF (LNPRCIDS) THEN
  WRITE (KLUN) LBOUND (NPRCIDS)
  WRITE (KLUN) UBOUND (NPRCIDS)
  WRITE (KLUN) NPRCIDS
ENDIF
LNGPSET2PE = ALLOCATED (NGPSET2PE)
WRITE (KLUN) LNGPSET2PE
IF (LNGPSET2PE) THEN
  WRITE (KLUN) LBOUND (NGPSET2PE)
  WRITE (KLUN) UBOUND (NGPSET2PE)
  WRITE (KLUN) NGPSET2PE
ENDIF
WRITE (KLUN) N_REGIONS_NS
WRITE (KLUN) N_REGIONS_EW
LN_REGIONS = ALLOCATED (N_REGIONS)
WRITE (KLUN) LN_REGIONS
IF (LN_REGIONS) THEN
  WRITE (KLUN) LBOUND (N_REGIONS)
  WRITE (KLUN) UBOUND (N_REGIONS)
  WRITE (KLUN) N_REGIONS
ENDIF
WRITE (KLUN) LSPLIT
WRITE (KLUN) LEQ_REGIONS
WRITE (KLUN) LSPLITOUT
WRITE (KLUN) LSYNC_SLCOM
WRITE (KLUN) LSYNC_TRANS
WRITE (KLUN) LSLDEBUG
WRITE (KLUN) LSLONDEM
WRITE (KLUN) LGPTOT_CAP
WRITE (KLUN) MP_TYPE
WRITE (KLUN) MBX_SIZE
WRITE (KLUN) MYPROC
WRITE (KLUN) MYSETA
WRITE (KLUN) MYSETB
WRITE (KLUN) MYSETW
WRITE (KLUN) MYSETV
WRITE (KLUN) MYSETM
WRITE (KLUN) MYSETN
WRITE (KLUN) MY_REGION_NS
WRITE (KLUN) MY_REGION_EW
WRITE (KLUN) NFLDIN
WRITE (KLUN) NSLPAD
WRITE (KLUN) NOUTTYPE
WRITE (KLUN) NWRTOUT
WRITE (KLUN) NDISTIO
WRITE (KLUN) LUSEWRGRIDALL
WRITE (KLUN) NCOMBFLEN
WRITE (KLUN) LMPOFF
WRITE (KLUN) NSPECRESMIN
WRITE (KLUN) LOUTPUT
WRITE (KLUN) NOUTPUT
WRITE (KLUN) NPRINTLEV
WRITE (KLUN) LMPDIAG
WRITE (KLUN) LOPT_SCALAR
WRITE (KLUN) LVECADIN
WRITE (KLUN) LOPT_RS6K
WRITE (KLUN) LSCMEC
WRITE (KLUN) NTRANS_SYNC_LEVEL
WRITE (KLUN) NPROC
WRITE (KLUN) NPRGPNS
WRITE (KLUN) NPRGPEW
WRITE (KLUN) NPRTRNS
WRITE (KLUN) NPRTRN
WRITE (KLUN) NPRTRW
WRITE (KLUN) NPRTRV
WRITE (KLUN) NSTRIN
WRITE (KLUN) NSTROUT
WRITE (KLUN) M_BARRINC_DIWRGRID
WRITE (KLUN) L_GATHERV_WRGP
END SUBROUTINE

SUBROUTINE LOAD_YOMMP0 (KLUN)

IMPLICIT NONE
INTEGER, INTENT (IN) :: KLUN

INTEGER :: IL1(1), IU1(1), IL2(2), IU2(2)
LOGICAL :: LNGPSET2PE, LNPRCIDS, LN_REGIONS
READ (KLUN) LNPRCIDS
IF (LNPRCIDS) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (NPRCIDS (IL1(1):IU1(1)))
  READ (KLUN) NPRCIDS
ENDIF
READ (KLUN) LNGPSET2PE
IF (LNGPSET2PE) THEN
  READ (KLUN) IL2
  READ (KLUN) IU2
  ALLOCATE (NGPSET2PE (IL2(1):IU2(1), IL2(2):IU2(2)))
  READ (KLUN) NGPSET2PE
ENDIF
READ (KLUN) N_REGIONS_NS
READ (KLUN) N_REGIONS_EW
READ (KLUN) LN_REGIONS
IF (LN_REGIONS) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (N_REGIONS (IL1(1):IU1(1)))
  READ (KLUN) N_REGIONS
ENDIF
READ (KLUN) LSPLIT
READ (KLUN) LEQ_REGIONS
READ (KLUN) LSPLITOUT
READ (KLUN) LSYNC_SLCOM
READ (KLUN) LSYNC_TRANS
READ (KLUN) LSLDEBUG
READ (KLUN) LSLONDEM
READ (KLUN) LGPTOT_CAP
READ (KLUN) MP_TYPE
READ (KLUN) MBX_SIZE
READ (KLUN) MYPROC
READ (KLUN) MYSETA
READ (KLUN) MYSETB
READ (KLUN) MYSETW
READ (KLUN) MYSETV
READ (KLUN) MYSETM
READ (KLUN) MYSETN
READ (KLUN) MY_REGION_NS
READ (KLUN) MY_REGION_EW
READ (KLUN) NFLDIN
READ (KLUN) NSLPAD
READ (KLUN) NOUTTYPE
READ (KLUN) NWRTOUT
READ (KLUN) NDISTIO
READ (KLUN) LUSEWRGRIDALL
READ (KLUN) NCOMBFLEN
READ (KLUN) LMPOFF
READ (KLUN) NSPECRESMIN
READ (KLUN) LOUTPUT
READ (KLUN) NOUTPUT
READ (KLUN) NPRINTLEV
READ (KLUN) LMPDIAG
READ (KLUN) LOPT_SCALAR
READ (KLUN) LVECADIN
READ (KLUN) LOPT_RS6K
READ (KLUN) LSCMEC
READ (KLUN) NTRANS_SYNC_LEVEL
READ (KLUN) NPROC
READ (KLUN) NPRGPNS
READ (KLUN) NPRGPEW
READ (KLUN) NPRTRNS
READ (KLUN) NPRTRN
READ (KLUN) NPRTRW
READ (KLUN) NPRTRV
READ (KLUN) NSTRIN
READ (KLUN) NSTROUT
READ (KLUN) M_BARRINC_DIWRGRID
READ (KLUN) L_GATHERV_WRGP
END SUBROUTINE








END MODULE
