MODULE UTIL_MODEL_DYNAMICS_TYPE_MOD

USE MODEL_DYNAMICS_MOD, ONLY : MODEL_DYNAMICS_TYPE

INTERFACE SAVE
MODULE PROCEDURE SAVE_MODEL_DYNAMICS_TYPE
END INTERFACE

INTERFACE LOAD
MODULE PROCEDURE LOAD_MODEL_DYNAMICS_TYPE
END INTERFACE

INTERFACE COPY
MODULE PROCEDURE COPY_MODEL_DYNAMICS_TYPE
END INTERFACE

INTERFACE WIPE
MODULE PROCEDURE WIPE_MODEL_DYNAMICS_TYPE
END INTERFACE



CONTAINS

SUBROUTINE SAVE_MODEL_DYNAMICS_TYPE (KLUN, YD)
USE UTIL_TDYNA_MOD
USE UTIL_TDYN_MOD
IMPLICIT NONE
INTEGER, INTENT (IN) :: KLUN
TYPE (MODEL_DYNAMICS_TYPE), INTENT (IN), TARGET :: YD

CALL SAVE (KLUN, YD%YRDYNA)
CALL SAVE (KLUN, YD%YRDYN)
END SUBROUTINE

SUBROUTINE LOAD_MODEL_DYNAMICS_TYPE (KLUN, YD)
USE UTIL_TDYNA_MOD
USE UTIL_TDYN_MOD

IMPLICIT NONE
INTEGER, INTENT (IN) :: KLUN
TYPE (MODEL_DYNAMICS_TYPE), INTENT (OUT), TARGET :: YD

CALL LOAD (KLUN, YD%YRDYNA)
CALL LOAD (KLUN, YD%YRDYN)
END SUBROUTINE


SUBROUTINE COPY_MODEL_DYNAMICS_TYPE (YD, LDCREATED)
USE UTIL_TDYNA_MOD
USE UTIL_TDYN_MOD
IMPLICIT NONE
TYPE (MODEL_DYNAMICS_TYPE), INTENT (IN), TARGET :: YD
LOGICAL, OPTIONAL, INTENT (IN) :: LDCREATED
LOGICAL :: LLCREATED

LLCREATED = .FALSE.
IF (PRESENT (LDCREATED)) THEN
  LLCREATED = LDCREATED
ENDIF
IF (.NOT. LLCREATED) THEN
  !$acc enter data create (YD)
  !$acc update device (YD)
ENDIF
CALL COPY (YD%YRDYNA, LDCREATED=.TRUE.)

CALL COPY (YD%YRDYN, LDCREATED=.TRUE.)

END SUBROUTINE

SUBROUTINE WIPE_MODEL_DYNAMICS_TYPE (YD, LDDELETED)
USE UTIL_TDYNA_MOD
USE UTIL_TDYN_MOD
IMPLICIT NONE
TYPE (MODEL_DYNAMICS_TYPE), INTENT (IN), TARGET :: YD
LOGICAL, OPTIONAL, INTENT (IN) :: LDDELETED
LOGICAL :: LLDELETED

CALL WIPE (YD%YRDYNA, LDDELETED=.TRUE.)

CALL WIPE (YD%YRDYN, LDDELETED=.TRUE.)

LLDELETED = .FALSE.
IF (PRESENT (LDDELETED)) THEN
  LLDELETED = LDDELETED
ENDIF
IF (.NOT. LLDELETED) THEN
  !$acc exit data delete (YD)
ENDIF
END SUBROUTINE



END MODULE
