MODULE UTIL_TCTY_MOD

USE INTDYN_MOD, ONLY : TCTY

INTERFACE SAVE
MODULE PROCEDURE SAVE_TCTY
END INTERFACE

INTERFACE LOAD
MODULE PROCEDURE LOAD_TCTY
END INTERFACE

INTERFACE COPY
MODULE PROCEDURE COPY_TCTY
END INTERFACE

INTERFACE WIPE
MODULE PROCEDURE WIPE_TCTY
END INTERFACE



CONTAINS

SUBROUTINE SAVE_TCTY (KLUN, YD)

IMPLICIT NONE
INTEGER, INTENT (IN) :: KLUN
TYPE (TCTY), INTENT (IN), TARGET :: YD

WRITE (KLUN) YD%M_EVEL
WRITE (KLUN) YD%M_VVEL
WRITE (KLUN) YD%M_PSDIV
WRITE (KLUN) YD%M_PSDVBC
WRITE (KLUN) YD%M_DIVDP
WRITE (KLUN) YD%NDIM
END SUBROUTINE

SUBROUTINE LOAD_TCTY (KLUN, YD)

IMPLICIT NONE
INTEGER, INTENT (IN) :: KLUN
TYPE (TCTY), INTENT (OUT), TARGET :: YD

READ (KLUN) YD%M_EVEL
READ (KLUN) YD%M_VVEL
READ (KLUN) YD%M_PSDIV
READ (KLUN) YD%M_PSDVBC
READ (KLUN) YD%M_DIVDP
READ (KLUN) YD%NDIM
END SUBROUTINE


SUBROUTINE COPY_TCTY (YD, LDCREATED)

IMPLICIT NONE
TYPE (TCTY), INTENT (IN), TARGET :: YD
LOGICAL, OPTIONAL, INTENT (IN) :: LDCREATED
LOGICAL :: LLCREATED

LLCREATED = .FALSE.
IF (PRESENT (LDCREATED)) THEN
  LLCREATED = LDCREATED
ENDIF
IF (.NOT. LLCREATED) THEN
  !$acc enter data create (YD)
  !$acc update device (YD)
ENDIF






END SUBROUTINE

SUBROUTINE WIPE_TCTY (YD, LDDELETED)

IMPLICIT NONE
TYPE (TCTY), INTENT (IN), TARGET :: YD
LOGICAL, OPTIONAL, INTENT (IN) :: LDDELETED
LOGICAL :: LLDELETED







LLDELETED = .FALSE.
IF (PRESENT (LDDELETED)) THEN
  LLDELETED = LDDELETED
ENDIF
IF (.NOT. LLDELETED) THEN
  !$acc exit data delete (YD)
ENDIF
END SUBROUTINE



END MODULE
