MODULE UTIL_TEOZOC_MOD

USE YOEOZOC, ONLY : TEOZOC

INTERFACE SAVE
MODULE PROCEDURE SAVE_TEOZOC
END INTERFACE

INTERFACE LOAD
MODULE PROCEDURE LOAD_TEOZOC
END INTERFACE

INTERFACE COPY
MODULE PROCEDURE COPY_TEOZOC
END INTERFACE

INTERFACE WIPE
MODULE PROCEDURE WIPE_TEOZOC
END INTERFACE



CONTAINS

SUBROUTINE SAVE_TEOZOC (KLUN, YD)

IMPLICIT NONE
INTEGER, INTENT (IN) :: KLUN
TYPE (TEOZOC), INTENT (IN), TARGET :: YD
LOGICAL :: LZOZCL, LZOZCLAQUA
LZOZCL = ALLOCATED (YD%ZOZCL)
WRITE (KLUN) LZOZCL
IF (LZOZCL) THEN
  WRITE (KLUN) LBOUND (YD%ZOZCL)
  WRITE (KLUN) UBOUND (YD%ZOZCL)
  WRITE (KLUN) YD%ZOZCL
ENDIF
LZOZCLAQUA = ALLOCATED (YD%ZOZCLAQUA)
WRITE (KLUN) LZOZCLAQUA
IF (LZOZCLAQUA) THEN
  WRITE (KLUN) LBOUND (YD%ZOZCLAQUA)
  WRITE (KLUN) UBOUND (YD%ZOZCLAQUA)
  WRITE (KLUN) YD%ZOZCLAQUA
ENDIF
WRITE (KLUN) YD%COZQC
WRITE (KLUN) YD%COZQS
WRITE (KLUN) YD%COZHC
WRITE (KLUN) YD%COZHS
WRITE (KLUN) YD%RSINC
WRITE (KLUN) YD%ROZT
WRITE (KLUN) YD%RPROC
END SUBROUTINE

SUBROUTINE LOAD_TEOZOC (KLUN, YD)
USE PARKIND1, ONLY : JPRD

IMPLICIT NONE
INTEGER, INTENT (IN) :: KLUN
TYPE (TEOZOC), INTENT (OUT), TARGET :: YD
INTEGER :: IL2(2), IU2(2), IL3(3), IU3(3)
LOGICAL :: LZOZCL, LZOZCLAQUA
REAL(KIND=JPRD), ALLOCATABLE :: ZTMP1 (:)
REAL(KIND=JPRD), ALLOCATABLE :: ZTMP2 (:,:)
REAL(KIND=JPRD), ALLOCATABLE :: ZTMP3 (:,:,:)
READ (KLUN) LZOZCL
IF (LZOZCL) THEN
  READ (KLUN) IL3
  READ (KLUN) IU3
  ALLOCATE (YD%ZOZCL (IL3(1):IU3(1), IL3(2):IU3(2), IL3(3):IU3(3)))
  ALLOCATE (ZTMP3(LBOUND(YD%ZOZCL,1):UBOUND(YD%ZOZCL,1), LBOUND(YD%ZOZCL,2):UBOUND(YD%ZOZCL,2), LBOUND(YD%ZOZCL,3):UBOUND(YD%ZOZCL,3)))
  READ (KLUN) ZTMP3
  YD%ZOZCL = ZTMP3
  DEALLOCATE (ZTMP3)
ENDIF
READ (KLUN) LZOZCLAQUA
IF (LZOZCLAQUA) THEN
  READ (KLUN) IL2
  READ (KLUN) IU2
  ALLOCATE (YD%ZOZCLAQUA (IL2(1):IU2(1), IL2(2):IU2(2)))
  ALLOCATE (ZTMP2(LBOUND(YD%ZOZCLAQUA,1):UBOUND(YD%ZOZCLAQUA,1), LBOUND(YD%ZOZCLAQUA,2):UBOUND(YD%ZOZCLAQUA,2)))
  READ (KLUN) ZTMP2
  YD%ZOZCLAQUA = ZTMP2
  DEALLOCATE (ZTMP2)
ENDIF
ALLOCATE (ZTMP1(LBOUND(YD%COZQC,1):UBOUND(YD%COZQC,1)))
READ (KLUN) ZTMP1
YD%COZQC = ZTMP1
DEALLOCATE (ZTMP1)
ALLOCATE (ZTMP1(LBOUND(YD%COZQS,1):UBOUND(YD%COZQS,1)))
READ (KLUN) ZTMP1
YD%COZQS = ZTMP1
DEALLOCATE (ZTMP1)
ALLOCATE (ZTMP1(LBOUND(YD%COZHC,1):UBOUND(YD%COZHC,1)))
READ (KLUN) ZTMP1
YD%COZHC = ZTMP1
DEALLOCATE (ZTMP1)
ALLOCATE (ZTMP1(LBOUND(YD%COZHS,1):UBOUND(YD%COZHS,1)))
READ (KLUN) ZTMP1
YD%COZHS = ZTMP1
DEALLOCATE (ZTMP1)
ALLOCATE (ZTMP1(LBOUND(YD%RSINC,1):UBOUND(YD%RSINC,1)))
READ (KLUN) ZTMP1
YD%RSINC = ZTMP1
DEALLOCATE (ZTMP1)
ALLOCATE (ZTMP2(LBOUND(YD%ROZT,1):UBOUND(YD%ROZT,1), LBOUND(YD%ROZT,2):UBOUND(YD%ROZT,2)))
READ (KLUN) ZTMP2
YD%ROZT = ZTMP2
DEALLOCATE (ZTMP2)
ALLOCATE (ZTMP1(LBOUND(YD%RPROC,1):UBOUND(YD%RPROC,1)))
READ (KLUN) ZTMP1
YD%RPROC = ZTMP1
DEALLOCATE (ZTMP1)
END SUBROUTINE


SUBROUTINE COPY_TEOZOC (YD, LDCREATED)

IMPLICIT NONE
TYPE (TEOZOC), INTENT (IN), TARGET :: YD
LOGICAL, OPTIONAL, INTENT (IN) :: LDCREATED
LOGICAL :: LLCREATED
LOGICAL :: LZOZCL, LZOZCLAQUA

LLCREATED = .FALSE.
IF (PRESENT (LDCREATED)) THEN
  LLCREATED = LDCREATED
ENDIF
IF (.NOT. LLCREATED) THEN
  !$acc enter data create (YD)
  !$acc update device (YD)
ENDIF
LZOZCL = ALLOCATED (YD%ZOZCL)
IF (LZOZCL) THEN
  !$acc enter data create (YD%ZOZCL)
  !$acc update device (YD%ZOZCL)
  !$acc enter data attach (YD%ZOZCL)
ENDIF

LZOZCLAQUA = ALLOCATED (YD%ZOZCLAQUA)
IF (LZOZCLAQUA) THEN
  !$acc enter data create (YD%ZOZCLAQUA)
  !$acc update device (YD%ZOZCLAQUA)
  !$acc enter data attach (YD%ZOZCLAQUA)
ENDIF








END SUBROUTINE

SUBROUTINE WIPE_TEOZOC (YD, LDDELETED)

IMPLICIT NONE
TYPE (TEOZOC), INTENT (IN), TARGET :: YD
LOGICAL, OPTIONAL, INTENT (IN) :: LDDELETED
LOGICAL :: LLDELETED
LOGICAL :: LZOZCL, LZOZCLAQUA

LZOZCL = ALLOCATED (YD%ZOZCL)
IF (LZOZCL) THEN
  !$acc exit data detach (YD%ZOZCL)
  !$acc exit data delete (YD%ZOZCL)
ENDIF

LZOZCLAQUA = ALLOCATED (YD%ZOZCLAQUA)
IF (LZOZCLAQUA) THEN
  !$acc exit data detach (YD%ZOZCLAQUA)
  !$acc exit data delete (YD%ZOZCLAQUA)
ENDIF








LLDELETED = .FALSE.
IF (PRESENT (LDDELETED)) THEN
  LLDELETED = LDDELETED
ENDIF
IF (.NOT. LLDELETED) THEN
  !$acc exit data delete (YD)
ENDIF
END SUBROUTINE



END MODULE
