MODULE UTIL_TEGSL_MOD

USE YEMGSL, ONLY : TEGSL

INTERFACE SAVE
MODULE PROCEDURE SAVE_TEGSL
END INTERFACE

INTERFACE LOAD
MODULE PROCEDURE LOAD_TEGSL
END INTERFACE

INTERFACE COPY
MODULE PROCEDURE COPY_TEGSL
END INTERFACE

INTERFACE WIPE
MODULE PROCEDURE WIPE_TEGSL
END INTERFACE



CONTAINS

SUBROUTINE SAVE_TEGSL (KLUN, YD)

IMPLICIT NONE
INTEGER, INTENT (IN) :: KLUN
TYPE (TEGSL), INTENT (IN), TARGET :: YD

WRITE (KLUN) YD%RIPORE
WRITE (KLUN) YD%RJPORE
WRITE (KLUN) YD%REGPK
WRITE (KLUN) YD%RNOBILE
WRITE (KLUN) YD%RHSUD
WRITE (KLUN) YD%RMERCAT
WRITE (KLUN) YD%RLON0R
WRITE (KLUN) YD%RELONC
WRITE (KLUN) YD%RELATC
END SUBROUTINE

SUBROUTINE LOAD_TEGSL (KLUN, YD)
USE PARKIND1, ONLY : JPRD

IMPLICIT NONE
INTEGER, INTENT (IN) :: KLUN
TYPE (TEGSL), INTENT (OUT), TARGET :: YD
REAL(KIND=JPRD) :: ZTMP0
READ (KLUN) ZTMP0
YD%RIPORE = ZTMP0
READ (KLUN) ZTMP0
YD%RJPORE = ZTMP0
READ (KLUN) ZTMP0
YD%REGPK = ZTMP0
READ (KLUN) ZTMP0
YD%RNOBILE = ZTMP0
READ (KLUN) ZTMP0
YD%RHSUD = ZTMP0
READ (KLUN) ZTMP0
YD%RMERCAT = ZTMP0
READ (KLUN) ZTMP0
YD%RLON0R = ZTMP0
READ (KLUN) ZTMP0
YD%RELONC = ZTMP0
READ (KLUN) ZTMP0
YD%RELATC = ZTMP0
END SUBROUTINE


SUBROUTINE COPY_TEGSL (YD, LDCREATED)

IMPLICIT NONE
TYPE (TEGSL), INTENT (IN), TARGET :: YD
LOGICAL, OPTIONAL, INTENT (IN) :: LDCREATED
LOGICAL :: LLCREATED

LLCREATED = .FALSE.
IF (PRESENT (LDCREATED)) THEN
  LLCREATED = LDCREATED
ENDIF
IF (.NOT. LLCREATED) THEN
  !$acc enter data create (YD)
  !$acc update device (YD)
ENDIF









END SUBROUTINE

SUBROUTINE WIPE_TEGSL (YD, LDDELETED)

IMPLICIT NONE
TYPE (TEGSL), INTENT (IN), TARGET :: YD
LOGICAL, OPTIONAL, INTENT (IN) :: LDDELETED
LOGICAL :: LLDELETED










LLDELETED = .FALSE.
IF (PRESENT (LDDELETED)) THEN
  LLDELETED = LDDELETED
ENDIF
IF (.NOT. LLDELETED) THEN
  !$acc exit data delete (YD)
ENDIF
END SUBROUTINE



END MODULE
