MODULE UTIL_TTND_MOD

USE INTDYN_MOD, ONLY : TTND

INTERFACE SAVE
MODULE PROCEDURE SAVE_TTND
END INTERFACE

INTERFACE LOAD
MODULE PROCEDURE LOAD_TTND
END INTERFACE

INTERFACE COPY
MODULE PROCEDURE COPY_TTND
END INTERFACE

INTERFACE WIPE
MODULE PROCEDURE WIPE_TTND
END INTERFACE



CONTAINS

SUBROUTINE SAVE_TTND (KLUN, YD)

IMPLICIT NONE
INTEGER, INTENT (IN) :: KLUN
TYPE (TTND), INTENT (IN), TARGET :: YD

WRITE (KLUN) YD%M_TNDU
WRITE (KLUN) YD%M_TNDV
WRITE (KLUN) YD%M_TNDU_NOC
WRITE (KLUN) YD%M_TNDV_NOC
WRITE (KLUN) YD%M_TNDT
WRITE (KLUN) YD%M_TNDPD
WRITE (KLUN) YD%M_TNDVD
WRITE (KLUN) YD%M_TNDGW
WRITE (KLUN) YD%NDIM
END SUBROUTINE

SUBROUTINE LOAD_TTND (KLUN, YD)

IMPLICIT NONE
INTEGER, INTENT (IN) :: KLUN
TYPE (TTND), INTENT (OUT), TARGET :: YD

READ (KLUN) YD%M_TNDU
READ (KLUN) YD%M_TNDV
READ (KLUN) YD%M_TNDU_NOC
READ (KLUN) YD%M_TNDV_NOC
READ (KLUN) YD%M_TNDT
READ (KLUN) YD%M_TNDPD
READ (KLUN) YD%M_TNDVD
READ (KLUN) YD%M_TNDGW
READ (KLUN) YD%NDIM
END SUBROUTINE


SUBROUTINE COPY_TTND (YD, LDCREATED)

IMPLICIT NONE
TYPE (TTND), INTENT (IN), TARGET :: YD
LOGICAL, OPTIONAL, INTENT (IN) :: LDCREATED
LOGICAL :: LLCREATED

LLCREATED = .FALSE.
IF (PRESENT (LDCREATED)) THEN
  LLCREATED = LDCREATED
ENDIF
IF (.NOT. LLCREATED) THEN
  !$acc enter data create (YD)
  !$acc update device (YD)
ENDIF









END SUBROUTINE

SUBROUTINE WIPE_TTND (YD, LDDELETED)

IMPLICIT NONE
TYPE (TTND), INTENT (IN), TARGET :: YD
LOGICAL, OPTIONAL, INTENT (IN) :: LDDELETED
LOGICAL :: LLDELETED










LLDELETED = .FALSE.
IF (PRESENT (LDDELETED)) THEN
  LLDELETED = LDDELETED
ENDIF
IF (.NOT. LLDELETED) THEN
  !$acc exit data delete (YD)
ENDIF
END SUBROUTINE



END MODULE
