INTERFACE
SUBROUTINE VERDER(KPROMA,KSTART,KPROF,KFLEV_IN,KFLEV_OUT,PDERI,PIN,POUT)
USE PARKIND1  ,ONLY : JPRD, JPIM     ,JPRB
USE YOMHOOK   ,ONLY : LHOOK,   DR_HOOK, JPHOOK
IMPLICIT NONE
INTEGER(KIND=JPIM),INTENT(IN)    :: KPROMA
INTEGER(KIND=JPIM),INTENT(IN)    :: KFLEV_IN
INTEGER(KIND=JPIM),INTENT(IN)    :: KFLEV_OUT
INTEGER(KIND=JPIM),INTENT(IN)    :: KSTART
INTEGER(KIND=JPIM),INTENT(IN)    :: KPROF
REAL(KIND=JPRD)   ,INTENT(IN)    :: PDERI(KFLEV_OUT,KFLEV_IN)
REAL(KIND=JPRB)   ,INTENT(IN)    :: PIN(KPROMA,KFLEV_IN)
REAL(KIND=JPRB)   ,INTENT(OUT)   :: POUT(KPROMA,KFLEV_OUT)
END SUBROUTINE VERDER

END INTERFACE
