INTERFACE
SUBROUTINE VERINT(KPROMA,KSTART,KPROF,KLEVIN,KLEVOUT,PINTE,PIN,POUT,KTYPE,KCHUNK)
USE PARKIND1  ,ONLY : JPRD, JPIM     ,JPRB
USE YOMHOOK   ,ONLY : LHOOK,   DR_HOOK, JPHOOK
USE YOMLUN   , ONLY : NULERR
USE OML_MOD  , ONLY : OML_IN_PARALLEL
IMPLICIT NONE
INTEGER(KIND=JPIM),INTENT(IN)    :: KPROMA,KLEVIN,KLEVOUT,KSTART,KPROF,KTYPE
REAL(KIND=JPRD)   ,INTENT(IN)    :: PINTE(KLEVOUT,KLEVIN)
REAL(KIND=JPRB),TARGET,INTENT(IN)    :: PIN(KPROMA,KLEVIN)
REAL(KIND=JPRB),TARGET,INTENT(OUT):: POUT(KPROMA,KLEVOUT)
INTEGER(KIND=JPIM),INTENT(IN),OPTIONAL :: KCHUNK
#if defined(_OPENACC)

#else
#ifdef PARKIND1_SINGLE        
  ALLOCATE(ZOUT(KPROMA,KLEVOUT))
  ALLOCATE(ZIN(KPROMA,KLEVIN))
  ZIN(KSTART:KPROF,:) = PIN(KSTART:KPROF,:)
#else

#endif
#endif

END SUBROUTINE VERINT

END INTERFACE
