MODULE YOEAERC

USE PARKIND1, ONLY: JPIM, JPRB
USE YOMHOOK,  ONLY: LHOOK, DR_HOOK, JPHOOK

IMPLICIT NONE

!     ------------------------------------------------------------------
!*    ** *YOEAERC* - TEGEN/GISS AEROSOL CLIMATOLOGY
!     ------------------------------------------------------------------

INTEGER(KIND=JPIM), PARAMETER :: NFDECSO4DIM=185 , NLDECSO4DIM=210
INTEGER(KIND=JPIM), PARAMETER :: ISHIST=1850, IEHIST=2100, INLAT=24


TYPE :: TEAERC_TEGEN
REAL(KIND=JPRB) :: REPAER = -HUGE(1._JPRB)
REAL(KIND=JPRB), POINTER, DIMENSION(:,:,:) :: RAERBC => NULL(), RAEROR => NULL(), RAERSD => NULL()
REAL(KIND=JPRB), POINTER, DIMENSION(:,:,:) :: RAERSS => NULL(), RAERSU => NULL()
REAL(KIND=JPRB), POINTER, DIMENSION(:,:,:) :: RAERV  => NULL()
REAL(KIND=JPRB), POINTER, DIMENSION(:)     :: RLATV  => NULL()
REAL(KIND=JPRB) :: RTAEBC(72,46), RTAEOR(72,46), RTAESD(72,46)
REAL(KIND=JPRB) :: RTAESS(72,46), RTAESU(72,46), RTAEVO(46)
INTEGER(KIND=JPIM) :: ISYEAR=IEHIST, IEYEAR=ISHIST

LOGICAL :: IS_INITIALISED = .FALSE.

END TYPE TEAERC_TEGEN

TYPE :: TEAERC_MACC
!- based on optical depth

REAL(KIND=JPRB),ALLOCATABLE, DIMENSION(:,:,:) :: RMACBC, RMACOR, RMACSD, RMACSS, RMACSU !! appear not to be used
REAL(KIND=JPRB),ALLOCATABLE, DIMENSION(:,:)   :: RMAEBC, RMAEOR, RMAESD, RMAESS, RMAESU

!- based on vertically integrated mass

REAL(KIND=JPRB), ALLOCATABLE, DIMENSION(:,:,:) :: RMACBC1, RMACBC2
REAL(KIND=JPRB), ALLOCATABLE, DIMENSION(:,:)   :: RMAEBC1, RMAEBC2
REAL(KIND=JPRB), ALLOCATABLE, DIMENSION(:,:,:) :: RMACOR1, RMACOR2
REAL(KIND=JPRB), ALLOCATABLE, DIMENSION(:,:)   :: RMAEOR1, RMAEOR2
REAL(KIND=JPRB), ALLOCATABLE, DIMENSION(:,:,:) :: RMACSD1, RMACSD2, RMACSD3
REAL(KIND=JPRB), ALLOCATABLE, DIMENSION(:,:)   :: RMAESD1, RMAESD2, RMAESD3
REAL(KIND=JPRB), ALLOCATABLE, DIMENSION(:,:,:) :: RMACSS1, RMACSS2, RMACSS3
REAL(KIND=JPRB), ALLOCATABLE, DIMENSION(:,:)   :: RMAESS1, RMAESS2, RMAESS3
REAL(KIND=JPRB), ALLOCATABLE, DIMENSION(:,:,:) :: RMACSU1
REAL(KIND=JPRB), ALLOCATABLE, DIMENSION(:,:)   :: RMAESU1

!arrays for input 3D climatology on a 3x3 deg and 60 level grid
!lon,lat,lev,month
REAL(KIND=JPRB), POINTER, CONTIGUOUS, DIMENSION(:,:,:,:) :: RMACBC13D => NULL(), RMACBC23D => NULL()
REAL(KIND=JPRB), POINTER, CONTIGUOUS, DIMENSION(:,:,:,:) :: RMACOR13D => NULL(), RMACOR23D => NULL()
REAL(KIND=JPRB), POINTER, CONTIGUOUS, DIMENSION(:,:,:,:) :: RMACSD13D => NULL(), RMACSD23D => NULL(), RMACSD33D => NULL()
REAL(KIND=JPRB), POINTER, CONTIGUOUS, DIMENSION(:,:,:,:) :: RMACSS13D => NULL(), RMACSS23D => NULL(), RMACSS33D => NULL()
REAL(KIND=JPRB), POINTER, CONTIGUOUS, DIMENSION(:,:,:,:) :: RMACSU13D => NULL()
REAL(KIND=JPRB), POINTER, CONTIGUOUS, DIMENSION(:,:,:,:) :: REF_MON_AER_PRS => NULL(),REF_MON_AER_DPRS => NULL()
REAL(KIND=JPRB), ALLOCATABLE, DIMENSION(:,:,:)   :: RMAEBC13D, RMAEBC23D
REAL(KIND=JPRB), ALLOCATABLE, DIMENSION(:,:,:)   :: RMAEOR13D, RMAEOR23D
REAL(KIND=JPRB), ALLOCATABLE, DIMENSION(:,:,:)   :: RMAESD13D, RMAESD23D, RMAESD33D
REAL(KIND=JPRB), ALLOCATABLE, DIMENSION(:,:,:)   :: RMAESS13D, RMAESS23D, RMAESS33D
REAL(KIND=JPRB), ALLOCATABLE, DIMENSION(:,:,:)   :: RMAESU13D
REAL(KIND=JPRB), ALLOCATABLE, DIMENSION(:,:,:)   :: REF_AER_PRS,REF_AER_DPRS

LOGICAL :: IS_INITIALISED = .FALSE.

END TYPE TEAERC_MACC

END
