MODULE YOMLDDH

IMPLICIT NONE

SAVE

!     ------------------------------------------------------------------
!     LOGIQUE DIAGNOSTIQUES DOMAINES HORIZONTAUX

!     LSDDH   : VRAI SI AU MOINS UN DIAGNOSTIC DDH ACTIF
!     LHDGLB = CALCULS EN VUE DES MOYENNES GLOBALES
!     LHDZON = CALCULS EN VUE DES MOYENNES ZONALES
!     LHDDOP = CALCULS EN VUE DES MOYENNES SUR DOMAINES LIMITES, POINTS
!              ISOLES COMPRIS
!     LHDLFA = TRUE IF OUTPUT ON LFA FILE OTHERWISE PSEUDOGRIB

!     LHDHKS = OPERE SUR MASSES, ENERGIES ET SOL
!     LHDMCI = OPERE SUR MOMENT CINETIQUE
!     LHDENT = OPERE SUR ENTROPIE

!     LHDPRG = CUMUL ET IMPRESSION MOYENNES GLOBALES
!     LHDPRZ = CUMUL ET IMPRESSION MOYENNES ZONALES (1 BANDE: NDHZPR)
!     LHDPRD = CUMUL ET IMPRESSION DOMAINES LIMITES (TOUS DOMAINES)
!     LHDPR = DES IMPRESSIONS SONT DEMANDEES

!     LHDEFG = CUMUL ET ECRITURE FICHIER DES MOYENNES GLOBALES
!     LHDEFZ = CUMUL ET ECRITURE FICHIER DES MOYENNES ZONALES
!     LHDEFD = CUMUL ET ECRITURE FICHIER DOMAINES LIMITES

!     LHDLIST = IMPRESSIONS COMPLETES
!            LES INDICATEURS SUIVANTS SONT DE NIVEAU 4 ET PLUS
!            AU PAS DE TEMPS EN COURS (NSTEP):

!     LHDOUFG = "SYNTHESIS" AND WRITE OUT GLOBAL MEAN DDH
!     LHDOUFZ = "SYNTHESIS" AND WRITE OUT ZONAL MEAN DDH
!     LHDOUFD = "SYNTHESIS" AND WRITE OUT LIMITED AREAS DDH
!     LHDOUP = EFFECTUER UNE SYNTHESE ET IMPRESSION

!     LHDFIL = IMPRESS. DE LA LISTE DES ARTICLES DES FICHIERS DE SORTIE.
!     LRDDHDYN = TRUE IF AT LEAST ONE DYNAMICAL DDH DIAGNOSTIC IS ACTIVATED
!     LRSLDDH = TRUE IF SEMI-LAG DDH  IS ACTIVATED
!     LRHDDDH = TRUE IF HORIZ. DIFFUSION DDH IS ACTIVATED
!     LRSIDDH = TRUE IF SEMI-IMPLICIT DDH IS ACTIVATED

TYPE :: TLDDH
LOGICAL :: LSDDH = .FALSE.
LOGICAL :: LHDGLB = .FALSE.
LOGICAL :: LHDZON = .FALSE.
LOGICAL :: LHDDOP = .FALSE.
LOGICAL :: LHDLFA = .FALSE.
LOGICAL :: LHDHKS = .FALSE.
LOGICAL :: LHDMCI = .FALSE.
LOGICAL :: LHDENT = .FALSE.
LOGICAL :: LHDPRG = .FALSE.
LOGICAL :: LHDPRZ = .FALSE.
LOGICAL :: LHDPRD = .FALSE.
LOGICAL :: LHDPR = .FALSE.
LOGICAL :: LHDEFG = .FALSE.
LOGICAL :: LHDEFZ = .FALSE.
LOGICAL :: LHDEFD = .FALSE.
LOGICAL :: LHDLIST = .FALSE.
LOGICAL :: LHDOUFG = .FALSE.
LOGICAL :: LHDOUFZ = .FALSE.
LOGICAL :: LHDOUFD = .FALSE.
LOGICAL :: LHDOUP = .FALSE.
LOGICAL :: LHDFIL = .FALSE.
LOGICAL :: LONLYVAR = .FALSE.
LOGICAL :: LHDORIGP = .FALSE.
LOGICAL :: LHDCDPI = .FALSE.
LOGICAL :: LFLEXDIA = .FALSE.
LOGICAL :: LRDDHDYN = .FALSE.
LOGICAL :: LRSLDDH = .FALSE.
LOGICAL :: LRSIDDH = .FALSE.
LOGICAL :: LRHDDDH = .FALSE.
LOGICAL :: LDDH_OMP = .FALSE.
END TYPE  TLDDH

!!TYPE(TLDDH), POINTER :: YRLDDH => NULL()

!     ------------------------------------------------------------------
END MODULE YOMLDDH
